### ISSUE TITLE
Set chosen to add "title" attribute to each generated span in amultiselect mode

### ISSUE THREAD

**Issue by maxpavlov** [harvesthq/chosen#1095]
I am using multiselect on a small admin page and the whole lines of options don't usually fit on the screen. I need user to be able to see the whole text of an option by hovering a selected item (manually injected title into a control-generated span):
![titledChosen](https://f.cloud.github.com/assets/669701/277312/56920350-90c2-11e2-8bad-13a48b779fd2.jpg)

Is there a setting that would force adding title to a generated span elements of the multi select chosen? Perhaps a more elegant solution to an aforementioned problem? Thank you in advance.

**Comment by JCorrivo** [comment]
I see it's still open, but I had to do something similar and this code is not too bad I think
```
 $("#Your_chosen").on("mouseover", "li",  function() {
                $(this).prop("title", this.innerText);
            });
```

**Comment by koenpunt** [comment]
Long options are wrapped, so I think this is no longer an issue.

![image](https://cloud.githubusercontent.com/assets/351038/19023155/546bc55e-88e7-11e6-9b95-29f9e8780809.png)
