### ISSUE TITLE
Disable/Clear Speed

### ISSUE THREAD

**Issue by patrickhousley** [harvesthq/chosen#1131]
I am currently working on a CRUD form that contains multiple chosen single-select elements. When switching between form functions, such as retrieve to update, the chosen elements need to be cleared and disabled. Doing this through the liszt:updated method is slow and causes noticeable delay on the UI. A better solution would be to have a dedicated event for disabling, enabling, and clearing the value of the chosen element.

```javascript
      this.form_field_jq.bind("liszt:clear", function(evt) {
        _this.results_reset();
      });
      this.form_field_jq.bind("liszt:disable", function(evt) {
        _this.search_field_disabled();
      });
      this.form_field_jq.bind("liszt:enable", function(evt) {
        _this.search_field_disabled();
      });
```

**Comment by pfiller** [comment]
Going to close this issue. Discussion can take place in the PR #1415 if necessary.
