### ISSUE TITLE
Filter and ignore special characters in selection list

### ISSUE THREAD

**Issue by pkuczaj** [harvesthq/chosen#1137]
I have the following list in my chosen dropdown:
Rock
Rap
R&B
Jazz
Pop

When I type "R" my dropdown reduces to:
Rock
Rap
R&B

I would like to continue to type RB and reduce to:
R&B

At the moment I get a "No Results Found", BUT if system would ignore the & and any special characters to simplify and make the user experience better.

**Comment by pfiller** [comment]
Something like #2618 would be right up your alley. Going to close this, but feel free to weigh in there.
