### ISSUE TITLE
Width Problem

### ISSUE THREAD

**Issue by alexfrancavilla** [harvesthq/chosen#1162]
Hi, when I use chosen on a select field like this:

`<select id="mySelect" style="width: 65.935%;" multiple>`

Chosen generated the `<ul class="chzn-choices">` with a width of 65.935 pixels instead of percent. For the moment I've hacked it with this initialization here

`$('#inputNewRecipient').chosen().next().css('width', '65.9574%');`

Kind regards

**Comment by danielmahadi** [comment]
This fix the issue for me

li.search-field{
    width: 100% !important;
}
li.search-field input.default{
    width: 100% !important;
}
