### ISSUE TITLE
Different text in multiselect options than in the "buttons"

### ISSUE THREAD

**Issue by silkfire** [harvesthq/chosen#1190]
Would it be possible to add a feature for alternative text for the multiselect options (dropdown) than what is seen in the buttons (the ones with the 'x' at the end)?

For example, I want the long name of an option to be visible in the dropdown, but when I select it, the button with the 'x' should have its abbreviated form (alternate form) only.

Also, when I hover of the button, I would like a tooltip that shoes the full name of the button.

**Comment by pfiller** [comment]
In addition to @pavanyadav05's solution, you could also put a max-width on the choices. That would keep options from getting too long. I don't think alternate text for choices is something we'll ever add to Chosen.
