### ISSUE TITLE
Search doesn't work for items in parantheses: searching for "foo" doesn't find "(Foo)"

### ISSUE THREAD

**Issue by archon810** [harvesthq/chosen#121]
Pretty much see topic - parentheses shouldn't be considered word parts and should be ignored during search, just like most other punctuation.

**Comment by Aymkdn** [comment]
For people that are looking at this thread, there is now the option `search_contains:true` that's doing the trick, but it's not documented.

**Comment by stof** [comment]
@Aymkdn it is documented, together with all options: https://harvesthq.github.io/chosen/options.html

**Comment by Aymkdn** [comment]
@stof thank you! I never noticed this page.... !

**Comment by koenpunt** [comment]
So this issue can be closed now?

**Comment by Aymkdn** [comment]
I think so.
