### ISSUE TITLE
Masking option values with HTML

### ISSUE THREAD

**Issue by johmanx10** [harvesthq/chosen#123]
Within my CMS, I use a lot of dropdowns for the ENUM and SET fields in my databases, as well for the foreign keys with multiple options. One of my clients has a dog encyclopedia and she uses a star based rating on the site. On the backend, this translates to enum fields with values 1 through 5. Now, it's hardly necessary, but it would be nice to have a masking implementation.

So how do I suggest an implementation?
Enable some kind of translation dictionary. If I put in an extra class, I can use jQuery to select the specific dropdowns and you could accept objects/arrays like:

Stars {1:'\<img src="images/stars1.png" />',2:'\<img src="images/stars2.png" />'}
Flags {us:'\<img src="images/flags/us.png" />',nl:'\<img src="images/flags/nl.png" />'}
Money {'$':'\<img src="images/dollar.png" />','€':'\<img src="images/euro.png" />'}

I deliberately chose the html format, rather than only being able to pass through just image urls. You could consider accepting an input value for either image or html, where the image would use an img-tag to complete the mask.

As an example of what I'm trying to achieve by this issue: http://lievheid.nl/examples/chosen/rating.png
Left is before; right is after.

Cheers,
J

**Comment by pfiller** [comment]
#692 is the PR of the library @brianfeister mentioned. It's been open a looooong time, but maybe someday we'll get around to it. Maybe.
