### ISSUE TITLE
Clicking on bottom edge of container shows then immediately hides the search_field dropdown [jsFiddle provided]

### ISSUE THREAD

**Issue by BrandonLWhite** [harvesthq/chosen#1255]
When using Chosen as a simple select/combobox with the {disable_search: true} option, a minor issue exists where if the very bottom edge of the container is clicked, the options will appear but then immediately disappear.  Please refer to [this fiddle](http://jsfiddle.net/LatencyMachine/YYYgn/) for a demonstration of the issue.

**Comment by pfiller** [comment]
I'm not able to recreate this issue so I'm going to assume it was fixed sometime in the past 3 years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.
