### ISSUE TITLE
display:none issue (still)

### ISSUE THREAD

**Issue by rdtype25** [harvesthq/chosen#1289]
After reading several issues around chosen not calculating the width correctly when the element is wrapped in a display:none div, all the suggested fixes don't work. 

For example, 

https://github.com/harvesthq/chosen/issues/795

I have a solution, and this works well in my project:

``` js
this.f_width = this.form_field_jq.outerWidth(); // add below code under this line at chosen.jqeury.js

  if (this.f_width==0){ 
      var cloneObj= this.form_field_jq.clone();
      cloneObj.removeAttr('id');
      $(document.body).append(cloneObj);
      var w = cloneObj.width();
      cloneObj.remove();
      this.f_width=w;
  }
```

However, the line of code suggested doesn't exist. 

Could anyone shed some light on a fix for this issue? 

Many thanks

**Comment by KZeni** [comment]
I just leave the default chosen width option (auto) and add
```
.chosen-container { min-width:5em; }
```
to my site's CSS (adjusting the min-width as needed). This makes it never become 0px (or just too small to use) while still fitting the select's ideal width when possible (forcing a 100% width or something to that effect doesn't work well when you have select elements inline with other content & this method addresses the core issue as well as allowing for inline select elements & seemingly offering the simplest & most straightforward implementation).
