### ISSUE TITLE
Seperate positioning styling and fancy styling

### ISSUE THREAD

**Issue by lukeapage** [harvesthq/chosen#1306]
It would be great if chosen could 

a) split up the styling between that needed for positioning and that needed for styling
b) use a preprocessor like less and variables to allow people to tweak size variables that then refactor all of the css in a way that works
c) split up the css parts into different parts of the functionality so that a user can choose which parts of the styling to include.

doing this would be a good precurser to then writing a css adapter which could make chosen compatible with bootstrap etc.

**Comment by pfiller** [comment]
Chosen's CSS is potentially getting a big overhaul in #2479. Feel free to take a look!
