### ISSUE TITLE
Include compiled JS in repo for bower

### ISSUE THREAD

**Issue by aq1018** [harvesthq/chosen#1333]
When installing chosen using [bower](http://sindresorhus.com/bower-components/):

```
bower install chosen
```

It fetches from this repo directly, and since there is no compiled JS file, it is currently not usable with bower.

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
