### ISSUE TITLE
Add search input placeholder option

### ISSUE THREAD

**Issue by marchenko1985** [harvesthq/chosen#1353]
It will be nice if there will be search input placeholder option, now workaround is something like this:

```
jQuery('#example').chosen();
jQuery('#example_chzn input').attr('placeholder', 'Search filter...');
```

**Comment by cadavre** [comment]
"Text noise"? From my point of view why not add this option and leave it empty as default? I'd like to add text as well because I redesigned Chosen widget and right now my search looks like a box – I certainly need placeholder.

**Comment by jeserkin** [comment]
For those, who are using angular, I added support for placeholder, even IE. https://github.com/sfos/angular-chosen

**Comment by AdamSGit** [comment]
I'm looking for this option too. I changed a bit the CSS and a placeholder is perfect with what I did. For now I solved it with an external line of javascript, but it would be more clean and convenient to have it as an option. Beside, It's not up to a plugin to decide if something is ok or not in term of design.

Maybe you want a pull request ?
