### ISSUE TITLE
Hidden options are still "selectable"

### ISSUE THREAD

**Issue by fcamblor** [harvesthq/chosen#1426]
See this [jsfiddle](http://jsfiddle.net/HejBe/3/) : when expanding select, "Hidden content" option is not displayed, this is fine.

Now, enter "H" in the search box :
- The message "No results" is not displayed
- No "selectable" result is displayed
- If we press "enter", the "Hidden content" option is selected

In the same idea, if every options were hidden, by using up/down arrows, then clicking enter, we can select options.

Tested against chosen 0.9.6 & 0.14.0 and same behaviour is present.

**Comment by danger89** [comment]
Actually the hidden should also work... I think this should be reopened? hidden works in FF in plain HTML.
