### ISSUE TITLE
Cannot read length of undefined

### ISSUE THREAD

**Issue by Luke-SF** [harvesthq/chosen#1452]
On this line, I get an error: Uncaught TypeError: Cannot read property 'length' of undefined

 Chosen.prototype.results_build = function() {
            return this.parsing = !0, this.selected_option_count = null, this.results_data = SelectParser.select_to_array(this.form_field), this.is_multiple ? this.search_choices.find("li.search-choice").remove() : this.is_multiple || (this.single_set_selected_text(), this.disable_search || this.form_field.options.length <= this.disable_search_threshold ? (this.search_field[0].readOnly = !0, this.container.addClass("chosen-container-single-nosearch")) : (this.search_field[0].readOnly = !1, this.container.removeClass("chosen-container-single-nosearch"))), this.update_results_content(this.results_option_build({first: !0})), this.search_field_disabled(), this.show_search_field_default(), this.search_field_scale(), this.parsing = !1
        }

Could it be the latest Chosen is incompatible with jQuery 1.10.2? I'm running .chosen({}) on some select elements, which causes this error.

**Comment by acnice** [comment]
http://t.racing.racingnsw.com.au/FreeFields/chosen.aspx
