### ISSUE TITLE
wrong letters underlining

### ISSUE THREAD

**Issue by yurks** [harvesthq/chosen#1463]
Given:
-- single selectbox with firstnames and lastnames
and
-- .chosen() applied with default values (so, "search_contains" is false by default)
When
-- selectbox is open
and
-- start typing leters in searchbox
and 
-- both words contains typed letters
Then
-- wrong word is underlining

![image](https://f.cloud.github.com/assets/4581398/938753/f0510556-0104-11e3-9ce4-fc0dfbfc706e.png)

**Comment by koenpunt** [comment]
Fixed by https://github.com/harvesthq/chosen/pull/2692
