### ISSUE TITLE
Add option to make use of JavaScript's replace method.

### ISSUE THREAD

**Issue by howardroark** [harvesthq/chosen#1469]
I have updated the API to accept an object property of "replace", which allows me to modify the text as it is output when chosen is in it's open state.  I get a lot of requests to do things like make the title bold.  This helps keep the the state of the original select element pristine but be a little more playful with he output.

```javascript
$('.chzn-select').chosen({"replace":[/([\w\s\d]+)\s-\s([\w\s\d]+)+/,"<span>$1</span><br /> $2"]});
```

It appears to be working bug free.  I would like to know if I should take the time to convert my revisions to coffee script and spend more time ensuring that it does not conflict with any of the other options (ie. search).

Thanks!

**Comment by pfiller** [comment]
This sounds pretty similar to the templating idea put forth in #692. I have no idea if something like that will ever get merged, but it's possible. Anything is possible.

**Comment by howardroark** [comment]
That looks great!  I can always use the fork. Thanks!
