### ISSUE TITLE
chosen.css and chosen.jquery.js not in github?

### ISSUE THREAD

**Issue by richb-hanover** [harvesthq/chosen#1472]
I'm completely new at this, but I don't see either the CSS or JS files for Chosen in the repo. Am I missing something? Thanks.

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
