### ISSUE TITLE
IE8: Clicking on multiple select container does not focus on the hidden input field

### ISSUE THREAD

**Issue by lihan** [harvesthq/chosen#1493]
### Steps to re-produce

1. Open http://harvesthq.github.io/chosen/#selected-and-disabled-support in IE8
2. The broken one is the "Multiple Select". Click on the right side of the container, do not click on somewhere that's  close to the selected item.
3. The cursor was not showing in the input field

---
### Updates:

In chrome, after I clicked inside the container, the cursor shows up and I can type to search.

While in IE8, after I clicked inside the container, there was no cursor showing, and so couldn't I type anything to search.

**Comment by pfiller** [comment]
This bug is 3 years old and Chosen has changed a lot in that time. I think IE8 support is probably not long for this world anyways. Going to close this up.
