### ISSUE TITLE
Highlight Doesn't Update Correctly to Currently Selected Option

### ISSUE THREAD

**Issue by AKKoe** [harvesthq/chosen#1504]
When I open the selection drop down and pick an option it is highlighted and selected correctly for the first selection. If I do this again, with a selection that is further down the list (e.g. if I selected Option-1 the first time, and then select Option-8), it is highlighted and selected but when I open the list again, the first selected item (Option-1) is highlighted and scrolled to the top instead of the actually selected item (Option-8).

You can see this behavior also on the Chosen demo page: http://harvesthq.github.io/chosen/    -- for the "Custom Width Support" selection, and intermittently for other single select items. So this is a bug that isn't happening in all cases for some reason I haven't been able to identify.

Tested in Chrome 29.0.1547.57, Firefox 22, using jQuery 1.10.3, and Chosen 1.0

**Comment by pfiller** [comment]
I believe this is resolved. I'm not seeing it on the Chosen demo page.
