### ISSUE TITLE
Hard dependency to create css and js 

### ISSUE THREAD

**Issue by rajibahmed** [harvesthq/chosen#1509]
Hi,

I use bower to manage all our external js libs. Previously when we used bower chosen had precompiled css and js. We just needed to point to that file. And use compressor compress it. 

But as our servers don't have Ruby and Node installed we now need to add a two step before minification. Is it possible to include all the js an css into a doc folder which we can use.

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
