### ISSUE TITLE
Incompatible with global "box-sizing:border-box"

### ISSUE THREAD

**Issue by giles-v** [harvesthq/chosen#1515]
Placing Chosen on a site with an existing rule like this:

```
* {
  -moz-box-sizing: border-box; 
  box-sizing: border-box;
 }
```

Causes the layout to be break slightly as heights are calculated according to the wrong box-model.  Something like this should correct it:

```
.chosen-container * {
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
```

**Comment by pfiller** [comment]
This was done in #2054.
