### ISSUE TITLE
Chosen does not appear to work for me on iOS Safari 

### ISSUE THREAD

**Issue by CaliHoya** [harvesthq/chosen#1534]
On my laptop (MacBook Pro), my page loads the Chosen dropdowns fine on Chrome and Safari. However, when loading on my iPhone 4 via Safari, the placeholder text does not show up and the dropdown added functionality (with input cursor, etc) does not work. I've attached an image of both what it looks like on the desktop Safari browser as well as iOS Safari (please only look at the three dropdowns as the input box at the bottom is separate).

iOS Safari:
![ios safari](https://f.cloud.github.com/assets/5186155/1089233/51e2b1d4-1640-11e3-93da-5639ed0d9faa.png)

Desktop Safari:
![desktop safari](https://f.cloud.github.com/assets/5186155/1089235/5566110c-1640-11e3-8bc4-d191726aa3e8.png)

Does Chosen not work on iOS smartphone browsers or is there something I can do to fix this?

**Comment by SivanKarthick** [comment]
Hi,

Its Working!!!!
Please Replace your "chosen.JS" file into below txt to change the js
http://realize.be/files/chosen.jquery.min_.js.txt
