### ISSUE TITLE
Stay open on multi select

### ISSUE THREAD

**Issue by silkfire** [harvesthq/chosen#1546]
Is there a way for the Chosen menu to stay open after I've selected an item? I want to be able to close it only by clicking outside the widget area.

**Comment by cuantico** [comment]
That works really fine. Thanks @ronanquillevere

**Comment by frahugo** [comment]
+1

**Comment by thekrotek** [comment]
Thanx for the hack, it works indeed. The only thing, that isn't perfect is cursor focusing after select - it always jumps to the first option. It would be great to make it remain on just selected option. I'm not very good in javascripting (more a PHP guy), so, guess, I'll have to wait, until someone implement this :-)

**Comment by maslianok** [comment]
+1

**Comment by mariarabinovich** [comment]
+1

**Comment by MicahBrown** [comment]
+1
+1
+1

**Comment by adnancehic** [comment]
Is there any way to make the fix that @ronanquillevere posted function when there are several multi-select elements on a single page?

**Comment by lucanos** [comment]
+1

**Comment by MuyBien** [comment]
+1

**Comment by n0v1** [comment]
+1, the main reason to have a mutli select is to be able to select mutliple options. Chosen should support doing this fast without having to reopen the select menu for every option. This would especially help with long list where the user may have to scroll to find the desired options.

**Comment by zyphlar** [comment]
This has been open since 2013, so I just decided to use Select2 instead.

**Comment by HarrisRobin** [comment]
+1

**Comment by HarrisRobin** [comment]
For those using angular-chosen, simply modify @ronanquillevere so it works with angular and place the function in ```initOrUpdate```.

Here is what I did:
```
(function () {
                var autoClose              = false;
                var chosen_resultSelect_fn = chosen.result_select;
                chosen.search_contains     = true;
                chosen.result_select       = function (evt) {
                  var resultHighlight = null;

                  if (autoClose === false) {
                    evt['metaKey'] = true;
                    evt['ctrlKey'] = true;
                    resultHighlight = chosen.result_highlight;
                  }
                  var stext = chosen.get_search_text();
                  var result = chosen_resultSelect_fn.call(chosen, evt);

                  if (autoClose === false && resultHighlight !== null)
                    resultHighlight.addClass('result-selected');

                  this.search_field.val(stext);
                  this.winnow_results();
                  this.search_field_scale();
                  return result;
                };
              })();
```

**Comment by zlatevbg** [comment]
+1

**Comment by Lightheaded** [comment]
+1 - it is only logical that multiselects with high probability of multiple choices would expect the box not to close. CMD/ctrl+click is a nice feature, but that's not good UX.

**Comment by nshackles** [comment]
+1 - We recently replaced an older multi-select with Chosen and one of the main complaints we are getting from our users is that it takes more clicks to select multiple items in the list because the dropdown closes each time.  Like others we are going to add a hack so it stays open by default for multi-select. It would be really nice if that was one of the options.

**Comment by ashliewebb** [comment]
+1

**Comment by KJoergensen** [comment]
+1

**Comment by VinceG** [comment]
+1 this is a vital feature. anyone willing to help with a PR?

**Comment by truthglow** [comment]
+1

**Comment by markkap** [comment]
Hi guys, any estimate when there will be a proper release that contains it? or did I miss anything?

**Comment by lvpro** [comment]
Looks like this much needed feature has been in master for 3 months now.

How about a new release? :) :)

**Comment by DATTAU** [comment]
Hi,   I am trying to keep multiple selections chosen by user after page refresh/ after the page is rendered. 
I am selected 5 multiple Districts (items) and main keyword for search. Often I want to search with different keyword within the same multiple selections. It is not very user friendly if user needs to repeat multiple selections.  I am using Chosen Jq lib.  Any help will be appreciated.   ---Datta

**Comment by DATTAU** [comment]
koenpunt,   Can you explain? Please!

**Comment by orik007** [comment]
Workaround if u need to keep it open all the way.
In onload, call this for firstopen
` $("#" + selectId).trigger("chosen:open");`

In chosen.jquery.js there is function:
`Chosen.prototype.results_hide = function() {
        if (this.results_showing) {
        this.result_clear_highlight();
        this.container.removeClass("chosen-with-drop");
        this.form_field_jq.trigger("chosen:hiding_dropdown", {
          chosen: this
        });
      }
      return this.results_showing = false;
    };`

replace it with:
`Chosen.prototype.results_hide = function() {
        return false;
    };`

**Comment by cavinlee** [comment]
i did it like this, look for this method
`Chosen.prototype.result_select`
add in another condition
```
Chosen.prototype.result_select = function(evt) {
  ...
  if (!(this.is_multiple && (!this.hide_results_on_select || (evt.metaKey || evt.ctrlKey)))) {
    //stay open temporary solution
    if (this.max_selected_options <= 0 || (this.max_selected_options > 0 && this.max_selected_options <= this.choices_count())) {
      this.results_hide();
      this.show_search_field_default();
    }
  }
  ...
};
```

**Comment by cinias** [comment]
I'm not sure if it is a bug or it was made like this. I have 18 items in multiselect  with "Ctrl" but when I'm trying to select f.e. 15th element in list, its is scrolling automaticly to the first unselected item. Is there any switch to keep opened window in last possition?

**Comment by ukg1** [comment]
I have used the hack of HarrisRobin and it is working fine with the first select. I have used multiple number of select box using chosen but this hack is not working with the rest select box than the first one. Would anyone please help me ?

**Comment by DeepaMGMG** [comment]
Hello All, 

Is this feature implemented now in 2019? :)
