### ISSUE TITLE
Option below disabled option does not get highlighted

### ISSUE THREAD

**Issue by DeepXP** [harvesthq/chosen#1558]
Please follow these steps to replicate the issue:

- A dropdown menu with disabled and selectable options (with search enabled)
- Select an option below any disabled option and it will never get highlighted
- Selecting any option value above disabled option will work fine.

Here is the video demonstrating the issue: http://d.pr/v/6rde/1LorXk66

Live demo can be checked on your website here: http://harvesthq.github.io/chosen/#selected-and-disabled-support

I tested this on Google Chrome 29.0.1547.65 running on Mac OSX 10.8.4

Hope this helps.

Deep

**Comment by pfiller** [comment]
I'm not able to recreate this issue so I'm going to assume it was fixed sometime in the past 2 1/2 years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.
