### ISSUE TITLE
Changing from Single Select to Multiple Select and back again

### ISSUE THREAD

**Issue by thomb** [harvesthq/chosen#1560]
I was wondering if it was possible to have Chosen redraw itself after you set "multiple" on the original select element?

I know this is possible if I destroy() the original Chosen select, then trigger Chosen again on the same select, but it would be ideal of this could be picked up by "chosen:updated".

Cheers, and thanks!
Thom

**Comment by pfiller** [comment]
The HTML between a single and multiple Chosen select are quite different and there's no good way to switch them back and forth. I don't think there's ever going to be a better way to do this than destroying Chosen and calling it on the select after the switch. Closing!
