### ISSUE TITLE
Q: How to enter one digit into Chosen select field if it two digits value already selected?

### ISSUE THREAD

**Issue by N0rbert** [harvesthq/chosen#1564]
I have a select list with values from 1 to 25. I use [JQuery Chosen plugin](http://harvesthq.github.io/chosen/) with this list.
If the two-digits value is already selected (from server-side), I unable to set it manually to one-digit value.

For example: 13 is selected, I go to this list with Tab or by mouse click and try to set 1 from keyboard, press Enter or Tab the value remains 13, not 1. If I enter 2 I got 2.

How I can get 1 instead of 13 (2 instead of 23 and so on)?

        <select class="chosen-select">
                <option value="1">1</option>
                ...
                <option value="25">25</option>
        </select>
        <script type="text/javascript">
        var config = {
            '.chosen-select': {
                disable_search_threshold: 10,
                no_results_text: "Oops, nothing found!",
                width: "150px"
            }
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
        </script>

My JSFiddle demo is here - http://jsfiddle.net/TKgqE/5/.

**Comment by pfiller** [comment]
This is a bit of an usual edge case and I don't think there's a very natural solution to bake into Chosen. Lists of numbers probably aren't the best application of a Chosen select.

Going to #wontfix this.
