### ISSUE TITLE
Use extend so that the sprite is only in one place and other css enhancements

### ISSUE THREAD

**Issue by lukeapage** [harvesthq/chosen#1567]
Hi,

Thanks for chosen, here are some things could be done to the css to make using it easier.

1. extend a .chosen-sprite that has the sprite and background no repeat in it - this way the css will only have one mention of the sprite. this means it is easy for me import it into less and convert the sprite into an inline data-uri url. alternatively use extend and then use compass to include the sprite in the css file once.

2. The css contains alot of styling and the selectors are complex.. this means that if I don't want to edit your output css file I have override alot of selectors.. or hack apart the css file and remove all the mentions of colours and a few borders etc.
it would be great to seperate the css into a. positioning and b. styling so that people could take just the positioning styling and then build their own styling on top.

In addition to this the css could be made far simpler by combining states into classes added further down in the dom e.g.
```css
.chosen-container-single .chosen-search
```

 could be
```css
.chosen-single-search
```

with the dom having
```html
class="chosen-search chosen-single-search"
```

this would make the css smaller, the control more performant and the css easier to override.

3.

if you do need to have selectors like this
```css
.chosen-container-single .chosen-single div b
```
use ```>``` - browsers evaluate every rule of a css file to work out if it applies to a node. With this rule, the browser has to test every b tag to see if it has a parent div and then has a parent X etc.
It is most performant if the right hand side of the selector is as exclusive as possible, yet many of your selectors end in span, div, b, abbrv - this is made even worse when hover selectors are applied on top.

**Comment by koenpunt** [comment]
If you want to customize the css, a better starting point is the sass source, which when imported, can have the background images overridden:

```scss
// my_chosen.scss

$chosen-sprite: url('data:...');
$chosen-sprite-retina: url('data:...');

@import "chosen";
