### ISSUE TITLE
Multiple list items get "result-selected" class

### ISSUE THREAD

**Issue by pavdro** [harvesthq/chosen#1568]
Hi,
I'm using latest 1.0.0.
Looks like last 2 selected list items are getting "result-selected" class in a single dropwodn list.

Thanks

**Comment by pfiller** [comment]
I'm not able to recreate this issue so I'm going to assume it was fixed sometime in the past 2 1/2 years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.
