### ISSUE TITLE
Option to mimic the default behaviour of select elements

### ISSUE THREAD

**Issue by afEkenholm** [harvesthq/chosen#1578]
To create a smooth user experience, we don't want visitors having to figure out how a chosenized single-select element works, but let them use them as they would expect them to behave.

Ideas:

* **Let the user open a focused select element using the space key.** This is the default behavior in Chrome, Safari and Opera (as far as I know) (at least on Mac). On searchable chosens: open the results without typing a leading space in the search field. On non-searchable chosens: call `evt.preventDefault()` to prevent the browser window from scrolling down.
* **Let the user select an item in a non-searchable select element using the space key.** Same default behavior as above.
* **Continuously highlight visible options through "invisible" search.** In a regular opened select element, you can type what you are looking for, and the first option matching your search would be highlighted, letter by letter. The current query is reset after a second or two. This is default in all browsers (I think), and is applicable for non-searchable chosens. One way to approach this might be to use the search field, hide it and set typing=resetting after 2s of idleness.

*"Why not just use the search?"* you might ask, regarding that last thing. *"Well"*, I might answer, *"I guess I'm a conservative"*. I might continue: *"Them magnifying glasses look aweful silly sometimes."*

Because some select element behaviour is different for different browsers (on Mac f.i., alt+down opens a select element), it might be a good idea to make these features an option like `mimic_default_behavior`.

**Comment by ayust** [comment]
:+1:

**Comment by pfiller** [comment]
> Let the user open a focused select element using the space key.

This is currently how Chosen works.

> Let the user select an item in a non-searchable select element using the space key.

This one is tricky and probably a non-starter. We have a search field and space is a character that can match text in search results. We'd have to decide if the person meant to hit space to separate words or to select an option. No good.

> **Continuously highlight visible options through "invisible" search.** In a regular opened select element, you can type what you are looking for, and the first option matching your search would be highlighted, letter by letter. The current query is reset after a second or two. This is default in all browsers (I think), and is applicable for non-searchable chosens. One way to approach this might be to use the search field, hide it and set typing=resetting after 2s of idleness.

This is one of the specific behaviors of normal selects that Chosen sought to improve. People don't know they can search in a normal select. The timing of when it "resets" is opaque to people who do now how to type. It's a truly awful experience.

Chosen isn't perfect, but I believe its search is a significant improvement over native selects. I don't think it's even close, frankly.
