### ISSUE TITLE
chosen dropdownlist items gets overflowed in IE11 even after list gets closed

### ISSUE THREAD

**Issue by puneetraja** [harvesthq/chosen#1579]
Hi,

The chosen dropdownlist items gets overflowed and shown even after the dropdownlist gets closed in IE 11.

What you have to do-

Just open the multi-select list and hover over the items and then close the list and you'll see the items are still visible in IE11.

Can you help me with this issue.
Here is the image of your site running in IE11.

![chosen](https://f.cloud.github.com/assets/4640164/1225201/67c854fa-2760-11e3-9200-30c06cf80a41.jpg)

**Comment by pfiller** [comment]
Is this still an issue in IE? Somehow I doubt it or there'd be more noise about it ... right?

**Comment by puneetraja** [comment]
Not sure about this. I have not used chosen from a long time now.

But thanks for helping.
