### ISSUE TITLE
Chosen - showing horizontal scrollbar for multi select

### ISSUE THREAD

**Issue by ssssmmmm** [harvesthq/chosen#1581]
Hi, 
  I'm trying to show horizontal scrollbar when the item selected in a multi select is too long. so i changed the style to have overflow-x:auto  and chosen shows the horizontal scrollbar as expected. 
.chosen-container-multi .chosen-choices{ overflow-x: auto; } 

But this tyle is causing issues in regards to selecting the items. Once horizontal scrollbar is visible, when i try to make a selection with the mouse by scroll down the choices, the item that's selected it not added to the selected list of choices instead the previous item to the selected item from the dropdown choices is added to the selected list.

Any help?

**Comment by pfiller** [comment]
This is an ancient issue (almost 3 years old!) so I'm going to close. If you're still experiencing this issue, please provide a link to a demo or [fiddle](https://jsfiddle.net/) that shows how to recreate the problem.
