### ISSUE TITLE
group_search

### ISSUE THREAD

**Issue by pk1m** [harvesthq/chosen#1595]
I'm not sure exactly how this flag is to be used.  I saw it as when searching, groups should not be included.  I'm trying get my search box to show the groups but not match it when searching.  IE "Customers" optgroup in the list, typing C should not return anything unless there is an object with 'Car' then optgroup should show as well since something is matched.

Right off the bat, disabling group_search causes my optgroup to be shown as undefined.  Looking at prototype.result_add_group, it seems like group.search_text is undefined. Caused by this section in winnow_results.

```javascript
if (!(option.group && !this.group_search)) {
  option.search_text = option.group ? option.label : option.html;
  option.search_match = this.search_string_match(option.search_text, regex);
}
```

This leads me to believe group_search is meant for disabling optgroups?  Is this a correct assumption?  

Curious because I'm patching it for my purposes and I want to see if it makes sense to use this group_search flag and fix it, or just create my own flag.

P.S. Posting this here to see if its an actual bug or intended behavior.

Thanks,
Peter Kim

**Comment by pfiller** [comment]
This is now fixed in master and will be available in the next release. Thanks to @k-zelenkov!
