### ISSUE TITLE
Chosen min jquery bug

### ISSUE THREAD

**Issue by ghost** [harvesthq/chosen#1598]
I have a bug when use chosen minify file. With is always 0px. When I use not minify file it's good. When i change minify with this algo it's good: http://refresh-sf.com/yui/

**Comment by pfiller** [comment]
I'm going to hope this issue was fixed sometime in the past 2 and a half years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.
