### ISSUE TITLE
Cropped search input

### ISSUE THREAD

**Issue by baldurpan** [harvesthq/chosen#1600]
Having the same issue as seen here: https://github.com/harvesthq/chosen/issues/1352
Except this only happens when loading the form via ajax.

![screen shot 2013-10-11 at 11 12 43 am](https://f.cloud.github.com/assets/5663654/1313998/5be1e694-3267-11e3-8b51-b2223f989b20.png)

**Comment by pfiller** [comment]
I'm not seeing this. If you'd like to re-open, please provide a link that shows the problem happening (ideally in the form of a [fiddle](http://jsfiddle.net)) so we can help you debug. Thanks.
