### ISSUE TITLE
Floated select causes problems with search

### ISSUE THREAD

**Issue by ncatanchin** [harvesthq/chosen#1607]
I have a select floated left of it's label that I apply chosen to:

![image](https://f.cloud.github.com/assets/2169122/1323511/68947b76-3484-11e3-8fdc-808983ecef44.png)

It causes problems with the dropdown:

![image](https://f.cloud.github.com/assets/2169122/1323514/719684c6-3484-11e3-890e-7cd4f302f397.png)

I used the Chrome console to disable the float left on the select - after it was converted to chosen - and the problem was fixed:

![image](https://f.cloud.github.com/assets/2169122/1323521/8da9897e-3484-11e3-80b1-231fe2eaf7d5.png)

This is not a problem when search is disabled.

**Comment by pfiller** [comment]
I'm going to close this. If you add CSS that breaks Chosen, it's not an issue with Chosen. Sorry!
