### ISSUE TITLE
Working plugin but no style

### ISSUE THREAD

**Issue by florentpoujol** [harvesthq/chosen#1609]
Hey

The plugin works but the form element is not styled correctly, as you can see here (a multiple select, but same thing with a simple select) https://dl.dropboxusercontent.com/u/51314747/chosen_bad_style.png

I added the CSS, and the JS file (the jQuery one, not the prototype), which are properly loaded. The images are in the same folder as the CSS (I tried other location with same results).

Note that my app uses Laravel 4.0.8 (PHP framework), Bootstrap 2.3.2, Former 3.2 (package for Laravel) and jQuery 1.7.1.

What did I do wrong ?
Thanks !

**Comment by pfiller** [comment]
This is almost 2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
