### ISSUE TITLE
Cannot scroll up when you are in bottom

### ISSUE THREAD

**Issue by flokixdev** [harvesthq/chosen#1614]
When you scroll down and then you want to scroll up, that's imposible.

URL: http://obchodpneumatik.cz/pneumatiky/Osobn%C3%AD-Offroad-SUV:-:-:-:-:-/undefined:false/false#filtry/Osobní-Offroad-SUV:155:-:-:-:-

**Comment by judewang** [comment]
I have faced this issue today, and I found this is a bug of jQuery. `.position()` can not get correct value when using jQuery v1.12.0 or some other versions. Updating jQuery to v1.12.1 can solve this issue, or you can update jquery-rails to v4.1.1 or higher.

https://github.com/jquery/jquery/commit/a0f5c357c4b256b03acdc57d5319ebfe4f25a69a
https://blog.jquery.com/?s=position%28%29
