### ISSUE TITLE
Add search field to multi select

### ISSUE THREAD

**Issue by yamlfd** [harvesthq/chosen#1615]
I got usability feedback from users and learned that they do not understand how the search in multi select works without educating them individually. This is a show stopper...

Please add the same search field like shown in single selects to multi selects, too.

**Comment by pfiller** [comment]
I think there's some room for design improvement with Chosen for sure. If you have ideas for how that would look, feel free to share.

Going to close this in the meantime. A redesign isn't on our radar right now.
