### ISSUE TITLE
Changing Image on Selection Not Working Properly

### ISSUE THREAD

**Issue by Travis959** [harvesthq/chosen#1618]
Hi all,

I'm using a script to change an image depending on which selection is made in the multiselect box which works fine as long as you pick your selection in reverse order of the drop down. 

For instance assuming the list is alphabetical, if I pick Brad before I pick Arnold, then the images will change correctly on selection. However, if I pick Arnold, before I pick Brad, the image will change to Arnold, but won't change to Brad. The script works fine in a normal multiple selection box, so I believe it has to do with the way Chosen is handling the selections. Doesn't seem to have anything to do with the selection values or the names of the selections. Only the order of the selection in regards to how it displays in the browser seems to effect it.

For reference sake here is my JavaScript code for changing an image on selection:

window.onload=function()
{
	bp='images/avatar/',
	imgnum=400,
	thumb=document.getElementById('thumb'),
	combobox=document.getElementById('selection[]');
	combobox.onchange=function()
	{
	thumb.src=bp+this.value+'.jpg';
	}
}

Any ideas?

Thank you.

**Comment by pfiller** [comment]
This is almost 2 1/2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
