### ISSUE TITLE
have [x] button on left in ltr mode. 

### ISSUE THREAD

**Issue by Moosh-be** [harvesthq/chosen#1629]
except if if miss a better solution,

when the label off an option is too long,  the  [x] button is out of the box.

Proposition be able to "start" the option with  [x]

![too short for labels withouts spaces](https://f.cloud.github.com/assets/388085/1428652/f78f5d28-40a5-11e3-878b-6023a179bc8c.png)

**Comment by pfiller** [comment]
This is how Chosen works currently. This issue is resolved!

![rtl](http://take.ms/eyvmW)
