### ISSUE TITLE
Original iPad shows blank pane

### ISSUE THREAD

**Issue by RafaPolit** [harvesthq/chosen#1631]
On the original iPad (may be on others as well, but cannot test it):

When you first click on the arrow, the pane appears empty (blank) with only the input box and the height of the would-be options, but no actual options are shown.

If I type on the input box, then it renders the 'filtered' options correctly, and, if I finally delete everything from the input box, it renders all the elements.

Also, if there are 'grouped' options on the chosen, you cannot select any options in the ipad.

I'm attaching an image of the original issue:
![photo](https://f.cloud.github.com/assets/4309019/1434289/ce69b64a-4114-11e3-9c68-e37671b57e07.PNG)

Thanks for any insight,
Rafael Pólit.

**Comment by pfiller** [comment]
I'm going to close this in favor of #2289. Chosen could clearly use some testing on the iPad, but we only need one thread to keep track of the issues.
