### ISSUE TITLE
Commit a distribution version for bower users

### ISSUE THREAD

**Issue by djalmaaraujo** [harvesthq/chosen#1636]
When we install chosen from bower, we don't have a dist file to use right away! In production servers, we have to create a special task only for chosen to run the build command. Usually, all bower components already have a dist file just to use. Please, compress the coffee and sass files intro single js and css files :)

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
