### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by nybblr** [harvesthq/chosen#1643]
Is there a way to add "aliases" for an object?

e.g. Suppose I have a tags multiselect field, and I have a tag called "Ruby on Rails." I'd like to be able to enter "RoR" and have it resolve (or suggest) "Ruby on Rails."

Is there any current functionality to do this, or would it be a feature to add to the bucketlist?

Thanks!
~ Jonathan

**Comment by xkidro** [comment]
+1

**Comment by krazyjakee** [comment]
Sorry to bump, but is there a work-around that doesn't involve using server-side logic? Any suggestions?

**Comment by billylaing** [comment]
+1

**Comment by pfiller** [comment]
Potentially available if something like #628 landed.

**Comment by pfiller** [comment]
Going to close in favor of #800 which has a discussion on searching by arbitrary values (aliases) as well.
