### ISSUE TITLE
Use style width attribute when select list is hidden

### ISSUE THREAD

**Issue by frogmonster** [harvesthq/chosen#1645]
If the select list or its container is hidden, width is set to 0px. I know that we can set the width option on the chosen() method (ie, chosen({width: '100px'}), but that forces us to use a chosen() statement for each and every hidden select vs being able to simply call $('.chosen-select').chosen() (and being able to control look and feel with page level css). 

If there is no width option and offsetWidth is 0px, then chosen should try to use the width style attribute on the select list.

```JavaScript
if (!this.form_field.offsetWidth && this.form_field.style.width) {
	return this.form_field.style.width;
}
else {
	return "" + this.form_field.offsetWidth + "px";
}
```

**Comment by pfiller** [comment]
See #2495 for the latest fix concept.
