### ISSUE TITLE
add dist files

### ISSUE THREAD

**Issue by ghost** [harvesthq/chosen#1656]
Out of 20~ish projects installed through package management, and automated through grunt, chosen is the first who doesn't have dist files in the project source, why is that? 
Since chosen is available through bower it seems like a good practise since people install it through a package manager 'for the web' and the project source right now is just there for contributors.

I tried to setup grunt-contrib-sass and parse it into css which resulted in the error below even though i have the compass gem installed.
Since i coulnd't get it to work i just end up manually downloading the package with the dist files.

'File to import not found or unreadable: compass/css3/box-sizing.'

So why aren't there any dist files/build map in the project source?

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
