### ISSUE TITLE
Chosen dropdown doesn't scroll and doesn't have scrollbars in iOS 4.3

### ISSUE THREAD

**Issue by manoj382** [harvesthq/chosen#1665]
Old iPad/iOS, yes, but I need to support it. Right now when you click on a chosen select menu, the drop down items can't be scrolled through so you're only able to select an item that's visible. 

I pulled up the demo page and confirmed the bug. Is there a quick fix for this that I could implement? Or is iOS < 5 not supported?

Thanks!

**Comment by willcooley** [comment]
I looked into this issue for Tablets:

Having the CSS property "-webkit-user-select" on the "chosen-container" class while using "ul" and "li" tags appears to what hinders its' ability. Removing the CSS property and replacing the "ul" and "li" tags with "div" tags fixes this issue. Obviously would need to update the CSS classes and properties if configured..

**Comment by pfiller** [comment]
Essentially duplicated by #2289 (which came a couple years later and is related to a specific bug fix ... but ends with the same result).
