### ISSUE TITLE
Feature Request :Make Chosen Caja Enabled

### ISSUE THREAD

**Issue by RiteshM** [harvesthq/chosen#1666]
some times i have to work on some Appscript spreadsheet applications.Chosen is pretty awesome for selectboxes its looks are amazing.but it doesn't work on on Appscript apps Html Service.i know u cant port all its features to caja but still u can make it port it upto a good extent.Please make it caja enabled so we can use it in AppScript

**Comment by pfiller** [comment]
I appreciate the request, but it's not gonna happen here. Feel free to fork the project, though!
