### ISSUE TITLE
Not working with jquery version 1.4.2

### ISSUE THREAD

**Issue by chandjitender** [harvesthq/chosen#1673]
Hi

I was using chosen previous veriosn which was working fine with jquery version 1.4.2. But I have problem with this version. It is transforming select menu to custom select menu but when I click to open it is not opening select menu option. Any Idea how to fix it.

Thanks
Jitender

**Comment by pfiller** [comment]
I think this was fixed. I just put together [a fiddle](https://jsfiddle.net/o488oymd/2/) with jQuery 1.4.2 and Chosen 1.5.1 seems to work fine. Marking this as resolved.
