### ISSUE TITLE
how to change option value before open

### ISSUE THREAD

**Issue by chandjitender** [harvesthq/chosen#1674]
Hi
I have dynamic select menu with option like 

``` html
<select id="state" class="chosen-select">
<option>select</option>
<option>New york</option>
<option>Las vagas</option>
</select>
```

I want when I open. The first option need to replace with "select state" and when I select this it should also display as selected option

https://gist.github.com/chandjitender/7750637

Thanks
jitender

**Comment by YogeshBendake** [comment]
how we should select element from chosen dropdown list in selenium webdriver?
please any one have code send, i want to select element using data option array index
 my code is



<div id="category_chosen" class="chosen-container chosen-container-single" style="width: 228px;" title="">
<a class="chosen-single chosen-default" tabindex="-1">
<span>Select an Option</span>
<div>
<b></b>
</div>
</a>
<div class="chosen-drop">
<div class="chosen-search">
<input type="text" autocomplete="off">
</div>
<ul class="chosen-results">
<li class="active-result" style="" data-option-array-index="1">Europe</li>
<li class="active-result" style="" data-option-array-index="2">Mahindra Europe S.R.L.</li>
<li class="active-result" style="" data-option-array-index="3">Mahindra Heavy Engines Pvt. Ltd.</li>
</ul>
</div>
</div>
