### ISSUE TITLE
Chosen Multiple reset doesn't work

### ISSUE THREAD

**Issue by PierceMcGeough** [harvesthq/chosen#1679]
Using the line $(".chosen-select").val('').trigger("chosen:updated"); in a jquery script does not reset the chosen form field. It works ok for the single dropdown though.

**Comment by markusguenther** [comment]
I tried to reset the whole form with something like that:

```javascript
        var form = $('form');
	form.get(0).reset();
	form.find('.filterSelect').trigger('chosen:updated');
```

But i have the similar problem ... for the single drop downs everythings works fine. But the multiple selects don`t have a placeholder anymore.

**Comment by koenpunt** [comment]
Multi-selects expect an array as value, so to reset it using jQuery you can use the following:

```js
$('.chosen-select').val([]).trigger('chosen:updated')
```
