### ISSUE TITLE
onFocus causes auto scroll to x=0 when search is hidden

### ISSUE THREAD

**Issue by demesne** [harvesthq/chosen#1686]
When search box is hidden, and a chosen select is clicked(only on focus), the page auto-scrolls to the hidden search input box, which should not be the case.

Sample:-

http://jsfiddle.net/2bVBN/

**Comment by jjustaments** [comment]
Hi guys,

We also run in this issue.
As a workaround we 'focus' call put inside the IF statement.
```
if (!this.container.hasClass("chosen-container-single-nosearch")) {
  this.search_field.focus();
}
```
