### ISSUE TITLE
How to change background color of the multiple select text box?

### ISSUE THREAD

**Issue by jamesyip** [harvesthq/chosen#1690]
There should be a way to change background color of the text box used to display the selected options.

**Comment by eterry1388** [comment]
Didn't work for me.  This is what I got instead:
![screen shot 2016-11-02 at 9 35 44 am](https://cloud.githubusercontent.com/assets/7739129/19932957/d930269e-a0df-11e6-9dd8-cc4e5e5d038f.png)

**Comment by MrMacvos** [comment]
It's the `ul` that has its own background color. Try this:
```
.chosen-container-multi .chosen-choices {
	background:unset;
}
```
It works for me with a multi-select.
