### ISSUE TITLE
bower install doesn't work

### ISSUE THREAD

**Issue by acornejo** [harvesthq/chosen#1698]
Installing this package through bower does not work.

The reason is that the distributable files (i.e. chosen.jquery.js) is not in the repository.

Please fix this, otherwise people who want to use chosen are forced to install npm, install grunt, and build the package manually. Actually its even worst than that, you also need to install ruby, gem, bundle (I had none of these) to build the css.

Please fix bower install.

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
