### ISSUE TITLE
Options prefixed with "&nbsp;" appearing in results

### ISSUE THREAD

**Issue by inaudi** [harvesthq/chosen#1707]
When I've looking for results starting with "n" I'm receiving the results containing the `&nbsp;`
My code looks like:

``` html
<select class="loc" multiple="multiple" name="rs_loc" data-placeholder="Locations" tabindex="3">

    <option class="lo" value="af_cd">&nbsp;&nbsp;Congo</option>

    <option class="lo" value="af_mz">&nbsp;&nbsp;Mozambique</option>

    <option class="lo" value="af_na">&nbsp;&nbsp;Namibia</option>

    <option class="lo" value="oc_nz">&nbsp;&nbsp;New Zealand</option>

    <option class="lo" value="oc_ph">&nbsp;&nbsp;Philippines</option>

</select>
```

and in results for "n" I'm receiving the:

``` html
&nbsp; Namibia
&nbsp; New Zealand
```

when I'm searching for other countries the results are being showed without the &nbsp;
How do I have to use chosen plugin to handle this issue?

Thanks,
Rob

**Comment by RuchiraG** [comment]
This issue is there again on version 1.4.2.

**Comment by RuchiraG** [comment]
Solution proposed by @tharban worked for me in the below thread

https://github.com/harvesthq/chosen/issues/2274

**Comment by chrisdeeming** [comment]
Just another vote to say there is a regression in the jQuery version for 1.4.2.

**Comment by ezhirkumaran** [comment]
hi Team
Still the bug is appearing in one of my uni project. Could someone look into it ?
