### ISSUE TITLE
Get input value even if "No results match"

### ISSUE THREAD

**Issue by Cynaraa** [harvesthq/chosen#1713]
Hi, I'm not sure if this issue is related to this:
https://github.com/harvesthq/chosen/issues/550#issuecomment-31435098

but my question is,

Hi, how do I get the input values in the text field when the select value is "no match".
I need to get the string input even if it is not included in the select options.

I need to get xxx from here:

No results match "xxx"

Thank you very much for your response!

**Comment by SivanKarthick** [comment]
$(".chosen-container").bind('keyup click',function() {
	if($(".chosen-results").children('li').hasClass('no-results'))
	{
		//alert("Please Select the value only from dropdown");
		var kart=$('.chosen-results .no-results span').text();
		$('.chosen-single span').text(kart);
		flag=1;
		return false;
	}
	else
	{
		flag=0;
		return true;
	}
});
