### ISSUE TITLE
Chosen spits out two "chosen-container" divs when more than two select inputs on screen

### ISSUE THREAD

**Issue by jazzdrive3** [harvesthq/chosen#1743]
This plugin is working as expected for most cases. I have one place where there are more than two selection inputs. At least that seems to be the thread.

It also throws the following error:

"Uncaught TypeError: Cannot read property 'length' of undefined "

But the first selection box gets two  "chosen-container" divs and then hides the wrong one. Very strange. See attached images. I get a "Select an option" text with no options.

![screen shot 2014-01-23 at 5 20 09 pm](https://f.cloud.github.com/assets/5509296/1989880/a7e5c7b0-847c-11e3-9835-fa153bf76c23.png)

Here is the HTML code:

```
<div class="chosen-container chosen-container-single chosen-select ctools-auto-submit form-select" style="width: 200px; /* display: none; */" title="" id="edit_select__4_chosen"><a class="chosen-single" tabindex="-1"><span>- Select -</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off"></div><ul class="chosen-results"><li class="active-result result-selected" style="" data-option-array-index="0">- Select -</li><li class="active-result" style="" data-option-array-index="1">59(24)</li><li class="active-result" style="" data-option-array-index="2">14(18)</li><li class="active-result" style="" data-option-array-index="3">02(16)</li><li class="active-result" style="" data-option-array-index="4">06(9)</li><li class="active-result" style="" data-option-array-index="5">05(8)</li><li class="active-result" style="" data-option-array-index="6">62(8)</li><li class="active-result" style="" data-option-array-index="7">2A(6)</li><li class="active-result" style="" data-option-array-index="8">2C(6)</li><li class="active-result" style="" data-option-array-index="9">60(6)</li><li class="active-result" style="" data-option-array-index="10">61(6)</li><li class="active-result" style="" data-option-array-index="11">2F(5)</li><li class="active-result" style="" data-option-array-index="12">CA(5)</li><li class="active-result" style="" data-option-array-index="13">1C(4)</li><li class="active-result" style="" data-option-array-index="14">1F(4)</li></ul></div></div>
```

```
<div class="chosen-container chosen-container-single" style="width: 90%;" title="" id="edit_select__4_chosen_chosen"><a class="chosen-single chosen-default" tabindex="-1"><span>Select an Option</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off"></div><ul class="chosen-results"></ul></div></div>
```

These come right after the other. The second one has no results and is the one shown.

This also breaks the rest of the javascript on the page, so other things do not work, like Colorbox.

As you can see, both have the same ID.

Any insight is appreciated.

**Comment by fadelle** [comment]
please help,
i know chosen consists of an input search and ul dropdown .
chosen:updated update all the chosen-select (input search and dropdown)
So the question is: what if i want to update only the dropdown list without updating the input search(because it is deleting my search text while updating)

**Comment by monuthakur** [comment]
How to change the auto direction??

**Comment by monuthakur** [comment]
How to add the auto direction option??

**Comment by akash-cp** [comment]
Any updates oon this, i am facing this issue ?
