### ISSUE TITLE
selecting items a second time "chosen:updated" does not work

### ISSUE THREAD

**Issue by bravehurts** [harvesthq/chosen#1747]
If you select items via selector the update will work only one time.
The second time the update does not work.

``` javascript
$('#test>option').attr('selected','selected');
$('#test').trigger('chosen:updated');
```

If you deselect all it will work every time

example
http://jsfiddle.net/kVE94/1/

click the all button, none button and all again

edit:tested on firefox 26 on windows 7 and ubuntu 
tested with jquery 1.10.1 and 2.0.2

edit second time

SOLUTION:

okay, I debugged the script and I found a solution. Seems that jquery/firefox does not set the selected property of the options. It will set a attribute "selected" and not the "selected" property to true. Seting the property will fix it.

This will fix the issue

``` javascript
$('#test option').attr('selected','selected');
$('#test option').prop('selected',true);
```

**Comment by kometen** [comment]
Thank you! :-)

**Comment by marcelm1706** [comment]
Wow this saved me a lot of time! Thanks a lot!

**Comment by simov** [comment]
:+1:

**Comment by dan33gopo** [comment]
had same problem in firefox. thank you.

**Comment by Said007** [comment]
Thanks

**Comment by mani619cash** [comment]
You are legend sir. Thanks for this.

**Comment by whereisbug** [comment]
This is the right solution. Think you very much !

**Comment by MetaiR** [comment]
@braddunbar 
solution is not working for me
