### ISSUE TITLE
Performance penalty for accessing offsetWidth in AbstractChosen.prototype.container_width

### ISSUE THREAD

**Issue by cnizzdotcom** [harvesthq/chosen#1759]
We heavily use chosen (v1.0.0) in a portion of our application which can have over 1000 instance of chosen drop down elements in a given page. It's extreme I know. I've been profiling the application attempting to determine why its so slow. I could see early on Chosen was a big culprit, but worried I'd be rewriting huge swaths of a library so I avoided rolling up my sleeves. Finally I did. The chrome profiler pointed me towards AbstractChosen.prototype.container_width().

It appears line 436 causes "browser reflows". I haven't educated myself on exactly what these are beyond they are slow. The solution is to set a width when you are instaniating chosen on a dropdown so it does not have to access offsetWidth. This massively improved performance in certain use-cases for us (like 20 seconds faster).

I'm putting this here for others that may run into this problem. Also to the developer(s) of chosen perhaps a console.log warning may be written if developers do not set a default width. This log could warn them of performance pitfalls. Thankfully, it was an easy fix and the developer(s) was smart to only use the offsetWidth if options.width was not set.

**Comment by pfiller** [comment]
Thanks @cnizzdotcom. Using 1000 instances of Chosen on a page is certainly unique so I imagine this is the kind of problem we won't try to solve with extra code.This is certainly useful for anyone who comes across a similar situation!
