### ISSUE TITLE
Feature: Select all (Ctrl+A) and delete in Multi-Select control

### ISSUE THREAD

**Issue by am11** [harvesthq/chosen#1760]
Inspired by: Stackoverflow.com > Ask Question > Tags box

Please bind the Ctrl+A key so all the selected boxes in multi-select box are selected. Once selected, pressing backspace (or del) should remove them all.

**Comment by pfiller** [comment]
I don't really see this as being a great thing to add to Chosen. Keyboard shortcuts make sense when they're somewhat natural or discoverable ... and I don't think I'd expect this behavior when hitting CTRL/Command + A.
