### ISSUE TITLE
How to change the background color on hover in chosen dropdown?

### ISSUE THREAD

**Issue by manuthalasseril** [harvesthq/chosen#1768]
I want to change the background color of chosen dropdown while we hover on elements. On which place we edit for achieve this?

**Comment by sohailamjed** [comment]
@pfiller  Is there any way to change the chosen drop down Menu background using java script/Jquery if there were no selection made. Means if there is chosen drop down where first Item is Please select Second option is OptionNumber 1 and 3rd is OptionNumber 2. If you user do not select Option number 1 and Option Number 2 then chosen drop down menu color should be changed...
