### ISSUE TITLE
Chosen With Zepto [ WORK ]

### ISSUE THREAD

**Issue by lucasbarbieri** [harvesthq/chosen#1773]
I have changed the jquery prop. to zepto prop in chosen.jquery.js and all work great.

outerHeight = height
outerWidth = width 

Just using box-size in css prop.

thanks.

**Comment by htstudios** [comment]
This is actually still a good idea because #1740 never made it. Making a small patch like the one @lucasbarbieri suggests to make it work with Zepto already helps tons because it frees one of the big jQuery dependency.
