### ISSUE TITLE
Max height and/or add scrollbars when many/all items selected

### ISSUE THREAD

**Issue by syg6** [harvesthq/chosen#1775]
I have multiple selects and have created a "Select all" button. It works fine but depending on the content, the Chosen select sometimes grows to absurd sizes.

Is it possible to set a max height, and if the content grows beyond that height, for scrollbars to appear?

**Comment by akhildave** [comment]
@willl  Yes it works better.. Thanks!!

**Comment by kalebanderson** [comment]
Thanks @willl for solving my problem almost 4 years later!
