### ISSUE TITLE
tabindex always set to -1

### ISSUE THREAD

**Issue by TDK1964** [harvesthq/chosen#1784]
No matter what I try I cannot get the correct tabindex set.

I have chosen v1.10 and have using it with MVC 4 like so
@Html.EditorFor(e => e.CostCode, "DropDownListChosen", new{tabindex = 5})

The editor template looks like this

<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl"%>
<%=Html.DropDownList("", (IEnumerable<SelectListItem>) ViewData[ViewData.ModelMetadata.PropertyName] , new { tabindex = ViewData["tabindex"], @class = "chosen-select", data_placeholder = "Default...", id = ViewData.ModelMetadata.PropertyName, style = "width:Auto;" })
%>

<script type="text/javascript">
    $(document).ready(function () {
        $("#<%=ViewData.ModelMetadata.PropertyName%>").chosen({ max_selected_options: 2, width: '254px' });
        //$(".chosen-deselect").chosen({ allow_single_deselect: true });
        $("#<%=ViewData.ModelMetadata.PropertyName%>").chosen().change();
        $("#<%=ViewData.ModelMetadata.PropertyName%>").trigger('liszt:updated');
        $("#<%=ViewData.ModelMetadata.PropertyName%>").chosen();
    });
</script>

**Comment by Jogai** [comment]
Here is a fiddle: http://jsfiddle.net/pwoyjy1m/1/
(was researching something else)

**Comment by pavdro** [comment]
Still having the issue in version 1.4.1.
Tried Chrome and FF
