### ISSUE TITLE
Disallow case sensitive search, allow space (blank)

### ISSUE THREAD

**Issue by ghost** [harvesthq/chosen#1799]
Hi, is there any option so i can search uppercase lowercase words without problems ??? because the search must be exact.

Thanks alot !

**Comment by EG3007** [comment]
I am using Chosen 1.4.2 and it's realy so big problem for me the case-sensitive.
For example; when i start to type "ist" it's not finding the result "İSTANBUL" i have to write İSTANBUL to find. How can i fix it ? What should i do ?
