### ISSUE TITLE
Dropdown closing on Microsoft Surface 1 RT

### ISSUE THREAD

**Issue by jonsprague0000** [harvesthq/chosen#1807]
When scrolling on the Microsoft Surface 1 RT the dropdown randomly closes.  The issue is not able to be reproduced on the Microsoft Surface 1/2 Pro.  Does anyone have a fix for this issue?

**Comment by pfiller** [comment]
Going to close this unless someone can still reproduce it. Does anyone even own an original surface or have they all been jettisoned to the moon?
