### ISSUE TITLE
Add "main" field to bower.json

### ISSUE THREAD

**Issue by donv** [harvesthq/chosen#1811]
This should fix the following message from rails-assets-tether:

```
This component doesn't define main assets in bower.json.
Please open new pull request in component's repository:
https://github.com/harvesthq/chosen
```

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
