### ISSUE TITLE
Background size search choices multi select

### ISSUE THREAD

**Issue by koenpunt** [harvesthq/chosen#1821]
When having a lot of items selected the background gradient gets expanded, which I think is not that nice..
@mlettini What is your opinion on this?

![screen shot 2014-03-11 at 17 11 02](https://f.cloud.github.com/assets/351038/2387526/d9469e08-a937-11e3-9862-6c85da56b4e6.png)

**Comment by koenpunt** [comment]
Even though the gradient is more subtle now, it's still expanding:
![image](https://cloud.githubusercontent.com/assets/351038/10247886/5eae4c58-691c-11e5-9910-7029fa0e1940.png)

**Comment by mlettini** [comment]
Because it's still a background gradient. That should be replaced by an inset `box-shadow`.

**Comment by koenpunt** [comment]
@harvesthq/chosen-developers anyone up for this huge task? :wink:

**Comment by pfiller** [comment]
Looks like this was fixed at some point? I think so!

![yeah?](http://take.ms/gGHTP)
