### ISSUE TITLE
Opening Chosen menu with spacebar when using disable_search_threshold scrolls page

### ISSUE THREAD

**Issue by kbav** [harvesthq/chosen#1834]
## Desired Behavior
Default browser behavior: When a `<select>` is in focus, hitting the spacebar opens the menu.

## The Bug
This works as expected in Chosen, except when using `disable_search_threshold`. _(I'm guessing that removing the search removes what was capturing the spacebar press.)_

Test case: This behavior can be found on [Chosen's documentation page](http://harvesthq.github.io/chosen/#hide-search-on-single-select):
 1. Focus the Chosen field demonstrating disable_search_threshold
 2. Press spacebar (to open the menu)
 3. Observe how the page scrolls instead of staying in place for the open menu

## Tested Browsers
Browsers effected:
- OSX: Chrome 33
- OSX: Safari 7.
- Win7: IE9 (spacebar doesn't open `<select>` as a default browser behavior but it otherwise does for Chosen fields)
- Win7: IE10

Browsers not effected:
- OSX: FireFox 28.

**Comment by pfiller** [comment]
I think this is probably a #wontfix. `disable_search_threshold` has no search field so there's no easy way for us to capture keyboard events. We'd have to add a bunch of code around a feature I'd prefer didn't exist anyways (Chosen with no search field).
