### ISSUE TITLE
Click selection after Tab selection on search

### ISSUE THREAD

**Issue by polmbo** [harvesthq/chosen#1857]
First type into the search field on Standard Select and then use the Tab key to select your value. Then open the choice list again and use the mouse to select an option, the value doesn't change. 

This is happening on http://harvesthq.github.io/chosen/ in both Chrome and IE

**Comment by pfiller** [comment]
This issue is over 2 years old, so I'm going to close it. Chosen has changed a lot in those 2 years and so have browsers. It's possible this isn't a thing any more.

If it is, please feel free to re-open.
