### ISSUE TITLE
For a simple select, should the drop down scroll under the mouse when item is partially hidden?

### ISSUE THREAD

**Issue by lukeapage** [harvesthq/chosen#1865]
When a result item is partially hidden and you mouse over it, it scrolls the results so the item is fully in view. Because the selected item is in view when opening this can cause the results to jump as the user moves the mouse down over the first item.

The jumping effect can be partly mitigated by changing the height of the results overflow to match an exact number of items, but a) smooth scrolling and b) when you have an item go on to 2 lines, means that you can still have the results jump as you mouse over.

I would suggest that it is a little better user behaviour for result_do_highlight to not scroll the results on mouse over. It should obviously continue when using the keyboard.

Do you agree? I am happy to make a pull request, but I wanted to get agreement that the concept is good before I work on it.

**Comment by pfiller** [comment]
I agree that the scroll behavior can be a bit jumpy at the bottom, but it doesn't bother me all that much. You have to be scrolling at the bottom and moving quite slowly. I'm going to #wontfix this.
