### ISSUE TITLE
Use chosen:ready to set additional data for each item.

### ISSUE THREAD

**Issue by samhibberd** [harvesthq/chosen#1876]
How do you access the original option(s) data- attributes within the on chosen:ready event. I need to access some data objects and append / prepend some html to the new list options, created by chosen, based on the values stored in data objects:

    <option value="star" data-vendor="Vendor" data-icon="<i class='fa fa-star'></i>">Star</option>

Any thoughts?

**Comment by pfiller** [comment]
This is over 2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
