### ISSUE TITLE
How to force line-break in chosen list

### ISSUE THREAD

**Issue by peterbra** [harvesthq/chosen#1889]
I am just curious - how to force `<br>` in chosen drop-down list ?
I've tried with `<br>` and `<wbr>`, but it seems that it just breaks line when sentence in list hit's full width of container. Can I force the line-break on place where I want that to be ? NOTE: I need just line break in drop-down list - NOT when option is selected (and it's wider than container so normally css overflow hidden kicks in and that's totally fine, so I need line break only in drop-down list )

**Comment by ElectricDrake** [comment]
Super old post but thank you for the clear:both; comment... was trying to accomplish this and using css clear:both; was exactly what I needed... it just wasn't coming to my brain for some reason...
