### ISSUE TITLE
Bug with showing and hiding options

### ISSUE THREAD

**Issue by neonwired** [harvesthq/chosen#1895]
If you use jquery to hide option elements then update chosen it works fine by adding an inline style of display: none to the list items that are now hidden. However when you show them again and update it then changes the inline css to display: inline rather than restoring it to it's previous state.

**Comment by pfiller** [comment]
I'm not able to recreate this issue. I'm guessing it's been fixed in the 2 years that have passed since it was open. If you are still seeing it, please re-open the bug with a link to a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.
