### ISSUE TITLE
Chosen placeholder behavior on mobile

### ISSUE THREAD

**Issue by hmaesta** [harvesthq/chosen#1901]
Chosen do not work in Mobile [#27], so the attribute ```data-placeholder``` is ignored.

The problem is, to have a placeholder in *desktop*, we need to add a blank  ```<option>```, like the documentation says:

> Note: on single selects, the first element is assumed to be selected by the browser. To take advantage of the default text support, you will need to include a blank option as the first element of your select list.

So, because of this blank ```<option>```, when we open a select [that uses Chosen] on mobile, the result is really confuse (and ugly).

![blank](https://cloud.githubusercontent.com/assets/741969/2747836/410b11c2-c78d-11e3-80d1-42943de64a05.png)

As a suggestion to fix it, I would say that instead of using a *blank option* we should use a *selected and disabled option*.
```html
<option selected disabled>placeholder</option>
```

So, when Chosen recognize that the first option is selected and disabled, it would shows it as a placeholder (and the attribute ````data-placeholder```` would be useless), **and** in mobile everything would be fine.

**Comment by MsDacia** [comment]
Do you have a working example of this suggested solution?

**Comment by pfiller** [comment]
> But on the other hand, is it actually a problem to have this empty value? 

I would argue that it's not. Going to close this issue with no changes.

**Comment by keshavakeshu** [comment]
By Default Its showing "0 Selected" and "0 items" as a placeholder on android and ios mobiles respectively. In Desktop the placeholder works fine but not in mobiles. My concern is to change the placeholder for Mobiles from "0 Selected" to "Select option". How can i achieve this plz suggest me.
