### ISSUE TITLE
feature(bower.json): add bower.json

### ISSUE THREAD

**Issue by remiwebs** [harvesthq/chosen#1908]
Bower only recognizes dependencies in bower.json. Because bower.json is missing, dependancies like jquery are not installed. In this case my request is to add bower.json.

Cheers

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
