### ISSUE TITLE
[Feature] Sorting for multiple selects

### ISSUE THREAD

**Issue by lightglitch** [harvesthq/chosen#192]
I started implementing a sortable option for multiple selects at:

https://github.com/lightglitch/chosen

My question is how should I submit the order to the server?
- Implement a hidden input with the sort order
- Implement a hidden select where the options are inserted in the correct order and rename the original
  ...

What do you think is the best option?

**Comment by abuzer-firdousi-confiz** [comment]
Any update on this?
