### ISSUE TITLE
Need to add custom value which are not present in chosen select options

### ISSUE THREAD

**Issue by AnshuDahiya** [harvesthq/chosen#1926]
Hi,
I want to type custom value in the chosen drop down and while save data, get that value from it. But while doing so, firstly it tried to matched with already predefined options. If not match, remove that text from there once we click over another field.
I need that value also so that i will add up custom value into db so that next time that value must shown up there.
How to do??

**Comment by dangbert** [comment]
FYI for those interested in this, [here's a snippet of code](https://github.com/harvesthq/chosen/pull/166#issuecomment-692317968) you can use with chosen allowing users to add custom options to the dropdown

![93138737-76bb8f80-f6ad-11ea-9ebb-4cc41fdefdcf](https://user-images.githubusercontent.com/6439020/93371049-8d292e80-f806-11ea-8fb4-f05b618c02e1.gif)
