### ISSUE TITLE
Chosen and Bootstrap 3.1.1 not playing well in Chrome?  (at least Chrome)

### ISSUE THREAD

**Issue by justicegray** [harvesthq/chosen#1931]
Saw someone raise this in a previous issue (1905) but that issue was closed when I left my comment.  At the time you asked for more detail, hopefully this helps.

Image one is the behavior in Chrome when I have references to bootstrap.min and bootstrap.theme from http://netdna.bootstrapcdn.com, and then a reference to the chosen.css:
![chosen_with_bootstrap](https://cloud.githubusercontent.com/assets/7016236/2909277/0b15c712-d631-11e3-802b-1bab1758e709.png)

Note the weird "garbage" on the text of the select.

Image two is the behavior in Chrome when I comment the CSS references to bootstrap out. That's literally the only difference.
![chosen_without_bootstrap](https://cloud.githubusercontent.com/assets/7016236/2909287/27324466-d631-11e3-8b1d-ffa88225e42f.png)

Tried this out on both Windows 7 and Mac Chrome.

**Comment by pfiller** [comment]
Both libraries have changed dramatically in the past 2 years. I think it's ok to close this issue!
