### ISSUE TITLE
Styling the multiple chosen select input

### ISSUE THREAD

**Issue by FishyZA** [harvesthq/chosen#1933]
Not sure where to ask or where to turn, I have copied the bit that I require for a little offline project into one php page, seems like everything is working, except the data-placeholder that does not display properly, it is as if the text or padding is too small or too much.

I tried editing the chosen.css but i cannot for the life of me figure out why it looks the way it does...
![chosen](https://cloud.githubusercontent.com/assets/7525977/2918725/6a0e5962-d6d3-11e3-8803-ea21e7103de7.JPG)

any help getting the placeholder to read properly?

**Comment by mbsankar84** [comment]
Hi..I need to add search input for chosen-multiple dropdown as single chosen-select ..  can you provide the fix / code here, or do we have fixed it in latest versions ? Thanx advance !
