### ISSUE TITLE
data-placeholer: chosen:activate not removing placeholder-text

### ISSUE THREAD

**Issue by CZ90** [harvesthq/chosen#1941]
I'm having several forms where i'm using Chosen-Multiselect-Boxes with data-placeholder texts. When i'm clicking the chosenbox, the placeholder text vanishes and i can start typing to search for entries in my chosenbox.
But if i'm triggering the "chosen:activate" event in my javascript, the placeholder-text is still inside the the chosen box and stays there, even when i start typing.

**Comment by neurotik1** [comment]
You can modify the Chosen.prototype.activate_field function to return an empty string if selected_option_count is 0/null.

For example, in chosen.jquery.js I changed:
`this.search_field.val(this.search_field.val());`
to:
`this.search_field.val(this.selected_option_count ? this.search_field.val() : '');`

**Comment by pfiller** [comment]
I'm not able to recreate this issue so I'm going to assume it was fixed sometime in the past 2 years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.

**Comment by k3nyamas** [comment]
This issue is still occurring https://jsfiddle.net/k3ntaro/ntoseaga/5/

Possible workaround:
When `chosen:updated` is called after `chosen:activate`, placeholder text is disappeared.

**Comment by k3nyamas** [comment]
This issue is still occurring https://jsfiddle.net/k3ntaro/ntoseaga/5/

Possible workaround:
When `chosen:updated` is called after `chosen:activate`, placeholder text is disappeared.
