### ISSUE TITLE
Uncaught TypeError: Cannot set property 'selected' of undefined

### ISSUE THREAD

**Issue by jonathanadler** [harvesthq/chosen#1942]
Hi,
I'm using jQuery v1.11.0 and Chosen v1.1.0, and in some particular situation I'm getting the error in the title.
It only happens when I choose an option and after that try to choose the last option (by clicking on it and by pressing enter).
I've also noticed that if I choose another option (other than the last option), the selected item I get (on the select element's value) is the one before what I've just chosen.

I'm using the most simple configuration, no multiselect or anything. I just use data-placeholder.

One last thing: 
I'm using Angularjs, and its ng-options directive (along with an ng-model), which means I first wait for the DOM to be ready and only then I call the chosen function (using timeouts).

Thanks.

**Comment by Hipokryta** [comment]
I have this same error and adding empty option tag didn't fix it :/
Any ideas ?

**Comment by pfiller** [comment]
I'm not able to recreate this issue so I'm going to assume it was fixed sometime in the past 2 years. If you are still experiencing it, please re-open the issue and include a demo or [fiddle](https://jsfiddle.net/ntoseaga/) that shows how to make it happen.

**Comment by Lomse** [comment]
I'm having the same issue. 
![screen shot 2017-04-14 at 5 52 22 pm](https://cloud.githubusercontent.com/assets/4754182/25051241/2a1ebf1c-213b-11e7-9da6-aea2e5512ecf.png)

**Comment by zm-john** [comment]
```javascript
$.ajax({
 
    // ...
    success: function() {

        $("#select_elem").empty();

        /* append option or update option there */

        $("#select_elem").trigger("chosen:updated");

    }

    // ...
 });
```

it works for me.

**Comment by Samkough** [comment]
@zm-john where did you put that code?

**Comment by zm-john** [comment]
@Samkough 
I haven't put code,  just adjust calling function order.

First call `empty` function. Then update select tag's options. Finally call `trigger`  function.

**Comment by fhls** [comment]
As victoria34's reference, try with adding an dummy <option> tag and it fixes this issue.
For example,
<select chosen class="form-control" ...>
	<option disabled></option>
</select>
