### ISSUE TITLE
Open dropdown when tabbed onto field

### ISSUE THREAD

**Issue by SFPink** [harvesthq/chosen#1947]
Hello,

Is there a way of opening the drop down when the user tabs onto the chosen select?
I haven't seen anything in the docs regarding this but then again I could have missed it.

Found this after a quick search:

    $('body').on('focus', '.chosen-container-single input', function(){
        if (!$(this).closest('.chosen-container').hasClass('chosen-container-active')){
            $(this).closest('.chosen-container').trigger('mousedown');
            //or use this instead
            //$('#select').trigger('liszt:open');
        }    
    });

Will give this ago. I don't suppose there is an option built in though?

Thanks

**Comment by pfiller** [comment]
@SFPink's temporary solution looks like a good workaround. I'm closing this up!
