### ISSUE TITLE
chosen conflicts after ajax form submission

### ISSUE THREAD

**Issue by dams666** [harvesthq/chosen#1952]
Hi,
I'm using chosen in a form that is sent in AJAX via jquery

The issue I'm facing is when the sub form is reloaded after invalidation : it triggers an event that send a  POST request when the dropdown list is showed

my code: this script is executed when the form is reloaded:

```javascript
$(function() {
	$('#step1-country').off();
	$('#step1-country').chosen({width: '100%'}).on('chosen:showing_dropdown', function(e, params) {
		;e.preventDefault();
	});
});
```

How can I delete the previous instance of chosen and re-initialize properly ?
Thanks in advance

**Comment by pfiller** [comment]
I'm going to assume that you don't need help on this 2 year old issue at this point. Closing it up.
