### ISSUE TITLE
Javascript Error when there is no option and the update event is fired

### ISSUE THREAD

**Issue by msieurtoph** [harvesthq/chosen#1955]
Let's say the `select` element does not have any `option` during the initial setup.
If you modify the DOM to add `option`'s in it and then trig the `chosen:update` event, a Javascript error pops up : 

```
Uncaught TypeError: Cannot read property 'length' of undefined 
```

I fixed it by modifying the line 788, (in `Chosen.prototype.results_build`) :
```
if (this.disable_search || this.form_field.options.length <= this.disable_search_threshold) {
```
into 
```
if (this.disable_search || (this.form_field.options? this.form_field.options.length : 0) <= this.disable_search_threshold) {
```

FYI , I am using the current version : http://cdnjs.cloudflare.com/ajax/libs/chosen/1.1.0/chosen.jquery.js
in Chrome Version 35.0.1916.114 m

Otherwise, thanks a lot for this excellent and really relevant plugin.

-----

EDIT : if it can help understanding the pb, I set up the chosen plugin this way : 
```
xxxx.chosen({no_results_text: "You did not type enough character",
			disable_search_threshold:-1, // always display search field even if empty
			placeholder_text_single : "Type at least 2 characters",
			})
```

I need to make the user type at least 2 characters before to dynamically populate the `select`, because the options list would be way too big if not. 
To populate, I listen to `keyup` and `paste` events on the search_field and make an ajax call to get a pre-filtered list of options to add to the empty `select`. 

I think the `disable_search_threshold:-1` is the problem key : this is not the way it should be used ... but I do not know how to display search_field otherwise.

**Comment by realmag1c** [comment]
This mistake disapear then i closed form tag </form> in html.

**Comment by pfiller** [comment]
I just tried to recreate this issue and couldn't do it. It's 2 years old, so it's possible that all of these things were fixed. I do seem to remember doing some work around these things, but it's hazy ... 2 years is a long time.
