### ISSUE TITLE
disabled dropdown doesn't have css applied

### ISSUE THREAD

**Issue by rajkishor09** [harvesthq/chosen#1958]
1. if a dropdown is disabled on page load then chosen is not rendering on those control.
2. in cascaded dropdown, primary dropdown showing properly but if dependant dropdown is disabled and it is enabled via AJAX operation then its keep on adding for each request. (http://imgur.com/uhEjvoz)
note: on AJAX call complete I am setting chosen again on that control

**Comment by pfiller** [comment]
Chosen works fine on a disabled dropdown. This issue is almost 2 years old so perhaps something fixed it along the way!
