### ISSUE TITLE
RTL scrolling issue

### ISSUE THREAD

**Issue by eugenem** [harvesthq/chosen#1967]
I've got strange issue with FF 30 and IE (9-11): when I've got long select (few dozen items) and RTL orientation, scrolling by mouse wheel doesn't work at all. I have to manually drag the scrollbar. You can check it here: http://mednikov.info/lawdata/search_psikim.html

Your sample page is working even with long RTL select. The only thing I do is:

	$('.main select').chosen( {
		disable_search: true
	});

And some CSS customizations, which I don't see how could be related...

**Comment by pfiller** [comment]
It's 2 years later, but I see your problem! You're being affected by #86. Your instance of Chosen is in a box with overflow:hidden turned on!
