### ISSUE TITLE
Breaks when select id attribute contains a dot

### ISSUE THREAD

**Issue by wosc** [harvesthq/chosen#1970]
If the tag id contains a dot (e.g. ``<select id="foo.bar">``), Chosen breaks when it looks for the matching label, since it passes the ID unescaped to jQuery (see also #110, same situation, different part of the codebase, has since been fixed).

I guess the solution is that set_label_behavior should employ the escaping mechanism outlined in https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/

**Comment by koenpunt** [comment]
Closing as not-reproducible. Might be an issue with older versions of jQuery
