### ISSUE TITLE
Bower installs a development package with no built JS or CSS

### ISSUE THREAD

**Issue by sr-ix** [harvesthq/chosen#1980]
Generally packages installed from Bower tend to have the pre-built scripts and styles for easy use right away.

Installing chosen using a a bower.json manifest installs only the development version, meaning one needs ruby & node to compile and build the src before even being able to use.

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.
