### ISSUE TITLE
How to clear selected value in single select dropdown

### ISSUE THREAD

**Issue by mahdi87gh** [harvesthq/chosen#1988]
Hi
I want to clear the current selected item when new search has no result , but i want to keep the search query in search box.
how should i do that?

**Comment by pfiller** [comment]
If you wanted to clear the selected result, you'd need to modify the [section of Chosen that display the no results messaging](https://github.com/harvesthq/chosen/blob/7b44637a605c315d7ef86f74ecf1514577849d1f/coffee/lib/abstract-chosen.coffee#L197-L199):

```
    if results < 1 and searchText.length
      this.update_results_content ""
      this.no_results searchText
      // Unset value here!
```
