### ISSUE TITLE
Trigger change event on selectedIndex change

### ISSUE THREAD

**Issue by whitekyo** [harvesthq/chosen#1992]
for example:
if we set a change event on the native select ,when, it's options 's value are all the same

```html
<select>
 <option value="1">1</option>
    <option value="1">2</option>
    <option value="1">3</option>
    <option value="1">4</option>
    <option value="5">5</option>
</select>
```
the change event will be happen when you chose the select,but ,in chosen ,it doesn't work,becase the code in chosen:
```js
this.form_field_jq.val() !== this.current_value
```
if the value of option does not change ,it will not trigger the change event。
I think it may not be a bug.but,it sometime bring uncomfortable when I use it.

**Comment by koenpunt** [comment]
This is no longer an issue.
