### ISSUE TITLE
Upon tapping a selection from the dropdown, the input element directly underneath gets focus

### ISSUE THREAD

**Issue by bguiz** [harvesthq/chosen#1996]
Affects iOS Safari.

When you have a chosen select, followed by a number of standard `<input>` fields directly below it:

- Tap the chosen select
- Dropdown appears, covering the standard `<input>` elements below it
- Tap one of the entries in the dropdown
- That entry gets selected, and the dropdown is hidden
- The `<input>` element directly underneath the dropdown entry that was tapped gets focus

The last step in this sequence in the problem. It should not happen. It seems that the event listener does not handle the event, and instead let's it bubble up the DOM hierarchy.

**Comment by pfiller** [comment]
Was this issue fixed when #2093 landed? If so, can #1997 be closed?

**Comment by pfiller** [comment]
I'm pretty sure this was fixed by #2093. If not, let us know.
