### ISSUE TITLE
Adding a character resets highlight selection

### ISSUE THREAD

**Issue by mitchhentges** [harvesthq/chosen#1999]
Regardless of what element is currently highlighted (regardless of reason - arrow keys or mouseover), adding an additional character to the search field will reset the highlight to the top element.

![addcharacterreset](https://cloud.githubusercontent.com/assets/7784737/3431740/5edb534c-006d-11e4-8a62-afb4a421827e.gif)

**Comment by koenpunt** [comment]
This probably only feels weird when having a lot of similar options. But it's hard to maintain a position in the list, when the options in the list are changing. So closing this, but in any case you want to submit a fix which doesn't involve to much logic, we might accept it.
