### ISSUE TITLE
Better handling of 0 width Chosen

### ISSUE THREAD

**Issue by utkant** [harvesthq/chosen#2001]
I am not sure why this is but I guess it is because it cannot be calculated its width. I therefore suggest it to be set to 100%(or not set at all) instead, so that it shows up when shown. If the function container_width could be changed to this:

    AbstractChosen.prototype.container_width = function() {
      if (this.options.width != null) {
        return this.options.width;
      } else {
          if (this.form_field.offsetWidth == 0) {
              return '100%';
          } else {
              return "" + this.form_field.offsetWidth + "px";
          }
      }
    };

I think that would make alot of people happy. I made that change and it helped me...

**Comment by pfiller** [comment]
Oh man this issue is sooooooo old. I think there's enough open width things (including my old, old pull #1439) that it's probably not necessary to keep it open.
