### ISSUE TITLE
ui elements not compatible with themeroller

### ISSUE THREAD

**Issue by rktsmshr** [harvesthq/chosen#2014]
For development, I selected a stock themeroller theme "froggy" so that ui anomalies stand out visibly. By using the ui-states, it is possible for chosen to not look out of place w/ other. It would alleviate the need for any colors or patterns in the css. Leaving just the layout for  chosen.css.

**Comment by pfiller** [comment]
Themeroller support is not something we're going to add in the official fork. Sorry about that!
