### ISSUE TITLE
jQuery chosen plugin don't search part of word

### ISSUE THREAD

**Issue by Son-kun** [harvesthq/chosen#2016]
~~When I have in select any sentence in quote/apostrophe Chosen plugin don't find that option correctly. But if I try find sentence where quote is in middle/begining of search then all is ok.~~

~~Example:
`<option>I write "words"</option>`~~

~~When i try find:
`[words]` I get empty list,
`["words]` I get good list, 
`[te "wor]` I get good list.~~

~~I do something wrong (configuration), or this is bug/feature :P~~

[Edit]
Problem is different. Chosen-select don't allow to search any parts of words in standard search mode.
Example:
`<option>I write any words</option>`

When I try find:
`[rit]` I get empty list,
`[writ]` I get good list.

It's any way to search using part of word in chosen-select??

**Comment by saltybrains** [comment]
> "Google is your friend" - I must call chosen() with parameter { search_contains: true } and all works great.

That's awesome, that worked! - literally 10 years later this came up when searching the same thing! - which means there is no need for the 'google is your friend' snark because perhaps ironically this is the post and the solution that google ranked when searching the problem... lol
