### ISSUE TITLE
empty <optgroup> doesn't show up in chosen generated markup

### ISSUE THREAD

**Issue by visaka** [harvesthq/chosen#2020]
i have an empty optgroup in my select element which means no children for that group.
after i initialize select with chosen empty group doesn't show up in the drop down.

eg: 
![select](https://cloud.githubusercontent.com/assets/4747165/3645774/b1474c9a-10ed-11e4-9190-094765a3c738.png)

![empty](https://cloud.githubusercontent.com/assets/4747165/3645739/625edc4c-10ed-11e4-96f2-108f53af1dcd.png)

any idea how we can set up chosen to show empty optgroups as well??

**Comment by pfiller** [comment]
I don't think we'd merge an option to show empty optgroups. It doesn't seem to be a common enough use case to justify having the extra complexity. I do sometimes regret the decision to hide empty options and optgroups. I'm not sure where that idea even came from and it's _possibly_ something that could be changed in a future version of Chosen.
