### ISSUE TITLE
Adding custom html element to chosen dropdown

### ISSUE THREAD

**Issue by Strae** [harvesthq/chosen#2024]
I need to add a button after the chosen dropdown, to allow to add options to the select box in particular conditions.

Maybe can be usefull for someone:
https://gist.github.com/Strae/e055f7285f5fd6b7c069

**Comment by ikunyemingor** [comment]
I know this is late but based on @Strae example you can add Font Awesome icons and html tags by doing this with JQuery:
`javascript
$('#foo').on('chosen:showing_dropdown', function () {
                var $_fooChosenResults = $('.chosen-results .active-result', $('#foo_chosen'));
                $_fooChosenResults.each(function () {
                    $(this).append('<span class="chosen-task-info pull-right ft-9 pl-10"><i>8 task</i><i class="fa fa-users" data-toggle="tooltip" title="Users"></i></span>');
                });
                $('.chosen-task-info i[data-toggle="tooltip"]', $_fooChosenResults).tooltip({
                    animation: 'fade',
                    trigger: 'hover',
                    container: 'body',
                    html: true
                });
            }).on('chosen:hiding_dropdown', function () {
                var $_fooChosenResults = $('.chosen-results .active-result', $('#foo_chosen'));
                $(document.body).find('div[role="tooltip"]').remove();
                $('.chosen-task-info', $_fooChosenResults).remove();
            });
`

**Comment by ganesh993** [comment]
how do i remove the border-top, border-left, border-right from the chosen dropdown
