### ISSUE TITLE
Multi-select placeholder text is cut off

### ISSUE THREAD

**Issue by trinzia** [harvesthq/chosen#2029]
The placeholder in multiple select is cut off (last letter).  Change the font to something wide like Verdana.   

The width of this element is controlled by JS:
     chosen-container-multi .chosen-choices li.search-field input[type="text"] 

Need to add an extra EM on the width of the input to show entire placeholder.

**Comment by jk171505** [comment]
bug not solved and closed?

**Comment by pfiller** [comment]
It's closed because nobody has provided a link to a reproduction of the issue that we can test out. We can't fix a bug we can't make happen.

As @tjschuck said:

> Can you link to a publicly accessible page (or better, a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

**Comment by orloc** [comment]
https://jsfiddle.net/h6f3hoks/

Fiddle as requested @usumoio is correct about bootstrap interference it seems. 

I am viewing this on the latest chrome version.

**Comment by pfiller** [comment]
Thanks @orloc, but the placeholder width seems to be working as expected in the Fiddle (at least for me). Can you tell me the steps to recreate the problem?

**Comment by trinzia** [comment]
Fiddle:
https://jsfiddle.net/h6f3hoks/1/

I see this HTML: 
<li class="search-field">
<input type="text" value="Choose US States" class="default" autocomplete="off" style="width: 118px;">
</li>

If you remove the padding from:
.chosen-container-multi .chosen-choices li.search-field input[type="text"]
Then the placeholder text almost fits.

So I think that the width 118px, assigned by JS, should be using an outerwidth to get padding instead of just the width of the text.

**Comment by orloc** [comment]
Hey all, trinzia is defiantly onto part of it. 

In-so-far-as re-producing the problem - all i needed to do was to pull in bootstrap3.02 and the problem persisted. 

The solution might be more helpful.  This (albeit may not be 100% correct as its kinda hacky) is what im doing atm:


 .chosen-container-multi .chosen-choices li.search-field input, .chosen-container-multi .chosen-choices li.search-field input[type=text] {
    padding: 0!important;
  }

**Comment by minkwe** [comment]
.chosen-container-multi input.default,  .chosen-container-multi li.search-field{
	width: 100% !important;
}

Works for me. The "padding: 0" variant did not work.

**Comment by rickshawhobo** [comment]
I also have this problem. I found a solution by adding this rule
.chosen-container .search-field {
float: none;
}
The problem is that the <li class="search-field"> where the placeholder goes was inheriting a float: left from

.chosen-container-multi .chosen-choices li {
  float: left;
  list-style: none;
}

**Comment by marianadgeorgieva2** [comment]
The problem is that the input in the serach field has width of 90px. I fixed it by adding this CSS rule:
.chosen-container .search-field input {
	width: 100% !important;
}

**Comment by DomHudson** [comment]
Thanks marianad!

**Comment by thatsus** [comment]
What we found out is under the li.search-field the input has an inline style of what ever width it wants to. This needs to be width: 100%. Once this is done anything in the data-placeholder will fit.

**Comment by fskhalsa** [comment]
Following _marianad's_ suggestion:

Add this to your CSS if you're looking for a solution. It will solve the cutoff issue, and in addition will avoid making the text wrap to a second line too early, as happens when using just the base selector suggested by _marianad_ above.

```
.chosen-container .chosen-choices .search-field:only-child input {
    width: 100% !important;
}
```

**Comment by ShudhPandit** [comment]
The jsfiddle

https://jsfiddle.net/shudhpandit/0h0qwtor/

Os: Windows 7
Browser: Chrome latest.

**Comment by akshayat** [comment]
I did $('.chosen-select').trigger("chosen:updated"); when it is shown as work around

**Comment by abigperson** [comment]
@fskhalsa "latest" CSS solution is working for me. Chrome 57 w/ Bootstrap 3.3.7
@akshayat solution works with no CSS
Thanks, big help on a frustrating issue! Great tool now that this little bug is sorted out.
