### ISSUE TITLE
I need busy icon for large dropdown lists

### ISSUE THREAD

**Issue by deterset** [harvesthq/chosen#2043]
I love the search feature in the drop down because I have some large lists ~15000. The problem is it takes 2 or 3 seconds to appear. I would like to add the class "busy" when the dropdown is activated and then remove the class "busy" when it is complete. I am using these for ajax right now. I'm just not sure where to place them for chosen. This is what I have tried.

```javascript
$('.select_box3').on('chosen:showing_dropdown', function(event, data){
    $("*").addClass("busy");
}).chosen();
$('.select_box3').on('chosen:ready', function(event, data){
    $("*").removeClass("busy");
}).chosen();
```

If anyone can help I would be thankful.
- Robert

**Comment by pfiller** [comment]
I think you probably want to add the "busy" class right when you're applying Chosen, not on some specific event. This issue is approaching 2 years old, so I'm guessing you've given up or found a solution, though. Gonna close it!
