### ISSUE TITLE
Chosen responsive with Foundation 5

### ISSUE THREAD

**Issue by datnguyen293** [harvesthq/chosen#2056]
I recently worked with Foundation 5 and here is my update to make Chosen works with Foundation 5 (it is more simpler than the changes for Bootstrap 3 as you see here: https://github.com/harvesthq/chosen/issues/1004#issuecomment-42730752):
```
.columns .chosen-container, .column .chosen-container {
	width: 100% !important;
	margin-bottom: 1rem;
}
```

**Comment by pfiller** [comment]
Thanks for sharing. Hopefully it helps anyone else who has the same problem!
