### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by DanTup** [harvesthq/chosen#2060]
Are there any plans to update the NuGet package soon? It hasn't been updated since Feb and there are some bug fixes (made shortly after that release!) that'd really be useful to us.

Ideally I'd like to update the NuGet package rather than have to take it out and manually put the files in.

**Comment by amastaneh** [comment]
+1

**Comment by stof** [comment]
@amastaneh putting a +1 here while it was closed years ago is useless. We are not maintaining the Nuget package. It is an unofficial one.

**Comment by wstaelens** [comment]
try this nuget package: https://www.nuget.org/packages/jquery.chosen.mvc/
