### ISSUE TITLE
Add Tree view structure for option group

### ISSUE THREAD

**Issue by ubgadeashish** [harvesthq/chosen#2061]
Hello,

We are using chosen dropdown and we came up with a request that, in option group there should be an option to show/hide options under the option group.

In “SelectParser.prototype.add_group” we are not adding some of the parameters for group. If we can add them then we may be able to add functionalities like Collapse/Expand group.
classes: option.className,
array_index: this.parsed.length,
options_index: this.options_index, 
value: option.value,

Thanks,
Ashish Ubgade

**Comment by pfiller** [comment]
Collapse/expand of option groups is out of scope for this project. Chosen has a pretty simple goal: replace select boxes. More complicated interactions and UIs are great, but belong in other libraries.
