### ISSUE TITLE
{"search_contains": true} not work after call chosen('destroy')

### ISSUE THREAD

**Issue by vicalloy** [harvesthq/chosen#2064]
$('select').chosen('destroy').chosen({"search_contains": true});
search_contains not work.
$('select').chosen({"search_contains": true}) is OK;

**Comment by pfiller** [comment]
Using `search_contains` in this way works just fine for me ([here's a fiddle](https://jsfiddle.net/61cmzv8L/)). This issue is almost 2 years old, so it's possible that something else fixed it. Neato!
