### ISSUE TITLE
Does not currently support loading in CommonJS?

### ISSUE THREAD

**Issue by liuwenchao** [harvesthq/chosen#2065]
Is there a version using UMD style?
```
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['jquery'], factory);
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        factory(require('jquery'));
    } else {
        // Browser globals
        factory(jQuery);
    }
}(function ($) {
    $.fn.jqueryPluginCommonJs = function () {};
}));
```
https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

**Comment by jmeas** [comment]
:+1: This, in tandem with #2206, would resolve #1433.

Fewer and fewer developers are using browser globals – and continue to be encouraged against it. It's a shame that it requires extra shimming to get Chosen up and running in these environments.

**Comment by pfiller** [comment]
Closing in favor of #2215
