### ISSUE TITLE
Change event is not triggered on the original selected option

### ISSUE THREAD

**Issue by pierrocknroll** [harvesthq/chosen#2067]
Hi, thanks for your great job, and sorry if this bug is already known :)

With this simple select
`<select>
 <option value="NONE">None</option>
 <option selected="selected" value="ALL">All</option>
 <option value="LANG">By lang</option>
</select>
`
, and Chosen with no particular option

`mySelect.on('change', function(event)
{
 console.log(this.val());
});
`

If I choose an option (here: 'LANG') then choose the original selected option (here: 'ALL'), the change event is triggered only for the first choice, never for the original option.

Thanks a lot

(jquery 1.11.1, Chrome 37, FF 28)

**Comment by pfiller** [comment]
I'm not seeing that behavior in [this fiddle](https://jsfiddle.net/3ahovy1h/1/). This bug is super old so it's possible something else fixed it. If you're still seeing it, please provide a demo or fiddle and steps to recreate.
