### ISSUE TITLE
Width 100% on multiple select will make it really small

### ISSUE THREAD

**Issue by janstieler** [harvesthq/chosen#2073]
Hi,
I have a little strange problem with an multiple select field.
If i set the chosen option width to 100% the field gets really small.

This is a screenshot without the option
![bildschirmfoto 2014-09-06 um 01 46 36](https://cloud.githubusercontent.com/assets/754880/4173243/089e0ee2-3557-11e4-97d0-b777de5575ad.jpg)
and this is with activate option
![bildschirmfoto 2014-09-06 um 01 46 59](https://cloud.githubusercontent.com/assets/754880/4173248/1c05be8a-3557-11e4-8f58-c60f708a787a.jpg)

Does anybody know because it gets smaller with the option?
On both situation the content of the dropdown will be cut off. This width could also not be the reason of that.

All other chosen elements will get the right width with this option only the multiple select field not.

BR

**Comment by fesioche** [comment]
i have the same problem,

I resolved it creating a div with the width that you want. Insde the div i create the control chosen and I establis the style width: inherit!important; and it works

**Comment by pfiller** [comment]
Are you specifying a width of 100% on the original select field or when you call Chosen? The proper way to do it is to include it when you call Chosen:

```JavaScript
$("select").chosen({ width: '100%' });
```

If you're using it that way and still seeing a bug, please provide a link that shows the problem happening (ideally in the form of a [fiddle](http://jsfiddle.net)) so we can help you debug. Thanks.
