### ISSUE TITLE
Suggestion: color options

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [harvesthq/chosen#2078]
I modified the code to put color in the options list using only the attribute "data-color-option" in each option item. This could become a new feature?

Data attribute:
![Data-attribute](http://i.imgur.com/gCRryRG.png)

Options:
![result1](http://i.imgur.com/UDa2AN5.png)

Selected:
![result1](http://i.imgur.com/suZXCTQ.png)

**Comment by ryan2johnson9** [comment]
Exactly what I needed guys, thanks. hook options would be grand too.

**Comment by pfiller** [comment]
Interesting. Very similar in idea to #2574 - you probably want to follow along there.

Going to close in favor of that.
