### ISSUE TITLE
Can the drop down actually drop up :)

### ISSUE THREAD

**Issue by adamelevate** [harvesthq/chosen#208]
I was thinking how awesome it would be to use this in pagination, but it only does a drop down sending the results off the bottom of the screen. I was looking at your very wonderful and complicated code and realized I do not have the expertise to do it myself yet. Cheers!

**Comment by nanvalcx** [comment]
CSS :
.chosen-drop { 
  /* I am add this to separate code css with jquery chosen, inside of class * /
  border-top-color: #aaaaaa;
  border-top-style: solid;
}
/* And finally inside of function"Chosen.prototype.results_show" i did the same that @Jaeyoung-Kim said, only that i am restoring the css of class "chosen-drop" opposite case */
// Add Here     
    var windowHeight = $(window).height() + $('html').scrollTop(),
    totalHeight  = this.container.height() + Math.ceil(this.container.offset().top)+270;
    if (totalHeight > windowHeight) {
        $('.chosen-drop').css({'top':'auto',"bottom":"100%","border-top-width":"1px"});
    } else{
        $('.chosen-drop').css({'top':'100%',"bottom":"auto","border-top-width":"0px"});
    }
// End

**Comment by cocoboy** [comment]
If you are using JQuery dialog I have added some additional code to adjust the dropdown based on the jquery dialog height and the position of the dropdown relative to the top of the dialog

            // Add Here    
            var windowHeight = $(window).height() + $('html').scrollTop(),
                totalHeight = this.container.height() + Math.ceil(this.container.offset().top) + 270;

            if ($(".ui-dialog").length) {
                windowHeight = parseInt($(".ui-dialog").css("height"));
                totalHeight -= $(".ui-dialog").offset().top;
            }

            if (totalHeight > windowHeight) {
                $('.chosen-drop').css({ 'top': 'auto', "bottom": "100%", "border-top-width": "1px" });
            } else {
                $('.chosen-drop').css({ 'top': '100%', "bottom": "auto", "border-top-width": "0px" });
            }
            // End
