### ISSUE TITLE
Autofill the selected value in Chosen Multiselect for Edit form

### ISSUE THREAD

**Issue by arpan209** [harvesthq/chosen#2082]
So i have a chosen multi select on my add client form which is working fine and showing the multi select dropdown list. And i am able to select the value and saving into database. I have a option of edit client also in which i am fetching the value from database and using the same form to populate the value through model on a form. All the regular dropdown,and text box fills the value fine but i an not able to pre populate the value on Chosen Multiselect which as a selected value. I see the drop down populate the values but need to display the values which was saved in database as selected value when the form load. . I did this but it dosnt seem to work.

var StudName = '@Model.StudentListText';
var StudDropDown = document.getElementById('StudentList');
StudDropDown.options[StudDropDown.selectedIndex].text = StudName.trim();

html

   <div class="editor-field">

```
        @Html.ListBox("StudentList", Model.Students

 , new

 {

     @class = "chzn-select",
      data_placeholder = "Choose  Student..."

 }
 )

     </div>
```

how to populate the chosen multiselect with value i have already saved in database? I am using MVC 4.5 and C#. Thanks in Advance.

**Comment by zeeshan-web-dev** [comment]
**arpan209**, i am facing the same issue . now, let you know me please how did you resolve that ..Thanks

**Comment by arpan209** [comment]
i am looping through the list  of items in my C# controller and adding them in  a List(). 
  List<SelectListItem> listSelectListItems = new List<SelectListItem>();
 foreach (var item in result.OrderBy(t => t.StudentLastName))
                {
 SelectListItem selectList = new SelectListItem()
                    {

                        Selected = (item.SID == StudId), ''' if there is a match then Selected will be "TRUE"
                        Text = item.StudentLastName + " - " + item.StudentFirstName,
                        Value = item.SID.ToString()

                    };
                    listSelectListItems.Add(selectList);
}
