### ISSUE TITLE
Cannot de-select a default selection in multiple list unless another option is selected first.

### ISSUE THREAD

**Issue by TroyLDay** [harvesthq/chosen#2083]
IF a multiSelect = true list has initially slected options, those options cannot be deselected until after one or more new options are also selected.

**Comment by pfiller** [comment]
I'm not able to reproduce this in the current version of Chosen. This issue is almost 2 years old, so it's possible something fixed it unintentionally. If you're still able to reproduce, please provide a demo or fiddle that shows the problem and tell us steps to recreate.
