### ISSUE TITLE
Show matches in default <g: select> Grails, as a placeholder? 

### ISSUE THREAD

**Issue by hagoromo** [harvesthq/chosen#2087]
I need to make it work something like attribute placeholder within the <g: select> in the multiple choice if you show me a default value, but in my case I do not need to be multiple, not want that default go included in the values ​​and select the label that has noSelection default Grails does this, currently have this: 

```
<g: select name = "product.id" ​​from = "$ {products}" optionKey = "id" value = "$ {product .id?}" class = "chosen-select" tabindex = "2" />
```

**Comment by pfiller** [comment]
This is almost 2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
