### ISSUE TITLE
Chosen break all blur event all other elements on page.

### ISSUE THREAD

**Issue by divined** [harvesthq/chosen#2089]
I have one element whith blur event. If i select chosen element after it - blur event not working.

**Comment by pfiller** [comment]
This is almost 2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
