### ISSUE TITLE
Disable click on tag

### ISSUE THREAD

**Issue by igusse** [harvesthq/chosen#2092]
Hello,

I use chosen to design tags for this layout:
![image](https://cloud.githubusercontent.com/assets/4283603/4431865/060ebe3e-467c-11e4-9a82-2844d8a76fa9.png)

All is good, but when I click to tag shown dropdown list. It good for inline tags, but not for me desing.

I tried to code like this:

    var $stars_field = $('select');
    $stars_field.on('chosen:ready', function(e, chosen) {       
        $("li.search-choice").click(function(){
            return false;
        });
    }).chosen({
        width: "100%"
    });

But it's no work for first time. 
How can I disable click on tag before init?

Here is code http://jsfiddle.net/ca1p15qd/2/

Thank you anyway!

**Comment by pfiller** [comment]
This is two years old so you've probably moved on, but ...

Our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
