### ISSUE TITLE
<option title="additional option info" discarded by chosen.js 

### ISSUE THREAD

**Issue by garrydelacruz** [harvesthq/chosen#2094]
First of all, this is an amazing good looking plugin. I am trying it for the first time.

I have one small issue. I am using a select box where each <option> has a corresponding title attribute showing additional information about the option when the user hovers it. It seems option is stripping out the title tag when it beautifies the element. Is there an easy way to workaround it without me having to make changes to the source code?

**Comment by pfiller** [comment]
> First of all, this is an amazing good looking plugin. I am trying it for the first time.

I'm a year and a half late, but thanks!

> It seems option is stripping out the title tag when it beautifies the element.

Since #1704 merged, Chosen carries over the title tags. Sweet!
