### ISSUE TITLE
Trigger "change" event even when current selected value is the same as previous

### ISSUE THREAD

**Issue by bl4de** [harvesthq/chosen#2096]
Hi,

I've got maybe not so common situation, but it is mandatory behavior in currently developed application.

I need to trigger "change" event even when currently selected value is the same as previous. Additional problem is that value from <option> element can be 0 (zero).

So, I've changed this code (line 1022 and below in chosen.jquery.min, v. 1.1.0 ):

```javascript
if (this.is_multiple || 
this.form_field.selectedIndex !== this.current_selectedIndex) {
                    this.form_field_jq.trigger("change", {
                        'selected': this.form_field.options[item.options_index].value
                    });
                }
```
To this:

```javascript
if (this.is_multiple 
|| this.form_field.selectedIndex !== this.current_selectedIndex 
|| this.form_field.selectedIndex === this.current_selectedIndex) {
                    this.form_field_jq.trigger("change", {
                        'selected': this.form_field.options[item.options_index].value
                    });
                }
```

It's here in CoffeeScript source:
https://github.com/harvesthq/chosen/blob/master/coffee/chosen.jquery.coffee#L361

 
I know it is far from good solution (I had to do it as quickly as possible - believe me, I just had to :) ), now it's working, but for me, developer, it is not acceptable solution.

Is there any other (proper) way to force such behavior in Chosen?

**Comment by pfiller** [comment]
I agree - this isn't going to happen in Chosen. It seems like your workaround worked, though!
