### ISSUE TITLE
Multiple Select should allow ctrl-clicking and drag-selection

### ISSUE THREAD

**Issue by AndrewIngram** [harvesthq/chosen#21]
Currently, with multiple select, each selection closes the dropdown. This forces the user to make a larger number of clicks to select muliple items compared to the enhanced widget.

The widget should allow more rapid selection of multiple values by letting you ctrl-click, and perhaps also click-drag over a number of consecutive choices.

**Comment by koenpunt** [comment]
#135 focuses on shift-selection, so closing in favor of that one.
