### ISSUE TITLE
Large options with multiple selection will result bad performance. 2000+ records for 1.5+ s

### ISSUE THREAD

**Issue by myc0210** [harvesthq/chosen#2105]
The main problem i find through chrome timeline is this function AbstractChosen.prototype.result_add_option which uses innerHtml and outerHtml. each time when render the dropdown list, this function will be called exactly times same as the number of list items. Then the browser will freeze for 1.5+ s and then show the dropdown list. Any suggestion for improving this ?

**Comment by Pheil** [comment]
Really noticeable with my option list of over 38,000 items.

**Comment by pfiller** [comment]
Duplicated by #2580. There's a nice summary of related issues in that thread, so I'm going to close this one.
