### ISSUE TITLE
Chosen automatically selects an option on iPad

### ISSUE THREAD

**Issue by DaanDD** [harvesthq/chosen#2118]
When I click the chosen select box on an iPad, it opens up, selects an option from the list and closes again. The second time I click the chosen element it works as intended.

**Comment by wcndave** [comment]
I find this too.  I wanted to implement chosen on desktop to mimic the behaviour of mobiles / tablets.  Multi select works nicely on these with tick lists, whereas desktop requires hold ctrl/cmd to select multiple.  Therefore I would rather just disable this on all mobile / tablet.  I see there is a way to add to a user agent regex, is there some easy way to just turn off for ALL mobile/tablets?

**Comment by tjschuck** [comment]
This was duplicated by #2171, but that issue has a bit more information and discussion.  Closing this one in favor of that one.  Please feel free to leave any feedback you have over there instead.

Thanks for reporting!
