### ISSUE TITLE
Split char or regexp could be an option

### ISSUE THREAD

**Issue by arosar** [harvesthq/chosen#2129]
When *enable_split_word_search* is set to true (and it is by default) the character to split the string to perform the search is " " (space). Some times it may be conveinient to change it.
As I needed to split words with "/" too I have implemented it in my local copy using the following code (in Chosen.prototype.winnow_results function):
```
(...)
} else if (this.enable_split_word_search && (/[\s\/]+/.test(option.html) || option.html.indexOf("[") === 0)) {
parts = option.html.replace(/\[|\]/g, "").split(/[\s\/]+/);
(...)
```
where /[\s\/]+/ is the regexp to match spaces and my char. I think it would be a useful feature that chosen came with this as an avaialble settable option.

**Comment by pfiller** [comment]
Closing in favor of the discussion in #424
