### ISSUE TITLE
Chosen displays on Windows Phone 8.1 (Lumia 520)

### ISSUE THREAD

**Issue by dan-bennett** [harvesthq/chosen#2135]
The current UA regex patterns don't match IE on Windows Phone - at least for the Nokia Lumia 520 running WP 8.1. I'm running Chosen 1.1.0 but have compared with the source for 1.2.0 and the `AbstractChosen.browser_is_supported` function hasn't changed, so I presume the issue still exists.

Full UA string according to PHP's `$_SERVER['HTTP_USER_AGENT']`:

```
Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like Gecko
```

Adding the following to `AbstractChosen.browser_is_supported` in the compiled `chosen.jquery.js` has resolved this for me, but I don't know CoffeeScript so I figured I'd post it here rather than potentially make a mess of the source. There's also a strong chance the patterns I've used can be optimised as I'm not a regex wizard.

```js
if (/IEMobile/i.test(window.navigator.userAgent) || /Windows Phone/i.test(window.navigator.userAgent)) {
  return false;
}
```

**Comment by koenpunt** [comment]
This was fixed by https://github.com/harvesthq/chosen/pull/2440
