### ISSUE TITLE
Chosen doesn't allow to set focus to another control after change()

### ISSUE THREAD

**Issue by asantos** [harvesthq/chosen#2139]
I'm trying to focus a text input after the user changes the value of the chosen-select.

> $('#select').change(function(){
>   $('#name').focus();
> }).chosen();

That did work on previous versions of chosen (0.9.8) but it's not currently working in 1.1.0. What could be blocking the focus() method?

**Comment by pfiller** [comment]
Yup - #1526 is the same. Chosen refocuses the text field after selecting an item, so that's what's stealing the focus. The easiest thing to do is to wait for the event loop to finish before focusing on the next thing:

```JavaScript
$('#select').change(function(){
  setTimeout(function(){ $('#name').focus(); }, 0);
}).chosen();
```
