### ISSUE TITLE
allow_single_deselect only work when first option ist empty

### ISSUE THREAD

**Issue by TomTheRock** [harvesthq/chosen#2143]
When you create a select Dropdown with some values which are empty but not in the first Position
you can not deselect them or select a empty Option, Chosen filter all empty Options which is very anoying: http://jsfiddle.net/o0f1mvo3/1/

**Comment by Cederman** [comment]
Confirmed

**Comment by tjschuck** [comment]
This is known and documented.  See the docs [

**Comment by tjschuck** [comment]
This is known and documented.  See the [docs for "Allow Deselect on Single Selects"](http://harvesthq.github.io/chosen/#allow-deselect-on-single-selects):

> This will only work if the first option has blank text.
