### ISSUE TITLE
dropdown menu flashes on refocus if input was in select

### ISSUE THREAD

**Issue by ircluzar** [harvesthq/chosen#2146]
If the focus in on the control then the user clicks inside another browser instance, the dropdown menu will flash wherever the user clicks on the original place whether he clicked on the contol or not.

> This can accidently cause the user to select an item that the control suggests while it flashes.

**Comment by pfiller** [comment]
I'm not able to recreate this, but the issue was opened a year and a half ago so it's possible something's fixed the problem. If it's still an issue, feel free to re-open and provide explicit steps for recreating the problem.
