### ISSUE TITLE
flash of unstyled content

### ISSUE THREAD

**Issue by mtjhax** [harvesthq/chosen#2147]
On my pages using Chosen, and on the demo page, on each page reload the original HTML controls appear momentarily before being replaced by the Chosen-styled versions. Most people would call this a "flash of unstyled content" or FOUC, which coincidentally sounds a lot like something web designers will utter on seeing this effect in their page.

It is likely that a simple technique such as hiding the controls until they are styled would suffice to help this situation -- having controls appear after page load isn't as bad as having them appear then mutate. If something like that works, a simple update to the documentation could suffice as a resolution to this issue, but it's possible a small tweak in the code may be needed. Before I start in on trial-and-error, I wanted to find out if there are any examples of this that anyone is using.

Happy to submit a PR if a tweak is needed though.

**Comment by niyazpk** [comment]
+1

**Comment by ComeBurguburu** [comment]
you can use
``````````````````````````````````html
<select id="chosen-select" size="1">

**Comment by JuusoPalander** [comment]
@ComeBurguburu how does that help? I don't see any difference myself.

**Comment by ComeBurguburu** [comment]
before chosen load the select multiple show one line instead of five lines

**Comment by pfiller** [comment]
You can definitely hide the original select and Chosen should still apply itself as normal. You will want to specify a width, however, as Chosen can't measure the select box if it's invisible.

```HTML
<select id="hidden" style="display:none;">
  <option>I'm the option</option>
</select>
```

```JavaScript
$("#hidden").chosen({width: '100%'});
```
