### ISSUE TITLE
Modal With Scrollbar

### ISSUE THREAD

**Issue by JhorenFox** [harvesthq/chosen#2149]
i am using a gridview in a modal with horizontal scroll, and after i select in dropdown the grid view resets, i think this is related in postback, i am using asp.net, bootstrap

**Comment by pfiller** [comment]
This issue is from November of 2014 so I'm guessing you don't need an answer any longer.

If you do, you should definitely try StackOverflow (there's a jquery-chosen tag) for questions like this. I'm not familiar with gridview!
