### ISSUE TITLE
Form reset doesn't reset Chosen elements

### ISSUE THREAD

**Issue by ngse** [harvesthq/chosen#215]
If you trigger the form's `reset()` function (i.e. using a `<button type="reset">`) it doesn't correctly reset the Chosen styled select elements.  It would be good to have a `reset()` method for Chosen that will reset the element.

I tried calling `trigger('liszt:updated')` but no joy.

I'm presently getting around this by removing the Chosen elements, removing the class from the `<select>` and then re-running Chosen on the `<select>` - example using jQuery:

``` javascript
$('button[type="reset"]').click(function(ev){
    ev.preventDefault();

    $('.chzn-container').remove();
    $('form').trigger('reset');
    $('select').removeClass('chzn-done').chosen();
  });
```

**Comment by tmacliang** [comment]
+1

**Comment by raghava1605** [comment]
$(".chosen-select").val('').trigger("chosen:updated"); from more information click `[here](http://www.dotnetqueries.com/Article/153/how-to-resest-jquery-chosen-dropdown)`

**Comment by pvanb** [comment]
Whereby "more information" you mean "please visit my site to get me some ad views?"

**Comment by tjschuck** [comment]
@pvanb Thanks for pointing that out.  I've removed the link and locked this thread — it's truly dead and doesn't need any more follow-up.
