### ISSUE TITLE
Chosen disabled on mobile devices AND tablets

### ISSUE THREAD

**Issue by tanloverluke** [harvesthq/chosen#2161]
I've been using Chosen for several months a love it. However I've only ever tested it on my desktop and Samsung mobile (S5). So today I checked it out on a Samsung Tab 3 (very old I know, belongs to my Mum) and noticed three problems:
1) on the Chrome mobile browser, links under the dropdown also receive the click
2) on the Samsung mobile browser, when I click on the dropdown it opens, selects the first option automatically, and closes directly
3) despite me wanting Chosen to be disabled on mobile browsers, it isn't being disabled. Hence the above two problems are being experienced.

I have tried to extend the mobile detected, as suggested in Issue #1848, but no luck as Chosen is still enabled in the Samsung Tab 3 tablet.

Is chosen supposed to be disabled on all mobile devices, which I though a tablet is classified as, or is it only disabled on mobile phones?

Many thanks / Luke

**Comment by pfiller** [comment]
Duplicated by #2443 which has a little more detail.
