### ISSUE TITLE
Choosen and reset button in form

### ISSUE THREAD

**Issue by bloodangel78** [harvesthq/chosen#2164]
Hi,

Just to report a little problem on chosen 1.2.0 and "reset" button in form.
<button type="reset">Reset form</button>
This button reset initial values in form after having changing them.

1) For multiselect and select the init value is correctly reset in the hidden select element, but the value in chosen div is not changed.

2) For multiselect the the label shown when no option is select is a little visible

You can see following a screenshot of the render when i reset form fields with the button (i have display hidden select to show the problem)
![sans titre](https://cloud.githubusercontent.com/assets/8994381/5340659/7d25dd3a-7eef-11e4-9eb8-6fd6cee75d3f.png)

Thanks for your plugin.

**Comment by jeremybenaim** [comment]
@bloodangel78 you might want to do the following as long as chosen doesn't support the reset event (since it is emmited at the `form` level)

```javascript
// init chosen w/ a single class to keep your code DRY
$('.chosen-select').chosen();

$('form').on('reset', function() {
  $('.chosen-select').each(function(){
    var resetValue = this.multiple ? [] : '';
    $(this).val(resetValue).trigger('chosen:updated');
  });
});
```

**Comment by koenpunt** [comment]
It does work with reset and triggering `chosen:updated`. However, when triggering `chosen:updated` on the click event, it is too early. Even on the form's reset event it is.

Workaround is to defer `chosen:updated` to the next runloop by using `setTimeout`:

```js
$('button[type=reset]').on('click', function() {
	setTimeout(function() {
    $('.chosen-select').trigger('chosen:updated');
  }, 0);
});
```

The first fiddle with the updated reset: http://jsfiddle.net/koenpunt/xLqohvfe/
