### ISSUE TITLE
Search stops working after 5 searches

### ISSUE THREAD

**Issue by unluckypixie** [harvesthq/chosen#2180]
Ok this seems really weird but it's been a problem for us for ages and I can't get to the bottom of it.

How to reproduce:

- Put 6 chosen drop downs (all can contain the same details) on a page.
- Click first one and type a search criteria to match an item and select with enter.
- repeat for the other items

it will work for the first five but on the sixth it will not work, i.e. you cannot actually type anything into the search box.  if you watch the dom while typing you can see the first element in the list rapidly selected and deselected as you type but no characters appear and nothing is highlighted in the dropdown.

If you then select one by scrolling and clicking with the mouse it (usually) starts working again for another five drop downs.

I should create a jsfiddle to prove this, but I've not got time just now! 

We had this problem with an old version of chosen too, I've just updated to the latest one and the same problem.  It's probably some side effect of another jquery plugin or something but i was hoping someone in the code might realise there is an array of size "5" somewhere that could be causing this!

**Comment by tjschuck** [comment]
I can select more than 5 using the [Chosen page itself](http://harvesthq.github.io/chosen/), so it seems like it might be a conflict with your particular page (or something else, who knows!).

What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

If you can link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce, that'd be great!  Or if _you_ can reproduce it on the Chosen home page itself, let us know the other above information about your browser/OS so we can test that out.

Closing until more info is provided, but will reopen when you do.

Thanks!
