### ISSUE TITLE
Disable / Enable multiple select on a chosen field

### ISSUE THREAD

**Issue by jinfollc** [harvesthq/chosen#2181]
I have a chosen select field and I would like to set the multiple tag of the underlying select field through jQuery after which the chosen field should turn into a single select or a multiple select field.

However I can't get the chosen field to update properly with the trigger: 
$('.chosen').trigger('chosen:updated');

Here is a fiddle: http://jsfiddle.net/uy3sztfu/

Am I doing something wrong, or is this just not possible with Chosen?

**Comment by tjschuck** [comment]
@jinfollc Your Fiddle is completely Chosen-free, so I can't quite say what's wrong with it aside from that :)

Did you link the wrong Fiddle?  And/or did you figure it out in the meantime?

Closing this (just for issue-management purposes), but will reopen if you come back with more info.
