### ISSUE TITLE
How to adjust the combo box so that the text is displayed entirely?

### ISSUE THREAD

**Issue by saxrub** [harvesthq/chosen#2182]
I struggle to find a solution that Chosen displays fully the text of the selected item. In fact, the string is always truncated by a few pixels.
In the attached example, the box PAYS
 has a calculated width of 44px; with a width of 53px, the FR text would be displayed correctly.
![chosen](https://cloud.githubusercontent.com/assets/10347069/5586878/ea35fcb4-90da-11e4-84eb-ad3f42b8c4f2.png)
An idea other than hard coding width = '53px'?

**Comment by tjschuck** [comment]
Agreeing with @tanloverluke -- this isn't a bug with Chosen, just a visual design issue with your chosen width.  You can either make the box slightly wider, or hide the arrow with CSS so that it doesn't take up that space.
