### ISSUE TITLE
multiple to single

### ISSUE THREAD

**Issue by kaiyulee** [harvesthq/chosen#2187]
As it is ,
How to change multiple to single selector dynamically.

I tried something like this.
```javascript
$('[name="country"]').prop('multiple', false).trigger('chosen:updated');
```
And the result turns out to be like this:
Before:
 ```html
value="2,3,4,5"
```
After:
```html
value="2"
```

As you can see, the value changed to single , but it still has multiple-look, and the single value is the last chosed value.
```
<ul class="chosen-choices">
    <li class="search-choice">...</li>
    <li class="search-choice">...</li>
    <li class="search-choice">...</li>
</ul>
```

Help~

**Comment by koenpunt** [comment]
This has been asked before in #1204. 

[I quote myself](https://github.com/harvesthq/chosen/issues/1204#issuecomment-22278516):

> With the latest version of Chosen (and some before that) you can call `$('select').chosen('destroy');` to destroy Chosen, change `multiple` attribute and call `$('select').chosen();` again to reinitialize Chosen.
