### ISSUE TITLE
trigger click in search field

### ISSUE THREAD

**Issue by catcologne** [harvesthq/chosen#2189]
I am adjusting a project which uses your “chosen” Plugin. I only show the "ul.chosen-results and hide the search field and the ul.chosen-choice. Therefor on load of the page I need to trigger the click on the search input field in in the “li.search-field” and it does not work. Could you tell me if one of these methods are correct? And which?
 
jQuery(".chosen-drop").trigger("chosen:updated");
            jQuery(".chosen-result").trigger("chosen:updated");
            jQuery(".search-field input").trigger("chosen:updated");
                        
            jQuery(".chosen-drop").trigger("chosen:activate");
            jQuery(".chosen-result").trigger("chosen:activate");
            jQuery("#resume_category").trigger("chosen:activate");
            jQuery(".search-field input").trigger("chosen:activate");
            
            jQuery(".chosen-drop").trigger("chosen:open");
            jQuery(".chosen-result").trigger("chosen:open");
            jQuery("#resume_category").trigger("chosen:open");
            jQuery(".search-field input").trigger("chosen:open");
 
At the moment I trigger a click event on the Label of the Select Element, the problem is, that on load of the page the focus is at the end of the page (where my select box is positioned). This result is not satisfying.

Many thanks,
Catarina.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.  Additionally, you should link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so others can attempt to reproduce.

For this specific issue, check out the [docs for triggerable events](http://harvesthq.github.io/chosen/options.html#triggerable-events).

**Comment by answerquest** [comment]
Hi, just FYI for devs, none of the options provided in https://harvesthq.github.io/chosen/options.html#triggerable-events does the act of actually triggering a dropdown selection event, as in `.on('change', function(evt,params){}`. It would be great if we could have a `.trigger('chosen:change');` command.
