### ISSUE TITLE
Is it possible to display placeholder text until search box has focus?

### ISSUE THREAD

**Issue by pdille** [harvesthq/chosen#2190]
I'm coming from version 0.9 to the latest release (1.3.0). In the old version, when I would load the page the placeholder text would always initially be there, no matter how many items were pre-selected. Now, this doesn't seem to be the case and the placeholder is only shown if no items are selected. Perhaps the latter is something I'm doing wrong? In any case, how would one go about having the placeholder always be shown unless the search field has focus? I know how to do this with a raw javascript on a standard input field, but chosen seems to be doing something more complicated with the input value.

Thanks!

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

Additionally, linking to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue will go a long way towards helping people reproduce your issue.

For this particular issue, regarding:

> I know how to do this with a raw javascript on a standard input field

That should probably be enough for what you're after -- update the underlying `select` however you want, and then call `chosen:updated` ([docs here](http://harvesthq.github.io/chosen/options.html#triggerable-events)).  That should update Chosen to match whatever you've done to the underlying `select`.
