### ISSUE TITLE
It's not compatible with NProgress

### ISSUE THREAD

**Issue by richardguancn** [harvesthq/chosen#2196]
Hi,

I used the NProgress plugin.
But It's not work.
I need to refresh the page manually, then It's work.

**Comment by stof** [comment]
Can you at least give a link to this NProgress plugin ? I have absolutely no idea what it is

**Comment by tjschuck** [comment]
Closing pending more info.  Will reopen once provided.

**Comment by tjschuck** [comment]
Additionally, please share what browser, browser version, OS, and OS version you're using, and which version of Chosen.

Please also link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.
