### ISSUE TITLE
repopulate for optgroup and multiple

### ISSUE THREAD

**Issue by danalo** [harvesthq/chosen#2199]
Hi

I encounter issues regrading select options by default for optgroup.

For optgroup, if I have two groups, and I only know value of the option that I want to set as default without knowing which group is it, how am I supposed to manage to do that.

And also for select which is both optgroup and multiple, how am I supposed to do that as in the same scenario?

Please help! Thanks in advance!

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

This actually doesn't even seem like a Chosen question particularly -- you're mostly just trying to select elements of the underlying `select`.  You can do that however you'd like in JS, and then just call `.trigger('chosen:updated')` ([docs](http://harvesthq.github.io/chosen/options.html#triggerable-events)) on your Chosen element to get Chosen to update itself accordingly.
