### ISSUE TITLE
Opening select with long options on mobile pushes screen to the left

### ISSUE THREAD

**Issue by qwelyt** [harvesthq/chosen#2201]
If you have a long option (an option that takes up a fair amount of width, possibly the entire screen width) and open the select-box when you have scrolled to the side, the opening of the results will force the viewport to be reset to the left-most position. This means that if you have a selectbox on the right side of your screen which you have to scroll to, you will be thrown away from it when you try to open it. The same behaviour is seen when selecting a result.

I have tested this in Chromes mobile-view (Inspect element --> Push the mobile icon) and on an iPad. The results seems to be the same.

Here's a fiddle to show what I mean http://jsfiddle.net/u9y29qyu/
Just scroll to the select and make selection. You should be thrown to the left again. I experianced this in Firefox, without using "responsive mode", and on Chrome in mobile-mode, and on an iPad.

**Comment by qwelyt** [comment]
This seems to be the same issue as #1410
Not sure if #1410 has the problem with selecting an option though.

**Comment by pfiller** [comment]
Chosen is supposed to be disabled for mobile devices and #1410 might seem to cover this. Closing and we'll investigate there.
