### ISSUE TITLE
Allow installation using Composer by using ComponentInstaller

### ISSUE THREAD

**Issue by holtkamp** [harvesthq/chosen#2204]
It would be great to be able to install Chosen using the [Composer package manager](https://getcomposer.org). For Javascript sources that typically need to be installed in a 'public' folder exposed to the internet, this can be achieved using [ComponentInstaller](https://github.com/RobLoach/component-installer)

Would you guys be open for a PR to support this?

**Comment by tjschuck** [comment]
I assume this has the same problem as [Bower installation](https://github.com/harvesthq/chosen#bower-installation), which is that unless the package manager itself supports a build step to compile the sources, this won't work.  Chosen's source repo only contains the CoffeeScript and Sass source files, not the compiled JavaScript + CSS (for many reasons).

_If and only if_ Composer supports either:

1. A build step to compile the CS + Sass into JS + CSS, **_or_**
2. The ability to reference the compiled ZIPs on the [GitHub releases page](https://github.com/harvesthq/chosen/releases)

then it would possibly be considered.

Closing this pending more info.  If you can come back with more info about either pursuing option 1 or 2, we'll reopen.

Thanks!

**Comment by holtkamp** [comment]
Ok, thanks for the swift and detailed response. I will dive into it, option 2 seems to be the most pragmatic approach. This[ part of the documentation](https://github.com/RobLoach/component-installer#packages-without-composer-support) kind of suggests that zip distributions are supported, but will test first.

**Comment by holtkamp** [comment]
I had a look and I managed to install the files from the compiled ZIP files by adding this to my project's composer.json file:

```
"repositories": [
        {
            "type": "package",
            "package": {
                "name": "harvesthq/chosen",
                "type": "component",
                "version": "1.3.0",
                "dist": {
                    "url": "https://github.com/harvesthq/chosen/releases/download/v1.3.0/chosen_v1.3.0.zip",
                    "type": "zip"
                },
                "extra": {
                    "component": {
                        "scripts": [
                            "chosen.jquery.js"
                        ],
                        "styles": [
                            "chosen.css"
                        ],
                        "files": [
                            "*.png",
                            "chosen.jquery.min.js",
                            "chosen.min.css"
                        ]
                    }
                },
                "require": {
                    "robloach/component-installer": "*"
                }
            }
        }
    ],
    "require": {
        "harvesthq/chosen": "~1.3"
    }
```

However, it seems NOT possible to use a composer.json file in the Chosen project itself in such a way that we can easily refer to it / do not require an interested user to provide all the details, like I tried here: https://github.com/holtkamp/chosen/blob/component-installer-support/composer.json

I guess this would be something to ask Composer maintainers like @Seldaek whether this is possible at all.

**Comment by stof** [comment]
This is not possible for Composer.
And it won't add a step to do the JS and CSS from Coffee and Sass because Composer is a PHP dependency manager, not a frontend one.

**Comment by holtkamp** [comment]
As a follow-up for other people interested in installation using Composer, check this plugin: https://github.com/francoispluchino/composer-asset-plugin

**Comment by ndubbaka** [comment]
Thanks holtkamp. That worked for me
