### ISSUE TITLE
Remove focus after selection from dropdown

### ISSUE THREAD

**Issue by i07** [harvesthq/chosen#2205]
normally I set focus to a invisible input field to remove focus on a drop-down; on a chosen element this is not working. I have tried multiple ways; blur(); but somehow I cannot manage to remove the focus.

using Version 1.2.0.

So before I start to go through the Chosen code; is this an known issue with a workaround?

Thanks

**Comment by tjschuck** [comment]
`chosen:close` should deactivate Chosen and cause it to lose focus.  [Docs here](http://harvesthq.github.io/chosen/options.html#triggerable-events).

Closing pending more info -- will reopen if necessary.

**Comment by i07** [comment]
Thank you for the reply; i've tried that; but it does not lose focus. So here is some more info 

I used:
```javascript
$('#columns').trigger("chosen:close");
```

btw. tabindex is working properly.

I am using the multi-select combo; after an selection, I want the object $('#columns') to lose focus, chosen:close.

Chosen init:
```javascript
$(function () {
        var config = {
            '.chosen-select': {},
            '.chosen-select-deselect': {allow_single_deselect: true},
            '.chosen-select-no-single': {disable_search_threshold: 10},
            '.chosen-select-no-results': {no_results_text: 'Oops, nothing found!'},
            '.chosen-select-width': {width: "95%"}
        };
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    });
```
The select
```html
<select 
    id="columns" 
    onchange="check_columns();"
    style="width:660px" 
    multiple 
    class="chosen-select" 
    data-placeholder="Select columns to add">
<option><option>
.....
</select>
```
Image (normal):
![columns_chosen](https://cloud.githubusercontent.com/assets/6317005/5907110/c7e9dfdc-a59c-11e4-9030-6ed519cdfd73.png)

Image (after chosen:close)
![after_chosen_close](https://cloud.githubusercontent.com/assets/6317005/5907267/e45418f8-a59d-11e4-9df6-f7da83a05cec.png)

Normally I use (in which focus_capture is a off-screen input ), this works fine everywhere I use it; except the chosen element simply does not want to give up the focus. 
```javascript
$("#focus_capture").focus();
```

So for now, the case is, after a item has been added, or removed, for the $('#columns') element to lose focus.

sadly chosen:close does not want to do this.

**Comment by StepanKuzmin** [comment]
Subscribing. I've got the same issue.
