### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jmeas** [harvesthq/chosen#2208]
This package has no doubt been tested by the thousands and thousands of developers using it, but are there no tests? Would you be interested in adding some tests?

**Comment by tjschuck** [comment]
Previous discussions: https://github.com/harvesthq/chosen/pull/1401 & https://github.com/harvesthq/chosen/pull/1462

**Comment by jmeas** [comment]
Ah, oops. I should have looked closer. My search for "test" and "unit" did not return either of those. Feel free to close this as a duplicate.

**Comment by tjschuck** [comment]
I'll close this one, but both of those discussions are old and never really ended up anywhere.  If you want to try to either reanimate one of them or start something anew, I'd love to get some tests in place.  /cc @stof @koenpunt

**Comment by jmeas** [comment]
Cool. If I've got time this week I might try to set something up.
