### ISSUE TITLE
Enter press dont chose the selected option

### ISSUE THREAD

**Issue by dorshay** [harvesthq/chosen#2210]
When 'Enter' pressed the select option dont get selected

**Comment by tjschuck** [comment]
Works for me on the [Chosen homepage](http://harvesthq.github.io/chosen/).

What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided.
