### ISSUE TITLE
Only open dropdown after typing has begun

### ISSUE THREAD

**Issue by pdaly85** [harvesthq/chosen#2211]
Great plugin! Is there a way to only activate the dropdown of options after a user has started typing? We have a lot of options within our selectbox and do not want to show them all to the user as soon as the input is clicked but instead only show the options related to their typing with suggestive search.

Thanks in advance
Paul

**Comment by pfiller** [comment]
Nope - this isn't an option in Chosen and is unlikely to become one.

Thanks for the kind words :)

**Comment by jatinabbacus** [comment]
Yes, There is no option for Only open dropdown after typing has begun. But if you need to do by hook or by crook then you need to change in chosen.css and chosen.js files.

Thanks
Jatin Soni
