### ISSUE TITLE
Validation Error Placement Issue

### ISSUE THREAD

**Issue by DeathBliss** [harvesthq/chosen#2216]
I m using this Plugin for enabling Search Option in Select Tag Chosen Plugin

But I m facing Issue When I Validate the Page .. It place Error on Top of the Select Control and The Error Look Like this 
![qjiey 1](https://cloud.githubusercontent.com/assets/10785831/5988151/9816f930-a979-11e4-9de6-7a95810ebfe3.jpg)

But I want to display Error after the Control 

Inspect Element 
![8cluy 1](https://cloud.githubusercontent.com/assets/10785831/5988149/8c0391bc-a979-11e4-9a0d-146f5de2e26c.jpg)

$('.chosen-select').chosen({
    disable_search_threshold: 10,
    no_results_text: "Oops, nothing found!",
    search_contains: true,
    width: "95%"
}).trigger("chosen:updated"); 

Please Suggest me How I can fix this issue

Thanks

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
