### ISSUE TITLE
Ideas for naming new option

### ISSUE THREAD

**Issue by spg** [harvesthq/chosen#2218]
I'm working on a Chosen clone written using GWT (https://github.com/ArcBees/gwtchosen).
I'd like to implement an option to hide the top div above the input, like in the image below:

![chosen_2](https://cloud.githubusercontent.com/assets/892367/6022886/1419a59e-ab8e-11e4-99c3-28f68586220b.png)

My question is: how would you guys name such an option? Does that div have a particular name amongst Chosen gurus?

My ideas so far are:
* hideChoice
* hideSelectBar

Any other ideas?

**Comment by pfiller** [comment]
What an interesting question! I don't think we have a common name for that area and the only css class on it is the unhelpful `chosen-single`. I'd probably wing it and go with something like `hideSelectedValue`? Dunno!

That's an interesting project. Thanks for sharing the link. :clap: :clap:
