### ISSUE TITLE
Invalid HTML Ouput block element not allowed on inline element a

### ISSUE THREAD

**Issue by jochen-werner** [harvesthq/chosen#2219]
the method **Chosen.prototype.set_up_html** generates invalid html. 
`this.container.html('<a class="chosen-single chosen-default" tabindex="-1"><span>' + this.default_text + '</span><div><b></b></div></a><div class="chosen-drop"><div class="chosen-search"><input type="text" autocomplete="off" /></div><ul class="chosen-results"></ul></div>');`

 the a href contains a block element `<div><b></b></div>`. this is not allowed for inline elements. use a `span` or somthing else instead.

http://www.w3schools.com/html/html_blocks.asp

**Comment by LostKobrakai** [comment]
It's not optimal, but it's not really bad either see here: http://html5doctor.com/block-level-links-in-html-5/

**Comment by jochen-werner** [comment]
headings and paragraphs may occur in a link element. thats correct. but ad div element is not allowed. try it on on W3C validator.

**Comment by pfiller** [comment]
In HTML5, pretty much anything goes and this is allowed just fine. It's a brave, new world!
