### ISSUE TITLE
Select all & disable remaining

### ISSUE THREAD

**Issue by 05BIT008** [harvesthq/chosen#2220]
Hello 
I have implemnet one dropdown for coutries. 
where first option is all  country. 
while change drop down , if i select first option other remaining option should be disabled. 
if i select India & then select all country , "India" should be removed from my drop-down box 

i am also storing all_country in db also. 
can you please suggest how to implement this feature. ?

Thank you

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

For this, you probably just need to do whatever value-setting/unsetting you need on the underlying `select`, then call [`chosen:updated`](http://harvesthq.github.io/chosen/options.html#triggerable-events) on it to rebuild Chosen.
