### ISSUE TITLE
<option numeric="True"> discarded in chosen.js

### ISSUE THREAD

**Issue by NileshPujari01** [harvesthq/chosen#2221]
Hi,

my dropdown items have two attributes,one is value and another is custom attribute "numeric". like shown below.

```html
<option value="123" numeric="True">test new</option>
```

when dropdown gets value from database. tag eliminates the numeric attributes and shows option tag like this.

```html
<option selected="selected" value="123">test new</option>
```

because of this i am not able to retrieve the numeric attribute value.
how can i access my both attributes using this plugin when data coming from database and getting by SelectedValue proeprty. 

How can we resolve this?

**Comment by qwelyt** [comment]
You forgot to add the code-tags. We can't see what you are doing.

**Comment by tjschuck** [comment]
@qwelyt Fixed it.

**Comment by tjschuck** [comment]
@NileshPujari01 Adding your `numeric` attribute to `option` is invalid HTML.

Do things behave more like you'd expect when you rename it to `data-numeric`, a valid custom attribute?

**Comment by pfiller** [comment]
I'm not sure what this issue has to do with Chosen. Chosen doesn't make any changes to the options in the original select field and shouldn't be doing anything to the `numeric` attribute. If this is a problem Chosen is causing, can you link to a [fiddle](http://jsfiddle.net) showing the problem happening?
