### ISSUE TITLE
change highlighted style when inherit_select_classes is true

### ISSUE THREAD

**Issue by ComeBurguburu** [harvesthq/chosen#2222]
item style didn't depends on inherit class when item is highligted

**Example**

```css
.missing{
  background-color: red;
}
```

```html
<select>
  <option>article 1</option>
  <option class="missing">article 2</option>
</select>
```

**Problem**

When no item are selected it's easy to distinct "missing" (in red) and none-"missing" value(white)
But when an item is highligted it is always blue can't distinct if it is "missing" or not

**piece of solutuion**
 
The solution should be to replace highlighted class by missing-highlighted class when `inherit_select_classes` is true but we need to be sure that "missing-highlighted" class exist

**Comment by tjschuck** [comment]
( @ComeBurguburu This is unrelated to your issue, but just giving you a pro-tip since you've opened a couple of issues now: GitHub provides a special syntax for code blocks + highlighting -- [documented here](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).  I updated your comment to use them, but now you know for the future!  :rocket: )

**Comment by ComeBurguburu** [comment]
``````````````````````js
inherit_select_classes: true
````````````````````````````
For each inherit class we imagine the class class_Name-highlighted (ex: missing-highlighted)
When we add highlighted class to an element we add both highlighted and class_Name-highlighted
If the css class class_Name-highlighted didn't exit no change, if yes the highlighted class is overwrite

I will work on a PR soon

**Comment by pfiller** [comment]
I don't think a PR is necessary on this as it's totally possible to make this work with scoped CSS selectors. I've made a [fiddle](http://jsfiddle.net/oj016p26/) that shows it in action, but here's a CSS selector that let's you do what you want with the missing class:

```css
.chosen-container .chosen-results li.highlighted.missing { background: red; }
```

**Comment by ComeBurguburu** [comment]
Great job @pfiller it's exactly what I was looking for (and very easy)
Could you update options page to explain how to overwrite highlighted CSS class ?

issue solved
