### ISSUE TITLE
Multiple select auto add third element on click 

### ISSUE THREAD

**Issue by tom-methot** [harvesthq/chosen#2223]
Like i said in the title, my multiple select auto add the third element when i click to open the list option and i can't find why it does this.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
