### ISSUE TITLE
Can't get the value using Knockout Js

### ISSUE THREAD

**Issue by ccruz2886** [harvesthq/chosen#2224]
clients = ko.observableArray([
               {clientid: 1, firstName: "John" }
]);
                        <select id="location-chosen" class="chzn-select" data-bind=" chosen: clients,
                                                                optionsText: 'property',
                                                                value: valueSelected">
                        </select>
valueSelected //<= Doesn't get the model value selected

ko.bindingHandlers.chosen = {
    init: function (element, valueAccessor, allBindingsAccessor) {
        ko.bindingHandlers.options.init(element);

        $(element)
            .chosen({
                disable_search_threshold: 10,
                placeholder_text_single: "Please select the Location..."
         }).change(function(e1,e2,e3,e4) {
                   //This is only triggered once
            });
        },
        update: function (element, valueAccessor, allBindingsAccessor) {
               ko.bindingHandlers.options.update(element, valueAccessor, allBindingsAccessor);
              $(element).trigger('liszt:updated');
    }
};

I can just get the text value, but not the value 
to get the text value I use $("#id").find(":selected").text()

I like to know If there something there that is wrong... Thanks :)

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
