### ISSUE TITLE
Disabled multiselect does not prevent the dropdown from opening and options being selected.

### ISSUE THREAD

**Issue by notionslate** [harvesthq/chosen#2229]
I recently upgraded to 1.2 webjar from 0.9.14 to get this fix:
https://github.com/harvesthq/chosen/issues/1235
but the problem appears to still be there. Can anyone confirm?

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  Does the problem still occur using the latest Chosen (1.3.0)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided.

**Comment by notionslate** [comment]
Can do. But can you point me to gidance that explains the correct way to disable a chosen component?  I don't see the option and there are several suggestions on past issues, but I can't seem to get any to work properly.

**Comment by tjschuck** [comment]
Just set `disabled` on the underlying `select`.  If you're trying to do it dynamically to an already initialized Chosen instance, set `disabled` on the `select`, and then call `trigger('chosen:updated')` on the `select` to update Chosen to match.

**Comment by notionslate** [comment]
OK, I'm getting up to speed ... much to do since 0.9.14 removing chzn's and liszt's...I feel like I have a lisp!
