### ISSUE TITLE
jQuery Chosen multiple controls

### ISSUE THREAD

**Issue by dzarezenko** [harvesthq/chosen#2233]
I have dynamically generated Chosen elements (cloned from first of them) on my page. But when I click one of cloned Chosen elements looks like it open first one drop-down. So all of cloned elements works via first one.

How can I dissociate cloned elements from first one and force them work separately?

**Comment by ComeBurguburu** [comment]
var new_element=$(my_select).clone(false);
$(new_element).chosen();

**Comment by dzarezenko** [comment]
Thanks a lot, works now!
