### ISSUE TITLE
`chosen:open` event not displaying options for single select

### ISSUE THREAD

**Issue by jmeas** [harvesthq/chosen#2235]
Maybe related to #2234.

As a workaround for #2234, I tried triggering the `chosen:open` event on the element whenever the label was clicked, but the event is also not displaying the options.

**Comment by tjschuck** [comment]
On the examples page, if you do:

```javascript
$("#single-label-example").trigger('chosen:open')
```

the select opens, but immediately closes (but retains focus).  If you do it a second time, it properly opens.

**Comment by tjschuck** [comment]
Oh, that ID is referring to the single select located at http://harvesthq.github.io/chosen/#labels-work-too, by the way.

**Comment by tjschuck** [comment]
^ that behavior also sounds suspiciously similar to https://github.com/harvesthq/chosen/issues/2171 -- wonder if they're related.

**Comment by pfiller** [comment]
> On the examples page, if you do:
> 
> ```javascript
> $("#single-label-example").trigger('chosen:open')
> ```
> 
> the select opens, but immediately closes (but retains focus).  If you do it a second time, it properly opens.

This is no longer true for me. I wonder if #2119 fixed this up, too. Closing until someone provides a Fiddle showing that it's not fixed.
