### ISSUE TITLE
multiple chosen items with checkbox

### ISSUE THREAD

**Issue by www741147** [harvesthq/chosen#2237]
is there any way to set option to chosen items with checkbox?

also,if I checked more items,it displays ellipsis.

**Comment by pfiller** [comment]
Nope - Chosen is only designed to work with HTML select boxes.

**Comment by www741147** [comment]
Thank you!

**Comment by saroz** [comment]
Hello There, 

Is it possible to use "search-choice-close" in "result-selected".
Actually I want to toggle "search-choice" by clicking on "result-selected".

Thank You.
