### ISSUE TITLE
"No Results" functioning link

### ISSUE THREAD

**Issue by wdews** [harvesthq/chosen#2241]
I'm inserting my own hardcoded link into the No Results pane in Chosen like so:

```
$('.chosen-select.locations').chosen({
           no_results_text: 'No locations match your search. <a href="/our-locations" target="_blank">View Locations</a>'
       });
```

However, the link isn't clickable. Its default link action is presumably being prevented using `preventDefault()` somewhere in the DOM tree for this plugin. Is there some easy way I can make this clickable?

I've tried numerous things, including `e.stopPropagation()` on the link itself. Any suggestions? Thanks.

**Comment by vialcollet** [comment]
Hi. Same issue with me. Any update?

**Comment by wdews** [comment]
Bump.

**Comment by koenpunt** [comment]
```js 
element.addEventListener('click', function(event){
  event.stopPropagation();
}, true)
```

Where `true` stands for capture

**Comment by eveyrat** [comment]
Same issue, Any update ?

**Comment by koenpunt** [comment]
Just verified that my proposed solution can work. To make it even easier, the snippet below enables clicking on links in the no results text for all instances on a page:

```js
document.addEventListener('click', function(event){
  if(event.target.matches('.chosen-container .no-results a')){
    event.stopPropagation()
  }
}, true);
```
