### ISSUE TITLE
select multiple and then deselect - placeholder text not displayed completely

### ISSUE THREAD

**Issue by pradeepa87** [harvesthq/chosen#2242]
In a multiple select, select multiple elements and then deselect one by one - on deselecting all the options, the placeholder text is not displayed properly - the input text box does not change its width on selecting multiple options and deselect

**Comment by pfiller** [comment]
I'm not able to reproduce this, but I seem to remember it happening in an older version of Chosen. Are you using the latest version (1.4.0)? If not, can you upgrade and see if it's still happening?

If it's happening on the latest, please provide a link to a [fiddle](http://jsfiddle.net) which reproduces the issue. Thanks!
