### ISSUE TITLE
Chosen doesn't apply width in %

### ISSUE THREAD

**Issue by Cristallix** [harvesthq/chosen#2243]
Hi,

When I use Chosen and set a width in %, Chosen convert it in px rather than staying in %. Sometime it can lead to width issue, and of course when the parent width change, the width isn't updated.

Can you fix this?

Thank you.

**Comment by pfiller** [comment]
If you want Chosen to have a % width, you actually need to pass it when you instantiate the plugin:

```JavaScript
$("select").chosen({ width: '100%' });
```
