### ISSUE TITLE
[bootstrap theme]: not issue: request

### ISSUE THREAD

**Issue by illuminate3** [harvesthq/chosen#2246]
This is not an issue but rather a request for a theme based on Bootstrap 3.3.x.
Chosen 1.0 had such a "theme" which works rather well with 3.3.x but chosen 1.3 doesn't.

Thanks!

**Comment by Erowlin** [comment]
https://github.com/dbtek/chosen-bootstrap
First google search. 
Just used it in my project, worked perfectly.

**Comment by tjschuck** [comment]
Closing, per @Erowlin's answer.  Not likely something that will be added to Chosen itself natively anyway.
