### ISSUE TITLE
chosen:updated lost the field value when it was a multiple selection

### ISSUE THREAD

**Issue by cidylong** [harvesthq/chosen#2247]
This is a very easy reproduce issue.

I got this issue from my Spring MVC project. Spring version is 4.1.2. Chosen version is 1.3

1. Build a form:select field with multiple selection support in a spring form. I included chosen.css, chosen.jquery.js, chosen.proto.js chosen-sprite.png and chosen-sprite@2x.png in my class path.

2. I modified chosen.css to point the images to right location.

3. include <link href="${pageContext.request.contextPath}/css/chosen.css" rel="stylesheet"/> and <script type="text/javascript" src="${pageContext.request.contextPath}/js/chosen.jquery.js"></script>

4. Define my form:select fields: 
<form:select class="chosen-container" id="siteentity_siteSurroundings" path="siteSurroundings" multiple="true" cssStyle="width:300px;">
																	<form:option value="None" label="*** Setup Your Surroundings ***"></form:option>
																	<form:options items="${fn:split(sitesurroundings_t, ',')}" />
																</form:select>
5. call chosen function from javascript: <script type="text/javascript"> 
																	$("#siteentity_siteSurroundings").trigger("chosen:updated");
																	$('#siteentity_siteSurroundings').chosen();
																</script>

Edit and save is working well.

6.When I load it back from DB and edit that field again, problem comes:

a. If I only select one item to save into DB, reload it back to JSP, the form:select field render properly, there is one item was selected in the field.
b. If I selected two or more items to save it to DB, the saving is works, that field value is combination of all selected value separated by ','. i.e.. it is one single string saved in DB. When we use the same JSP load the form:select field value back from DB, there is nothing shows in the selected field. All lost.

I believe it is a bug, developer don't handle multiple selection result case at all.

If it is true, please have it follow up. Actually it is a very nice program, well done, guys!

Please

**Comment by tjschuck** [comment]
Please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

**Comment by pfiller** [comment]
Closing until more info (and a reproduction) are provided.
