### ISSUE TITLE
html encoded values is not finding search match

### ISSUE THREAD

**Issue by dibiancoj** [harvesthq/chosen#2248]
I have a select list item where the text displayed for an option is "E&O". When searched we never find a match.

In Chosen.prototype.get_search_text  return $('<div/>').text($.trim(this.search_field.val())).html();

I believe we should be returning .text() instead of .html(). This way we aren't searching for html encoded items.

**Comment by pfiller** [comment]
I think this is fixed now as a result of #2254. Please re-open with a link to a [fiddle](http://jsfiddle.net) if you're still seeing the problem after upgrading.

**Comment by dibiancoj** [comment]
Still doesn't work. Type O. E&O should be returned. Fiddle is below.

https://jsfiddle.net/hpv4La79/4/

**Comment by adunkman** [comment]
@dibiancoj that Fiddle doesn’t work! :)

**Comment by adunkman** [comment]
I should be more clear. The fiddle throws a script error, and Chosen isn’t initialized.

**Comment by tjschuck** [comment]
Aha, not finding "E&O" for "O" is probably this instead: https://github.com/harvesthq/chosen/pull/1483

**Comment by dibiancoj** [comment]
Try this link
http://jsfiddle.net/hpv4La79/6/

**Comment by adunkman** [comment]
Looks like you’re just missing an option — `search_contains: true`. 

See this updated fiddle: http://jsfiddle.net/hpv4La79/7/. I believe it now works as you’re expecting.

**Comment by dibiancoj** [comment]
Actually let me pull the changes into my full solution with all my chosen and check if the change worked

**Comment by dibiancoj** [comment]
Thanks for your help guys. Everything is working as expected!
