### ISSUE TITLE
HTML entities in options not working

### ISSUE THREAD

**Issue by ngardner** [harvesthq/chosen#2252]
`<select class="chose-select">
<option value="1">Lastname, Firstname &lt;my@email.com&gt;</option>
</select>`

This option doesn't show up correctly in the Chosen widget, the `&lt;` and `&gt;` get converted to their HTML characters, causing invalid markup. Similar to issue #2248

**Comment by pfiller** [comment]
I believe this was resolved when #2254 landed in master. Please grab the latest and re-open if you're still seeing this issue.
