### ISSUE TITLE
Bug when search for phrase from middle words and contain blank space

### ISSUE THREAD

**Issue by jyuan** [harvesthq/chosen#2253]
When I search for a phrase, for example 

> Brooklyn New York

It works fine when I type 

> Brooklyn New

and I can easily choose the item that I want.

But when I try to type 

> New Y

It doesn't work and return null.

**Comment by tjschuck** [comment]
Duplicate of https://github.com/harvesthq/chosen/pull/1483 -- please leave any feedback you have there.  Thanks!
