### ISSUE TITLE
Bower install for latest version throwing a 404 on Windows.

### ISSUE THREAD

**Issue by allanmclemore** [harvesthq/chosen#2256]
Note the older bower install for chosen 1.3 works fine:
bower install https://github.com/harvesthq/chosen/releases/download/v1.3.0/chosen_v1.3.0.zip

However, the latest bower install for chosen 1.4 you have posted on Github is throwing a 404:

 bower install https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip

Terminal window messaging for chosen 1.4 bower install is as follows:

bower not-cached    https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip#*
bower resolve       https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip#*
bower download      https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip
bower EHTTP         Status code of 404

**Comment by ComeBurguburu** [comment]
The link is :
https://github.com/harvesthq/chosen/releases/download/1.4.0/chosen_v1.4.0.zip
not this:
https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip

#2257

**Comment by tjschuck** [comment]
Just updated the tag to be correct.  This should be fixed now.
