### ISSUE TITLE
Add dist folder

### ISSUE THREAD

**Issue by chassq** [harvesthq/chosen#2261]
Hey Guys,

Great lib! Would you mind adding a dist folder with compiled code? It would be nice to have when we use bower to install pkg. Right now we only seem to get the source and would have to compile ourselves. Would be a nice convenience!

Thanks!

**Comment by adunkman** [comment]
@chassq check out the [releases](https://github.com/harvesthq/chosen/releases) section for compiled code. We’re not so happy to include build artifacts in the source repository, since, well, they’re build artifacts. 

Thanks for the interest, though!

**Comment by chassq** [comment]
The issue is your releases section is not set up for a bower pull. You should consider it. Many other javascipt libraries do this and have a build directory on the main release branch.

Sent from my Windows Phone
________________________________

**Comment by tjschuck** [comment]
Bower does not currently support adding a post-install/build step.  We don't provide compiled sources in the repos for many reasons which have been repeatedly stated throughout the issue tracker.

However, you can specify that you'd like to use [the release ZIP](https://github.com/harvesthq/chosen/releases/latest), which includes the compiled and minified sources.

Either install from the command line with 

```
$ bower install https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip
````

or add Chosen to your own project's `bower.json` file, like:

```json
{
  "name": "my-project",
  "version": "1.0.0",
  "dependencies": {
    "jquery": "1.11.0",
    "chosen": "https://github.com/harvesthq/chosen/releases/download/v1.4.0/chosen_v1.4.0.zip"
  }
}
```

See #1509, #1472, and #1333 for more info.

This is even [documented in the README](https://github.com/harvesthq/chosen#bower-installation).

**Comment by pfiller** [comment]
`bower install chosen`

As of 1.4.2, Chosen supports bower installs. Read [the 1.4.2 release notes](https://github.com/harvesthq/chosen/releases/tag/1.4.2) for details.

**Comment by alvarotrigo** [comment]
I personally always find the `dist` folder useful. Even to just compare the amount and size of code I'm going to include in my project or to just compare it with alternatives out there. In this case, `select2`.

**Comment by stof** [comment]
@alvarotrigo having conflicts on all pull requests each time we merge one, because of the dist folder (and so being unable to merge 2 PRs in a row) is a huge burden for maintainers. If you want to see the code size, look at the other repository where we store built files (updated only for releases, not for every push into master)

**Comment by alvarotrigo** [comment]
@stof I see... Just as a though. Maybe pull request can be done in a `dev` branch with no dist folder in it ?
