### ISSUE TITLE
Icon on selected options looks like html code

### ISSUE THREAD

**Issue by andrconstruction** [harvesthq/chosen#2262]
Hi all. Please explain me. Why when I use icons (font-awesome) within chosen, in a list looks like a icon, but when selected, displayed like html code instead an icon.
And I didn't find js file in the new version

![error](https://cloud.githubusercontent.com/assets/7435330/6569076/38c1dc1e-c6f4-11e4-913f-2324e8fb605b.png)

**Comment by tjschuck** [comment]
@andrconstruction Rendering HTML in the options in the first place was actually a security bug, and was recently reverted in 1.4.0 in https://github.com/harvesthq/chosen/pull/2254.  See the linked issues there for more info.

As for the general feature of "adding some design/HTML to options", in these parts we refer to that as "templating", and the canonical place to discuss that is https://github.com/harvesthq/chosen/pull/692.  There's a number of other issues and PRs linked from that one, but please leave any additional feedback you have there.  Closing this in favor of that one.
