### ISSUE TITLE
retrive data by change the filter

### ISSUE THREAD

**Issue by erfanpj** [harvesthq/chosen#2266]
hi
thank you so much for Chosen 

i have some problem and i need to help 
actually i have more than 1000 value and it make my site very fast if i want to retrive all of them
is there a way to retrieve related value by changing text in that input ?
i mean some thing like this =>
if some one write more than 2 character like 'Jac'  and then i just select query the records that contain 'jac'
maybe something like 20 record should be retrieve 

and also i used  

```javascript
$('.my_select_box').on('change', function(evt, params) {
  alert(1);
});
```

but doesn't work :(
Best Regards,

**Comment by pfiller** [comment]
Hi @erfanpj. I apologize, but I don't totally understand your question. It kind of sounds like you're describing the behavior Chosen already does. Can you try another way of asking?

The JS snippet you posted above should work, though. Do you mind making a [fiddle](http://jsfiddle.com) that shows it not working? That will help explain what's wrong or debug it if there's a problem.

Closing pending further information.
