### ISSUE TITLE
Word Label Option is too long. iPhone does not work well on Chosen.

### ISSUE THREAD

**Issue by ajunizar** [harvesthq/chosen#2269]
Hi, I really need help on this problem at iPhone (iOS)

Please check below and choose the 'long' word on iPhone. 
Samsung Note works really well.
FF, Chrome on Desktop are well too. 

Please open it on iPhone : 
http://ifdemo.com/singtel/phase2/request-bill-copy-1.html

I tried with text-overflow:ellipsis but it didnt work. I used original jQuery Chosen here.

I got this problem since it overlap the arrow behind the word selection. 

Is this a bug? 

Please check screenshot below : 
![img_5419](https://cloud.githubusercontent.com/assets/4169200/6669241/d2ea1746-cc32-11e4-9efa-b23599ddb27e.PNG)

**Comment by tjschuck** [comment]
Chosen is [disabled on mobile-sized iOS devices](https://github.com/harvesthq/chosen/blob/c4aa372d4a58dea166f46bf7db77d9f6dd4fc400/coffee/lib/abstract-chosen.coffee#L278-L279) (iPhones and iPods, particularly), and the styles in your screenshot are not Chosen's.  Seems like it's not a Chosen issue.
