### ISSUE TITLE
Ampersands not displaying properly

### ISSUE THREAD

**Issue by tl8roy** [harvesthq/chosen#2271]
![chosen_error](https://cloud.githubusercontent.com/assets/3813500/6699619/7626c400-cd4f-11e4-9e3a-809d65ce4996.png)
While the list shows the ampersands properly, the selected element doesn't. This seems to be a bit strange. I am using Firefox but I have seen it in Chrome.

**Comment by tjschuck** [comment]
What browser version, OS, and OS version are you using?  And what version of Chosen?  Does it still happen using the [latest released version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided.

**Comment by tl8roy** [comment]
I was using 1.3. I have upgraded to 1.4.1 and the issue has gone away.
Thanks
