### ISSUE TITLE
Options having HTML entity or tags appear on matching the HTML char

### ISSUE THREAD

**Issue by vaikoovery** [harvesthq/chosen#2274]
I've an issue with Chosen, in fact, it is a request for new option

I initialize the chosen by,

$("select.has_chosen").chosen({no_results_text:'Oops, nothing found!', width:"100%",search_contains:true});

The issue is when I've used option elements having '&nbsp;' to have space in the options (to have tree structure). Now, when I type n or b or s or p, it checks the '&nbsp' and displays the options having spaces.

Can we have an option like, strip_html_in_search or omit_html_in_search, and if it is set to true, all the HTML chars will not be appearing in result.

Or some other methods are there? Screenshot given below for better clarity.
![html entities](https://cloud.githubusercontent.com/assets/5166249/6729833/67965ece-ce5c-11e4-985b-4310576845b8.png)

**Comment by vaikoovery** [comment]
Replacing space with Code Point - U+2001 (em quad) (Decimal - 8193) and disabling the encode space worked like a charm, however if we can have a feature like requested above would be great.

**Comment by pfiller** [comment]
I don't think this is a problem in the current version of Chosen. Search for html sequences does not trigger a match for me. Please try the latest version!

**Comment by vaikoovery** [comment]
As mentioned above, if I type 'nb', it will display the results including the HTML characters.

To be more clear, I have JSFiddle link with example for you.
https://jsfiddle.net/Vaishak/d6c319su/

I hope you understand what I meant.

**Comment by tharban** [comment]
@pfiller I think this should be reopened. I see this with all html entites happening and the JS fiddle above shows this as well (he uses https://harvesthq.github.io/chosen/chosen.jquery.js within the JS fiddle - which IS the latest version afaik).

Simply search for nb in the fiddle and you see HTML entities popping up all over the place.

**Comment by tharban** [comment]
I hacked this by decoding the entities before I do the search - does not seem to be the right solution though, but that's up to @pfiller to implement ... I got lost in the library as I did not understand all intricacies of the code 

```javascript
      function decodeEntities(input) {
          var y = document.createElement('textarea');
          y.innerHTML = input;
          return y.value;
      }

    AbstractChosen.prototype.search_string_match = function(search_string, regex) {

      var decodedSearchString = decodeEntities(search_string);

      var part, parts, _i, _len;
      if (regex.test(decodedSearchString)) {
        return true;
      } else if (this.enable_split_word_search && (decodedSearchString.indexOf(" ") >= 0 || decodedSearchString.indexOf("[") === 0)) {
        parts = decodedSearchString.replace(/\[|\]/g, "").split(" ");
        if (parts.length) {
          for (_i = 0, _len = parts.length; _i < _len; _i++) {
            part = parts[_i];
            if (regex.test(part)) {
              return true;
            }
          }
        }
      }
    };
```

**Comment by tharban** [comment]
Another change needed here:

          option.search_text = option.group ? option.label : option.text;

instead of 

          option.search_text = option.group ? option.label : option.html;

**Comment by RuchiraG** [comment]
@tharban's solution worked for me. Thanks!

**Comment by johnobono** [comment]
I recommend to use normal spaces and applying css rule "white-space: pre;" to the chosen-class .chosen-container .chosen-results li.active-result
