### ISSUE TITLE
jQuery('select').chosen() innot working my magento web 

### ISSUE THREAD

**Issue by baricvpz** [harvesthq/chosen#2277]
jQuery('select').chosen() innot working my magento web . It showing an error 
Uncaught TypeError: undefined is not a function(index):529 (anonymous function)
jquery-1.10.2.min.js:
4 x.Callbacks.cjquery-1.10.2.min.js:4 x.Callbacks.p.fireWithjquery-1.10.2.min.js:
4 x.extend.readyjquery-1.10.2.min.js:4 q
error url : http://www.puregrowndiamonds.net/customer/account/create/

WEB URL :puregrowndiamonds.net
user:pgd
pwd:pgd123

**Comment by cortopy** [comment]
It's not a problem with chosen but JS conflict in magento. Until Magento 2 is out, you have to run jQuery in no conflict mode.

Try

```
var $j = jQuery.noConflict();
$j('select').chosen();
```

**Comment by tjschuck** [comment]
Closing this per @cortopy's answer -- sounds like it's not a Chosen issue.
