### ISSUE TITLE
search_contains in the global configuration of chosen

### ISSUE THREAD

**Issue by AlexisDarbon** [harvesthq/chosen#2279]
Hello, 

I have just discovered Chosen and it seems to be pretty powerful and adaptable. 

However, I have a simple problem with the search_contains option: I would like to set it at "true" for all instances of chosen. 

On my website, there are numerous reasons to allow people to search for strings inside names so all the "select" boxes would have to call chosen while including { search_contains: true }, which means a lot of repetitive code. So, I would like to be able to configure it from the start at "true" (and, if the need arises, I would set it back to false on specific select boxes).

I have seen that one could configure a global width (and other default settings) for chosen through the variable 
var config = {
 '.chosen-select-.width' : {width:"95%"}
}

So I tried to add '.chosen-select-search': {search_contains:true}
I also tried with '.chosen-select-search-contains': {search_contains:true}
and with simply '.chosen-select': {search_contains:true}

but it never worked. 

Is there a way to configure chosen this way?

Thank you for your help

Alexis

**Comment by pfiller** [comment]
That global config setting is a custom thing built for the Chosen demo pages. It's not actually built into Chosen itself. In order to set up defaults, you could do something like create a settings object and pass it to Chosen every time you initialize it.

```JavaScript

var defaultChosenOptions = { 'search_contains': true }

// default options
$(".field1").chosen(defaultChosenOptions);
$(".field2").chosen(defaultChosenOptions);

// no search contains
$(".field3").chosen();
```

**Comment by AlexisDarbon** [comment]
Okay, thank you
