### ISSUE TITLE
seems impossible to use a virtual keyboard with chosen

### ISSUE THREAD

**Issue by yianni** [harvesthq/chosen#2280]
Seems not possible to use a virtual keyboard (like mottie) with chosen since the text box on the drop down has no id.

Am I missing something? Is there any way to change 
```javascript
<input type="text" autocomplete="off" tabindex="5">
```
which is the textbox to something custom that includes an id in it?

**Comment by pfiller** [comment]
I'm not sure why you'd want to use a virtual keyboard, but an ID is _not_ a requirement of Mottie. Take a look at the "QWERTY Text" example on [their page](http://mottie.github.io/Keyboard/).

**Comment by yianni** [comment]
Many thanks for prompt reply. Need a virtual keyboard cause simply there not a physical one :). Anyway, I had a look on their examples before posting here cause all of them take the id of the textbox. :(
