### ISSUE TITLE
Bower improvements

### ISSUE THREAD

**Issue by hostep** [harvesthq/chosen#2288]
Hi

I just noticed you added support for bower, which is great!
But I have a few remarks:
- You should also add the prototype build, not only the jquery build
- You should also add the non-minified versions (both js and css)

Thanks!

**Comment by pfiller** [comment]
I agree with the non-minified versions, but am not sold on shipping the Prototype version. jQuery is the top library on Bower's install stats and, as far as I can tell, there isn't even an official bower package for Prototype.

**Comment by hostep** [comment]
Ah, well let me explain.
We use the Chosen library in a few Magento projects, and Magento ships with Prototype by default, so we already have Prototype in our project, it isn't pulled in with bower.

**Comment by SimoSca** [comment]
Command
````
$ bower install chosen
````

does install a wrong version. After time, i've noted the `bower-chosen` repo.

I suggest update the [chosen readme](https://github.com/harvesthq/chosen) for other user.

I've solved with

````
$ bower install harvesthq/bower-chosen --save
````

Bye!

**Comment by stof** [comment]
@pfiller please register the ``chosen`` package in the Bower registry

**Comment by jblotus** [comment]
is there any way we can have unminified  versions of js and css included in bower-chosen ? we have our own minification pipeline and prefer unminified for development

**Comment by pfiller** [comment]
Going to close this up. The non-minified versions are now in bower and the repo seems to have been properly registered in the bower repository.
