### ISSUE TITLE
Is there any way to unmount chosen ?

### ISSUE THREAD

**Issue by nicolas-besnard** [harvesthq/chosen#2290]
I can't find it in the documentation. I'd like to unbind `chosen` from my `<select>`

**Comment by koenpunt** [comment]
Easy
```js
$('select').chosen('destroy');
```

Or use `enable` / `disable`

**Comment by koenpunt** [comment]
But good that you bring this up, because apparently this is nowhere to be found in the documentation..

**Comment by koenpunt** [comment]
Oh my bad there's no enable or disable, but destroy should work.
@harvesthq/chosen-developers anyone feels up to the task of adding docs for destroy? Or am I missing something?

**Comment by tjschuck** [comment]
@koenpunt Added in #2436 (finally!).
