### ISSUE TITLE
I demand order! Heh.

### ISSUE THREAD

**Issue by intellilogic** [harvesthq/chosen#2291]
The order of a list is important for some uses of this plugin.  I would like to be able to drag and drop reorder a ‘Multipule Select’ as well as place cursor at a position and add an item.  Any other means of managing the order would also be great :)   How to add Feature Request label?  Can someone do this for me?

**Comment by tjschuck** [comment]
Chosen aims to be a progressive replacement for HTML select elements. Native multi-selects don't support a notion of order -- they're submitted in the order that the selected elements appear in the DOM -- therefore neither does Chosen.

See #1847 for slightly more, or search the issues for "order" for a lot more.
