### ISSUE TITLE
Older versions of chosen no longer available via bower

### ISSUE THREAD

**Issue by jcbrand** [harvesthq/chosen#2294]
``bower info chosen`` only shows versions 1.4.1 and 1.4.2 as available.

I have a stack that depends on a much older version and therefore get the error:
```
bower chosen#0.9.11  ENORESTARGET No tag found that was able to satisfy 0.9.11
```

I see that the odler tags are still there, so I'm not sure whether this is a bower issue or a chosen issue.

Any help with this would be appreciated.

**Comment by chrisgalvan** [comment]
as a workaround you can try in bower.json point to the original repo and specify your version: 
"chosen": "https://github.com/harvesthq/chosen#0.9.11"

**Comment by stof** [comment]
@pfiller It would make sense to include older chosen releases in our special repo

**Comment by jcbrand** [comment]
So that's the problem. You have now bower specific repo which only has versions 1.4.1 and 1.4.2.

@chrisgalvan thanks for the workaround, but this means I have to hunt down every single dependency of our project which itself might depend on an older version of chosen and update its bower.json file (potentially requiring a fork in the process).

**Comment by stof** [comment]
@jcbrand given that chosen 0.x is not maintained anymore since 1.5 year (and 0.9.11 is itself 6 months older than the last 0.x release). So updating to the maintained version is a needed work anyway

**Comment by tjschuck** [comment]
Additionally, Chosen versions < 1.4.1 were _never_ in bower, so this doesn't really seem like a change in any way.

You can read the old bower docs removed in [this commit](https://github.com/harvesthq/chosen/commit/8897bbc56cab0e9059d260897405362176a272bd) for instructions on using bower to install old versions from the [Releases page](https://github.com/harvesthq/chosen/releases).

**Comment by jcbrand** [comment]
@stof yeah, I understand it's an old version, but this is not a reason to make something that was previously available now unavailable.

@tjschuck They definitely were in bower. Here's a commit from January 2014 which adds chosen to Patternslib's bower.json: 
https://github.com/Patternslib/Patterns/commit/199bc035dd68d2bcce0f19ed951cfbb860afb687

We've been using Patternslib (with chosen 0.9.11) with bower all this time.

**Comment by pfiller** [comment]
@jcbrand I'm sorry we broke old versions of Chosen working with Bower. I did not anticipate that side effect of our change and it sucks that our recent change will make more work for you.

That being said, we were kind of stuck between a rock and a hard place. The only way we could realistically support Bower going forward was to move to a new repo. The only way we could move to a new repo was to remove the old Bower instance.

If there's a way to add older tags to the bower-chosen repo without making a mess of that project, I'd consider a PR. I don't know that there's a way to do it that makes sense, though?

**Comment by kim3er** [comment]
To expand on @chrisgalvan's workaround, the following worked for me:

```
"chosen": "git://github.com/harvesthq/chosen.git#0.9.11"
```

**Comment by stof** [comment]
I would strongly advice you to upgrade to a maintained version of Chosen though. 0.9 is unmaintained since more than 2 years

**Comment by kim3er** [comment]
@stof: No doubt! My specific need was for a project (of a similar age), that has Bower as part of the deployment strategy. The project in question has budget for additional work. I suspect other people will be in a similar situation, which is why I posted the update.
