### ISSUE TITLE
instant close of the dropdown list

### ISSUE THREAD

**Issue by feralanPaladin** [harvesthq/chosen#2296]
Hi,

In my project I need an event to trigger the instant close of the dropdown list even it is currently selected or mouse is over the chosen.

So I have added a trigger in Chosen.prototype.register_observers function like;

      this.form_field_jq.bind( "chosen:instantClose.chosen", function () {
          _this.close_field();
      } );

Is this a hacky way to fulfill my needs or it is suitable. And if it is suitable, would you like to consider to add an instant closing mechanism to chosen library.

Yours sincerely.

**Comment by pfiller** [comment]
Thanks @feralanPaladin. This hasn't been a commonly requested feature and we like to limit features we add to Chosen. I appreciate you sharing the snippet so other folks can find it!

**Comment by aiperon** [comment]
I agree it is rare case. In our project I decided to use one direct call:

    $('select.chosen').data('chosen').close_field()

It will let you make further updates of this library.
