### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by bek816** [harvesthq/chosen#2299]
I have a select multiple and when I try to remove the last option, I get an error:

```
Uncaught TypeError: Cannot read property 'length' of null
Chosen.result_deselect chosen.jquery.js:994 
Chosen.choice_destroy chosen.jquery.js:989 
Chosen.choice_destroy_link_click chosen.jquery.js:978 (anonymous function)
jquery-2.1.3.min.js:3 n.event.dispatchjquery-2.1.3.min.js:3 n.event.add.r.handle
```

I'm using chosen Version 1.4.2.  

Here's an example of my Select multiple:

```html
<select multiple class="chosen-select" data-placeholder="Select" style="width: 400px; display: none;">
<option value="ALC">ALC</option>
<option value="Arizona">Arizona</option>
<option value="Arkansas">Arkansas</option>
</select>
```

Note that the select multiple is populated when the user clicks to show a modal from data in a DataTable (similar to what you would see here:  https://datatables.net/examples/api/multi_filter_select.html)

```js
var select = $('<select multiple class="chosen-select" data-placeholder="Select" style="width:400px;"></select>')
...
column.data().unique().sort().each( function ( d, j ) {
    select.append( '<option value="'+d+'">'+d+'</option>' )
} );
```

And finally:

```js
$(".chosen-select").chosen({
            	width: "50%"
            });
```

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?

Can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

**Comment by bek816** [comment]
I can actually explain this one on my own.  I got a little thrown off track by the strack trace referencing Chosen at the top.  The error has nothing to do with Chosen.  I had some jquery code that fired in an on change event that was generating the error.

**Comment by tjschuck** [comment]
@bek816 Glad you figured it out, and thanks for following-up!
