### ISSUE TITLE
Cannot close multiple select's dropdown

### ISSUE THREAD

**Issue by feralanPaladin** [harvesthq/chosen#2302]
Hi,

By triggering chosen:close, I cannot manage to close the dropdown menu of the multi selectable chosen.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If you're not using the [latest version of Chosen](https://github.com/harvesthq/chosen/releases), does the issue still happen if you upgrade?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
