### ISSUE TITLE
"chosen-results" is empty on first load

### ISSUE THREAD

**Issue by spadilha** [harvesthq/chosen#2303]
First I'd like to thanks for this great plugin. Good job guys.

I'm working on a project that I need to style the scrollbar of the options list and I'm using Tinyscrollbar to do that. The good thing is that Chosen already transformed the options list in a UL list, which is required. The only problem is when Chosen is loaded for the first time it doesn't populate the UL list items inside "ul.chosen-results". As the list is empty, the tinyscrollbar doesn't work.

I've found a work around, which is trigger 'chosen:open' and then 'chosen:close' before I call tinyscrollbar, but the bad thing is that the list "blinks" on the page when it's loaded. 

So, is there any better way to force Chosen to populate the list items inside "chosen-results" when it first loads? 

Thanks!

**Comment by tjschuck** [comment]
Does just triggering `chosen:updated` work?

**Comment by pfiller** [comment]
I don't think Chosen and Tiny Scrollbar work very nicely together.

Tiny Scrollbar doesn't appear to keep track of changes to the div its applied on. That means that any time the div changes shape, you'd need to call `update` on Tiny Scrollbar to make it look right. In Chosen, that means you'd want to call `update` any time a search happens (a search for "" happens the first time you open Chosen).

Chosen doesn't currently have any kind of "search results changed" event which means you'd need to modify its source code to call Tiny Scrollbar's update. It's not impossible, but it does seem like a lot of trouble to replace a scrollbar.

Good luck, @spadilha!
