### ISSUE TITLE
Scripting API for changing things on the fly

### ISSUE THREAD

**Issue by MK-Chris** [harvesthq/chosen#2305]
Hi

I'm wondering if you'd consider adding some API methods; apologies if I've missed this, but I don't think it's something that's available at the moment, which is a shame as I'd love to start using it.

Some useful options to include would be:

* Enable.
* Disable.
* Change selected option(s).
* Add options.
* Remove options.

Thanks

Chris

**Comment by tjschuck** [comment]
Check out [the options page](http://harvesthq.github.io/chosen/options.html), particularly the bottom section of "Triggerable Events".

For your bottom three examples, you would just update the underlying `select` however you chose, and then call `chosen:updated` to update Chosen to match.

**Comment by MK-Chris** [comment]
Ah okay thank you, I'll check that out - I'm wondering if that would work for disabling / enabling as well, though if not I guess I could encase it in a div that gets hidden instead as a workaround.

**Comment by tjschuck** [comment]
For enable/disable:

* If you mean opening/closing, there are events for that -- `chosen:open` and `chosen:close`
* If you mean actually enabling/disabling Chosen itself, you call `.chosen()` on the `select` itself to enable, and you can disable it with `.chosen('destroy')` (which is unfortunately currently undocumented -- see #2290)

**Comment by MK-Chris** [comment]
I mean as though the select has the disabled property set as in:

    <select disabled="disabled">

I've just tested and this works:

    $(".chosen").prop("disabled", true);
    $(".chosen").trigger("chosen:updated");

So all sorted, thank you!

**Comment by tjschuck** [comment]
Aces, glad it's working out for you!
