### ISSUE TITLE
data-placeholder doesnt work

### ISSUE THREAD

**Issue by neonwired** [harvesthq/chosen#2308]
My html is below, on load it displays 'All' instead of the placeholder text.
```
<select name="spill" class="chosen" data-placeholder="Type">
	<option value="">All</option>
	<option value="1">type 1</option>
	<option value="2">type 2</option>
	<option value="3">type 3</option>
	<option value="4">type 4</option>
</select>

**Comment by neonwired** [comment]
My html is below, on load it display 'All' instead of the placeholder text.
```
<select name="spill" class="chosen" data-placeholder="Type">
	<option value="">All</option>
	<option value="1">type 1</option>
	<option value="2">type 2</option>
	<option value="3">type 3</option>
	<option value="4">type 4</option>
</select>

**Comment by tjschuck** [comment]
The option has to be blank.  See [the docs for placeholder text](http://harvesthq.github.io/chosen/#default-text-support):

> To take advantage of the default text support, you will need to include a blank option as the first element of your select list.

**Comment by neonwired** [comment]
It is blank?

```
<option value="">All</option>
```

**Comment by MrGeneric** [comment]
I believe he means it should look like this.

```
<select name="spill" class="chosen" data-placeholder="All">
    <option value="Type"></option>
    <option value="1">type 1</option>
    <option value="2">type 2</option>
    <option value="3">type 3</option>
    <option value="4">type 4</option>
</select>
```

**Comment by tjschuck** [comment]
@neonwired 

```html
<option value="">All</option>
            <!-- ^^^ Not blank -->
```

You first option must be something like `<option></option>` or `<option value="foo"></option>`.

**Comment by yairEO** [comment]
you should initialize Chosen with `placeholder_text_single:'Choose your user identifier'`
