### ISSUE TITLE
Overlap issue using two chosen drop downs

### ISSUE THREAD

**Issue by matt-tyas** [harvesthq/chosen#231]
I am having a problem whereby if I have two selects using chosen (one above the other visually) then the drop down area of the first one appears below the select below making it harder to choose the correct option. Has anyone else had this issue? It looks like a z-index thing and it does it in all browsers.

Cheers

**Comment by rushdib** [comment]
> I noticed the same thing. I applied a similar hack to @matt-tyas:
> 
> ```
> $('.chzn-container').each(function(i){
> 
>     $(this).closest('div').css('z-index', 999-i);
> });
> ```

Having the overlap issue. I added the solution by phrischybar but nothing is changing.
