### ISSUE TITLE
TypeError: Undefined is not a function ( evaluting $(selector).chosen(config[selector]) )

### ISSUE THREAD

**Issue by salmenbej** [harvesthq/chosen#2313]
I have this error only on mobile. How can i resolve it?

My Code:

```javascript
var config = {
    '.country'                   : {},
    '.state'                       : {},
    '.product-size'           : {disable_search: true},
    '.user-title'                 : {disable_search: true},
    '.languages'              : {disable_search: true}
}
for (var selector in config) {
  $(selector).chosen(config[selector]);
}
```

**Comment by tjschuck** [comment]
Chosen is disabled on mobile, so it's unlikely a Chosen issue.  See the [third question in the FAQs](http://harvesthq.github.io/chosen/#faqs).

However, if you still think it's Chosen, what mobile browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided.

**Comment by salmenbej** [comment]
Thanks for the reply. It was my fault, i solved the problem.
