### ISSUE TITLE
chosen:update event ignores selected options

### ISSUE THREAD

**Issue by modo-lv** [harvesthq/chosen#2317]
1) I have a multiple select box with several options (none selected).
2) I call .chosen() on it.
3) I mark several options with "selected" attribute using JavaScript.
4) I trigger 'chosen:update', but the selected options are ignored and the Chosen box stays empty.

**Comment by modo-lv** [comment]
My apologies, is mistyped and was calling 'chosen:update' instead of 'chosen:updated'.

**Comment by yairEO** [comment]
It's sooo confusing right??? why was it name "updated" if you are updating it right at that moment!? it should have been "update" because you are giving it a command to **be** updated. an "updated" event is something that should be triggered **after**  you trigger your "update".
