### ISSUE TITLE
Option for <em> tag when type in input

### ISSUE THREAD

**Issue by samansoft** [harvesthq/chosen#2318]
In Persian and Arabic languages when we search on input typed text will be selected on ```<em>``` tag and make the options to be unreadable for if the ```<em>``` tag will be optional this problem will be fixed

Example: 
options are: استاتیک
when we type است result will be اتیک**است**

you see there is break because Persian letter could stick to each other to form something

**Comment by tjschuck** [comment]
Can you please create a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

**Comment by saman-php** [comment]
Sure [codepen link](http://codepen.io/xengil/pen/GJgRRP)

Because you don't have Persian keyboard just copy "ص" to see the problem

tnx for your works

**Comment by saman-php** [comment]
I find out this problem exits in google chrome 41 in fire fox this looks good

**Comment by pfiller** [comment]
The codepen link seems to be broken and I'm not sure I understand the issue. Would welcome this being re-opened if someone can provide a new demo link and explanation.

**Comment by samansoft** [comment]
I created another [Codepen](http://codepen.io/xengil/pen/gMPrOK), You can copy "س" to search input and characters will separate, the reason this happens as you may notice is in Persian characters will connect to each other to create a new word in opposite of English that just alphabet create word
