### ISSUE TITLE
CDN update

### ISSUE THREAD

**Issue by cortopy** [harvesthq/chosen#2321]
Could the project be updated on the jsDelivr CDN? Only 1.1.0 available there

http://www.jsdelivr.com/#!chosen

**Comment by kevin-brown** [comment]
jsdelivr only supports automatic updates at the moment, and [chosen doesn't have an `update.json` file](https://github.com/jsdelivr/libgrabber#add-updatejson-schema). jsdelivr requires the compiled assets to be available in the repository, which was not possible until recently.

You might want to submit a PR to jsdelivr which sets up the autoupdate based on the [bower-chosen repository](https://github.com/harvesthq/bower-chosen).

**Comment by pfiller** [comment]
Yup - @kevin-brown is right. We don't have any control over what's in jsDelivr (in fact, this is the first I've ever heard of it). They should be able to point at the other repo ([bower-chosen repository](https://github.com/harvesthq/bower-chosen)) to get the latest versions.

**Comment by delmicio** [comment]
+1
