### ISSUE TITLE
how using?

### ISSUE THREAD

**Issue by onepiece2015** [harvesthq/chosen#2322]
i don'know how to use it, who can tell me, thanks!

**Comment by stof** [comment]
Have you read the documentation ? http://harvesthq.github.io/chosen/

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
