### ISSUE TITLE
IN IE 9 Browser :SCRIPT5007: Unable to get value of the property 'length': object is null or undefined 

### ISSUE THREAD

**Issue by kranjith21** [harvesthq/chosen#2323]
I am using chosen_v1.4.2 autosearch 

Dependent drop down autosearch fields are in modal popup(example:country,State,City)...

while select the country,the following error is came in only IE9(Higher version in os is 9). Also post back not working (select country)
Ajax Control Toolkit version: 3.0.30930.0

SCRIPT5007: Unable to get value of the property 'length': object is null or undefine
ScriptResource.axd?d=ZfqeTAf_CX9NaNMbCmfz2oJlaxrA2P9BNBwaaMYgFL4CqtZoGlvElQVvCQC-eKgB_4dX0SrgvAClYz1pE9oUYDfXM8q8sj6EEgTVtwDR6XHmzE6Px-PJDVV1hEucu5Q5wlauG7pvvpV7sPILrW5Nn5qHB781&t=ffffffff967a6818, line 172 character 17 

Please find the below screen shots ......

![sdsdsd](https://cloud.githubusercontent.com/assets/12274743/7494342/ae2da3fe-f424-11e4-9c6f-17e148363357.png)
![untitled](https://cloud.githubusercontent.com/assets/12274743/7494348/b32dc1ea-f424-11e4-8068-657933c29ebc.png)

**Comment by tjschuck** [comment]
@kranjith21 Do you get the same error on the [Chosen demo page](http://harvesthq.github.io/chosen/)?

**Comment by kranjith21** [comment]
No the above error is not coming in chosen demo page.I opened chosen demo page in IE 9 browser i found that chosen jquery is not applied.But i used choosen drop down in my asp.net form pop up,the chosen auto search is works fine in IE 9.but while select the chosen drop down above i mentioned error is came.this error is affect the post back trigger of drop down

**Comment by kranjith21** [comment]
my IE  version 9.0.2.

**Comment by kranjith21** [comment]
In IE 11 environment system .the above mentioned error not coming in IE 9.Only get the error in IE 9 environment system.

**Comment by wedneyyuri** [comment]
What the jQuery version you are using on your page?

**Comment by pfiller** [comment]
Is this still an issue now that Chosen is at 1.5.1? If so, can you provide a link that shows the bug in action?
