### ISSUE TITLE
Issue with quotes in Post back data "1" instead of 1

### ISSUE THREAD

**Issue by jmb-mage** [harvesthq/chosen#2326]
I am using the Chosen control which works fine but it is adding in quotes to the Post data that throws off the MVC Validation.

Instead of `1` we get `"1"` back during Post processing in the Controller.

**Comment by pfiller** [comment]
Chosen doesn't do anything to the original select form's values so any POST data issues are coming from the form itself or the code parsing the submitted data. You should be able to confirm this by turning Chosen off and submitting the form.
