### ISSUE TITLE
chosen not scrollable on android tablet

### ISSUE THREAD

**Issue by k-risc** [harvesthq/chosen#2330]
As said in #2239, chosen is supported on Android tablets. However, we are experiencing problems on an Android tablet (Android 5.1 with Chrome 42.0.2311.11):
The chosen dropdown is not scrollable, and thus in longer lists only the initially **visible** entries are accessible and choosable. If searching is enabled, the user can make other entries visible by entering an appropriate search text, of course. But for lists without search enabled, there is no way to scroll entries into view that are initially not visible.

Has anybody made similar experiences?

**Comment by basnilsson** [comment]
Same problem here on ipad with chrome.

**Comment by SerjNarbut** [comment]
Some problem on chrome 43.0.2357.97 android 4.4.2

**Comment by wkerswell** [comment]
I have this problem on the iPad 2 safari. List loads with options which the user can search through with the keyboard but can not scroll.

**Comment by JustasKuizinas** [comment]
Same problem with ipad2 cannot scroll

**Comment by wkerswell** [comment]
I ended up editing the code in include iPad in the list of ignored devices. Not great but needed a quicker fix.

**Comment by PanMinion** [comment]
chosen is scrollable but in ver 1.4.0 on 1.4.1 and 1.4.2 it doesn t work (on Tablet).
Can u do something with this ?

**Comment by setage** [comment]
If you read documentation carefully, you will see that:

> All modern desktop browsers are supported (Firefox, Chrome, Safari and IE9). Legacy support for IE8 is also enabled. **Chosen is disabled on iPhone, iPod Touch, and Android mobile devices**

Let users use native mobile OS selects, which more convenient on these devices.

**Comment by koenpunt** [comment]
This problem apparently occurs on all tablet devices. Closing in favor of #2289
