### ISSUE TITLE
Bind event after Chosen is updated (not select)

### ISSUE THREAD

**Issue by piotrkulpinski** [harvesthq/chosen#2331]
Hi,

I'm trying to create such functionality for multiple select field using chosen: https://www.dropbox.com/s/bc60xvprvntxuii/Screenshot%202015-05-20%2012.11.20.png?dl=0

In order to do that I bind 'change' select and count all 'seach-choices' in chosen field and it works ok when I add values to selection. The problem occurs when I try to remove the selected values.
The 'change' event is bind to select field and when it's triggered the deleted value isn't yet removed so I can't count those selected values correctly.

Is there an event which triggers after chosen is updated (not select field values) or do you plan to implement it in near future?

Cheers, Piotrek

**Comment by yazanalsaber** [comment]
I have the same issue
the "chosen-choices" is empty, even after select some choices

**Comment by pfiller** [comment]
> The 'change' event is bind to select field and when it's triggered the deleted value isn't yet removed so I can't count those selected values correctly.

Why do you need to count the choices using Chosen's DOM elements when you can count the number of selected values on the field itself? 

```JavaScript
values = $("#select_you_applied_chosen_two").val()
values.length // the number of selected values
```
