### ISSUE TITLE
Fails to load with tabs

### ISSUE THREAD

**Issue by joneastwood** [harvesthq/chosen#2332]
I have chosen working on others pages in my app all fine, But if I try to use chosen in my css tabs it fails.

If I try to create a chosen element outside of tab mark up it's fine, if its within the active tab its also fine but if its within a none active tab it fails to load.

See pics:

Outside Tab mark up: - http://www.spiralsites.com/webimages/outside.jpg
In Active Tab mark up - http://www.spiralsites.com/webimages/active.jpg
Inactive tab until clicked - http://www.spiralsites.com/webimages/fail.jpg

Any ideas

**Comment by arjen15** [comment]
try setting width: `.chosen({ width: "100%" });` 
had a similar issue and got the solution from here: https://github.com/harvesthq/chosen/issues/2309

**Comment by joneastwood** [comment]
Thanks yes that's sorted it
