### ISSUE TITLE
Optgroup doesn't seem to work for later JQuery

### ISSUE THREAD

**Issue by shelterit** [harvesthq/chosen#2333]
Using Jquery 1.11.1, the optgroup doesn't pick up the group label; it's gone

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

Closing until more info is provided.

**Comment by shelterit** [comment]
Keep it closed; there was an incompatibility with another plugin that modified optgroup's. Chosen is innocent, the other was badly written, and the offending plugin has been ejected from the premises! :)

**Comment by tjschuck** [comment]
@shelterit Thanks for following up!  Glad to hear we've been exonerated.
