### ISSUE TITLE
element.chosen is not a function

### ISSUE THREAD

**Issue by deepsaurabh** [harvesthq/chosen#2334]
This error is coming up very seldom, as when page is refreshed several times it is appearing once

**Comment by stof** [comment]
You need to call ``.chosen()`` on a jQuery object, not on a DOM element

**Comment by tjschuck** [comment]
Closing assuming @stof's answer is sufficient.  If it's not, please provide more information about your issue.

What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.
