### ISSUE TITLE
Prototype Chosen: this.form_field.getAttribute is not a function

### ISSUE THREAD

**Issue by brianwalleshauser** [harvesthq/chosen#2338]
Trying to implement Prototype Chosen into Magento.  Getting this error.  Any ideas?  Google has nothing for me.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
