### ISSUE TITLE
how to open dropdown upside

### ISSUE THREAD

**Issue by jignesh87** [harvesthq/chosen#2339]
how to open dropdown upside?

**Comment by kevin-brown** [comment]
This appears  to be a duplicate of https://github.com/harvesthq/chosen/issues/155.

**Comment by d07RiV** [comment]
Not possible. I modified mine to do that but it was quite a lot of work, since the default styles don't support it, either.

**Comment by tjschuck** [comment]
Yep, duplicate of https://github.com/harvesthq/chosen/issues/155.  Leave any feedback you have there.
