### ISSUE TITLE
tab order issue on Firefox

### ISSUE THREAD

**Issue by MilosRasic** [harvesthq/chosen#2341]
Pressing tab while a closed chosen select is in focus will focus the hidden ul.chosen-results associated with it. Giving the ul elements tabIndex="-1" seems to resolve the issue.

**Comment by tjschuck** [comment]
What version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?  What version of Firefox, and what OS and OS version?

Can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?  Or can you confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue?

Closing until more info is provided, then we'll reopen.
