### ISSUE TITLE
JS validity on deselectable select

### ISSUE THREAD

**Issue by felixkk** [harvesthq/chosen#2343]
Hi,

"allow_single_deselect" needs an empty option to work.
This empty option seems to cause some problems with field validity : 
If my select is required and disabled, $('.myField')[0].validity.valid should be true, even if nothing is selected. 
However, when i add the empty option, validity.valid is always false.

Do you have a workaround  ?

Edit : I'm not sure it's chosen fault, I might have a conflicting script. I'll make some tests tomorrow to be sure.

Thanks

**Comment by tjschuck** [comment]
Seems like you're using some sort of form validation plugin.  If they're the one reporting a form is invalid that you think should be valid, you should open an issue with them!  Doesn't seem like a Chosen issue.
