### ISSUE TITLE
Radio/Checkbox Filtering {feature request}

### ISSUE THREAD

**Issue by xziler8** [harvesthq/chosen#2344]
Certain situations dictate a user being prompted to filter an extensive dropdrown based on tags attributed to each option. I think this would be a valuable feature adaptation and I'm not sure I'm able to pull off a fork.
I foresee adding a "data-attribute-tag" to each <option> with a comma separated list of tags by category and the filter header would be generated dynamically by reading these attributes, such as...

```html
<option value="" data-attribute-tag="{'category1':'R':'tag11','tag12','tag13'};{'category2':'C':'tag21','tag22','tag23'};">text</option>
```

or something similar. 

Maybe another identifier to switch between radio buttons [R] within a category (1 choice) to checkboxes \[C] (1+ choices) for the filtering.

![radiofiltercombo](https://cloud.githubusercontent.com/assets/5086045/8113295/066a4662-103b-11e5-87f2-7a06d537dd13.png)

Thanks,
Alan

**Comment by tjschuck** [comment]
I'm not 100% sure I understand your request, but I'm pretty sure you can do everything you're after already using Chosen.

To update the elements in Chosen, simply update the `options` that are in the underlying `select` element however you see fit using JavaScript based off your checkboxes and radio buttons, then call `.trigger('chosen:updated')` to rebuild Chosen and reflect the changes.

See [the docs](http://harvesthq.github.io/chosen/options.html#triggerable-events) for more information on the `chosen:updated` triggerable event.

**Comment by xziler8** [comment]
Not closed... instead of using a search box to filter the select options by
matching text comparison, use checkbox/radio elements displayed in a filter
fieldset, of which are generated by data-attributes on the original options
tags...

seems pretty clear, but I can clarify again if needed.

Alan

On Thu, Jun 11, 2015 at 2:48 PM, T.J. Schuck <notifications@github.com>
wrote:

> I'm not 100% sure I understand your request, but I'm pretty sure you can
> do everything you're after already using Chosen.
>
> To update the elements in Chosen, simply update the options that are in
> the underlying select element however you see fit using JavaScript based
> off your checkboxes and radio buttons, then call
> .trigger('chosen:updated') to rebuild Chosen and reflect the changes.
>
> See the docs
> <http://harvesthq.github.io/chosen/options.html#triggerable-events> for
> more information on the chosen:updated triggerable event.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/harvesthq/chosen/issues/2344#issuecomment-111237137>.
>



-- 
Thanks,

Alan

**Comment by tjschuck** [comment]
Aha, I get what you're saying now.  However, it's unlikely that this feature will be added into Chosen.

You could still achieve this yourself using the method described above, writing your own custom controls to modify the `select`'s `option`s and then calling `chosen:updated`.
