### ISSUE TITLE
Using max-width to be responsive

### ISSUE THREAD

**Issue by nagyt234** [harvesthq/chosen#2345]
I have a feature request. Beside "width" the using of "max-width" as an option could allow us to be more responsive. E.g. the style options `width="100%";max-with="200px";` allow us to have a not very wide input field which will be reduced if the screen is getting narrower.

Currently we can set only `width`, and the chosen select is floating out of the screen if it is to narrow. It looks quite ugly on mobiles.

**Comment by lenamtl** [comment]
+1

**Comment by VamshiKrishnaZL** [comment]
+1

**Comment by pbosko** [comment]
+1

**Comment by mpiontek** [comment]
I have done this manually. On line 626 of chosen.jquery.js - just change to:

`'style': "width: 100%;",`

I know ... you will always have to correct that after an update - but now it is also working in responsive design.

**Comment by koenpunt** [comment]
Applying a max-width to a container element will make Chosen "inherit" this width. So I don't think adding an option for this is be necessary. 
If I'm missing something here, please let me know and I'll be happy to reopen.
