### ISSUE TITLE
Include SCSS in bower or remove sprite and use base64

### ISSUE THREAD

**Issue by nikolowry** [harvesthq/chosen#2347]
Using custom styling and do not want to include the sprite image - but after trying numerous times to get the full repo via bower, I now have to manually copy and paste your sass here to overwrite (which means using the newest chosen after this ships will be impossible).

Reason being:
![screenshot from 2015-06-16 11-25-59](https://cloud.githubusercontent.com/assets/597310/8186839/8d75bb2c-141a-11e5-8d4e-79aabdc1f78b.png)

**Comment by tristanlins** [comment]
I also never the precompiled version, even though I always think it's good that it is included. I always use the SASS/SCSS sources in my build chain.
For the moment I can help me out with the following line:
`"chosen": "https://github.com/harvesthq/chosen.git#v1.4.1"`

**Comment by AlJohri** [comment]
+1 on using base64. seems like there's no downside and just easier usage for everyone else?
+1 also on serving raw scss via bower similar to the `bootstrap-sass` package on bower officially provided by twbs

see https://github.com/harvesthq/chosen/issues/2368#issuecomment-143320940 for details on removing compass as a dependency

**Comment by zyre91** [comment]
+1 for sass files with bower so I can change the image path

**Comment by koenpunt** [comment]
What should a package consist of? Source or compiled files? Or both? Because as far as I know it's not common to put source files in a package.

**Comment by kevin-brown** [comment]
Per bower/bower.json-spec#43 :

> Use source files with module exports and imports over pre-built distribution files.

Select2 (along with a bunch of others, include Bootstrap) made this change a little over a year ago, shortly after the spec was updated and the dust settled. https://github.com/select2/select2/pull/3350

**Comment by tristanlins** [comment]
IMO the scss Files are part of the "executable". The css is more like a "dist" package. While the scss are the "executable" files. The scss files are the "sources" as well.
