### ISSUE TITLE
How to set multiple options as selected from JS?

### ISSUE THREAD

**Issue by sergeda** [harvesthq/chosen#2349]
I tried to do it like this, but only last got selected and added to chosen:

                    $(rslt.countries).each(function(k,v){
                        $('#select-countries option').each(function(key, option){
                            if(v['country_id']==$(option).val())
                            {
                                $(option).prop('selected','selected');
                            }
                            else{
                                $(option).prop('selected','');
                            }
                        })
                    })
                  $('#select-countries').trigger("chosen:updated");

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

More information is probably needed for this issue anyway -- is your underlying `select` a multiple-select?    You should provide more information (preferably linking to a [Fiddle](http://jsfiddle.net) showing a reproduction) when you post to StackOverflow.
