### ISSUE TITLE
Distinct results

### ISSUE THREAD

**Issue by thiagogsr** [harvesthq/chosen#2352]
Hi

I've searched for this feature, but I did not find. I need an option to show distinct results after search. There are options with same text and value and I only need one option when someone search. ps: there are options with same text and value because I am showing a "feature list" first, then I show all items of list after. Is there an option to do it?

Thanks very much.

**Comment by pfiller** [comment]
There's no option to do this in Chosen and I doubt there ever will be. If you need to eliminate duplicates, I'd suggest doing it before you put options into your select.
