### ISSUE TITLE
Deprecated linear-gradient syntax

### ISSUE THREAD

**Issue by altras** [harvesthq/chosen#2363]
Howdy!

In our project we're using https://github.com/jenius/autoprefixer-stylus and chosen.js and from that combo I saw a couple of warnings like:
```
{ type: 'warning',
  text: 'Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".',
  node: 
   { type: 'decl',
     parent: 
      { nodes: [Object],
        type: 'rule',
        parent: [Object],
        source: [Object],
        before: '',
        between: '',
        selector: '.chosen-container-single .chosen-single',
        semicolon: false,
        after: '',
        lastEach: 10,
        indexes: {},
        _autoprefixerDisabled: false,
        _autoprefixerPrefix: false },
     source: { start: [Object], input: [Object], end: [Object] },
     before: '',
     prop: 'background',
     between: ':',
     value: 'linear-gradient(top,#fff 20%,#f6f6f6 50%,#eee 52%,#f4f4f4 100%)',
     _autoprefixerDisabled: false,
     _autoprefixerPrefix: false,
     _autoprefixerValues: { '-webkit-': '-webkit-linear-gradient(top, #fff 20%, #f6f6f6 50%, #eee 52%, #f4f4f4 100%)' } },
  plugin: 'autoprefixer' } 0 [ { type: 'warning',
    text: 'Gradient has outdated direction syntax. New syntax is like "to left" instead of "right".',
    node: 
     { type: 'decl',
       parent: [Object],
       source: [Object],
       before: '',
       prop: 'background',
       between: ':',
       value: 'linear-gradient(top,#fff 20%,#f6f6f6 50%,#eee 52%,#f4f4f4 100%)',
       _autoprefixerDisabled: false,
       _autoprefixerPrefix: false,
       _autoprefixerValues: [Object] },
    plugin: 'autoprefixer' } ]
```

I see in some places (https://github.com/harvesthq/chosen/blob/master/sass/chosen.scss#L278, https://github.com/harvesthq/chosen/blob/master/sass/chosen.scss#L67) that indeed chosenjs is using deprecated linear-gradient syntax `top` instead of `to top` 

Since it's an easy fix  I would like to understand in the first place is it necessary to use the old deprecated syntax :? Seeing this post https://github.com/postcss/autoprefixer/issues/473#issuecomment-119508310 -> `Wrong gradient direction creates real problems.` I'm wondering how we should approach this warning? xD

**Comment by mlettini** [comment]
@altras is correct http://www.w3.org/TR/css3-images/#linear-gradients

Luckily the default direction is `to bottom`, which is exactly the direction our gradients grade (is that even the right verb? I don't know, but I'm using it). Which means all we have to do is remove the word `top` in those 2 places and everything should still work as normal.

**Comment by altras** [comment]
@mlettini \m/
