### ISSUE TITLE
Search doesn't find specific text

### ISSUE THREAD

**Issue by integrationservices** [harvesthq/chosen#2365]
I have a drop down with names of toy licences, one of them is "Star Wars".
When I use the text search it doesn't recognise the item if I type "Star" but does "Wars.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Note that the [Chosen demo page](http://harvesthq.github.io/chosen/) does not show this issue:

![chosen a jquery plugin by harvest to tame unwieldy select boxes 2015-07-13 16-30-18](https://cloud.githubusercontent.com/assets/308724/8660019/7a3f3cc8-297c-11e5-8262-68dbbf98d978.jpg)

![chosen a jquery plugin by harvest to tame unwieldy select boxes 2015-07-13 16-30-48](https://cloud.githubusercontent.com/assets/308724/8660038/88fc9bb6-297c-11e5-81ce-b50d55204552.jpg)

Closing until more info is provided, then we'll reopen.
