### ISSUE TITLE
use chosen with bootstrap pill tabs 

### ISSUE THREAD

**Issue by serezha93** [harvesthq/chosen#2367]
I use bootstrap tabs in whose are some select chosen element. The problem is that the dropdown list displayed is not true and its width minimize to a few pixels. If remove 'display: none'  properties from class 'tab-pane' - dropdown list view is correct. But I need this properties. How to be?

http://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp

**Comment by tjschuck** [comment]
I think this is a duplicate of https://github.com/harvesthq/chosen/issues/2332 -- please try the workaround there.
