### ISSUE TITLE
A way to get user typed text on "chosen:no_results"

### ISSUE THREAD

**Issue by VFiber** [harvesthq/chosen#2370]
If you define a handler for 'chosen:no_results' event its pretty tricky to get the text (what provided the 'no result') from user input.

Could you please add a function (or extra parameter to the callback) to make it possible to get the text from the input field?

**Comment by kylehayes** [comment]
+1

**Comment by adamnbowen** [comment]
Seconded.  It seems that [the current method](https://github.com/harvesthq/chosen/blob/910a12599c10a11b7005feedb1e53e4b4535100e/coffee/chosen.jquery.coffee#L413-L418) doesn't actually pass the terms through, though I was able to grab them in a super awkward way:

```javascript
$('.select--chosen').on('chosen:no_results', function(event, parameters) {
    console.log(parameters.chosen.search_results[0].textContent.match(/No results match "(.+)"/)[1])
  });
```

**Comment by dzeju555** [comment]
Has anyone any idea how to solve that problem?

**Comment by adamnbowen** [comment]
@dzeju555 which problem? The code I posted above makes it possible to grab the text the user typed, it's just a bit awkward.  Otherwise, a pull request needs to make changes to the library to give us an easier way to get at the data.

**Comment by dzeju555** [comment]
I mean, the easier way to do that. I have to do a selectlist which allows user to select an option. But if there is no option user typed, I have to add it to a database dictionary. I though that it will be a good option that Chosen could sent typed text in form with another input fields and in my controller (I use MVC application) I would do the rest. What is important, I want typed text to be still in Chosen field, now it disappears when Chosen is closed and user is not sure what will be sent to the database. I will try to replace placeholder with typed text in jQuery when not found trigger is ran.

**Comment by Modifikator** [comment]
```
var obs = $('select').chosen({width: '100%'}).data('chosen');
            obs.search_field.on('keyup', function(e){
                console.log($(this).val());
            });
```

**Comment by niktrix** [comment]
+1

**Comment by joao-bjsoftware** [comment]
Maybe this can works.
      
`
$('.select-chosen').on('chosen:no_results', function(event, element){
   console.log($(element.chosen.search_results).find('span').text());
});
`

**Comment by koenpunt** [comment]
This is already possible:

```js
$('.chosen-select').on('chosen:no_results', function(event, data){
  console.log(data.chosen.get_search_text());
});
```
