### ISSUE TITLE
Use 'label' attribute for selected option tag in multiple select

### ISSUE THREAD

**Issue by jzeta** [harvesthq/chosen#2377]
I would like to be able to have more control over how each selected option displays in a multiple select field. Right now each option's tag seems to display the `value` attribute, but it would be useful to have it display the `label` instead.

For example, the code here would display "ESOTM" in the option tag when it's selected, rather than "Eternal Sunshine of the Spotless Mind."

```html
<select class="chosen-select" tabindex="2">
     ...
     <option value="Eternal Sunshine of the Spotless Mind" label="ESOTM"></option>
     ...
</select>
```

**Comment by h3xx** [comment]
Why not just use the standard HTML method of designating displayed text:

    <option value="Eternal Sunshine of the Spotless Mind">ESOTM</option>

**Comment by tjschuck** [comment]
@jzeta I'm with @h3xx, at least for the specific example you gave.  Do you have another use case for the `label` option aside from what would be solved using the content of the `option` tag?

Closing for now, but will reopen if you can provide a case where `label` makes sense.

**Comment by kevin-brown** [comment]
I might as well point out that the `label` attribute is part of the HTML specification, though it's not as commonly used (and Select2 has the same issue). Basically `HTMLOptionElement.label` defaults to the content of the `<option>` tag if there is no `label` attribute. But I think this may be inconsistent in older browsers.

http://jsbin.com/lubopeqoho/1/edit?html,js,output

Chrome, IE, and Edge at least default to the `label` when picking what to display in the dropdown.
