### ISSUE TITLE
If option text longer than field itself set text as title for field

### ISSUE THREAD

**Issue by jeserkin** [harvesthq/chosen#2381]
Is this `^` option possible at the moment? I looked at the code and I see that there is some work going on with title, but it is not clear exactly, what is happening.

Is there any way to do that in `1.4.2` version?

**Comment by pfiller** [comment]
There's no current way to do this. Anything that requires measuring the width of options is going to be potentially computationally expensive and add complexity to the code. I'm inclined not to consider things like that and instead prefer to try and keep Chosen focused.
