### ISSUE TITLE
NuGet package broken for Visual Studio 2015

### ISSUE THREAD

**Issue by davidnmbond** [harvesthq/chosen#2385]
When trying to add the NuGet package in VS2015, I get:

PM> install-package Harvest.Chosen
Attempting to gather dependencies information for package 'Harvest.Chosen.1.4.2' with respect to project 'ProjectName.Web', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Harvest.Chosen.1.4.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Harvest.Chosen.1.4.2'
Resolved actions to install package 'Harvest.Chosen.1.4.2'
Adding package 'PrototypeJS.1.7.1' to folder 'F:\Projects\ProjectName\packages'
Added package 'PrototypeJS.1.7.1' to folder 'F:\Projects\ProjectName\packages'
Added package 'PrototypeJS.1.7.1' to 'packages.config'
Successfully installed 'PrototypeJS 1.7.1' to ProjectName.Web
Adding package 'Harvest.Chosen.1.4.2' to folder 'F:\Projects\ProjectName\packages'
Added package 'Harvest.Chosen.1.4.2' to folder 'F:\Projects\ProjectName\packages'
File Conflict
File 'Scripts\chosen.proto.min.js' already exists in project 'ProjectName.Web'. Do you want to overwrite it?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "N"):A
Overwriting existing file 'Scripts\chosen.proto.min.js'..
Overwriting existing file 'Scripts\chosen.proto.js'..
Overwriting existing file 'Scripts\chosen.jquery.min.js'..
Overwriting existing file 'Scripts\chosen.jquery.js'..
Overwriting existing file 'Content\chosen.min.css'..
Overwriting existing file 'Content\chosen.css'..
Install failed. Rolling back...
Package 'Harvest.Chosen 1.4.2' does not exist in project 'ProjectName.Web'
Removed package 'PrototypeJS 1.7.1' from 'packages.config'
Removing package 'Harvest.Chosen 1.4.2' from folder 'F:\Projects\ProjectName\packages'
Removed package 'Harvest.Chosen 1.4.2' from folder 'F:\Projects\ProjectName\packages'
Removing package 'PrototypeJS 1.7.1' from folder 'F:\Projects\ProjectName\packages'
Removed package 'PrototypeJS 1.7.1' from folder 'F:\Projects\ProjectName\packages'
install-package : Could not find file 'C:\Users\david.bond\.nuget\packages\Harvest.Chosen\1.4.2\content\Content\chosen-sprite%402x.png'.
At line:1 char:1
+ install-package Harvest.Chosen
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 

Seems to be related to the at (@) symbol in the filename.  The file chosen-sprite@2x.png IS present in the solution packages folder at the point that it asks to overwrite the chosen.proto.min.js file for example.

**Comment by BaddyBy** [comment]
after getting this error go to Package Manager Console and type > Install-Package Harvest.Chosen -Source C:\Users\[your user name]\.nuget\packages\Harvest.Chosen\1.4.2

**Comment by pfiller** [comment]
We don't have anything to do with a package manager for Visual Studio. You'd need to find the repo that manages that package to get this fixed.
