### ISSUE TITLE
Chosen disappears on postback

### ISSUE THREAD

**Issue by eligoldner** [harvesthq/chosen#2387]
Hello,

I am using Chosen to make my asp.net dropdown lists look presentable. It looks just fine, though upon postback the chosen replacement disappears and I'm left with the old ugly dropdown list.
Notes:
1. I'm using .net 3.5
2. I have the postback triggered as follows: the dropdownlist has a <dropdown name>_selectedIndexChanged event which is being called, and the original dropdownlist has autopostback set to true (it's all sitting in an update panel).
3. I have another element on the page (a label) whose text gets updatd based on the selected index - this part is working properly.

Any help is appreciated,

Eli

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

Additionally, if you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue, you'll be much more likely to get specific, actionable help.
