### ISSUE TITLE
Disabling fieldset doesn’t disable its descendants.

### ISSUE THREAD

**Issue by arkhi** [harvesthq/chosen#2389]
Form controls within a disabled fieldset should be disabled: https://www.w3.org/TR/html5/forms.html#attr-fieldset-disabled

Chosen does not seem to support this case: http://codepen.io/arkhi/full/rVPddZ/

**Comment by tjschuck** [comment]
Thanks for the report, @arkhi -- seems like a legitimate bug.

**Comment by portus84** [comment]
+1000!
