### ISSUE TITLE
Chosen not working in Microsoft Edge (Windows 10)

### ISSUE THREAD

**Issue by F1MLB** [harvesthq/chosen#2390]
Hi,

I'm trying to use a single chosen select in Microsoft Edge (Windows 10) and when you select an option it causes the page to reload.

**Comment by kevin-brown** [comment]
I wasn't able to reproduce this on the [Chosen homepage](http://harvesthq.github.io/chosen/) using Edge on Windows 10.

**Comment by F1MLB** [comment]
Sorry, you're right. I will upgrade to the latest version of Chosen and try again!
