### ISSUE TITLE
Destroy chosen on mobile / tablet

### ISSUE THREAD

**Issue by LitNit** [harvesthq/chosen#2391]
How can i destroy the chosen plugin on mobile / tablet and put a normal select ?

**Comment by besartberisha** [comment]
Use ```$('.chosen').chosen('destroy');```

**Comment by stof** [comment]
or don't apply chosen at all in the first place

**Comment by tjschuck** [comment]
Additionally, Chosen _shouldn't_ apply itself on mobile anyway.  See [the rules here](https://github.com/harvesthq/chosen/blob/dd269d4bef3d2118c00d51feebb370ab82967580/coffee/lib/abstract-chosen.coffee#L284-L291).  If the user agent matches iPod, iPhone, or Android Mobile, Chosen should not display.

Is there another mobile platform that you're seeing Chosen work on?  We should probably blacklist that as well.

Tablets, however, _are_ currently supported.  You can use the methods mentioned above to selectively disable Chosen for whatever other platforms you choose.
