### ISSUE TITLE
errors with custom behaviors

### ISSUE THREAD

**Issue by ChicoMetal** [harvesthq/chosen#2393]
Hi, I'm using this extension and it seems good, but I have some problems,
for example, using the extension of jquery.validate, create a custom validation for select, working perfectly before using the filter, once you deploy the filter, for some reason this validation is skipped and could not make the take, also when cleaning the form with the reset input comvencional forms the select left with the choices and not the first which is what is left by default, as usually happens without the use of filter.

in cunclusion I can say that the use of the filter is intervening catastrophically with the instructions set nececitan to select.

use the version v1.4.2

**Comment by pfiller** [comment]
I believe jQuery validate skips hidden fields and Chosen hides the field. I think we prefer to focus any effort towards fixing this on the more modern HTML5 required element (see #515).

**Comment by ChicoMetal** [comment]
mmm
