### ISSUE TITLE
 Quizás quisiste decir: cambio dinámico dynamic change

### ISSUE THREAD

**Issue by krloscharlis19915991** [harvesthq/chosen#2394]
hello could help me, I can not dynamically change the selected option from javascript, I need select the default option to submit the form or clean it does not work in the conventional way.

thanks

v1.4.2

**Comment by stof** [comment]
if you select an option programmatically, you need to trigger the ``chosen:updated`` event on the select element to let Chosen know that some changes were made and it needs to update its own interface to reflect them.

**Comment by tjschuck** [comment]
@stof's answer is correct, but please note that the GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

**Comment by krloscharlis19915991** [comment]
OK thanks.
PS: if I am using the option chosen:updated but still I have this problem

**Comment by stof** [comment]
@krloscharlis19915991 are you using an uptodate Chosen version, or a very old 0.9.x version ?

**Comment by krloscharlis19915991** [comment]
the v 1.4.2, please be careful, hello, but since most found my mistake, I thought I only had to use the Chosen: updated only when you turn the extension on select, but I found this feature to be added when make every change in the select $ (value) .val ('0') trigger ("Chosen: updated.");
