### ISSUE TITLE
Change  hover color 

### ISSUE THREAD

**Issue by bharos** [harvesthq/chosen#2396]
![image](https://cloud.githubusercontent.com/assets/4263644/9161145/ba658e96-3f5d-11e5-996f-bd21a153b3e8.png)

Please refer the attached image. I need to change this blue color to some other color. This color comes during mouse hover, but none of CSS styles are coming into effect.Can I know how this is possible ?

**Comment by kevin-brown** [comment]
That looks like a standard `<select>` from a browser, not Chosen. Are you sure Chosen is working on your page?

I don't think you can override the styles on a `<select>` that is rendered by the browser, but there is most likely CSS rules for overriding the hover style in Chosen.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

@kevin-brown is right, though -- that screenshot is not of a Chosen select.

**Comment by bharos** [comment]
Okay. thanks.
I am able to do it with chosen.
