### ISSUE TITLE
Ability to prompt before deleting a multiselect option 

### ISSUE THREAD

**Issue by eagle779** [harvesthq/chosen#2398]
Deleting an item from a multiselect is a big deal in my use-case scenario as it deletes a lot of data.   Can we add a hook for my developer .. a BeforeDelete(cancel) event so that we can prompt the user and if need be cancel the delete from proceeding please?

regards

**Comment by eagle779** [comment]
PS I'm prepared to sponsor some beer money for someone if they can do it within 2 weeks, contact me via html2pdfrocket.com and bring your paypal account, cheers.

**Comment by pfiller** [comment]
I'm not sure this is something I see getting added. I appreciate the use case, but it seems like a modification that belongs in a fork. There doesn't seem to be much demand for it.

> I'm prepared to sponsor some beer money

Too bad I noticed this 10 months later. I could have used some beer last August 🍻

**Comment by eagle779** [comment]
so can I pay you to create a custom version for me? I'm happy to share the
code back to the community..
cheers
