### ISSUE TITLE
values not retained in the multiselect field after form is submitted

### ISSUE THREAD

**Issue by sushilsingh94** [harvesthq/chosen#2399]
Hi Team,

I have integrated this plugin in my project and everything works just perfectly. I have one concern here or may be issue.
When i submit the form where I have used multiselect feature, values are not retained in the field when form page loads after submit.
Expected : 
Values should be retained i the field and selected values from multiselect dropdown should be disabled  so that user cannot select again.

Before submit:
![image](https://cloud.githubusercontent.com/assets/8100644/9192429/b1860f14-4028-11e5-955d-a15101783cfd.png)

After Submit:
![image](https://cloud.githubusercontent.com/assets/8100644/9192488/2b867c36-4029-11e5-89cb-673f4c7d2ba5.png)

Thanks

**Comment by tjschuck** [comment]
That screenshot shows a textarea, not a Chosen multiselect.

Regardless, form fields never retain their values across page loads.  It's up to your serverside software to persist those values and repopulate the fields.

**Comment by sushilsingh94** [comment]
yes you are true its textarea in the screenshot. i dint copied new the screenshot where I used chosen multiselect.
But My question is If I save those selected values in some temp variable and repopulate on page reload then how do I make those selected in chosen so that user cannot select those values again and shows disabled. Is there any method where I can pass these values on page reload to make it selected by default.

![image](https://cloud.githubusercontent.com/assets/8100644/9218837/a1c7e40a-40f3-11e5-985c-9d409ed2e2a7.png)

**Comment by tjschuck** [comment]
You just need to operate on the underlying `select` element, re-selecting the values as you choose, and then call `.trigger('chosen:updated')` on your Chosen select to have Chosen reflect the changes.

As for setting the actual values on the `select`, there's an assortment of ways you can do that.  [This StackOverflow answer gives a couple](http://stackoverflow.com/questions/6966260/jquery-multiselect-set-a-value-as-selected-in-the-multiselect-dropdown).

In the future, please note that the GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

**Comment by zhulei007** [comment]
hi
I want to know what is the way to get the value of the multiple which I selected?
I want to get value ,eg:$(".chosen").value(); but i just get the first value of all my selected.

**Comment by tjschuck** [comment]
@zhulei007 `.val()`.  From [the docs](http://api.jquery.com/val/):

> In the case of `select` elements, it returns [...] an array containing the value of each selected option when there is at least one and it is possible to select more because the `multiple` attribute is present.

**Comment by sandeep2244** [comment]
Hi Bro,
Its Very Easyyy
In Jquery use add below lone and your problem will solved in one line 

 console.log($(event.target).val());


It will show you array of multipleSelect
