### ISSUE TITLE
i want to create multiple instances of the chosen multi select plug ins within my page

### ISSUE THREAD

**Issue by vishalnasta** [harvesthq/chosen#2403]
i want to create multiple instances of the chosen multi select plug ins within my page dynamically. i am keeping the class of the select element as chosen-select but when i trigger the chosen updated event after updating the select element it does not work for the subsequent instances that I am adding it works for the first instance only.

**Comment by tjschuck** [comment]
Can you please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

Additionally, what browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Closing until more info is provided, then we'll reopen.

**Comment by vishalnasta** [comment]
I am using chosen-jquery version 1.3.0 and browser is IE 11.0.

**Comment by vishalnasta** [comment]
ok I will download the latest version and see.

**Comment by vishalnasta** [comment]
I downloaded the latest version but the same problem persists. only the first select element when I fire the chosen:updated event works properly not the subsequent ones.

Here is my code. we have to add rows to the table tblCPTCodes dynamically.
<div class="infoDiv" id="divCPTText">
    <img src="Images/cc_x_u41.png" style="cursor: pointer" align="right" id="imgCPT" />
    <div class="sectionHd"><span class="sectionHd" id="Span1" runat="server">CPT</span></div>
    <hr class="sectionHr"></hr>    
    <div class="sectionTxt" style="height:auto; /*overflow-y: auto*/">
        <table id="tblCPTCodes" cellspacing="0" cellpadding="0" style="border: 1px solid rgb(177, 177, 177); font-size: 13px; font-family: Verdana; border-collapse: collapse; width: 100%">
            <tr style="background-color: #d3d3d3;">
                <td width="25%" style="text-align: center; height: 12px;" class="GridBorderRight"><b>CPT Code</b></td>
                <td width="27%" style="text-align: center; height: 12px;" class="GridBorderRight"><b>DX Search</b></td>
                <td width="22%" style="text-align: center; height: 12px;" class="GridBorderRight"><b>DX Association</b></td>
                <td width="6%" style="text-align: center;"><b>Action</b></td>
            </tr>
            <tr style="line-height: 26PX">
                <td style="text-align: center">
                    <div class="ui-widget" style="width: 88%;">
                        <select class="combobox ui-widget-CPTcontent" id="cmbCPT_0">
                            <option value="">Select one...</option>
                            <option value="021869F5-BFF0-4A80-B275-6DB09B906FBF">99307 - NURSING FAC CARE SUBSEQ</option>
                            <option value="F8ABC799-B258-420D-9ACC-1422AEE19459">99308 - NURSING FAC CARE SUBSEQ</option>
                            <option value="3D1DB647-8052-4748-BCFD-DA72299F30A2">99309 - NURSING FAC CARE SUBSEQ</option>
                            <option value="46E0B0F5-C4D7-4DDD-B789-6085B2A469E7">99310 - NURSING FAC CARE SUBSEQ</option>
                        </select>
                    </div>
                    <input type="hidden" class="hidCPTVal" id="idCPTVal_0" value="" />
                </td>
                <td style="text-align: center">
                    <input type="text" id="txtDXSearch" class="inputNotes" style="width:77%;" />
                </td>
                <td style="vertical-align: top;">
                    <div>
                        <select data-placeholder="Choose a DX..." id="chSelect" class="chosen-select" multiple style="width: 100%; vertical-align: top;" tabindex="4">
                        </select>
                    </div>
                </td>
                <td style="text-align: center;">
                    <img src="Images/Remove.png" class="RemoveCPTDX" />
                    <img src="Images/Add.png" class="AddCPTDX" />
                </td>
            </tr>
        </table>
    </div>
</div>
