### ISSUE TITLE
chosen-select

### ISSUE THREAD

**Issue by amarsalunke** [harvesthq/chosen#2406]
Hi, I am wanting to update the the options in one chosen based on the value selected in another select option fill, using AJAX.Please help about code

<select data-placeholder="Choose a Country..." class="chosen-select" id=" drpaccountheadcode" style="width:350px;" tabindex="2">
                                    <option value="">SELECT</option>

                                </select>
<script type="text/javascript">

    $(document).ready(function () {
        $("#drpLedgerType").chosen().change(function () {
            var dID= $(this).val();

            $.getJSON("../DataEntry/LoadPhysiansByDepartment", { deptId: dID },
                   function (data) {
                       var select = $("#drpAccountHeadCode");

                       select.empty();

                       select.append($('<option/>', {
                           value: 0,
                           text: "Select"
                       }));

                       $('#drpAccountHeadCode').addClass('chosen-select');
                      // alert(data);
                       $.each(data, function (index, itemData)
                       {
                           alert(data);
                           select.append($('<option/>', {
                               value: itemData.Value,
                               text: itemData.Text
                           }));
                       });

                   });

        });
    });

    
    </script>

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
