### ISSUE TITLE
user can create new tags

### ISSUE THREAD

**Issue by watoo** [harvesthq/chosen#2408]
I have configured the code as:

```javascript
$('.chosen-select').chosen({
  create_option: true,
  persistent_create_option: true,
  skip_no_results: true
});
```

But its not working. It does not let user create new tags.

**Comment by matrixagent** [comment]
I think that feature is not available in this master version, it's from a fork and there is a pull request: https://github.com/harvesthq/chosen/pull/166

**Comment by tjschuck** [comment]
Correct, none of these are valid Chosen options.  Please see http://harvesthq.github.io/chosen/options.html for documentation of all the existing options.
