### ISSUE TITLE
Search in optgroup not Working Properly

### ISSUE THREAD

**Issue by rollisoj** [harvesthq/chosen#2409]
For example, using your demo page.  If you type Green Bay it finds Green Bay Packers and underlines it correctly, if you type Bay it works until you type <space> Packers.  It does not find Bay Packers in the search list.

**Comment by tjschuck** [comment]
Duplicate of https://github.com/harvesthq/chosen/pull/1483 -- please leave any additional feedback you have there.  Thanks!
