### ISSUE TITLE
Single select: Default selection is not removed after you make a selection

### ISSUE THREAD

**Issue by SlavaEremenko** [harvesthq/chosen#2410]
Only with single selects.

Issue: The default selected option initially has class "result-selected".
After I select a different option for the first time, "result-selected" class is not removed from the default option.

I believe the reason for that is because this.result_single_selected is not set to the default item, and "result-selected" class is not deleted.

**Comment by SlavaEremenko** [comment]
I apologize, didn't realize I'm using version 1.0.... I think that the issue has been fixed

**Comment by tjschuck** [comment]
I think this is fixed in [the latest version](https://github.com/harvesthq/chosen/releases).  Please clarify if it's not.
