### ISSUE TITLE
Can't fix a maximum number of displayed choices.

### ISSUE THREAD

**Issue by medbenji** [harvesthq/chosen#2412]
When selecting multiple items, all the items that have been selected are displayed to the user, which makes the simple select box huge 

http://stackoverflow.com/questions/32221919/chosen-multiple-select-becomes-huge-when-many-all-options-are-selected

**Comment by pfiller** [comment]
We do have `max_selected_options`, but that just limits the number of selections and not the number of options we display. To be honest, I'm not sure how we'd even go about implementing this and think it's unlikely to be something that happens in Chosen.

**Comment by 3zzy** [comment]
It would would be great to have this really.

**Comment by mdprw** [comment]
We also need this feature. Implementation as suggested in https://github.com/harvesthq/chosen/issues/918#issuecomment-51839329 would be great
