### ISSUE TITLE
Dynamically update chosen dropdownlist

### ISSUE THREAD

**Issue by iamstanly** [harvesthq/chosen#2414]
Hi,
I'm using chosen dropdownlist... Its working for single dropdownlist.

If i use dpendent dropdownlist filled by ajax json...

I'm using asp.net mvc..

Kindly help me...

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
