### ISSUE TITLE
Configure twbs/no-carrier to maintain active issues 

### ISSUE THREAD

**Issue by koenpunt** [harvesthq/chosen#2415]
> NO CARRIER is a tool to auto-close old GitHub issues that were abandoned by their reporter, which is to say that we were waiting for a response from the reporter but never got a response in a reasonable amount of time.

**Comment by tjschuck** [comment]
* http://blog.getbootstrap.com/2015/08/04/no-carrier/
* https://github.com/twbs/no-carrier

**Comment by koenpunt** [comment]
Oh yeah, of course, forgot the link

**Comment by tjschuck** [comment]
@koenpunt No worries — that's as much for future-me as anyone :)

**Comment by koenpunt** [comment]
I've took the first steps to make this happen;

Created a user:
https://github.com/chosen-bot

A repo:
https://github.com/chosen-bot/chosen-no-carrier

And a Heroku app: (which obviously doesn't have a web frontend)
https://chosen-no-carrier.herokuapp.com/

**Comment by pfiller** [comment]
@koenpunt this is an interesting idea. Did you delete the chosen-bot user, though?

**Comment by koenpunt** [comment]
Hm, no I did not, but I'll check it in the morning, in about 10 hours or so

**Comment by koenpunt** [comment]
Oh well, Github doesn't like the username I guess. Will fix it later ![image](https://cloud.githubusercontent.com/assets/351038/13161652/6a5f82ce-d69f-11e5-9d75-6e65019221fa.png)

**Comment by koenpunt** [comment]
@pfiller I contacted GitHub support so that will be sorted out shortly (I presume). But you should already have access to the repo, or is that access blocked as well?

**Comment by koenpunt** [comment]
GitHub reinstated the account, so you should be able to check it out. Should I add you to the Heroku application?

**Comment by pfiller** [comment]
I added @chosen-bot as a read-only contributor to this repo. I think that gives it the ability to close issues, but you should confirm. I'm not all that concerned with getting access to the Heroku app. If it starts behaving badly, the worst thing it could do is close a bunch of issues ... not sure that would be such a bad thing.

@tjschuck what do you think?

**Comment by koenpunt** [comment]
Read only doesn't give the ability to close issues..

**Comment by koenpunt** [comment]
> If it starts behaving badly, the worst thing it could do is close a bunch of issues
I don't expect anything like that, because I presume the guys at @twbs know what the're doing :)

**Comment by tjschuck** [comment]
@koenpunt Add me to the Heroku app, please!  tj@[my GitHub username].com

**Comment by koenpunt** [comment]
Done! Do you have permission to enable write permissions for @chosen-bot?

**Comment by koenpunt** [comment]
Because then I can configure the scheduled task :)

**Comment by tjschuck** [comment]
@koenpunt 

1. I'm on the Heroku app now — thanks!
2. @chosen-bot now has Write permissions.

**Comment by koenpunt** [comment]
Should be up-and-running! I've set the number of days to 30, instead of the 14 @twbs uses because we're often not the fastest ourselves either :see_no_evil:

**Comment by koenpunt** [comment]
Oh well, might just set that back to 14, I misunderstood the working of the bot; it doesn't add labels, it only checks for issues which has the specific label for a set number of days, and closes those who have passed that limit.

**Comment by koenpunt** [comment]
Updates of the master branch in the chosen-no-carrier repo will automatically deployed to Heroku
