### ISSUE TITLE
Suggestion: keep class option (inherit_option_classes:true)

### ISSUE THREAD

**Issue by ryosama** [harvesthq/chosen#2416]
I would like the classes I defined in the options stay in the chosen select box.

What about an option like :
`$(".chzn-select").chosen({
    inherit_option_classes:true
});`

Here the modifications in chosen_build function : 
`"class": "search-choice " + $(this.form_field).children('option')[item.array_index].getAttribute('class')`

**Comment by setage** [comment]
Hello, chosen inherits option classes by default. 
Also there is the option for adding this functionality to select tag: ```inherit_select_classes: true```
Think, you already have, what you need.

**Comment by pfiller** [comment]
Yup - @setage is totally right! Thanks!
