### ISSUE TITLE
Chrome doesn't show anything nor is clickable

### ISSUE THREAD

**Issue by notuo** [harvesthq/chosen#2417]
Hi.

First time here. I just tried  chosen and in my tests worked fine, but now checking in another browsers is not.  In Firefox, Explorer, Edge is showing fine but in Opera or Chrome doesn't show anything, nor is clickable but inspecting the source, the list elements are present.

I don't have any idea what is happening. Any advise is welcome. 

Versions: 
Chrome: 44.0.2403.157
Opera: 12:16 (1860)

Firefox 40.0.3

Jquery: 1.6.4
Chosen  1.4.2

This is a screenshot of the field (is a countries list)
![chrome-country](https://cloud.githubusercontent.com/assets/14099382/9644099/07ad5bd6-518b-11e5-920e-feb472d72b5a.jpg)

Thanks for your time and help.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

Chosen definitely works in Chrome, so there's something up with your particular setup.  Linking to a publicly accessible page or a [Fiddle](http://jsfiddle.net) that shows the issue will help you get an answer even faster.
