### ISSUE TITLE
Chosen dosen't work with newest JQuery

### ISSUE THREAD

**Issue by Risord** [harvesthq/chosen#2418]
Edit: Problem solved. I love inability of browsers to throw parse errors.

With 1.6.4 (which is used in demo) it works fine but with 1.11.3 / 2.1.4 result is just:
Uncaught TypeError: selector.chosen is not a function
Using chrome 45.0.2454.85

**Comment by tjschuck** [comment]
@Risord Based on your update, can you confirm that this wasn't a Chosen issue?  Thanks!
