### ISSUE TITLE
Enable/Disable Chosen

### ISSUE THREAD

**Issue by dallf44** [harvesthq/chosen#2419]
I've search in your options and I can not find an enable/disable option for the chosen select, which is the best way to achieve these?

**Comment by tjschuck** [comment]
Chosen respects [the `disabled` attribute on your `select` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).  Set that attribute however you'd like, and then initialize Chosen.  If you're setting it dynamically after initialization, call [`chosen:updated`](http://harvesthq.github.io/chosen/options.html#triggerable-events).
