### ISSUE TITLE
Arrow and Close icon do not appear when using C#

### ISSUE THREAD

**Issue by prmk** [harvesthq/chosen#2420]
I have a dropdown with an empty value at the top. 
```c#
<asp:DropDownList runat="server" CssClass="chosen-single chosen-select-deselect"></asp:DropDownList>
```

and corresponding javascript code 
```javascript    
$(".chosen-select-deselect").chosen({
        allow_single_deselect: true
});
```
However, the arrow up/down icon and the close icon are not appearing. C# language, chosen v1.4.2

![chosendropdown](https://cloud.githubusercontent.com/assets/3215153/9820400/c2bbe6ca-5881-11e5-96f2-41a304c71278.png)

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

This specific issue is very unlikely a bug in Chosen, and is probably an issue either with your own CSS overriding Chosen, or not being able to find the image sprite file that provides these UI elements.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.  You'll also get better and more actionable help if you can provide a link to a publicly accessible page or a [Fiddle](http://jsfiddle.net) that shows the issue.
