### ISSUE TITLE
Option to use textarea instead of normal text input, when multiple selections are made.

### ISSUE THREAD

**Issue by Znow** [harvesthq/chosen#2426]
Option to set the plugin to render a textarea instead of a normal text input, for the larger size and scrolling abilities.

If we are using a normal text input, which is limited in width, the input will not expand horizontally, but vertically

So, using a textarea, with overflow, would do the trick, if alot of selections are made in the dropdown.

Regards

**Comment by pfiller** [comment]
I don't think there's a lot of demand for using a textarea instead of input. The most common use case would seem to be people typing a few characters and moving on. This almost certainly isn't going to happen.
