### ISSUE TITLE
Lost focus after removing a selected option on multiselect mode

### ISSUE THREAD

**Issue by sebastian-ilari** [harvesthq/chosen#2429]
Hello guys, I did a quick search and haven't found this bug raised but apologies in advance if it is already there and I missed it.

**Steps to reproduce**

* Click on the empty box
* Select an item
* Type one character
* Remove the selected item by clicking on the X

Expected result: the user is able to type a new filter. Maybe also the options panel can be collapsed

Actual result: the focus is lost so the user is not able to type a new filter, the only way to use the control again is by clicking somewhere else on the page

This issue can be reproduced on the multiple select version of the demo page https://harvesthq.github.io/chosen/

I have noticed a slight difference between browsers:

On Chrome clicking on the empty input doesn't return the focus back to the control although on IE it does

Thanks!!!

**Comment by tjschuck** [comment]
@sebastian-ilari Seems legit!  Thanks for the report -- I can reproduce.

However, the last bit:

> On Chrome clicking on the empty input doesn't return the focus back to the control

That's actually not true -- you're just clicking too far to the right :)  You just re-found https://github.com/harvesthq/chosen/issues/1729.  If you click a bit further to the left, it will re-focus as expected.

**Comment by sebastian-ilari** [comment]
Thanks for the prompt response TJ and you are right about the re-found :)
