### ISSUE TITLE
chosen search are not working in mobile

### ISSUE THREAD

**Issue by anandp910** [harvesthq/chosen#2432]
I have tried your code its working properly but in mobile search are not work
please help

**Comment by tjschuck** [comment]
Chosen is disabled on mobile.  Here's the regex that disables Chosen on mobile devices: https://github.com/harvesthq/chosen/blob/dd269d4bef3d2118c00d51feebb370ab82967580/coffee/lib/abstract-chosen.coffee#L284-L291

This is in the Chosen FAQs in the docs: http://harvesthq.github.io/chosen/#faqs -- see the third bullet point, as well as the link to more info about why.
