### ISSUE TITLE
Chosen Dropdown same width as longest option

### ISSUE THREAD

**Issue by mav2287** [harvesthq/chosen#2433]
I am working with a responsive theme and we have a lot of chosen selects that need to size themselves. The issue I am having though is when that happens it will get sized based on the selected option not the options in the drop down. What I would like to happen is to have the chosen box size itself based on the longest option. This way the width is always the width of the longest option on 1 line rather than breaking it apart.  This would also mean the size of the chosen wouldn't change each time you selected a different length option. How would I go about doing this?

**Comment by pfiller** [comment]
Chosen's sizing is entirely based on how wide the `select` is when Chosen is instantiated. You can manually specify a width by passing the `width` option, but that's not always a great solution.

Ultimately, a solution as described in #406 is the only thing that would solve this. I'm going to close in favor of that issue.
