### ISSUE TITLE
Improve accented character handling

### ISSUE THREAD

**Issue by chrismilway** [harvesthq/chosen#2434]
Currently if you have a list of values which include accented characters, finding values with those accented characters is hard, especially for English language users who don't frequently use accents. In my case that's a list of world countries – it's hard to find Côte d'Ivoire because it's not returned with a search of 'Co'.

**Comment by tjschuck** [comment]
Duplicate of https://github.com/harvesthq/chosen/issues/536 -- please leave any feedback you have there.  Thanks!

**Comment by chrismilway** [comment]
Oops, obviously didn't look hard enough.

**Comment by tjschuck** [comment]
@chrismilway No worries! Thanks for reporting it.
