### ISSUE TITLE
Chosen is enabled on Blackberry browser but dropdowns are not usable

### ISSUE THREAD

**Issue by tremby** [harvesthq/chosen#2439]
On the Blackberry Z10 device I'm testing with, Chosen is enabled. It looks like the [code only checks for Iphone etc al and Android](https://github.com/harvesthq/chosen/blob/4b03346635d59ca6028ca267590b84354b8eead4/coffee/lib/abstract-chosen.coffee#L284). But the dropdown won't scroll on touch events and so Chosen is somewhat unusable.

Is the lack of a test for Blackberry intentional, or could it be added?

This device identifies itself as `Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.2.1.3247 Mobile Safari/537.35+`.

**Comment by tjschuck** [comment]
@tremby Blocking Blackberry is probably a good idea.  Submit a PR if you're able!

**Comment by tremby** [comment]
Well there are similar things in #1848 and #1850 which haven't been merged. I'd probably just do `/Mobi/.test(navigator.userAgent)` as [suggested by MDN](https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent#Mobile.2C_Tablet_or_Desktop). I'll submit a PR for that if it would be an acceptable solution? According to MDN you then wouldn't need the iPhone/iPod/Android tests, and you probably wouldn't need the mobile clause of the IE test either.

**Comment by tjschuck** [comment]
`Mobi` is no good because that includes tablets, particularly iPads -- see https://github.com/harvesthq/chosen/pull/1850 that you linked above for that.

https://github.com/harvesthq/chosen/issues/1848 also looks good (and similar to this), but that was also just an issue, not a PR, so couldn't be merged :)

**Comment by tremby** [comment]
Ah, the meaning of the comment where that was mentioned wasn't clear to me. Noted. But as I've just posted in #1850 I'm not going to just copy and paste someone else's code and commit it with my own name on it, so I'll wait for its author to respond. Closing this in favour of that.
