### ISSUE TITLE
Chosen select drop down get too long when all the options are removed

### ISSUE THREAD

**Issue by kanup** [harvesthq/chosen#2445]
In IE (I've only tried IE 11), for a chosen select with lots of options, if the drop down is clicked once and then the items are cleared from the list, the updated empty drop-down becomes massively long.

http://jsfiddle.net/3op4gmmh/8/

This is only seen when one of the divs where select element is nested has width specified specified in non-percentage value: 

    .outerdiv {
        width: 25em;
    }
or

    .outerdiv {
        width: 250px;
    }

However, if I change width of all the divs, where select is nested, to a percentage value, the issue is not seen.

    .outerdiv {
        width: 90%;
    }

The problem is my select is actually in a bootstrap's modal where I don't have control on the widths of the parent elements.

**Comment by chameeya** [comment]
I am having this identical issue. however, I am not using Bootstrap. So it may not be Bootstrap related.

I've not tried your edit to resolve this. It does only appear to happen in IE11. Doesn't seem to happen Chrome.

This may explain why the vertical and horizontal scrollbars seem to appear and disappear at random whether the list is empty or not

**Comment by pfiller** [comment]
Potentially related to #2402?
