### ISSUE TITLE
Bower configuration is not following spec

### ISSUE THREAD

**Issue by koenpunt** [harvesthq/chosen#2448]
Some things I noted:

- `"main"` includes images, which it should not.

  > Do not include assets files like images, fonts, audio, or video

- `"version"` is deprecated

  > Use git or svn tags instead. This field is ignored by Bower.

https://github.com/bower/spec/blob/master/json.md

**Comment by rohan-deshpande** [comment]
Yeah and why does the bower install only include minified css and javascript? It should include the whole repo

**Comment by sebastianzillessen** [comment]
Yes, this is a real blocking issue! I would like to import it via http://rails-assets.com, but as you are not following the bower specs your project is messed up!
Please include the bower.json in this repository as well!

**Comment by valdelama** [comment]
Please give us the uncompressed versions of the files via bower!

**Comment by rohan-deshpande** [comment]
Yeah it sucks just use select2, that's what I did.

**Comment by koenpunt** [comment]
@rohan-deshpande Chosen is open source, if you have a fix, you can always open a pull request. Because just shouting something sucks, (generally) doesn't do anything.

**Comment by rohan-deshpande** [comment]
I don't think I shouted anything. Just gave people an alternative to a different lib which configured its bower install correctly.

**Comment by rpalacio86** [comment]
Main section references "chosen.css" which is not provided via bower installation.
