### ISSUE TITLE
Inconsistency in tagging

### ISSUE THREAD

**Issue by koenpunt** [harvesthq/chosen#2450]
Mostly there is a `v` prefix, sometimes there's not, sometimes both.

![image](https://cloud.githubusercontent.com/assets/351038/10417809/ef876a38-7048-11e5-9ffc-d6531e53bd5c.png)

The `bower-chosen` releases [always gets tagged with a `v` prefix](https://github.com/harvesthq/chosen/blob/master/bower-publish.sh#L24), which seems the most sensible to me.

I guess it's not intentional?

**Comment by tjschuck** [comment]
Man, we are super inconsistent on this :sob:

There are also [these lines in the Gruntfile](https://github.com/harvesthq/chosen/blob/6e01e4e105c13902b96e49ce8d036d584204ccf1/Gruntfile.coffee#L6-L7) which say "prefix with `v`!", but it doesn't actually seem to do the git-tagging...

**Comment by pfiller** [comment]
Going forward, I'll make sure there's a leading v. I don't think it's a good idea to go back and change the past tags, though. Do you guys?

**Comment by koenpunt** [comment]
I guess not, although it would make live easier, in terms of sorting..

**Comment by pfiller** [comment]
As I show in #2527, sorting is pretty straightforward even with the improperly named tags in there. I'd rather they had been consistent the entire time, but I can't turn time back and changing them seems to be a real bad idea based on the reading I've been doing.

If you guys find a process that allows us to change the release without doing anything gross, I'm totally on board. Until then, I'm just gonna shrug this off.

Thanks, @koenpunt!

**Comment by koenpunt** [comment]
We could a v-prefixed tag for the tags that are missing, and leave those without a prefix around as well. Although this could be confusing..
