### ISSUE TITLE
Cannot read text from multiselect

### ISSUE THREAD

**Issue by Ra1ningSn0w** [harvesthq/chosen#2453]
When using Chosen with a html <select multi> it is not possible to retrieve the text typed in. Getting a chosen value is possible, typed in text not chosen is not. I Need the typed in value for use with AJAX dynamic option generation.

**Comment by pfiller** [comment]
Are you asking for a way to get the value of the search text field in Chosen? You can just apply a listener to the form field (there's only one input in any given Chosen) and listen there. There isn't a way to do this automatically through Chosen.
