### ISSUE TITLE
Not compatible with jQuery 3.0.0 alpha

### ISSUE THREAD

**Issue by thomasdavis** [harvesthq/chosen#2457]
Examples on homepage don't work correctly when using jQuery 3.0.0. The search box always scrolls to the bottom.

**Comment by pau1phi11ips** [comment]
I'm using jQuery 2.2.0 and have the same issue.

**Comment by koenpunt** [comment]
2.2.0 has a bug with scrolling if I recall. Try 2.2.1.

And for v3, this might be a reintroduction of the same bug, but Chosen isn't said to be compatible with v3 yet

**Comment by stof** [comment]
> And for v3, this might be a reintroduction of the same bug, but Chosen isn't said to be compatible with v3 yet

This might simply be that they haven't released a new alpha version of 3.0 when releasing 2.2.1.
A way to test it would be to try with jquery master branch rather than the existing alpha release.

**Comment by pau1phi11ips** [comment]
@koenpunt Thanks! I've changed to 2.2.3 and that has indeed sorted it out!

**Comment by pfiller** [comment]
I'm going to close this for now. Fixing issues for an alpha is not going to happen here. More likely, the problem is in jQuery and should be reported/fixed there.
