### ISSUE TITLE
dynamically add or remove options to a <select> after running .chosen()

### ISSUE THREAD

**Issue by MareoRaft** [harvesthq/chosen#2458]
Hey guys,

I am building a very dynamic website.  One thing I will need to do is add or remove options when things change.  After creating a chosen() multiselect, I can use

    $('.chosen').append('<option value="new" selected>NEW</option>')

To add a new option to the HTML.  But unfortunately this doesn't add the option to the chosen multiselect.  I assume chosen reads the HTML when initializing and then ignores it afterwards.

Is there some sort of chosen.update() or dynamic way of updating the multiselect?

-Mareo

**Comment by tjschuck** [comment]
See [the documentation](http://harvesthq.github.io/chosen/options.html#triggerable-events) -- you just need to do `$('.chosen').trigger('chosen:updated');`

**Comment by mabdullah4014** [comment]
I couldnt resolve this issue with $('.chosen').trigger('chosen:updated'); help me please.

**Comment by tjschuck** [comment]
@mabdullah4014 The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.  `'chosen:updated'` definitely works (or else we'd have a lot more issues), so this isn't a bug in Chosen.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

**Comment by eyre** [comment]
I resolve this with below:

> window.setInterval(function() {
>      $('.chosen').trigger('chosen:updated');
> }, 1000);
