### ISSUE TITLE
The chosen-results is not updated with the new values even when the select it self is 

### ISSUE THREAD

**Issue by CLS-CLS** [harvesthq/chosen#2459]
This demo demonstates a possible bug in Chosen Plugin when used with angular.
The first select contains a list of departments
The second select contains the list of employees filtered by the selected 
department. It is also appled the Chosen plugin
The third select is the exact same as the 2nd without the chosen plugin

1. Select a department
2. click on the second and third select fields to check if the employees are
   filtered correctly. 

While the 3rd select has the employees properly displayed, the 2nd has not 
updated the employees. Moreover if you check the source code of the page 
you will see that the 2nd select HAS PROPERLY updated the employess in its 
options but the chosen has not updated the employees in its own divs

the workaround is to use a timout function as following to trigger a 
chosen:update event after the angular has finished the digest phase

setTimeout(function(){
  var select = $("select.alt);
  select.trigger("chosen:updated");
}, 100);

TEST CASE
URL:  http://plnkr.co/edit/U4p884lr4o91m9Kx96Gl?p=preview

**Comment by stof** [comment]
Well, if you change the content of the select, you need to trigger ``chosen:updated`` to tell chosen that you made changes and it should rebuild itself to account for them.
And you of course need to trigger it *after* the changes are done.

**Comment by tjschuck** [comment]
Yeah, I'm with @stof -- it seems like this is behaving as expected.  If you update the underlying `select`, you need to trigger `chosen:updated`.

Let us know if we're misunderstanding your issue.
