### ISSUE TITLE
Chosen for disabling select observes events

### ISSUE THREAD

**Issue by Qwertovsky** [harvesthq/chosen#2460]
1. Open in Chrome Browser (http://codepen.io/Qwertovsky/full/pjWOpp/)
2. Right mouse click on chosen
3. Left mouse click on chosen
4. Press [Ctrl+V]
5. Chosen dropdown appears.

**Comment by tjschuck** [comment]
I cannot reproduce.

What Chrome version, OS, and OS version are you using?

Closing until more info is provided, then we'll reopen.

**Comment by Qwertovsky** [comment]
Windows 7  6.1.7601 x64
Chrome 45.0.2454.101 m
Chrome 46.0.2490.71 m

**Comment by tjschuck** [comment]
Okay -- I don't have access to a Windows computer, but I'm reopening based on your report.

**Comment by koenpunt** [comment]
Just confirmed this is happening
