### ISSUE TITLE
Destroy Method should not remove select input listeners...

### ISSUE THREAD

**Issue by KaipiYann** [harvesthq/chosen#2461]
Hi,

I found an issue with the Prototype version of Chosen. When you destroy a chosen instance the destroy method call on Line 711: 

this.form_field.stopObserving(); 

But this method removes all the listener of the form_field...It would be a lot better to just remove the chosen listener like this :

this.form_field.stopObserving("chosen:updated");
this.form_field.stopObserving("chosen:activate");
this.form_field.stopObserving("chosen:open");
this.form_field.stopObserving("chosen:close");

Because in my case I wanted to destroy then rebuild a chosen select because the select was not visible and the chosen one take a 0 width...but when doing so I lost the original listeners of my select field.

Thks

**Comment by stof** [comment]
this method is meant to remove the listeners registered by chosen, and there are many more than the 4 you list here.

**Comment by KaipiYann** [comment]
@stof I don't think there are more observer on the form_field. 
But even if I forgot one I think you understand my point : If a listener has been added outside of Chosen I don't think it should be remove by Chosen without notice...
