### ISSUE TITLE
Problem with selected and long lists

### ISSUE THREAD

**Issue by asantos** [harvesthq/chosen#2462]
Chosen automatically highlights selected options and removes disabled options. That works. But, if the list is too long and the selected item is at the bottom, the user still has to scroll down until the highlighted item is displayed.

**Comment by dim1triy** [comment]
https://github.com/harvesthq/chosen/issues/2585

**Comment by koenpunt** [comment]
So you're suggesting that for single select, we should scroll to the selected option, if any? Sounds sensible, I'd welcome a PR

**Comment by pfiller** [comment]
That _is_ the current behavior of Chosen. If you open a single select with a selected value, the value is highlighted and moved to fit in the viewport.

Here's a fiddle showing Zambia selected and visible upon open:
https://jsfiddle.net/f13mn1rh/
