### ISSUE TITLE
Keyboard Only Tab Issue - FF Only, Long Lists Only

### ISSUE THREAD

**Issue by wcndave** [harvesthq/chosen#2469]
http://jsfiddle.net/uxh723ch/

If you use chosen on a multiple select field, which has more than 10 options (and causes the list to have a scrollbar), Firefox requires two tabs to move to the next element.

On the first tab, there is no on screen focus, and therefore keyboard only users are in what's called a "keyboard trap".  They don't know where they are.

This only happens on FF, and it only happens when the options are long enough to create a scrolling list.

See the fiddle link for an example.

Now, I can get this to work if I add tabindex to all elements, however consider a large dynamic web site, with lots of menu and navigation links, and things like "sign in" and "New message", it's just not practical to apply tab index to every possible link / element in the page.

The natural DOM layout should support correct tab order.

Hope someone can help, as I require a high level of accessibility.

Thanks!

**Comment by tjschuck** [comment]
What version of Firefox?  And what OS and OS version are you using?

Can you confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) also shows the issue?

Thanks!

**Comment by wcndave** [comment]
Using version 41.0.2 on windows 7 64 bit.

It does not occur on the chosen demo, because there is a "hard coded" tabindex value on each field.

If I copy your page, remove all tab index attributes, then the issue does indeed occur.

Let me know if you need anything else, we have found a few other accessibility issues when a professional third party reviewed it, and I note some accessibility comments / questions going back a few years now, would it be better to try and deal with them all in one go?

As a power user who uses keyboard mostly, I do find that accessibility is just a good thing for all users.  mostly.

Thanks for quick response.  Dave

**Comment by tjschuck** [comment]
Thanks for the follow-up!

> Let me know if you need anything else, we have found a few other accessibility issues when a professional third party reviewed it, and I note some accessibility comments / questions going back a few years now, would it be better to try and deal with them all in one go?

Smaller, more focused PRs are definitely more likely to get reviewed and merged, for better or worse.

**Comment by wcndave** [comment]
Any thoughts on this at all? I'd like to know if I need to develop a jQuery process to programatically add tabindex to all items on a page.

Thanks, Dave

**Comment by mgifford** [comment]
I just tested this in FF 84.0.1 (64-bit) and didn't find any issues. I suspect that this issue can be closed as it's pretty old and all the code has changed a lot.

**Comment by tjschuck** [comment]
@mgifford Thanks for following up!  I'm all for stale issue cleanup.  We'll reopen if necessary.
