### ISSUE TITLE
jQuery Chosen on WordPress when add new widget to sidebar

### ISSUE THREAD

**Issue by skylarkcob** [harvesthq/chosen#2470]
I'm using jQuery Chosen for my WordPress widget. Everything is working correctly, but when I drag and drop new widget to sidebar on dashboard, the function not working.

I've tried this:
```
$('div.widgets-sortables').bind('sortreceive', function() {
	$(this).find('.chosen-select').chosen();
});
```
And it just duplicate the input field, and event doesen't work.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.
