### ISSUE TITLE
trigger("chosen:open") and trigger("chosen:activate") on page load

### ISSUE THREAD

**Issue by MK-Chris** [harvesthq/chosen#2471]
Hello

I'm using the jQuery version of this and am trying to either open or activate the select list when the page has loaded, but it seems that putting either of these in the following statement doesn't do anything:

```javascript
$(document).ready(function(){
  $("#player_select1").trigger("chosen:open");
});
```

I know the code around the trigger statement is working, because I can output `console.log`s, but this neither performs the action, nor generates an error.  The same thing happens in both Chrome 46 and Firefox Developer Edition 44 (both Windows 7).  I know the trigger statements work in general because I can use them in response to an event, just not on page load.

Is there any way around this please, or am I doing something completely stupid - as a point of interest, the trigger statement definitely comes after the actual `chosen()` command (first thing I checked!)  I have also tried generic `$("select").chosen()` command and more specific calls on each select: `$("#player_select1").chosen()`.

Many thanks in advance.

Chris

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

When posting, if you include a link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows your issue, you'll also be much more likely to get assistance there.

**Comment by MK-Chris** [comment]
Got it - apologies.

**Comment by tjschuck** [comment]
@MK-Chris No worries -- just trying to help you get an answer faster!
