### ISSUE TITLE
Is chosen.jquery.js missing?

### ISSUE THREAD

**Issue by Dulcin** [harvesthq/chosen#2478]
I'm probably overlooking it, but I just downloaded the zip and I can't find the actual chosen.jquery.js file?

I downloaded it from your example page instead, but I can't find it in the zip?

**Comment by stof** [comment]
have you downloaded the zip generated by github with the content of the repo, or the ``chosen_*.zip`` archive containing the build files attached to each release in https://github.com/harvesthq/chosen/releases ?

The github archives indeed does not contain generated files (github does not generate them)

**Comment by tjschuck** [comment]
Closing per @stof's information above -- the ZIP from the releases page should include all the generated files.

**Comment by Dulcin** [comment]
Sorry for my late reply, but that was indeed my mistake!
