### ISSUE TITLE
Using jQuery validation error messages do not dissappear until re-submitted

### ISSUE THREAD

**Issue by storres56** [harvesthq/chosen#2485]
Typically when using jquery validation, an error will dissapear as soon as you have corrected it.  When using Chosen, I get the error displayed, but it will remain after correcting it until I actually submit.  I want it to react the same as other fields so usability is consistent.  Is there a way to do this?

**Comment by pfiller** [comment]
I believe jQuery validate uses blur to decide when to reevaluate a field. Chosen only triggers the change event on the original field so you'd need to tell the validation library to listen for that.

See #515 for more discussion about validation (especially with the HTML5 required element).
