### ISSUE TITLE
Select dropdown not showing properly in Bootstrap Modal

### ISSUE THREAD

**Issue by saranggupta94** [harvesthq/chosen#2486]
<img width="293" alt="screen shot 2015-12-08 at 2 38 05 am" src="https://cloud.githubusercontent.com/assets/16077266/11636197/ca4c45e2-9d55-11e5-9978-d8c7b67d785a.png">

The select element does not display properly inside the bootstrap modal. The width is not adjusted properly although displays alright outside the modal.

**Comment by drmuey** [comment]
+1 same here :( bootstrap 3 specifically

**Comment by koenpunt** [comment]
Please use the search before posting an issue. This is because the modal initially is a hidden element. Adding a width property to the initialization options of Chosen should solve this.

**Comment by drmuey** [comment]
Weird, I did search first which is how I found this issue :) (Also, I just +1d it; I didn't create it). Thanks for the tip, FTR after I +1d this issue I tried doing various width things but it had no effect.

**Comment by koenpunt** [comment]
@drmuey my comment was not directed towards you ;) But you didn't solve the issue yet?
