### ISSUE TITLE
Feature Request: adjust the height of the box.

### ISSUE THREAD

**Issue by antonydandrea** [harvesthq/chosen#2487]
Expose the option to adjust the height of the box. Sometimes issues such as this one (http://stackoverflow.com/questions/21111652/how-do-you-set-the-max-height-of-an-expanded-select-drop-down-box) means that we have to add CSS or in my case change the CSS of the project. Would be nice to have an exposed option or if it respected the selects 'size' attribute.

**Comment by koenpunt** [comment]
There is the `max_shown_results` option, which you can use to limit the number of results being shown (obviously). 

If that's not a solution, updating the max height of `.chosen-results` is the fix:
```css
.chosen-container .chosen-results {
    max-height: 100px;
}
```
Just make sure that bit of css in loaded after the Chosen css file is loaded and all should be good.
