### ISSUE TITLE
return ID and Add label to options

### ISSUE THREAD

**Issue by elibushehri** [harvesthq/chosen#2490]
hi
1.I want to set an id to each <option id="1"> and then access to every id that I choose. please guide me how to do that?
2. I want to add the label attribute in <optgroup label="op"> inside the name of each <option>, so when I choose one option like <option>op1</option> from an optgroup I want to show that in textbox like " op: op1". I mean showing label of optgroup at first and then name of the option that is been selected.
thanks

**Comment by koenpunt** [comment]
2 is easy; just set `include_group_label_in_selected` to `true`:

```js
$('.chosen-select').chosen({include_group_label_in_selected: true});
```

**Comment by koenpunt** [comment]
Point 1 is not really clear to me what you want to achieve?
