### ISSUE TITLE
No POST field in POST requests when I delete all items from Chosen Box

### ISSUE THREAD

**Issue by dzarezenko** [harvesthq/chosen#2492]
Hi, 
I have a filter form on my page and I use multiple chosen element, so I receive array of IDs in the POST field after form submit. When I remove all items from chosen box (by click on cross) and submit my form I didn't receive empty array as field value in the POST data. So this field is simply not in the POST, but looks like must be an empty array.

How can I fix this, maybe I missed something.
Thanks!

**Comment by koenpunt** [comment]
This is standard html select behavior, the same will happen without Chosen applied.
(Chosen only instructs a standard select)
