### ISSUE TITLE
Middle part of word

### ISSUE THREAD

**Issue by Pumych** [harvesthq/chosen#2494]
Can we get the word by part of it like in this example: if I typing "ppl" it would find "Apple" word too, like as if I type "App"?

**Comment by MrGeneric** [comment]
https://harvesthq.github.io/chosen/options.html

Check out the options page. The search_contains option is the one you're looking for. Set that to true.

**Comment by tjschuck** [comment]
Closing per @MrGeneric's answer — thanks, @MrGeneric!
