### ISSUE TITLE
Css display optgroup name - whole line

### ISSUE THREAD

**Issue by slk500** [harvesthq/chosen#2496]
![chosen css](https://cloud.githubusercontent.com/assets/13615024/12107927/89460b50-b371-11e5-932b-ba1fc910569a.jpg)

How I can change css to display optgroup name (red color on my photo) filling whole line?  On my example the first optgroup is OK - becasue is long. But second one is short and its comes with another word "abordaz" :/

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

This is something you should be able to do independent of Chosen via your own CSS. Please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.  You'll also be more likely to get a speedy answer if you can link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue.
