### ISSUE TITLE
Chosen does not work when copied into another dom

### ISSUE THREAD

**Issue by slim12kg** [harvesthq/chosen#2497]
I have a situation where i need to copy the dom element  that contains chosen select box, but somehow the  chosen does have effect on the copied element when i paste it into another div but its totally not interactive. I cant change the value of any of the select box but they look just like the copied selectbox instantiated with chosen but i can't seem to change the value or remove the selected ones.

i have tried calling the chosen:updated on it like so : $('.chosentable').trigger('chosen:updated');
but noting happen and when i try to re instantiate like so  $('.chosentable').chosen() nothing happens.

Any help with it

**Comment by stof** [comment]
the issue is that copying a DOM node does not copy listeners on the other DOM element (but jQuery will copy the data telling Chosen that it was already applied).

**Comment by slim12kg** [comment]
so how do i solve that

**Comment by slim12kg** [comment]
For anybody with similar problem.I simply solved this by looping through my cloned dom node and getting all my selecet like such : 
$('div#editstash67').find('select').each(function(){
	$(this).css('display','block');
	$(this).appendTo('#empty');
});

And appending into another created div then i re instantiate chosen on those select boxes.It might seems too much trouble but its worth it
