### ISSUE TITLE
chosen dropdown update

### ISSUE THREAD

**Issue by fadelle** [harvesthq/chosen#2501]
please help,
i know that chosen consists of an input search (class="default") and ul dropdown(class="chosen-drop") 
"chosen:updated" update the whole chosen-select (input search and dropdown)
So the question is: what if i want to update only the ul dropdownlist without updating the input search(because "chosen:updated"  is deleting my input search text while updating)

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

For this specific case, you'll probably just have to save the current input value, update Chosen, and re-apply the saved value back to the input.
