### ISSUE TITLE
Enable mobile devices as an "experimental", not supported option

### ISSUE THREAD

**Issue by Senthe** [harvesthq/chosen#2503]
As far as I understand there are some problems regarding Chosen search and layout breaking on mobile devices. However I don't understand why still enabling it is not even an option for a developer who wills to use it even if it's not fully supported.

For example, I've been using Chosen for simple dropdowns like this:
![zrzut ekranu 2016-01-14 o 13 42 29](https://cloud.githubusercontent.com/assets/14551750/12324728/fee9bd70-bac4-11e5-94a9-d4f747bdc27c.png)

I don't need chosen to have complicated features, I need it only to actually initialize and work, I can style and control it on my own. It's only divs and links, I don't think there's anything that will break my design. Why can't I use the plugin at all?

I use it as Rails gem and can't edit the files. I could fork Chosen and make a gem on my own but first please explain why is there no option to use functionable parts of the plugin on mobile? I just don't really get it?

**Comment by pfiller** [comment]
We're not going to add an "experimental" option, but there's an easy enough workaround. In `browser_is_supported`, you can delete any user agents you want Chosen to show up on. Easy!

**Comment by Senthe** [comment]
Well this is disappointing. I guess that you don't expect people to use your plugin as gem or via bower, grunt, npm or any other dependency management tool.
