### ISSUE TITLE
Chosen not working on Microsoft Edge

### ISSUE THREAD

**Issue by paztis** [harvesthq/chosen#2505]
Hi,

Chosen seems to be not supported in latest Edge version.
On chosen homepage (http://harvesthq.github.io/chosen/), select box are not transformed.
On my code, selectbox are transformed, but cannot be opened.

**Comment by stof** [comment]
I tried the demo page in Edge, and it works properly for me.

do you get any error in the browser console when it does not work ?

**Comment by paztis** [comment]
Nothing at all...
Le 15 janv. 2016 19:30, "Christophe Coevoet" <notifications@github.com> a
écrit :

**Comment by paztis** [comment]
Sorry, it's a proxy problem on my side for jquery.
No bug at all ^^

**Comment by tjschuck** [comment]
@paztis Thank you for following up!
