### ISSUE TITLE
chosen.css do not exist in the repo

### ISSUE THREAD

**Issue by GesJeremie** [harvesthq/chosen#2508]
Bower.json
```json
  "main": [
    "chosen.jquery.min.js",
    "chosen.css",
    "chosen-sprite@2x.png",
    "chosen-sprite.png"
  ],
```

chosen.css isn't present in the repo.

**Comment by stof** [comment]
Sure it does not exist in this repo. This is because Bower does not handle properly the difference between source files and build files.
Bower is reading the package from https://github.com/harvesthq/bower-chosen

**Comment by tjschuck** [comment]
Closing per @stof's answer.  Chosen not including the compiled files is well discussed and intentional.

**Comment by GesJeremie** [comment]
@tjschuck 

Your bower.json: 

```
  "main": [
    "chosen.jquery.min.js",
    "chosen.css",
    "chosen-sprite@2x.png",
    "chosen-sprite.png"
  ],
```

The repo downloaded by bower:

```
.bower.json
bower.json
chosen-sprite.png
chosen-sprite@2x.png
chosen.jquery.min.js
chosen.MIN.css
```

What I'm saying it's only to update your main entry with **chosen.MIN.css** and not **chosen.css**

For people who are reading that thread, if you use Brunch.io, just override your root bower.json and put that: 

```
  "overrides": {
    "chosen": {
      "main": [
        "chosen.jquery.min.js",
        "chosen.min.css",
        "chosen-sprite@2x.png",
        "chosen-sprite.png"
      ]
    }
  }
```

**Comment by tjschuck** [comment]
@GesJeremie Sorry!  You're right.  That's actually a known issue as well, and has been "fixed", however that fix won't take effect until the next release is cut, which hasn't happened yet... 

See https://github.com/harvesthq/chosen/issues/2324 for the original report of the issue, and see https://github.com/harvesthq/chosen/pull/2306 for the fix.

See https://github.com/harvesthq/chosen/pull/2449#discussion-diff-42010359 as well about this issue and how it's "fixed" but not released.  (The lack of a new release is a different issue, but again, one that's known...)

Sorry again for the misunderstanding, and thanks for your report!

**Comment by GesJeremie** [comment]
@tjschuck No problem mate, my bad :)
