### ISSUE TITLE
Option for case-sensitive search

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [harvesthq/chosen#2509]
Request: add a settings option to make case sensitive searches.

Use case: in my web app I have a drop down with a list of letters: a, b, c, ... A, B, C,... that get used a lot by the content editors. I'd like to speed up their workflow so instead of opening the drop down, pressing z then moving the arrow down (to move from z to Z), they can just press shit-z to get to Z directly.

**Comment by tjschuck** [comment]
:+1: Seems legit.
