### ISSUE TITLE
[Edge] Autocomplete is enabled when used in an .aspx form

### ISSUE THREAD

**Issue by guillaumeboudreau** [harvesthq/chosen#2510]
I just wanted to let you know that the autocomplete=off tag is ignored when chosen is used in an aspx page within a 
```html
<form runat="server">
</form>
```
I've searched way too long to find this and I just wanted to let everyone know that this is why it does not work. I understand that it's probably not a resolvable issue but at least now I know where it comes from.

**Comment by tjschuck** [comment]
This sounds like it's probably more of an ASP bug (or an ASP... known issue?).

I'm going to assume that you're right and it can't be resolved by Chosen.  If you figure out a simple way to resolve it that makes sense in Chosen independent of ASP-specific code, please let us know!  You can open a PR and reference this issue.

If you can't fix it in a platform-agnostic way within Chosen itself but figure out some other workaround, feel free to just leave the workaround in this issue for future searchers.

Closing this given the above, but hopefully your report helps some future frantic Googler!

Thanks @guillaumeboudreau !
