### ISSUE TITLE
Select not updated in http success callback

### ISSUE THREAD

**Issue by mobiusinversion** [harvesthq/chosen#2514]
I am populating a select box with angular chosen:

    <select ng-change="checkSelection()" 
        chosen="" 
        class="form-control chosen-select input-md" 
        data-placeholder="Select a Thing" 
        ng-model="theThing" 
        ng-options="thing.name for thing in things"></select>

When I hardcode the list of things in the Controller, this does works, but when I set the things in a success function of an http call (which succeeds) the box is not populated:

     $scope.getThings = function() {
        $http.get('/rest/Things', {}).
            success(function(data, status, headers, config) {
               $scope.things = data;
            }).
            error(function(data, status, headers, config) {
                console.log("Could not get list of things " + data);
            });
    }

Does not work. How can I get the select to update?

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

However, based on "how can I get the select to update?", are you just looking for `.trigger("chosen:updated");`?  [Docs](http://harvesthq.github.io/chosen/#change-update-events).
