### ISSUE TITLE
Have input inherit classes

### ISSUE THREAD

**Issue by jrock2004** [harvesthq/chosen#2517]
So your plugin is really cool. Is there a way that the classes that are added to the select, be put on the input that your library creates? Thanks

**Comment by tjschuck** [comment]
There's an option called `inherit_select_classes`. [Docs](http://harvesthq.github.io/chosen/options.html#options).

**Comment by jrock2004** [comment]
When I tried that, its putting those classes on the div that surrounds the input

**Comment by tjschuck** [comment]
You just need to change your selector then to be for the input itself, like `.my-class input[type="text"]`.

Regardless, the GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.  For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.  Although all of this is pretty standard CSS selector-ing, so maybe just tag it as CSS.  You should also link to a [Fiddle](http://jsfiddle.net) or publicly accessible page — that will help people answer your question more directly.
