### ISSUE TITLE
Unable to validate chosen select

### ISSUE THREAD

**Issue by buddalasunil999** [harvesthq/chosen#2520]
I get the error An invalid form control with name='' is not focusable. always.
I tried the solution present in the below link http://jsfiddle.net/emamut/CBjmj/4/ with no luck. Could you please point me to the right direction. I want to use bootstrap and jquery validation on this control

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

**Comment by buddalasunil999** [comment]
After searching on stack-overflow for many days, I wrote the question here hoping to get answer.

**Comment by buddalasunil999** [comment]
@tjschuck tjschuck
