### ISSUE TITLE
Inconsistent delete behavior

### ISSUE THREAD

**Issue by ramdog** [harvesthq/chosen#2521]
There is inconsistent behavior with respect to deleting a search.  Steps to reproduce:
### Flow A:
1. Search for something (non matched query)
2. Delete to the beginning (command + backspace)
3. Note the message the remains about an unmatched query
### Flow B:
1. Search for something (non matched query) - same as above^^^
2. Select all (command + A)
3. Delete (backspace)
4. Note it clears the search, which is different than the behavior as noted above

I would expect it to always work as Flow B.  Flow A seems like a bug to me.

Screencast taken directly from [demo page](https://harvesthq.github.io/chosen/):
![ulxzkbt7dc](https://cloud.githubusercontent.com/assets/5456178/12799112/fb85b072-ca81-11e5-9dee-5fdada0d8d40.gif)

**Comment by tjschuck** [comment]
Thanks for the detailed report, @ramdog !

However, I can't reproduce :grimacing:  What browser, browser version, OS, and OS version are you using?

**Comment by ramdog** [comment]
@tjschuck Thanks for the quick reply!  Good point, should have noted:

1.  Chrome Version `48.0.2564.97 (64-bit)`
2.  Mac OS X Yosemite Version `10.10.5 (14F1509)

**Comment by tjschuck** [comment]
Hm, on the same version of Chrome, I'm not seeing the issue.  If I press cmd-backspace, as soon as I release command, it clears as I'd expect.

I'm on OS X El Cap, though, so perhaps that's the problem, though I doubt it would be...

**Comment by ramdog** [comment]
Hmm, I just borrowed my cubemate's machine which is on El Cap (not sure on Chrome version) and I saw the same behavior (the buggy behavior).  

Also, when you say you can't reproduce, does that mean you only see the results in Flow A or Flow B?

**Comment by tjschuck** [comment]
Same as your expectations -- Flow B seems correct; Flow A seems like a bug.  But for me, Flow A (cmd-backspace) also clears the search as expected.

**Comment by ramdog** [comment]
Got it, interesting.  One thing I've noticed (without looking at the source yet) is that there seems to be some sort of debounce when updating the  `No results match "blahhhhhhhhhhhhhhh"` _but specifically on delete_.  In other words, if you:

1.  enter a long random (unmatched string), you'll note the "no results match" message, then
2.  hold down delete for a second or two to iteratively delete few characters in a row...

then I don't see the search update from:
 `No results match "blahhhhhhhhhhhhhhh"`

to

 `No results match "blahhh"`

until I let go of delete.  Just a random observation, not sure if that's related to the issue.  In any case, if you'd rather close this issue, that's cool.

**Comment by tjschuck** [comment]
I'll leave it open for now for someone else to hopefully confirm/deny a reproduction on their end as well.  Please submit a PR if you have any ideas on getting the behaviors to match!

**Comment by ramdog** [comment]
Will do, thanks.  Last thing to note for anyone looking into this: it seems I get the expected (Flow B) behavior when I use `option + delete` (word by word delete) vs `command + delete` (delete to beginning of line), on my mac keyboard.

**Comment by koenpunt** [comment]
I can reproduce. Probably the keyup event of the meta key is not handled.

**Comment by IanSimpson** [comment]
I can reproduce. [This Stackoverflow thread](http://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key) has details of the issue. It is expected behaviour, with no known workaround to the root issue.

I've submitted a PR which simply allows the search function to run when Cmd is pressed. This is an effective workaround, and doesn't seem to introduce any issues (other than potentially being less efficient if someone is pushing Cmd/Windows Key).
