### ISSUE TITLE
cannot select new option after removing previous options

### ISSUE THREAD

**Issue by ParagCool** [harvesthq/chosen#2522]
I am using chosen.jquery to convert my select to multiple select. When I remove the current options from my select field and load the new ones, I am not able to select the newly added options.

 This is how I remove old options from select list.

```javascript
 var select = document.getElementById(fieldObj);
	 for (var i=0;i<select.length;i++) {		 
		 select.remove(i); 
		 $('#partnerCasteId').trigger("liszt:updated"); 
     }
```

I just noticed that liszt:updated option is not present in the Chosen.jquery. Do I need to get a different version? Please help

**Comment by tjschuck** [comment]
All of the `liszt` namespaced options are from a _very_ old version of Chosen, so you're either looking at an old version of Chosen or old docs.

You can find the latest release version of Chosen on [the releases page](https://github.com/harvesthq/chosen/releases), and the docs for it are (mostly) on [the main project page](http://harvesthq.github.io/chosen/) (although there's a lot more on the [options](http://harvesthq.github.io/chosen/options.html) page).

Specifically, you're looking for [this section about "Updating Chosen Dynamically"](http://harvesthq.github.io/chosen/#change-update-events) and the trigger `chosen:updated`.

**Comment by ParagCool** [comment]
var select = document.getElementById(fieldObj);
     for (var i=0;i<select.length;i++) {         
         select.remove(i); 
         $('#partnerCasteId').trigger("chosen:updated"); 
     }

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.  If you can post a link to a publicly accessible page or a [Fiddle](http://jsfiddle.net) that shows your issue, you'll also probably have much better luck getting assistance.

**Comment by ParagCool** [comment]
I already posted my issues on stackoverflow using jquery-chosen tag.  But did not get any response. My entire work is pending due to this. I would really appreciate if you can help me where things are wrong in terms of the coding standards. Or if you can share an example of how to remove options from select list.

**Comment by ParagCool** [comment]
I found the issue. I appreciated your help.
