### ISSUE TITLE
allow_single_deselect behavior when options have values

### ISSUE THREAD

**Issue by a-opazo** [harvesthq/chosen#2526]
Consider the following case (html):

```
<select id="my_id" data-placeholder="Select (Optional)...">
     <option value="-1" selected></option>
     <option value="1">Option 1</option>
     <option value="2">Option 2</option>
     <option value="3">Option 3</option>
     <option value="4">Option 4</option>
     <option value="5">Option 5</option>
</select>
```

and the following javascript call:

`$("#my_id").chosen({width:"100%", search_contains: "true", no_results_text: "NOT FOUND", allow_single_deselect: true});`

This will produce a select element, and can be deselectable. Doing a:

`$("#my_id").val();`

When nothing is selected, it returns "-1" which is expected.

The problem arises when one selects an option, and then deletes the option (using the "X" icon)... Doing a:

`$("#my_id").val()`

after deleting the option, to get what option was selected, always returns 1. (And i've expected to return "-1" as specified in the html option)

If i change the first option to:

`<option value=""></option>`

produces the same result.

Bug or feature?... Tested on Firefox 44 and MSIE 11, using chosen 1.4.2 and jquery 1.11.3

Thanks in advance for any reply. (And sorry about my english, not my native language)

**Comment by koenpunt** [comment]
Could you set up your example on http://jsfiddle.net? That way it's easier to review your problem.

**Comment by a-opazo** [comment]
Nevermind... One of the coders did a small change to chosen and told nobody about it. This was the culpirit. Sorry for the noise.

Closing.
