### ISSUE TITLE
how to fire onclick event for chosen jquery select box

### ISSUE THREAD

**Issue by sreedharL** [harvesthq/chosen#2531]
i have a chosen drop down  on my page

i want to fire onclick event on  chosen dropdown to load some data in it. but its not firing

$("select[id^=ddServType_]").chosen().click(function () {
    debugger
    });

**Comment by koenpunt** [comment]
There's a `chosen:showing_dropdown` event, which is being triggered when the select is clicked.

```js
$("select[id^=ddServType_]").chosen().on('chosen:showing_dropdown', function () {
debugger
});
```

> to load some data in it.

Not sure what your want to achieve with loading on demand, but if you update the options of the select, make sure to trigger `chosen:updated` on the select so that Chosen will reflect the changes.

**Comment by koenpunt** [comment]
An alternative is to bind a click event to the `chosen-container` when Chosen is ready, although I do not recommend it;

```js
$("select[id^=ddServType_]").on('chosen:ready', function() {
  $('.chosen-container').bind('click', function() {
    debugger
  });
}).chosen();
