### ISSUE TITLE
Use chosen and tooltipster

### ISSUE THREAD

**Issue by praveenlobo7** [harvesthq/chosen#2535]
We have used Tooltipster for all the validations. Tooltipster validation is not working for Chosen.
How do we use tooltipster with chosen?

Below is the link for tooltipster:
http://iamceege.github.io/tooltipster/

Please find the below screenshot for reference. 

![validator](https://cloud.githubusercontent.com/assets/5987400/13000279/8c637522-d17e-11e5-881c-6676e5bf1645.png)

**Comment by pfiller** [comment]
In your screen grab, it looks like you're not using Chosen or you've modified the CSS pretty heavily. Chosen doesn't do anything funny with positioning on the main select element, so I can't think of any reason it wouldn't work with a tooltip library.

I recommend posting somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen), and provide a link to a publicly accessible page or a [Fiddle](http://jsfiddle.net) so people can reproduce your issue.  You'll be more likely to get a quick answer there from someone who is familiar with Tooltipster.
