### ISSUE TITLE
Update the bower repo to 1.5

### ISSUE THREAD

**Issue by dtsn** [harvesthq/chosen#2538]
Even though you have released a new version 11 days ago the bower version remains at 1.4.1. Could you please update the bower version.

**Comment by tjschuck** [comment]
/cc @pfiller 

The [demo + docs pages](http://harvesthq.github.io/chosen/) are also still running the old version... Isn't updating all of these a part of the build pipeline?

**Comment by dtsn** [comment]
@tjschuck Taking a look at the bower-publish.sh it appears that this wouldn't get built and deployed automatically because the credentials are missing from the script. I guess only people who have the credentials can do the build. 

Why isn't the bower repo push from the github release cycle?

**Comment by tjschuck** [comment]
@dtsn There actually _were_ commits made to https://github.com/harvesthq/bower-chosen (with the automated commit message provided by `bower-publish.sh`) on Feb 5 (the date of the new release), but those commits seem to be missing all of the changes...

Something's messed up.  @pfiller is the master of the releases, though — hopefully he'll be able to clarify and fix the issue.

**Comment by pfiller** [comment]
The bower release should automatically update when we publish a new version, but it's broken. #2527 or something like it will fix it.

I forgot to publish to gh-pages, though. Just did it now!

**Comment by tjschuck** [comment]
#2528 should fix #2527 which should fix this.

**Comment by tjschuck** [comment]
@dtsn This should be fixed by the [latest release](https://github.com/harvesthq/chosen/releases/tag/v1.5.1).

Thanks for the heads up!
