### ISSUE TITLE
Tabbing through form ignores .chosen()-enabled input

### ISSUE THREAD

**Issue by janbaykara** [harvesthq/chosen#2540]
I just can't get the form not to skip past the `.chosen()` input. Is this a bug?

**Comment by tjschuck** [comment]
Tabbing on [the demo page](http://harvesthq.github.io/chosen/) works just fine, so it seems like it's probably an issue with your particular HTML/JS.

I recommend posting somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen), and provide a link to a publicly accessible page or a [Fiddle](http://jsfiddle.net) so people can reproduce your issue.  You'll be more likely to get a quick answer there.
