### ISSUE TITLE
Can I place the chosen items in another "ul" container?

### ISSUE THREAD

**Issue by jacob-xie** [harvesthq/chosen#2542]
Hi~It's an excellent plugin and would you please help me solve my problem? Thank you.
I'm dealing a multiple select and need to place the chosen items in another "ul" list, like:

```
<select class="chosen_select"><option value="1">a</option><option value="2">b</option></select>
<ul id="chosen_list"></ul>
```

Now, when I choose item "a" , it need to be in the ``ul(id="chosen_list")``, How can I deal with it? Thanks a lot.

**Comment by stof** [comment]
Well, I suggest you to use the ``change`` event, exactly like when Chosen is not applied on the ``select``.

**Comment by jacob-xie** [comment]
Thanks, I will try about it. @stof

**Comment by tjschuck** [comment]
Closing per @stof's answer.  This is something that can be handled independent of Chosen.
