### ISSUE TITLE
Change event - $.each function causes error when deselecting last option in list

### ISSUE THREAD

**Issue by kayex** [harvesthq/chosen#2544]
I have a Change event to get a list of the selected IDs in the multi-select. When I add an $.each function, it breaks the Chosen select. I am able to select items to the multi-select, and remove them, but I cannot remove the very last one.  It looks like it gets stuck in the selected box, because the option appears back in the list again.

The error I see in the console log when I click on the last item's "X" is:

**"Uncaught TypeError: Cannot read property 'length' of null"  jquery.js:2**

code:

     $("#location_id").chosen().change(function() {
		var locationIds = $("#location_id").val();
		$.each( locationIds, function( index, locationId ) {
           // Do something
		});
 	});

Using chosen 1.5.1 and jquery 2.1.1

**Comment by koenpunt** [comment]
You're sure that `locationIds` is iterable? Or even has a value? Try add `console.log(locationIds)` just after `var locationIds = ...` and let me know what you get in the developer console.

**Comment by kayex** [comment]
You got me on the right path.  I needed to check locationIds to see if the last option removed from the list made locationIds null.  If not null, run the $.each function.    Thank you for your response.
