### ISSUE TITLE
Add versioning in the bower releases

### ISSUE THREAD

**Issue by prateekbhatt** [harvesthq/chosen#2546]

**Comment by stof** [comment]
What do you mean ?

**Comment by tjschuck** [comment]
Not sure either.

@prateekbhatt Can you please clarify your issue? Closing this until more info is provided, then we'll reopen.

**Comment by prateekbhatt** [comment]
Sorry for not making it clear.

What I meant is when I install via bower, i.e `bower install chosen --save`, the "chosen" version defaults to "*" because the bower repo of "chosen" does not declare version numbers (semver) in the bower.json file: https://github.com/harvesthq/bower-chosen/blob/master/bower.json

If there are any breaking changes to future releases of "chosen", this would cause problems in existing projects using it via bower.

**Comment by tjschuck** [comment]
The last commit to that repo/file (to release 1.5.1) seemingly removed that line: https://github.com/harvesthq/bower-chosen/commit/bd15e354583a6cec0745266768a56fc62f6ddfcf

I'm not sure if that was intentional or not, but pinging @pfiller to clarify.

Reopening!  Thanks for following up, @prateekbhatt

**Comment by kevin-brown** [comment]
The `version` specifier shouldn't be required anymore, [it's actually deprecated](https://github.com/bower/spec/blob/ae94955c54801120f718b248f8eae8b9463be708/json.md#version) in favor of SCM tags.

**Comment by tjschuck** [comment]
@kevin-brown Thanks for the link!  That must be why we axed it.  We [are using tags as suggested](https://github.com/harvesthq/bower-chosen/releases).

@prateekbhatt Closing this per the doc linked above by @kevin-brown.  Thanks!
