### ISSUE TITLE
word-wrap & white-space attributes not functioning

### ISSUE THREAD

**Issue by livingaudio** [harvesthq/chosen#2547]
I was wondering how I can handle text-wrap with long strings via chosen.css library. I can't seem to properly break & wrap a long unordered list with links.

You can see what I'm trying to replicate on [http://jsfiddle.net/Ex5fA/69/].

**Comment by pfiller** [comment]
So, I'm pretty confused when I click through to that Fiddle. It's neat looking, but it doesn't seem to actually be Chosen! Looks like a Bootstrap dropdown and Bootstrap CSS.
