### ISSUE TITLE
Chosen loses the search if I select one of matching resul in the list while presing CONTROL - KEY

### ISSUE THREAD

**Issue by falinsin** [harvesthq/chosen#2549]
If I  press CONTROL KEY in chosen while select multiple elements in the list teh list of elements stay open and dont close and this is very helpfull in our proyect with lost of elements.

But wen I set a filter in yhe multiselect an start selecting elements in the list of matching results while pressing CONTROL-KEY the box do not close but teh search for filtering is reseted when I press one of the matching results and cant continue selecting more of the matching results.

How can I avoid lost the search in this cases?

PLease i need help on this because is the most important behavior for our client.

Where in the code can I patch this  behavior in case it isn't implemented?

Thanks in advance

**Comment by Insider32** [comment]
Correct me if I am wrong but you want the text in the input area to remain after selecting an option
right?

If that is the case you have to find in the code where and when it is resetting the search field.
Particularly check `show_search_field_default` and more precisely `this.search_field.val("");`.

The relevant call should be on `result_select` in line 1077.

**Comment by koenpunt** [comment]
Good point. The results are still filter using the query, but the query itself has been removed from the input. This shouldn't happen.

**Comment by falinsin** [comment]
Thanks for you help, finally I could do it. Now the search stay and using CONTROL-KEY I can select some elements in the filtered list which is a lot of convenient for the finals users

**Comment by koenpunt** [comment]
I want to keep this open for the aforementioned reason.

**Comment by KGDSOsixer** [comment]
Feel shy, which can not be found Chinese?？
