### ISSUE TITLE
Edit options displaying text

### ISSUE THREAD

**Issue by gbgkogkas** [harvesthq/chosen#2552]
I would like to refine some options` text by appending an icon or text.
My problem is that every time I open the dropdown the options are recreated.

To rectify my problem used the following code:
```
$('select').on('chosen:showing_dropdown',function(){
    $('.disabled-result.missing_data').each(function(){
        $(this).html($(this).text() + $('#missing_data_warning').html());
    });
});
```

Is there a way to assign this directly to chosen and avoid the continue repeats?

**Comment by pfiller** [comment]
There isn't currently a way to automate this, no. Something like #692 (adds templating support) would help a lot if it were to land. Closing in favor of discussion there.
