### ISSUE TITLE
Tablet behavior: both <select> and .chosen-container hidden

### ISSUE THREAD

**Issue by Onotoley** [harvesthq/chosen#2554]
So here's the thing, with the latest .min.js realease included - my .chosen-container gets display:none !important on tablet as the tablet is a touch device.

Yet, the <select> tag has a display: none; as an inline style. Therefore, on tablet I've got neither of them.

Am I missing something or this was not supposed to be like that?

**Comment by koenpunt** [comment]
> my .chosen-container gets display:none !important on tablet

If I understand you correctly, you want to show the native select on iPad, instead of Chosen, am I right?

The most efficient way would be only initializing when the useragent doesn't match `iPad`, something like:

```js
var isiPad = /iPad/i.test(window.navigator.userAgent)

if(!isiPad) {
  $('.my-select').chosen();
}
```

If that's not an option, you could also set a `display: static !important` to the `<select>` itself, because `!important` will overrule inline style.

**Comment by Onotoley** [comment]
Thanks for the reply. Yet, that doesn't fully answers my question.

Thing is that i don't need native select in particular, i want any of them to be shown on all tablets. The iPad, Nexus 9, Nexus 7 are larger than mobile yet they are touch. I believe this is sort of a "bug", see the screens-shot [here](https://gyazo.com/ebf08059720e86bb757f864e133b6fb3), Select has the display none and the chosen container is hidden because it's a touch device (taken from Chrome emulation of Nexus 9)

**Comment by koenpunt** [comment]
The `.touch .chosen-container {}` part is not default (as in, it doesn't exist in [`chosen.scss`](https://github.com/harvesthq/chosen/blob/master/sass/chosen.scss)), so you probably have that defined somewhere in your project.

**Comment by tjschuck** [comment]
Closing this per @koenpunt's last comment — this is happening outside of Chosen itself.
