### ISSUE TITLE
Update jQuery to a more recent version in the docs

### ISSUE THREAD

**Issue by Pezmc** [harvesthq/chosen#2557]
I [note](https://github.com/harvesthq/chosen/blob/master/public/index.html#L1461) it's at 1.6.4 while jQuery is now at 1.12.1. It's suggested that people use a recent build of both chosen and jQuery, the docs should probably be doing the same!

```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
```

**Comment by tjschuck** [comment]
@Pezmc Where do we suggest a recent build of jQuery?  We support as far back as jQuery 1.4.

**Comment by koenpunt** [comment]
@Pezmc probably means that jQuery suggests using their latest version. But what is the win of using it in this case?

**Comment by tjschuck** [comment]
@koenpunt He might also be referring to [this comment](https://github.com/harvesthq/chosen/pull/2555#issuecomment-190388250) from me about upgrading specifically from versions 1.12.0 or 2.2.0 to 1.12.1/2.2.1, but that's to fix a bug in those particular versions, not recommending a general jump beyond other old versions.

Regardless, I suppose we _are_ on a slightly arbitrary version.  We are neither on the latest version nor the oldest supported version, so I guess there's no real reason to stay where we are ¯\\\_(ツ)_/¯

**Comment by Pezmc** [comment]
> Regardless, I suppose we are on a slightly arbitrary version. We are neither on the latest version nor the oldest supported version, so I guess there's no real reason to stay where we are ¯\_(ツ)_/¯

Yes that's the point I was trying to make, it seems like the number on the docs page has been chosen at random! A newer copy, or at least a copy chosen with some documented decision would make sense here.

**Comment by koenpunt** [comment]
> it seems like the number on the docs page has been chosen at random!

Pun intended here? :smile: But it was probably the latest version available at that time

**Comment by koenpunt** [comment]
While addressing the docs, we might consider looking into this again: #1829

**Comment by tjschuck** [comment]
@Pezmc Like @koenpunt, I assume it was the latest version available the last time it was updated :wink: 

I'd be okay with a version bump PR.

**Comment by koenpunt** [comment]
@Pezmc do you still want to address this?
