### ISSUE TITLE
Enable drop-down search/filter on mobile

### ISSUE THREAD

**Issue by BradSmithSC** [harvesthq/chosen#2558]
Drop-down has a typeable search/filter field on desktop but not mobile. 

Is this a setting? 
If so, can the drop-down be disabled (search/filter only)?

![image](https://cloud.githubusercontent.com/assets/2806158/13434979/f89b5c34-dfa5-11e5-8a0e-3045f1d6a706.png)

**Comment by tjschuck** [comment]
@BradSmithSC Chosen is intentionally disabled on mobile.  See [the third bullet point in the FAQs](http://harvesthq.github.io/chosen/#faqs) and issue https://github.com/harvesthq/chosen/pull/1388 for more information.
