### ISSUE TITLE
Multiple Select - Post Variable only Contains last Value

### ISSUE THREAD

**Issue by mpiontek** [harvesthq/chosen#2559]
For every multiple select, for which i use chosen, the post variable only contains the last selected option. The other options are not in the variable. Is there  special 'trick' to do this?

**Comment by koenpunt** [comment]
Yes, add `[]` to the name of your select. So if it was previously like this:

```html
<select name="countries">
...
</select>
```

You should use:

```html
<select name="countries[]">
...
</select>
```

This was the post value will contain an array of all the options.

**Comment by mpiontek** [comment]
In my case it is not working. Outputting the $_POST Variable shows

`<pre>
Array
(
    [category] => Rigging
)`

although send post looks like this:

`category	Ton
category	Meister
category	Logistik
category	Lager
category	Rigging`

**Comment by koenpunt** [comment]
What does your html look like?

**Comment by mpiontek** [comment]
Sorry Koenpunt! It was my fault - i did make the mistake to add the [] to the ID instead of the name at one select field. Thank your very much for your help!
