### ISSUE TITLE
Chosen post_form issue

### ISSUE THREAD

**Issue by wmlmusic** [harvesthq/chosen#2564]
Hello, I would first like to thank you for your amazing multi-select dropdown. I am however having an issue of using it on my post_form page in my admin panel for the Client: field. It works on my artist_form for clients, but in the inspector of my browsers it is showing an error on the post_form page. The first screenshot is from the post_form with the error, the second is from the artist_form where I have your fine plugin working, and the third is from my header.php where the link to the chosen.css file is posted. If you can assist me with resolving this issue I would greatly appreciate it.
![chosen_postform](https://cloud.githubusercontent.com/assets/16200414/13512030/37f95202-e166-11e5-9f93-5bc57338a5d6.png)

![image](https://cloud.githubusercontent.com/assets/16200414/13512042/59110bb0-e166-11e5-9962-e9d43dd9ddee.png)

![image](https://cloud.githubusercontent.com/assets/16200414/13512116/d6266208-e166-11e5-9c2c-0c9c4afa18ef.png)

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be much more likely to get a quick answer there if you also can link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue.

**Comment by koenpunt** [comment]
The problem is probably because you forgot to add Chosen's js-file. And you have added jQuery itself twice.

**Comment by wmlmusic** [comment]
Hi Koenpunt thanks for your input <script src="public/js/chosen.jquery.min.js" type="text/javascript"></script> would be the chosen js file you are referring to correct, or is it <script src="public/js/chosen.jquery.js" type="text/javascript"></script>? the other jquery.min.js file I see where I think you may be referencing is for another plugin used on the page if I remember correctly. Should it not work on my post_form page if the same code is being used on my artist_form page though? I did nothing different from one page to the other.
![image](https://cloud.githubusercontent.com/assets/16200414/13514286/a4a23734-e175-11e5-8830-60a505f17c78.png)
![image](https://cloud.githubusercontent.com/assets/16200414/13514317/e8226da8-e175-11e5-8c55-1c0ab34f1e20.png)

**Comment by wmlmusic** [comment]
Update: I was able to get it to show on the post_form now. I deleted and re-pasted the code <script type="text/javascript">
        var config = {
      '.chosen-select'           : {},
      '.chosen-select-deselect'  : {allow_single_deselect:true},
      '.chosen-select-no-single' : {disable_search_threshold:10},
      '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
      '.chosen-select-width'     : {width:"95%"}
    }
    for (var selector in config) {
      $(selector).chosen(config[selector]);
    }  	
	$(document).ready(function () {
                $.validator.setDefaults({ ignore: ":hidden:not(select)" })
		$('#postForm').validate({
			errorElement: "div",
			rules: {
			    name: { required: true },			
			    details: { required: true },
			    category: { required: true }
		  	}
		});
		$('#restform').click(function(){
            $('#postForm')[0].reset();
 		});
	});
</script> at the bottom of the post_form and it somehow works now. Thanks for your assistance koenpunt
