### ISSUE TITLE
capture output by post (php)

### ISSUE THREAD

**Issue by mambo06** [harvesthq/chosen#2565]
how to capture output and echo from multiple selection.

foreach ($_POST['index'] as $a){ echo $a; }

doesnt seem to work.
thanks

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.
