### ISSUE TITLE
Deleting a Populated List from an array 

### ISSUE THREAD

**Issue by StudySearch** [harvesthq/chosen#2566]
I tried to populate the chosen selected options by combining PHP & JQUERY by appending the `$('ul.chosen-choices')` which worked well. My choosen list was populated successfully.

bellow is my code for populating the choosen which is inside a loop

```php
<?php
			for($i=0; $i<= (sizeof($_SESSION['country_php_list'])-1); $i++)
			{
			?>
$('ul.chosen-choices').append('<li class="search-choice"><span><?=ucfirst($_SESSION['country_php_list'][$i]);?></span><a data-option-array-index="<?=$i+1;?>" class="search-choice-close"></a></li>');
			<?php }
```

**Now my problem**

Deleting the each choosen list-item was not possible.

Can u kindly assist me on how to make the delete work for each item on the list i added from my array.

My email :: okechukwu0127@gmail.com
My Skype :: okechukwu0127
My Phone:: +2348067135499

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

However, that said, it seems like you're using Chosen incorrectly.  You seem to be building up a Chosen dropdown by populating the Chosen element directly.  This is not how you should create a Chosen dropdown.

You should define your dropdown as a standard `select` element, and then call `.chosen()` on it.

Similarly, if you wish to update your Chosen dropdown (such as deleting items like you mentioned), you should operate on the underlying `select`, removing `options` from inside of it, and then call `.trigger("chosen:updated")` to rebuild Chosen.

[See the docs](http://harvesthq.github.io/chosen/) for more info.

**Comment by StudySearch** [comment]
Found my way around. Though its a bit messy approach.

<select tabindex="8" multiple class="questions-input chosen-select"
id="forchosen" data-placeholder="Type a country">
<option value="Afghanistan"
<?=$this->StudySearchModel->choosen('Afghanistan',$_SESSION['country_php_list']);?>>Afghanistan</option>

<option value="Albania"
<?=$this->StudySearchModel->choosen('Albania',$_SESSION['country_php_list']);?>>Albania</option>

<option value="Algeria"
<?=$this->StudySearchModel->choosen('Algeria',$_SESSION['country_php_list']);?>>Algeria</option>
..........
..........
</select>

the *choosen *function returns *selected *if param1 is found in
param2-Array.

I would prefer a more efficient way to handle populating the select/option
with Jquery/javascript

Kind regards
