### ISSUE TITLE
Labels & Disabled Select

### ISSUE THREAD

**Issue by Zbenfeild-cotter** [harvesthq/chosen#2567]
Clicking on a label for a disabled chosen select applies the focus/active class, however clicking away does not remove it as it would on a normal chosen select. 

Tested on the examples page by changing the "single-label-example" select to disabled, triggering update then clicking label.

**Comment by mattumotu** [comment]
I am also seeing this issue

**Comment by mattumotu** [comment]
Fiddle: http://jsfiddle.net/j75o4hfy/

**Comment by pfiller** [comment]
@mattumotu's Fiddle doesn't seem to show the issue for me.

Here's an updated Fiddle:
https://jsfiddle.net/9wxtkysL/
