### ISSUE TITLE
Doesn't work after postback when within UpdatePanel

### ISSUE THREAD

**Issue by cirenep** [harvesthq/chosen#2568]
When I put the chosen jQuery dropdownlist on my ASPX page it works fine. But, when I put it within an UpdatePanel, after postback, all the effects of the dropdownlist disappear. What is the correct work-around for this? Thanks! Great product!

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

That said, if Chosen seems de-activated and you're just getting your normal `select` again, it sounds like you just have to re-apply chosen with `$(".my-select").chosen()`, or _maybe_ just trigger an update on it with `$(".my-select").trigger("chosen:updated");` (but my money's on the first suggestion).
