### ISSUE TITLE
Add option to generate select list from JSON array

### ISSUE THREAD

**Issue by skiracerdude** [harvesthq/chosen#2573]
Hey all!

Just a quick feature suggestion for the future, add the option to generate the select list using a JSON array passed in via options!

Would be cool :)

**Comment by koenpunt** [comment]
Chosen is initialized with a select element as state, so populating Chosen itself is not what you want to do.
You could however populate the select with your JSON array, and trigger `chosen:updated` on it after to make Chosen reflect the changes.
