### ISSUE TITLE
Adding this.search_results.scrollTop() in Chosen.prototype.result_do_highlight breaks scrolling for long lists

### ISSUE THREAD

**Issue by rabinnh** [harvesthq/chosen#2579]
Vertical scrolling on long lists is broken when moving mouse cursor from scrollbar to select.

### Steps to reproduce

1. Create a single select list with enough entries for at least 3 full "pages" based on the size of the dropdown.

2. Use the scrollbar to scroll down more than halfway through the list.

3. Move the cursor to select an item.

4. The list will jump to the end.

### Environment

Chosen 1.5.1

jQuery 2.2.0

Chrome LinuxVersion 49.0.2623.87 (64-bit)

Ubuntu 14.04.3

### Additional information

The bug is at this line:

https://github.com/harvesthq/chosen/blob/6e01e4e105c13902b96e49ce8d036d584204ccf1/coffee/chosen.jquery.coffee#L220

It should be changed because adding this.search_results.scrollTop() is unnecessary and breaks behaviour:

high_top = this.result_highlight.position().top + this.search_results.scrollTop();

to

high_top = this.result_highlight.position().top;

**Comment by tjschuck** [comment]
This is actually a bug in jQuery (versions 1.12.0 and 2.2.0), not Chosen.

See https://github.com/harvesthq/chosen/issues/2506 for more info, but jQuery has released [1.12.1 and 2.2.1](http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/) which should fix the issue.

Please let us know if that _doesn't_ fix your issue, and we'll reopen. Thanks!
