### ISSUE TITLE
Fix problem scroll to long list.

### ISSUE THREAD

**Issue by dim1triy** [harvesthq/chosen#2585]
The problem with a numeric variable, the number is too long, after the comma. It did not fire condition for scrolling

Function fix
```
    Chosen.prototype.result_do_highlight = function(el) {
      var high_bottom, high_top, maxHeight, visible_bottom, visible_top, toScrollHeight;
      if (el.length) {
        this.result_clear_highlight();
        this.result_highlight = el;
        this.result_highlight.addClass("highlighted");
        maxHeight = parseInt(this.search_results.css("maxHeight"), 10);
        visible_top = parseInt(this.search_results.scrollTop());
        visible_bottom = parseInt(maxHeight + visible_top - 30);
        high_top = parseInt(this.result_highlight.position().top + this.search_results.scrollTop());
        high_bottom = parseInt(high_top + this.result_highlight.outerHeight());
        // 
        toScrollHeight = parseInt(high_bottom - maxHeight);
        // 
        if (high_bottom >= visible_bottom) {
          return this.search_results.scrollTop((toScrollHeight) > 0 ? (toScrollHeight + 30) : 0);
        } else if (high_top < visible_top) {
          return this.search_results.scrollTop(high_top);
        }
      }
    };
```

**Comment by koenpunt** [comment]
What is the problem and how are you fixing it? Also, please format your code using the markdown markup (click the [M?] button for help), this would make it much more readable.

**Comment by dim1triy** [comment]
After refreshing the page without scrolling performed on the highlighted line in large lists (274 options row). I added rounded to the nearest whole for all variables. Browser Firefox 45.

high_top: 3975.0000610351562 not work if (high_bottom >= visible_bottom) , After rounding up the whole, is works. 

Also added to the scroll +30, and then scrolled to the line, most of the selected line to be seen. There may need to adjust differently.

**Comment by pfiller** [comment]
Sorry, I still don't understand what the issue is here. Can you please provide a [fiddle](https://jsfiddle.net/ntoseaga/) that shows the problem and tell us the explicit steps to see the issue?
