### ISSUE TITLE
Feature request: Callback or event on no results

### ISSUE THREAD

**Issue by VenkateshSM** [harvesthq/chosen#2587]
Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. This is the first step

  2. This is the second step

  3. Further steps, etc.

Additionally, please link to a working demo that shows the issue so we can attempt to reproduce.  You can use [this template](https://jsfiddle.net/5v3v353z/) as a base.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

### Expected behavior

Tell us what should happen.

### Actual behavior

Tell us what happens instead.

### Environment

  - **Chosen Version**:

  - **jQuery or Prototype Version**:

  - **Browser and Version**:

  - **OS and Version**:

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by tjschuck** [comment]
Already exists: `chosen:no_results` — see [the docs](http://harvesthq.github.io/chosen/options.html#triggered-events).
