### ISSUE TITLE
How can I read the text entered in search input of chosen plugin ?

### ISSUE THREAD

**Issue by tahiralvi** [harvesthq/chosen#2588]
Hi,

I have used the chosen plugin in modal, and I want to read the text entered by user during search.

I want to populate the<select> on the basis of search text entered by the user.

Here is my code for getting the text input, but not working somehow.

 $('#ModalNewMedication').on('shown.bs.modal', function () {
            $('#ddlMedications', this).chosen();

            $('#ddlMedications').on('input', '.chosen-search input', function(event){
                alert('iam done');
            });

        });

**Comment by pfiller** [comment]
Hi @tahiralvi -

Your selector is searching for a `.chosen-search` selector inside of a `select` and that doesn't exist. Chosen inserts its HTML immediately after the select box it replaces. You need something more like:

```JavaScript
$('#ModalNewMedication').on('shown.bs.modal', function () {
  $('#ddlMedications', this).chosen();
  $('#ModalNewMedication').on('input', '.chosen-search input', function(event){ alert('iam done'); });
});
```
