### ISSUE TITLE
data attributes in select option does not copy over

### ISSUE THREAD

**Issue by defaria** [harvesthq/chosen#2591]
My select dropdown option's tag has data attributes (data-something="thing"). I noticed that while classes copy over to the UL/LI list, the data attributes don't.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. add data attribute ->  <option data-something="thing">

  2. check ul.chosen-results li and notice that the attributes are missing

**Comment by yaroslavk1** [comment]
We are working on it. 
You can subscribe on this pull request https://github.com/harvesthq/chosen/pull/2574

**Comment by pfiller** [comment]
Closing in favor of a discussion on #2574
