### ISSUE TITLE
How to Display the  Chosen’s container div by default

### ISSUE THREAD

**Issue by gaoguoxin** [harvesthq/chosen#2595]
```html
<select id='id' class='chosen-with-drop chosen-container-active' multiple>
  <option value='1'>v1</option>
  <option value='1'>v1</option>
  <option value='1'>v1</option>
  <option value='1'>v1</option>
</select>
```
```js
$('#id').chosen({
  inherit_select_classes:true
})
```

As you can see, I want to show the container when I come in the page,but not work,is there any error?
I have checked the doc about the options and I saw the inherit_select_classes that explains as follow:
```txt
When set to true, Chosen will grab any classes on the original select field and add them to Chosen’s container div.
```

**Comment by koenpunt** [comment]
So you want to have the select open when someone enters the page? And you want to keep it open after interaction as well?

**Comment by gaoguoxin** [comment]
yes that's what I want

**Comment by koenpunt** [comment]
Even though `inherit_select_classes` will pass on the classes, the javascript will eventually remove it. For now the only way I can think of that could be possible is by using CSS, optionally with `!important`

**Comment by gaoguoxin** [comment]
It seems that not work,the li elements in the container not exist  until I click the container

**Comment by pfiller** [comment]
You could open it when the page loads by triggering the open event on the select:

```JavaScript
  $('#some_select_box').trigger('chosen:open');
```

Keeping it open isn't really the way the library is designed so you'll have to fight a number of code spots to make that happen. It's out of scope for this project, though.
