### ISSUE TITLE
Collapsable Optgroup? (Feature Request)

### ISSUE THREAD

**Issue by jdtechsol** [harvesthq/chosen#2598]
Is it possible for you to add a feature allowing the groups to start out, collapsed? This could come in handy is during situations where you are scrolling through the a full list not-reduced by searching. Obviously text search is the fastest way but I like others do not always use it especially when the group I am looking for seems closer than it actually is. 

I have to ask one other question.. Why do you use li tags for optgroup? why not structure it with a li ul li?

**Comment by pfiller** [comment]
That's an interesting feature idea, but it's outside of the scope for this project. For better or worse, we err on the side of "what does a standard select do?" Collapsable groups would be a pretty severe departure.

> Why do you use li tags for optgroup? why not structure it with a li ul li?

Heh - that decision was made many years ago at this point. Who can remember!?
