### ISSUE TITLE
How to open Chosen drop down outside  scroll modal, like HTML dropdown…  

### ISSUE THREAD

**Issue by uirajatmal** [harvesthq/chosen#2601]
How to open Chosen drop down outside 
![scroll-modal](https://cloud.githubusercontent.com/assets/4692315/15188041/c70857f4-1771-11e6-91f8-5e3acf335095.png)
 scroll modal, like HTML dropdown…

**Comment by pfiller** [comment]
Duplicate of #96. There are some solutions discussed in there, but there's currently no official solution.
