### ISSUE TITLE
Problem in Single select chosen

### ISSUE THREAD

**Issue by bharathidasans** [harvesthq/chosen#2604]
I am using Chosen_V1.5.1.

I tried all the options that available and its working fine.

In my project i am using webkitdfb-2.3.0 package. I implemented chosen as plugin. 
For multiple selection, i am able to load and selecting multiple data fine
But my problem is single selection only. When i click on component (single selection and disable search option) the drop down box not working but at the same time when i press space bar it opens drop down box and its working.

Please suggest me any other options for single selection.

**Comment by pfiller** [comment]
Sorry, I don't understand your problem. Can you please link to a publicly accessible page (or a Fiddle) that shows the issue so we can attempt to reproduce? Please provide explicit steps for repeating the problem.

Closing pending more information.
