### ISSUE TITLE
Add tagging support like Select2

### ISSUE THREAD

**Issue by chrispcb** [harvesthq/chosen#2606]
Tagging support with Automatic tokenization like "Select2"  would be a nice feature.

**Comment by pfiller** [comment]
Duplicate of #5. You may want to have a look at #166 which has a working solution.

**Comment by chrispcb** [comment]
Nice, thank you.
You should add an exemple in demo page, no ?

**Comment by pfiller** [comment]
> You should add an exemple in demo page, no ?

No, we don't document features in forks at this time. We only document the features that Chosen supports.

**Comment by iszlailorand** [comment]
Can i ask u why don't you integrate this feature, it's nice one and a needed one?
