### ISSUE TITLE
select not displaying inside a jquery accordion initializing closed (not active).

### ISSUE THREAD

**Issue by chrisrauz** [harvesthq/chosen#2607]
select not displaying inside a jquery accordion initializing closed (not active).

### Steps to reproduce

This code will produce an accordion with a non-usable chosen select:

```html
    <div id="accordion">
        <h3>
            TEST
        </h3>
	    <div>
            <select id="Select1" class="chosen-select" style="width:100px;">
                <option>test 1</option>
                <option>test 2</option>
                <option>test 3</option>
                <option>test 4</option>
                <option>test 5</option>
            </select>
        </div>
    </div>

    <script>
        $(".ui-accordion .ui-accordion-header").css({ padding: "1px 1px 1px 30px" });
        var icons = {
            header: "ui-icon-circle-arrow-e",
            activeHeader: "ui-icon-circle-arrow-s"
        };
        $("#accordion").accordion({
            icons: icons,
            active: false,
            collapsible: true,
            heightStyle: "content"
        });

        $(".chosen-select").chosen({
            disable_search_threshold: 30,
            no_results_text: "Oops, nothing found!"
        });
  </script>
```

---note the active: false line in accordion call. Comment it out and all is well except the accordion initializes open:

```html
    <div id="accordion">
        <h3>
            TEST
        </h3>
	    <div>
            <select id="Select1" class="chosen-select" style="width:100px;">
                <option>test 1</option>
                <option>test 2</option>
                <option>test 3</option>
                <option>test 4</option>
                <option>test 5</option>
            </select>
        </div>
    </div>

    <script>
        $(".ui-accordion .ui-accordion-header").css({ padding: "1px 1px 1px 30px" });
        var icons = {
            header: "ui-icon-circle-arrow-e",
            activeHeader: "ui-icon-circle-arrow-s"
        };
        $("#accordion").accordion({
            icons: icons,
       //     active: false,
            collapsible: true,
            heightStyle: "content"
        });

        $(".chosen-select").chosen({
            disable_search_threshold: 30,
            no_results_text: "Oops, nothing found!"
        });
  </script>
```

Additionally, please link to a working demo that shows the issue so we can attempt to reproduce.  You can use [this template](https://jsfiddle.net/5v3v353z/) as a base.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

### Environment

  - **Chosen Version**:
Version 1.5.1
  - **jQuery or Prototype Version**:
jquery-2.2.2
  - **Browser and Version**:
Chrome Version 50.0.2661.102 m
Firefox 46.0.1
IE 11

**Comment by tjschuck** [comment]
@chrisrauz I'd be willing to bet this is the same issue as the one described here: https://github.com/harvesthq/chosen/issues/2332 (that's for inactive tabs, not accordions, but seems very similar).  There's a workaround there -- please try that!

**Comment by chrisrauz** [comment]
TJ - yes. that works. Thanks. I usually just set the control width and that is sufficient. I'll just carry over the width to the chosen call too. Also - the dropdown, when expanded, is hidden behind the accordion. You think a z-index thing?

**Comment by tjschuck** [comment]
@chrisrauz Not sure, but that'd be my first guess.

**Comment by tjschuck** [comment]
#646 and the handful of workarounds there might help, though ¯\\\_(ツ)_/¯

**Comment by chrisrauz** [comment]
Thanks TJ. Your help is appreciated.

**Comment by tjschuck** [comment]
Don't mention it!

**Comment by chrisrauz** [comment]
in case anyone may care-  i fixed the width issue like this in chosen.jquery.js file. Approximately line 501 not minimized.
`AbstractChosen.prototype.container_width = function () {
      if (this.options.width != null) {
        return this.options.width;
      } else {
          //   return "" + this.form_field.offsetWidth + "px";
          return "" + this.form_field.style.width;
      }
    };`
I haven't figured out the z-index issue yet.....
