### ISSUE TITLE
Need to detect disabled attribute of original select and to trigger "chosen:disable" / "chosen:enable" event

### ISSUE THREAD

**Issue by EvoWebFrance** [harvesthq/chosen#2610]
Hello,
For dynamic forms I need to enable/disable the select linked to the chosen object.

1. Is it possible to detect the "disabled" attribute of the original select when adding chosen object and set the chosen drop-down to disabled (and perhars add a specific class for css) ?
2. Is it possible to trigger two new events : "chosen:disable" and "chosen:enable" or perhaps detect the "disabled" attribute on "chosen:updated" ?
Thank you

**Comment by pfiller** [comment]
Chosen doesn't have a way to turn itself on and off, but you can just destroy the Chosen instance and re-instantiate it whenever we want.

```JavaScript
// make it go away
$("#form_field").chosen("destroy");

// bring it back
$("#form_field").chosen();
```

Hope that helps.
