### ISSUE TITLE
How to add new option?

### ISSUE THREAD

**Issue by marspe** [harvesthq/chosen#2615]
Is there any ability to choose option which is not preloaded in the multiple select instead of displaying "no results" message?

**Comment by jfoo1984** [comment]
If you look on the Options documentation page, you can trigger the `chosen:updated` event, which will reload the select box with the newly added options:

```
  // tell Chosen that a select has changed
  $('.my_select_box').trigger('chosen:updated');
```

There's also a `no_results_text` options you can set when creating the Chosen box.  However, if you need to override the no_results_text dynamically, I'm not sure if there is a better documented way of doing it, but I was able to use the following to dynamically override the no results text:
 ```$('.my_select_box').attr("data-no_results_text", "This shows up instead of no results. ")```

**Comment by tjschuck** [comment]
I think @marspe is specifically talking about dynamically adding options based on the user's input, which is _not_ currently supported by Chosen.  There's an open PR for that here: https://github.com/harvesthq/chosen/pull/166.  Please leave any additional feedback you have there.

As for doing this manually, that's probably possible using the APIs @jfoo1984 mentioned (thanks, @jfoo1984!).  More information about those APIs [here](http://harvesthq.github.io/chosen/#change-update-events) and [here](http://harvesthq.github.io/chosen/options.html).
