### ISSUE TITLE
I cant use virtual keyboard with chosen

### ISSUE THREAD

**Issue by Sua26** [harvesthq/chosen#2616]
Im using mottie keyboard and I dont know how i can configurate it, nobody knows? Im trying use the search with a variable but is impossible, what is wrong? this is my code:

```
$('.chosen').chosen({ width: "500px" });
$("#popupSelect").trigger('chosen:open');


$('#popupSelect').val(tempVariable).trigger('chosen:updated');
 
```

**Comment by tjschuck** [comment]
Can you confirm whether the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue?

**Comment by Sua26** [comment]
I dont find, I have a textarea to insert a new value and i want to pass it to the chosen search, how can i do?

**Comment by Sua26** [comment]
this dont works for me:

$('.chosen-search input[type="text"]').val($variable).trigger('chosen:updated');

I want to put a search with a variable and i can´t

**Comment by Sua26** [comment]
Finally I made it, this is my solution. X is a value taken from a textarea and pass to chosen as "search", runs for me.


                                   var x=document.forms.maintenance_product_texts.valueToLocate.value;
    				   $("#popupSelect").attr("data-placeholder", x).trigger('chosen:updated');
     				   $('#popupSelect').trigger('chosen:activate');
    				   $('ul.chosen-choices').trigger('click');

**Comment by pfiller** [comment]
Cool! Glad you found a solution. Hopefully someone looking to solve the same problem will find this thread in a search. Thanks for sharing.
