### ISSUE TITLE
Enforce HTTPS for harvesthq.github.io

### ISSUE THREAD

**Issue by konklone** [harvesthq/chosen#2626]
Sorry for veering off the template -- this is a bug report for the GitHub Pages configuration of this repo itself, rather than the software project.

GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://harvesthq.github.io/chosen/ So this should be a trivial fix.

I recommend going through any other repos that use the harvesthq.github.io domain to flip the switch there too.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by adunkman** [comment]
You got it! Checked the box like a champ, but the site still seems accessible over HTTP — perhaps the next build will fix it, or perhaps it takes some time — in any case, going to mark this as ✅ !

Thanks for keepin’ an eye out, @konklone!

**Comment by konklone** [comment]
http://harvesthq.github.io/chosen/ redirects to HTTPS for me:

```
$ curl --head http://harvesthq.github.io/chosen/
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://harvesthq.github.io/chosen/
```

Thanks for doing this! :smiley_cat:
