### ISSUE TITLE
bower-chosen

### ISSUE THREAD

**Issue by vakorovin** [harvesthq/chosen#2627]
Hello, i want use https://github.com/harvesthq/bower-chosen in my Yii2 project. But i have problem. Bower-chosen marked as 1.5.1, but actually is 1.5.0. Can you update this repository? Thank you.

**Comment by koenpunt** [comment]
The package publishing has been updated, and there we found a bug which was caused by tagging before committing, which was solved by #2633.

Using v1.6.1 should satisfy your needs
