### ISSUE TITLE
Cannot .focus() chosen element

### ISSUE THREAD

**Issue by jirir** [harvesthq/chosen#2629]
The html element with applied chosen.js cannot be focused by the `focus()` method.

The intention is to have a page with command-line-like interface powered by `chosen` auto-completion. Page loads and user can send (actually _choose_) commands using keyboard. Without the ability to focus the `chosen` element on page load the user has to manually navigate to the chosen element which is critical to the user experience.

### Steps to reproduce

1. The code (see [demo](https://jsfiddle.net/hws2xp1d/)):

 `<form id="formID">`
 `          <select  id="selectID" data-placeholder="Choose a Color ..." class="chosen-select" style="width:350px;" tabindex="1">`
`            <option value="" selected></option>`
`            <option value="Red">Red</option>`
`            <option value="Blue">Blue</option>`
`          </select>`
`</form>`

2. Execute this in the Console (Safari-Web Inspector-Console)

`document.getElementById("selectID").focus()`

or

`document.getElementById("formID").focus()`

### Expected behavior

The `select` or `form` element get focus.

### Actual behavior

Neither `select` nor `form` element get focus.

### Environment

  - **Chosen Version**: see [demo](https://jsfiddle.net/hws2xp1d/)

  - **jQuery or Prototype Version**: see [demo](https://jsfiddle.net/hws2xp1d/)

  - **Browser and Version**: Safari 9.1.1

  - **OS and Version**: OS X 10.11.5

**Comment by vbrmnd** [comment]
You will have to focus the anchor element which contains selected element,

`$("#selectID").next().find('a.chosen-single').focus();` 
Or, `$('.chosen-single').focus();`

Hope, this will get things done.

**Comment by koenpunt** [comment]
You can focus the Chosen select by "activating" it: 

```js
$('.chosen-select:first').trigger('chosen:activate')
```

Does this answer your question?
