### ISSUE TITLE
Where is css class for "chosen-select"?

### ISSUE THREAD

**Issue by huanhaihu** [harvesthq/chosen#2630]
Hi,

I am trying to test and see how the v 1.5.1 multi-select combobox feature works, so I viewed the source code and added all the .css and .js requested, but I can't find where is the definition of chosen-select class definition? I can see chosen-container, chosen-search...etc but where is chosen-select which your guys used for the demo.

Thanks
Tony

**Comment by koenpunt** [comment]
That's just the class used to target the Chosen selects from JavaScript, so no CSS is attached
