### ISSUE TITLE
NPM Installation

### ISSUE THREAD

**Issue by artursopelnik** [harvesthq/chosen#2631]
For our customer project we need compiled js files without bower-installation. Currently we use [napa ](https://www.npmjs.com/package/napa) for setup bower-repo as a npm-repo. But this approach is slower and vulnerable.

**Possible solutions:**
- Add (dist-files ~ compiled js files) to current repo. 
- Or update 2nd Chosen repository with package.json
- Or create 3nd Chosen repository with package.json for npm.

**Comment by stof** [comment]
We won't add the dist files to the current repo (this is not maintainable as it creates conflicts for each merge).
But NPM does not need dist files in the git repo anyway. It needs the dist files in the archive submitted to the npm registry.

I'm closing this issue in favor of #1433 though, as we already have a discussion about it
