### ISSUE TITLE
Bower-chosen - minified versions

### ISSUE THREAD

**Issue by fracsi** [harvesthq/chosen#2635]
Bower-chosen 1.4 contained the minified version of the chosen assets (css and js), but after 1.5, the minified versions are missing.

**Comment by stof** [comment]
This was done intentionally in https://github.com/harvesthq/chosen/pull/2306

**Comment by fracsi** [comment]
My opinion is that both versions should be there, as stated in the other thread comment: https://github.com/harvesthq/chosen/pull/2306#issuecomment-90440115

**Comment by koenpunt** [comment]
As long as they're not in the `bower.json`, that shouldn't be a problem, I think. https://github.com/bower/spec/blob/master/json.md#main
