### ISSUE TITLE
"transform-style: preserve-3d" mess up with .chosen-results

### ISSUE THREAD

**Issue by DudeSJ** [harvesthq/chosen#2637]
### Description

If you place the css style "transform-style: preserve-3d" to the parent element of the "select" element, the ul.chosen-results element lost its z-index.

Normal:
![image](https://cloud.githubusercontent.com/assets/20208294/16456543/1c43cfd6-3e10-11e6-94bd-4074d98e11f9.png)

With the css transform-style:
![image](https://cloud.githubusercontent.com/assets/20208294/16456500/ef9381d4-3e0f-11e6-8b5f-8bc723d018a5.png)

### Steps to reproduce

Access the [https://harvesthq.github.io/chosen/#selected-and-disabled-support](url) and edit the HTML of the page like the image:

![image](https://cloud.githubusercontent.com/assets/20208294/16456371/90a86554-3e0f-11e6-8eef-f4366f567d68.png)

Just place: **style="transform-style:preserve-3d"** on the parent of "select" element and after it, open the results of that combo box.

I tried on other browers with their compatible css lines (-webkit, -ms, -o, etc) and the same result.

### Environment

  - **Chosen Version**: v1.6.1

  - **jQuery or Prototype Version**: jQuery v2.1.1

  - **Browser and Version**: Chrome 51.0.2704.103m and IE 11.0.9600

  - **OS and Version**: Windows 7

### Additional information

Tried to change the z-index of the ul.chosen-results element to 999999 and the other elements to lower (so the content comes up front) and no success. 
Without the Chosen attributes (only with the plain select) with works great.

**Comment by koenpunt** [comment]
Just wondering why you want to apply `transform-style:preserve-3d`?

**Comment by DudeSJ** [comment]
Because I wanted to make the parent DIV of the Chosen element to rotate 180º within a button click (have an animation). I had that issue but found the solution.

The elements that will appear behind the Chosen results must have:
z-index:-1;
position:relative;

If the elements stay the same, try instead to apply to their parents.
