### ISSUE TITLE
what should i do to reset the chosen's value_text？

### ISSUE THREAD

**Issue by dzlishen** [harvesthq/chosen#2640]

**Comment by FPerisa** [comment]
I'm not sure what you mean exactly, but you could update it with
`$("#form_field").trigger("chosen:updated");`
or rebuild:
`$(#form_field).chosen("destroy").chosen(options)`
(thanks to @ComeBurguburu for the rebuild solution in this [comment](https://github.com/harvesthq/chosen/issues/2232#issuecomment-74040455) which helped me!)

**Comment by koenpunt** [comment]
@dzlishen could you elaborate on what you mean?
