### ISSUE TITLE
Chosen breaks behaviour of siblings when in <label>

### ISSUE THREAD

**Issue by utek** [harvesthq/chosen#2646]
Using chosen on `select` without label inside `label` for different input breaks behaviour of non "chosen" elements. 

### Steps to reproduce

Tell us how to reproduce this issue.

1. Create select inside label

2. add additional form element inside that label

3. Chosen select

4. additional form element is loosing focus

Working demo 

https://jsfiddle.net/goy40mts/

### Additional information

issue is with this line https://github.com/harvesthq/chosen/blob/master/coffee/chosen.jquery.coffee#L266

I've fixed it using custom `chosen.jquery.js` in our project with mentioned line changed:

`@form_field_label = @form_field_jq.parent().find("label")`

**Comment by koenpunt** [comment]
Nesting elements this way isn't allowed according to the html spec. 

![image](https://cloud.githubusercontent.com/assets/351038/18542020/e7c86aa4-7b28-11e6-8e5c-0a55d479e22f.png)
