### ISSUE TITLE
Single Select with Groups order gets rearranged when we select  more than one value from group and enter random text(text with add option) 

### ISSUE THREAD

**Issue by santosh646** [harvesthq/chosen#2647]
[chosen example.zip](https://github.com/harvesthq/chosen/files/361510/chosen.example.zip)
1.attached is the example zip using the 1.5.1 with create jquery 1.5.1 version
2.try to add the group with more than one value and random text order gets rearranged refer below image
![selected](https://cloud.githubusercontent.com/assets/20439573/16804360/1b9a9488-4929-11e6-82ed-5366a627f919.PNG)
3.when we select the text order gets rearranged  as below
![groups_rearranged](https://cloud.githubusercontent.com/assets/20439573/16804441/762d4e18-4929-11e6-8415-d0a6c29f1565.PNG)
4.anyhelp would be appreciated

**Comment by koenpunt** [comment]
This issue should be created at my fork, as this is about option adding; https://github.com/koenpunt/chosen/issues/new
