### ISSUE TITLE
issue when usin bootstrap modal esc keypress

### ISSUE THREAD

**Issue by wkjesus** [harvesthq/chosen#2653]
i found a solution , hopes implement on future release; 
the situation is when using bootstrap modal, and shows chosen item, if press esc key, both modal and chosen close,,, expected only chosen hide, and modal stills i modifed 
i use stoppropagation.
the calls con keyup_checker and keydown_checker and put this lines:
[keydown_checker]
case 27:
          if (this.results_showing) {
            evt.stopPropagation();
            this.results_hide();
          }
          return true;

[keyup_checker]
case:27
if (this.results_showing) {
            evt.stopPropagation();
            this.results_hide();
          }
          return true;

**Comment by koenpunt** [comment]
Would you mind creating a pull request for this? Thanks!
