### ISSUE TITLE
Issue on tablets with not being able to select items

### ISSUE THREAD

**Issue by bigc9heese** [harvesthq/chosen#2654]
Hi,
There appears to be an issue with some over the newer Android tablets and Chosen.
Using a Galaxy Tab S2 (Android 5.0.2; SM-T815Y, Chrome 51.0.2704.81), and using the main demo page (https://harvesthq.github.io/chosen), you can open the dropdown, but you can't select any of the items - they highlight momentarily, but then dehighlight. Basically, the control is useless.

On an older tablet (Android 4.2.2; GT-P5110 - but same Chrome version), it works fine, just like on a desktop.

I think the touchmove event is causing the problem - the newer tablet is firing those events in overtime, whereas I don't think the older one is.
I've added 
$('.chosen-container .chosen-results').off('touchmove.chosen');
to my project where the problem is also occurring, and that seems to have solved the issue for me - I'm not sure how good a solution that is, but it solves a user complaint for now.
Hopefully you can advise further.

Stuart

**Comment by koenpunt** [comment]
Not sure how to handle this because it is so specific to a single type of tablet. Could it be a bug in the OS of the tablet?

**Comment by ThomasPeoLeo** [comment]
Hello ! This post have been closed, but we still don't have any solution, do we ????

Thnaks !

**Comment by koenpunt** [comment]
If I'm correct this is already being tracked in https://github.com/harvesthq/chosen/issues/2289
