### ISSUE TITLE
How to remove all selected nodes from multi

### ISSUE THREAD

**Issue by nodesocket** [harvesthq/chosen#2670]
How to remove all selected nodes from a multiple select using version `0.10.0`? Note, we cannot upgrade Chosen, as it would break lots of dependent code.

Trying:

````
<select id="tags" name="tags[]" multiple="multiple" class="span6" data-placeholder="Select tags...">
````

````
$("#tags option").prop("selected", false);
$("#tags").trigger("liszt:updated");
````

While the native select seems to clear out the selected values, the values are still present in the div display boxes.

**Comment by koenpunt** [comment]
Chosen 0.10.0 is about 3 years old. We generally provide support for these old versions. 
However, the code snippet you posted seems right. Maybe upgrading to 0.10.1 could fix your issue?

**Comment by koenpunt** [comment]
But I did a quick test, and the problem because the first option (the empty one) is deselected too. 

It should work if you use it like this:
```js
$("#tags option:not(:first)").prop("selected", false);
$("#tags").trigger("liszt:updated");
```

**Comment by nodesocket** [comment]
This works, but leaves the first option selected. I'd like to remove all options.

**Comment by koenpunt** [comment]
The first should be an empty option. But this is probably related: #2513

**Comment by nodesocket** [comment]
Same behavior, leaves options using:

````javascript
$("#tags").val([]).trigger("liszt:updated");
````

I'm just looking for a hack solution, since I know the version of chosen I am using is super old and crusty.

![screen shot 2016-09-16 at 1 33 56 pm](https://cloud.githubusercontent.com/assets/523312/18600413/520027f6-7c12-11e6-8f66-64b702bc11c4.png)

**Comment by koenpunt** [comment]
If the same still happens with the current version of Chosen, we can look into it. Otherwise this is probably already fixed along the way.

**Comment by koenpunt** [comment]
Closing because this issue has been open for over 2 weeks now. My previous comment still applies.
