### ISSUE TITLE
How to show only filtered options

### ISSUE THREAD

**Issue by tjod** [harvesthq/chosen#2671]
An issue for my client is this: they never want to reveal all options.
AFAIK, this is the default initial behavior for Chosen.

So, is it possible to start with an empty option list and have the
search use, say a JS array (of option-text, option-value and optgroup-text),
and then populate the Chosen list with the successful searches?

I've not used Chosen, so I have no version info to report.
But with the demo and glowing reports, it seems like I want to.

Thanks,
TJ O'Donnell

**Comment by koenpunt** [comment]
You could probably override the CSS classes so that the options are initially `display: none;`, and are updated to `display: block;` when the option is a valid result
