### ISSUE TITLE
There's a chosen_v1.6.2.zip inside chosen-1.6.2.zip

### ISSUE THREAD

**Issue by hkirsman** [harvesthq/chosen#2672]

**Comment by hkirsman** [comment]
My bad. I guess it is supposed to be there.

**Comment by stof** [comment]
no, I don't think so. This is a failure of the gitignore rule IMO (the ignore rule is covering only ``chosen.zip``).

@koenpunt you are the one committing this archive in 6da777d83b1aa900123225ac4ff8216b65313431. Was it indeed a mistake ?

**Comment by koenpunt** [comment]
Hm, that would be my mistake yes. Currently on vacation, so if someone else can submit a PR for deleting it that would be great.

**Comment by tjschuck** [comment]
Au revoir, ZIP.

Thanks for the heads up, @hkirsman !
