### ISSUE TITLE
chosen('destroy') actually creates a chosen element

### ISSUE THREAD

**Issue by crh3675** [harvesthq/chosen#2674]
Create a select box:

    var s = $('<select><option value="1">One</option></select>');

Append to body:

    $(document.body).append(s);

Call destroy (even though we know it was never applied):

    s.chosen('destroy');

What happens? A &lt;div.chosen-container&gt; gets created for the &lt;select&gt;.

Expected behavior, chosen ignores the "destroy" because it really doesn't exist in the first place.

**Comment by koenpunt** [comment]
I believe this was already fixed, what version are you using?

**Comment by crh3675** [comment]
Sorry, behind the times with 1.2.0.  What version might address this issue?  We have also added the feature to allow multi-select with options open so I don't want to lose that with an update.

**Comment by koenpunt** [comment]
1.2.0 is really old. I'm currently on mobile, but you can try searching for "destroy" in the closed pull requests

**Comment by tjschuck** [comment]
@koenpunt is right — this was fixed in [version 1.5.0](https://github.com/harvesthq/chosen/releases/tag/v1.5.0) — original issue is #2095, and the fix was #2446.
