### ISSUE TITLE
Pressing the "x" while searching does not reset the dropdown

### ISSUE THREAD

**Issue by fimbriaco** [harvesthq/chosen#2675]
While searching on the dropdown with IE 11 an "x" shows up next to the magnifying glass. If I press the "x" the dropdown doesn't reset the options (like "Delete" does), but only clears the search box.

The "x" doesn't show up in Chrome.

I can even reproduce the issue in the first dropdown on https://harvesthq.github.io/chosen/ The one that shows the country of the world.

Is there any way to hide the "x" in IE11?

Thanks for your help.

**Comment by fimbriaco** [comment]
Never mind :-) I have fixed the issue with 

::-ms-clear
{
    display: none !important;
}

It's an issue with IE

**Comment by tjschuck** [comment]
Thanks for following up, @fimbriaco !
