### ISSUE TITLE
Select an <option> via Jquery ?

### ISSUE THREAD

**Issue by NexusFred** [harvesthq/chosen#2676]
Hello,

I need to select an option via Jquery.
Usually I use something like this $( "#myMenu option[value='myOptionValue']" ).attr("selected", "selected"); but with chosen it's not working. Any ideas ?

Thanks

**Comment by tjschuck** [comment]
You just need to call `"chosen:updated"` on your select after updating it.  Something like

```javascript
$("#myMenu").trigger("chosen:updated");
```

Docs here: https://harvesthq.github.io/chosen/#change-update-events

**Comment by NexusFred** [comment]
Thanks. 
Newbie mistake (RTFM) :*)
