### ISSUE TITLE
style for chosen selectbox not working on mobile

### ISSUE THREAD

**Issue by lemonkazi** [harvesthq/chosen#2677]
Hi I placed chosen library in my select box. It displaying fine in desktop chrome browser. But when I try to run that in my android set with chrome browser style not working. 
[image1](http://i.stack.imgur.com/81hBv.png)
Here is my sample site link http://notundeal.com/aherns/ahernsshopping-v.2.html

Also here my list when switch to another tab according to functionality it should display selected "localStorage" in just below window but email and sms button. It aslo displaying fine in desktop but not working in android set it becomes blank.
[image2](http://i.stack.imgur.com/dO5jo.png)
I am confused why this not working in android mobile. Please help me here why this functionality different in mobile.

**Comment by mateuspv** [comment]
Hi, chosen is disabled by default in iOS, android and other devices, please take a look at this pull request for more information: https://github.com/harvesthq/chosen/pull/1388

**Comment by tjschuck** [comment]
Yep — Chosen is disabled on mobile.  Closing per @mateuspv's answer.

**Comment by kathirr007** [comment]
Hi, Do we have any solution to enable chosen on mobile devices.

Thanks.

**Comment by tjschuck** [comment]
@kathirr007 There's no built-in option.  You can modify your copy of Chosen if you'd like to change how it works.  [`browser_is_supported` is the method you're looking for](https://github.com/harvesthq/chosen/blob/76d144673e2f012c810468f2e79a29a99f72f551/coffee/lib/abstract-chosen.coffee#L367-L377).

**Comment by nickmarkos49** [comment]
Here is link for mobile support.
https://realize.be/blog/mobile-support-chosen#comment-4906

**Comment by processor50** [comment]
> Here is link for mobile support. https://realize.be/blog/mobile-support-chosen#comment-4906





https://stackdev.space/questions/some-android-devices-experience-compatibility-issues-with-ajax-while-others-are-able-to-run-it-without

**Comment by imob-system** [comment]
> Here is link for mobile support. https://realize.be/blog/mobile-support-chosen#comment-4906

Thanks dude! i'm using it in 2025
