### ISSUE TITLE
select element too narrow to fit choices

### ISSUE THREAD

**Issue by dbeusee** [harvesthq/chosen#2681]
I'm evaluating using chosen for my bugzilla site, but this issue prevents me from going forward with it.  I have a simple test case at: [http://jsfiddle.net/Lgo83p4s/6/](http://jsfiddle.net/Lgo83p4s/6/)

As you can see, all you get when you go to the above page is ... because the width is too small.  

I modified the test case slightly to show how a value is wrapped due to the same thing:
[http://jsfiddle.net/Lgo83p4s/7/](http://jsfiddle.net/Lgo83p4s/7/)

In this second case, the last value wraps the last character on the next line for me at 150% zoom.

It should be calculating the size based on the max length of the list items, compensating for other factors like the browser's zoom level (I keep mine at 125% or 150%), different windows xpi scale factor setting (mine is at 175%), browser font size (small, medium, etc), etc..  It should use extra spacing if it cannot compensate for these factors.

You can see the versions of jquery and chosen from the fiddle test case.

I am using chrome Version 52.0.2743.116 m on windows 10 x64.

**Comment by tanloverluke** [comment]
You can overcome this with css: `.chosen-select {padding: 0 10px;} `
[http://jsfiddle.net/Lgo83p4s/8/](http://jsfiddle.net/Lgo83p4s/8/)

**Comment by dbeusee** [comment]
That work-around works well, thank you!  I made a new test case, and it includes this work-around ([https://jsfiddle.net/05n6x818/2/](https://jsfiddle.net/05n6x818/2/)), but there are more problems, and I find that this project doesn't get enough attention as evident by the number of issues that remain for years, some of which I have encountered, and I'm giving up.  The biggest show-stopper for me is lack of support on mobile devices like andriod phone.  I'm unfortunately forced to go back to jquery combobox for when I need search capability (with long lists) and will use the normal SELECT element for small lists.  The old test cases will no longer work, because I will take down the referenced resources from my site.  The new test case uses harvesthq hosts resources.  I would consider this issue closed when a permanent fix has been released into a new version.

**Comment by koenpunt** [comment]
The word wrap can be prevented using CSS; `white-space: nowrap`. But still, it can always happen that the content takes up more space than the results can fit, and this can also happen to a native select. 

So in case of the Chosen select, your best bet is customizing the CSS to your needs.

**Comment by dbeusee** [comment]
What word wrapping?  white-space: nowrap doesn't fix this test case.  I'm not sure you even looked at it.  Plane and Car are small values.  There's no reason for the ... when Chosen just has to have a min width to fit small values.  It shouldn't be necessary for your users to struggle with such a simple thing that should work out of the box.
