### ISSUE TITLE
Chosen input stealing focus on page load

### ISSUE THREAD

**Issue by Mech117** [harvesthq/chosen#2683]
Using Chosen with JQuery and Salesforce Visualforce, initializing it on a selectlist, the input field of the chosen element steals focus and causes the dropdown list to appear. This happens even if we try to assign focus to other elements on the page after chosen is loaded. This also happens even if the chosen element is not the first input on the page. 

EDIT: this seems to only be happening on multi-select picklists. Single-select picklists don't automatically open. 

### Steps to reproduce
  1. Create a Salesforce Visualforce page with a selectlist. Add other inputs above and below the select list. 

  2. In the javascript ondocumentready, initialize chosen on the select list

  3. Load the page. When chosen finishes initializing, the input field for chosen will have focus and the dropdown will appear. 

### Expected behavior

Chosen initializes, but does not steal focus and the dropdown does not appear without the element being clicked on. 

### Actual behavior

Chosen initializes, steals focus, and the dropdown appears. 

### Environment

  - Chosen 1.4.2 (EDIT: tried updating to 1.6.2, same issue)

  - JQueryUI 1.12.0

  - JQuery 2.2.3

  - Salesforce Visualforce 37.0

  - Running on Google Chrome for Mac

**Comment by tjschuck** [comment]
Chosen 1.4.2 is about a year and a half old.  Does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

**Comment by Mech117** [comment]
Tried updating to 1.6.2, same issue

**Comment by koenpunt** [comment]
Would it by any change be possible to reproduce this outside of Salesforce Visualforce? For example in [a fiddle](https://jsfiddle.net)
