### ISSUE TITLE
Get select value through chosen

### ISSUE THREAD

**Issue by ricardocosta89** [harvesthq/chosen#2684]
Prior note: I tried looking for a way to get the selected value through `chosen` instead of the `<select>` but couldn't find anything.

As of now, if you have a form using chosen and your frontend validation depends on a `<select>` that has been `chosen`ed, a malicious user might bypass the UI selected value by directly changing the `select` value. When performing validation, getting the value using `val()` will return an option different from the one selected in chosen.

### Steps to reproduce

Select an option through UI:
<img width="771" alt="screen shot 2016-09-03 at 16 24 28" src="https://cloud.githubusercontent.com/assets/11922336/18225773/8b9ec28e-71f3-11e6-9059-465bedd68da3.png">

Verify the current value:
```
$('.chosen-select').val()
"United States"
```

Change the value using `val()`:
`$('.chosen-select').val('Afghanistan')`

Verify that the UI did not change:
<img width="996" alt="screen shot 2016-09-03 at 16 33 14" src="https://cloud.githubusercontent.com/assets/11922336/18225794/2ef17058-71f4-11e6-82d0-b9613b2e2653.png">

The returned value is something different than the UI:
```
$('.chosen-select').val()
"Afghanistan"
```

This issue is reproducible with the [Chosen demo page](http://harvesthq.github.io/chosen/).

### Expected behavior

There should be a way to get the selected value **after** matching the UI displayed value with the behind-the-scene `<select>` option.

### Actual behavior

Additional lookup is required after getting the `<select>` value to make sure it matches the UI selection.

### Environment

  - **Chosen Version**: Chosen v1.4.2

  - **jQuery or Prototype Version**: v1.8.2

  - **Browser and Version**: Chrome 53.0.2785.89 (64-bit)

  - **OS and Version**: OS X 10.11 El Capitan

### Additional information

Potential solution: Add a method to chosen to get the value after the lookup is made to match the selected UI with the value in `<select>`. This would make it harder to bypass the UI selection.

**Comment by koenpunt** [comment]
To make Chosen reflect the changes of the select, you have to trigger `chosen:updated`. This is documented here: https://harvesthq.github.io/chosen/#change-update-events
