### ISSUE TITLE
show options out of iframe bounds

### ISSUE THREAD

**Issue by alirezaimi** [harvesthq/chosen#2688]
Hi
I have a problem with overlapping elements inside of an iframe to out of that iframe, 
natural select by default show options out of iframe and every elements that under it , but when use this module on selects the result always show inside of iframe bounds, 

this is chosen one : 
![1](https://cloud.githubusercontent.com/assets/1029949/18542747/ad2ddb68-7b41-11e6-9bde-2c34616a6e36.png)
and this is natural select : 
![2](https://cloud.githubusercontent.com/assets/1029949/18542752/aef70a46-7b41-11e6-8a09-cf73c6f02e5b.png)

How can i show options like select tag out side of iframe bounds ?

thanks.

**Comment by koenpunt** [comment]
Content can't extend the bounds of the iframe. The difference with a native select is that it's, ehm, native. So this isn't something we can fix.
