### ISSUE TITLE
"Cannot read property 'length' of undefined" error

### ISSUE THREAD

**Issue by shakedg** [harvesthq/chosen#2698]
I downloaded the project's zip files to use it in my website design. 
I also added this code line in my HTML home page (as without it the Chosen code wasn't recognized, I hope this is what I should've done):
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.js"></script>

And now when I run it, I get an exception saying "Cannot read property 'length' of undefined". It refers to this part, "this.form_field.options.length", in the "chosen.jquery.js" file (it is in the function assigned to the "Chosen.prototype.results_build" variable).

What is the issue here? 

Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. This is the first step

  2. This is the second step

  3. Further steps, etc.

Additionally, please link to a working demo that shows the issue so we can attempt to reproduce.  You can use [this template](https://jsfiddle.net/5v3v353z/) as a base.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

### Expected behavior

Tell us what should happen.

### Actual behavior

Tell us what happens instead.

### Environment

  - **Chosen Version**:

  - **jQuery or Prototype Version**:

  - **Browser and Version**:

  - **OS and Version**:

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by koenpunt** [comment]
Hi @shakedg, the issue template isn't there for nothing, so please use it as described. Because now we can only guess what's happening. And so my guess would be; you're not applying Chosen to a select but to another element. 
Please update the issue and I'll be happy to reopen.
