### ISSUE TITLE
Scroll is very slow

### ISSUE THREAD

**Issue by manovraresoft** [harvesthq/chosen#2699]
Scroll is super slow. When a user Clicks scroll once, then scroll one line, if the user spins the scroll wheel make it scroll more times then the "tick"

### Expected behavior

Like any other select box or webpage when a fast scroll is registered it scrolls further than just on line per registered "scroll tick"

### Actual behavior

If I spin the scroll wheel fast and say it registers 10 scroll clicks on the wheel it will only scroll 10 lines.

### Environment
PHP
Most recent Chosen and jQuery

**Comment by koenpunt** [comment]
Could it be the same issue as https://github.com/harvesthq/chosen/issues/2622 ?

**Comment by manovraresoft** [comment]
This is not closed.
