### ISSUE TITLE
Unexpected token < when load chosen

### ISSUE THREAD

**Issue by QuentinVaut** [harvesthq/chosen#2708]
Hello, 

I use chosen plugin with ASP.NET, I use it in two pages.

In one page the plugin work fine but in another I've this error : 

![Image of Yaktocat](http://image.noelshack.com/fichiers/2016/39/1475141186-chosen-bug.png)

I use the same method for load it.

In my working page : 

    <head id="Head2" runat="server">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="/Styles/plugins/chosen/chosen.min.css">
    <script type="text/javascript" src="/js/plugins/chosen/chosen.jquery.min.js"></script>
    <![endif]-->
    <asp:ContentPlaceHolder ID="HeadContent1" runat="server">
    </asp:ContentPlaceHolder>
   </head>

And is the same method in other page, I don't unterdsant why work in page but not in other.
I use master page for load my JS script.

The path for chosen is correct.

EDIT : When postback is occured, the plugin work fine, but when I load the page for the first time I've these errrors.

**Comment by stof** [comment]
Well, the dev tools are telling you that there is a syntax error something. It may be the cause for chosen not being defined after that. You should debug this issue.

And I never used ASP.NET, so I cannot help you for that

**Comment by QuentinVaut** [comment]
This error is caused by chosen when I remove the script tag for load chosen there are no errors except the error chosen is not a function because is not load.


I can not find the error for the syntax error.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.
