### ISSUE TITLE
Bug: vertical scrollbar don't show in ipad

### ISSUE THREAD

**Issue by supercreator** [harvesthq/chosen#2720]
Chosen work normally in desktop  but when i view it in ipad, the dropdown lists don't show scrollbar although there are many rows . User can't scroll down too.

![img_0472](https://cloud.githubusercontent.com/assets/21234822/19218926/17b92518-8e30-11e6-9330-1ff512de8469.PNG)

**Comment by koenpunt** [comment]
This issue is already being tracked in https://github.com/harvesthq/chosen/issues/2289

**Comment by supercreator** [comment]
Thank you Koenpunt
