### ISSUE TITLE
Some of the chosen multi-select drop-downs are freezing(could not select options) after changing the year of the datepicker.

### ISSUE THREAD

**Issue by acnice** [harvesthq/chosen#2728]
Environment : jQuery UI 1.12.1 jQuery Chosen plugin v1.6.2 Browsers: Chrome v53.0.2785.143, IE 9, edge

The html code for the drop down looks like below;

<div class="dv-prizemoney-search search-item-margin">
   <span class="search-title">Prize Money</span>
   <select size="1" name="ctl00$MainContent$lstPrizeMoney" multiple="multiple" id="ctl00_MainContent_lstPrizeMoney" tabindex="4" data-placeholder="Choose a Prize Money" class="lst-prizemoney chosen-select" style="width:100%;">
      <option selected="selected" value="0">All Prize Monies</option>
      <option value="&lt;= $5,000">&lt;= $5,000</option>
      <option value="$5,000 - 10,000">$5,000 - 10,000</option>
      <option value="$10,000 - 20,000">$10,000 - 20,000</option>
      <option value="$20,000 - 30,000">$20,000 - 30,000</option>
      <option value="$30,000 - 50,000">$30,000 - 50,000</option>
      <option value="$50,000 - 75,000">$50,000 - 75,000</option>
      <option value="$75,000 - 100,000">$75,000 - 100,000</option>
      <option value="> $100,000">&gt; $100,000</option>
   </select>
</div>

 And input box for date picker looks like as below;

<div class="hdn-to-date"><input type="hidden" name="ctl00$MainContent$txtToDate" id="ctl00_MainContent_txtToDate" value="16/01/2017" /></div>

Jquery for datepicker:

 $("#ToDate").datepicker({
     dateFormat: 'dd/mm/yy',
     changeMonth: true,
     changeYear: true,
     yearRange: "2016:2020",
     minDate: startDateFrom,
     onSelect: function(dateText) {`enter code here`
         $('.hdn-to-date').find(':input').val(dateText)
     }
 });

Chosen Settings:
var config = {
    '.chosen-select': {},
    '.chosen-select-deselect': {
        allow_single_deselect: true
    },
    '.chosen-select-no-single': {
        disable_search_threshold: 10
    },
    '.chosen-select-no-results': {
        no_results_text: 'No results found!'
    },
    '.chosen-select-width': {
        width: "95%"
    }
}
for (var selector in config) {
    $(selector).chosen(config[selector]);
}

Change year event in the Jquery UI plugin(line number 736):
_selectMonthYear: function(id, select, period) {
  var target = $(id),
  inst = this._getInst(target[0]);

  inst["selected" + (period === "M" ? "Month" : "Year")] =
  inst["draw" + (period === "M" ? "Month" : "Year")] =
  parseInt(select.options[select.selectedIndex].value, 10);

  this._notifyChange(inst);
this._adjustDate(target);
},

When changing the year from the date picker this event receives a wrong element for the "select" parameter(I received chosen-select object instead).

I would like if anyone can assist in this matter.

Full Question:[stackoverflow]( http://stackoverflow.com/questions/40066162/jquery-chosen-v1-6-2-multi-select-abnormal-behaviour-with-jquery-ui-datepicker
)

**Comment by koenpunt** [comment]
As this is a too specific (and badly formatted) question, I'm going to close this.
However, I've added a comment on your SO post.

**Comment by acnice** [comment]
Sorry for the badly formatted question. I have replied to SO post.

Whenever changing year/month from "To" datepicker then it will affect to 2nd chosen dropdown(Prize Money). Is it happening due to datepicker z-index overlapped by chosen-drop div? Following is the test URL

http://t.racing.racingnsw.com.au/FreeFields/chosen.aspx
