### ISSUE TITLE
Select multiple order

### ISSUE THREAD

**Issue by iLenTheme** [harvesthq/chosen#2735]
Hello, when a select this order: AA, BB, CC but selecting the multiple choose well the CC, AA, CC, when values ​​get this if it respects the order you select them?

**Comment by koenpunt** [comment]
Options are sent to the server as they are presented in the source, so even if you select them in a different order using Chosen, the order will remain as it's shown in the source.

**Comment by tjschuck** [comment]
Just to clarify @koenpunt's answer a little bit, "options are sent in the order they appear in the source" isn't _Chosen's_ behavior per se, it's the behavior of the actual underlying `select`.  Chosen strives to be a drop-in visual replacement for native `select`s, and does its best to maintain the native behavior in most instances.  This is one of those instances.

**Comment by iLenTheme** [comment]
But I think you should see an option to obtain the values ​​of the order to be selecting, I do not think it's something that breaks the concept, it is simply a necessity.
