### ISSUE TITLE
The Prototype script is missing a class

### ISSUE THREAD

**Issue by patstuart** [harvesthq/chosen#2741]
The Prototype script is missing the Template class, which causes the constructor to throw an error.

### Steps to reproduce

  1. Call the prototype with a select element

Working demo (see the second error): https://jsfiddle.net/p9wq6efy/4/

### Expected behavior

The class should instantiate without error

### Actual behavior

An error is thrown:
`ReferenceError: Template is not defined`

### Environment

  - **Chosen Version**: 1.6.2

  - **jQuery or Prototype Version**: Prototype

  - **Browser and Version**: Chrome 54

  - **OS and Version**: Windows

### Additional information

N/A

**Comment by koenpunt** [comment]
You have not included the prototype library in your fiddle.

**Comment by koenpunt** [comment]
To elaborate, the Chosen fiddle template is for the jquery version of Chosen. If one want to create a fiddle for the prototype version, they have to include the required files themselves.

**Comment by patstuart** [comment]
Please go back and look again. It includes Chosen.proto.js but not the jQuery version. I did include jQuery so I could manipulate the DOM.The documentation says nothing ahout including any files other than proto.js and proto.css.

**Comment by koenpunt** [comment]
You're mixing prototypejs and jQuery, they are different libraries with similar purpose. Please have a look at http://prototypejs.org

**Comment by koenpunt** [comment]
> I did include jQuery so I could manipulate the DOM.

With prototypejs you can manipulate the DOM as well.

**Comment by patstuart** [comment]
You're right; I completely misunderstood. Sorry about that.
