### ISSUE TITLE
NPM module doesn't contain sprite image

### ISSUE THREAD

**Issue by fsparv** [harvesthq/chosen#2742]
### Steps to reproduce

Tell us how to reproduce this issue.

  1. Download package from NPM for version 1.6.2
  2. observe that only 2 files are received: chosen.css and chosen.jquery.js 
  3. Use downloaded files in application, observe failing http requests for css/chosen-sprite.css

Additionally, please link to a working demo that shows the issue so we can attempt to reproduce.  You can use [this template](https://jsfiddle.net/5v3v353z/) as a base.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

### Expected behavior

Package should be usable out of the box without separate downloads.

### Actual behavior

Package causes 404 errors when used unmodified.

### Environment

  - **Chosen Version**: 1.6.2

  - **jQuery or Prototype Version**: any

  - **Browser and Version**: npm not bower, github broke bower for automated builds with auth requirements.

  - **OS and Version**: any

### Additional information

Perhaps convert it to a data: uri is easiest? would seem to also solve #2347 too

**Comment by tjschuck** [comment]
@koenpunt This sounds similar to https://github.com/harvesthq/chosen/pull/2643 ?

**Comment by tjschuck** [comment]
Actually, the comments on #2641 sound even more closely related...

**Comment by koenpunt** [comment]
I just verified that the package contains the images, by creating a webpack example using Chosen from npm. You can see that here: https://github.com/koenpunt/chosen-webpack-example

What's your setup? How are you including the npm files?

**Comment by fsparv** [comment]
Hmm interesting. I'm using the ClientDependencies gradle plugin to fetch dependencies:
https://github.com/craigburke/client-dependencies-gradle

```
clientDependencies {
  installDir = "${buildDir}/npm" 

  npm {
    'patternfly'('3.5.1') 
    'jsog'('1.0.7')
    'moment'('2.10.6')
    'urijs'('1.18.1')
    'node-uuid'('1.4.6')
    'rangy'('1.3.0')
    'sortablejs'('1.4.0')
    'chosen-js'('1.6.2')
  }
}
``` 

That gets me this: http://s14.postimg.org/m2n1alor5/Screen_Shot_2016_10_27_at_2_46_58_PM.png

**Comment by koenpunt** [comment]
I think your copy task configuration excludes `.png` files:

https://github.com/craigburke/client-dependencies-gradle#the-copy-task

**Comment by fsparv** [comment]
hmm this seems to be true, though it would be more accurate to say that the default configuration for the plugin fails to include them... which is downright odd given that css and svg are listed. 

https://github.com/craigburke/client-dependencies-gradle/blob/master/src/main/groovy/com/craigburke/gradle/client/plugin/ClientDependenciesExtension.groovy#L50

Sorry looks like it's not your bug after all. Thanks for your time.
