### ISSUE TITLE
Button in Chosen <li>

### ISSUE THREAD

**Issue by s4m4n** [harvesthq/chosen#2744]
Is it possible to have one or some buttons per < li > with chosen?

something like http://jsfiddle.net/b22ww/2/

I tried appending to < li >'s with chosen:ready trigger but it seems that chosen rebuilds whole < ul > when we hover on the elements and the appended HTML will be gone.

Thank you

**Comment by koenpunt** [comment]
This is essentially about templating, which are already a lot of issues about. This is currently not possible, however maybe you can achieve the same by using a CSS pseudoselector and the content property?
