### ISSUE TITLE
Search for parameter problems

### ISSUE THREAD

**Issue by M7lrv** [harvesthq/chosen#2745]
I would like to ask if the value of parameters to the option to search, then how allocation? The default option seems to be the text of the search.

**Comment by tjschuck** [comment]
Sorry, @M7lrv, not sure I understand your question.  Can you clarify?

**Comment by M7lrv** [comment]
I am in China, may not be very good in English, I am sorry. The problem is that the type of search box search can only be set to search only the option value attribute or name attribute?

**Comment by tjschuck** [comment]
@M7lrv Ah, I understand now.  You're right — the only thing that is searched is the option's text, and there's no built-in way to change that currently.

"Searching by value" is another issue opened here: #800, so I'm going to close this as a duplicate of that one.

**Comment by M7lrv** [comment]
Do you want to update the version?
