### ISSUE TITLE
Mobile first option always selected

### ISSUE THREAD

**Issue by dadixon** [harvesthq/chosen#2746]
In mobile safari, the first option is always selected for multiple selection, every other time the dropdown is selected.

1. Go to the page on mobile device, it shows "0 Items"
2. Click select dropdown and choose any option. That option and the first option is selected and the selection says "2 Items"
3. Click select dropdown again and click "Done" and then it displays the correct number of selected items.

It goes through this loop every time you click the select dropdown.

Using the chosen 1.6.2

**Comment by vermosi** [comment]
You can fix the "2 items" by having a disabled first option that is a placeholder for the list. I'm having issues still with the "0 items" bit though.

**Comment by dadixon** [comment]
If you go to https://harvesthq.github.io/chosen/ on an iPhone in the Safari or Chrome browser and look at the second section where it says Multiple Select, it has "0 Items" at the start. When you click to choose an item, let's say United States, it then closes the list and says "2 Items" when I only chose 1. When I click to choose another item but don't select an item, I click done instead, that's when it shows the name of United States.

**Comment by tjschuck** [comment]
This has nothing to do with Chosen.  In fact, Chosen is disabled completely on iPhone.  What you're seeing when you go to https://harvesthq.github.io/chosen/ is just the native iOS multi select.  Note how the left and the right sides behave the same — the left side is supposed to be showing you a native select in the first place.

**Comment by tjschuck** [comment]
(More information about Chosen being disabled on mobile is on that very page down in the [FAQs — see the third item](https://harvesthq.github.io/chosen/#faqs).)
