### ISSUE TITLE
Chosen Dropdown Obscured

### ISSUE THREAD

**Issue by alvin1981** [harvesthq/chosen#2747]
I am seeing an issue where the chosen dropdown is displayed underneath another element instead of above it.  Here is a link to a screenshot which shows the chosen dropdown being displayed below an input text field:
https://drive.google.com/open?id=0B0LZG3TdZpKwM3ZBbEZtTTk4ZzQ
I am using chosen Version 1.6.2, chrome version 54.0.2840.71, windows 7.

How can I resolve this issue?  Thanks.

**Comment by koenpunt** [comment]
The input field that is overlapping Chosen probably has a `z-index` higher that Chosen's. As this is a problem with your implementation and not with Chosen, I'm going to close this issue.
