### ISSUE TITLE
Unexpected scroll reset bug

### ISSUE THREAD

**Issue by denfm** [harvesthq/chosen#2749]
If the (chosen) select is on the page or in the (div) block, which has a horizontal scroll, the scroll scrolls to the very beginning, when its values are selected by mouse.
Windows 10. Chrome 54.0.2840.71 m (64-bit)
Chosen 1.6.2
URL https://jsfiddle.net/9m1xhsLh/

**Comment by koenpunt** [comment]
This is already fixed on master, but not yet released.
