### ISSUE TITLE
Highlight when a value has been selected - Feature Request

### ISSUE THREAD

**Issue by PaulZahra** [harvesthq/chosen#2750]
My use case is that there are approximately 50 drop down lists in a page (for mapping imported data to system data) and it is easy to miss that you have not selected a value for one of them.

It would be useful for my situation but also a nifty feature to be able to change the color / background color of the text when an item has been selected... just to clarify I know you highlight the selected item when the list is expanded... but what I mean is when you expand the list, then choose an option and it collapses; then the selected text is displayed... to be able to change the background color / font color of that 'collapsed' selection.

**Comment by tjschuck** [comment]
That sounds like something too niche to be added to Chosen itself, but something you could pretty easily do on your own using Javascript and CSS.

Chosen is just an abstraction on top of a native `select`, so you can just observe the original `select` itself for state changes.  Using those change events, you can just add/remove styles as needed to the Chosen elements.
