### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by YvesHenri** [harvesthq/chosen#2756]
This is a question. I've been using chosen 1.6.1 for a while, but as far as I'm concerned, it doesn't work with mobile browsers, does it? If not, is there a hack we could do for it to work, like this: http://realize.be/mobile-support-chosen (this is version 1.1.0, though)?

**Comment by tjschuck** [comment]
Chosen is disabled on iPhone, iPod Touch, and Android mobile devices.  There's more information about that decision on https://github.com/harvesthq/chosen/pull/1388.  It's not likely to be reversed any time soon — sorry.
