### ISSUE TITLE
init and runtime disabled / enabled

### ISSUE THREAD

**Issue by standus** [harvesthq/chosen#2758]
How to make runtime disabled / enabled property like normal <select> ?
I need it for synchronization with another select.

**Comment by koenpunt** [comment]
You mean disabled options? As simple as setting the `disabled` property on the option:

```html
<select class="my-chosen">
  <option></option>
  <option disabled>Disabled option</option>
</select>
```

Or do you mean by runtime using javascript? Then it would be something like this:

```js
$('.my-chosen option:first').prop('disabled', true);
$('.my-chosen').trigger('chosen:updated');

**Comment by standus** [comment]
No I am talking about <select> not about <option>. Normal select is possible disable with attribute "disabled". Exists any way to disable/enable complete chosen?

**Comment by koenpunt** [comment]
```html
<select disabled class="my-chosen">
  <option></option>
  <option>Disabled option</option>
</select>
```

Or 

```js
$('.my-chosen')
  .prop('disabled', true)
  .trigger('chosen:updated');
```

**Comment by standus** [comment]
Yeah this:"chosen:updated" was solution, what I was looking for. Thx.

**Comment by rolandjlevy** [comment]
Hello, 

Is there a way of enabling chosen after it has been disabled? I have looked everywhere and tried these solutions but still can't get it to work. 

This works for disabling chosen:

```$('.my-chosen').prop('disabled', true).trigger('chosen:updated');```

But none of these work for re-enabling chosen:

```
$('.my-chosen').prop('disabled', false).trigger('chosen:updated');
$('.my-chosen').attr('disabled', false).trigger('chosen:updated');
$('.my-chosen').removeAttr('disabled').trigger('chosen:updated');
```

Can someone help? Thanks

**Comment by rolandjlevy** [comment]
Apologies, this actually works fine so no need to respond:

```$('.my-chosen').removeAttr('disabled').trigger("chosen:updated");```
