### ISSUE TITLE
Chosen plug cant display into bootbox dialog

### ISSUE THREAD

**Issue by hamzalla** [harvesthq/chosen#2759]
0
down vote
favorite
Hi I'm trying to include chosen plugin in my project it work perfectly in normal forms but when I'm in bootbox modal it won't display the problem came from z-index I tried some css but it doesn't work

please help me thanks

**Comment by koenpunt** [comment]
Please have a look at other issues concerning modal windows and z-index: https://github.com/harvesthq/chosen/search?utf8=%E2%9C%93&q=modal+z-index&type=Issues

As this presumably isn't an issue with Chosen itself (only with the specifics of the implementation), I'm going to close this.
