### ISSUE TITLE
Multiple chosenicon on the same page

### ISSUE THREAD

**Issue by TheMasterRoot** [harvesthq/chosen#2760]
use two selects whit chosenicon 

whem i change the select option on the first select ( in this select the icons arent showed ) in the second select the icons are changed to the icons that would be in first one

**Comment by koenpunt** [comment]
What icons are we talking about? Like the little arrow and magnifying glass?

**Comment by TheMasterRoot** [comment]
no the inside option icons
look the ss
![image](https://cloud.githubusercontent.com/assets/7121027/20794105/84288b08-b7b1-11e6-8afe-20c6f42d8015.png)
this first one show the second select

now this is the first whit diferent icons
![image](https://cloud.githubusercontent.com/assets/7121027/20794116/9be96f0a-b7b1-11e6-9be1-be28a8741bab.png)
full blank inf i choose any item om second select but if i schoose anu item on the first one this hapen
![image](https://cloud.githubusercontent.com/assets/7121027/20794127/b71c6214-b7b1-11e6-84ba-499b1bb992b4.png)

the icon from the first select is seted on the second

**Comment by koenpunt** [comment]
Icons like that are not supported by Chosen, so I'm guessing you using a modified version of the plugin, for which we can't give you support.

**Comment by TheMasterRoot** [comment]
what icon are suported?

**Comment by TheMasterRoot** [comment]
im using this plugin https://github.com/EmranAhmed/chosen-icon

**Comment by TheMasterRoot** [comment]
sory if i used it on the wrong place

**Comment by koenpunt** [comment]
> im using this plugin https://github.com/EmranAhmed/chosen-icon

Then you should open an issue on that repository ;)
