### ISSUE TITLE
FEATURE REQUEST - add verbatim text entries

### ISSUE THREAD

**Issue by Squid2112** [harvesthq/chosen#2763]
A nice additional feature to this component might be to add the ability for input text to be added to the container items, not just items found in the select list. Additionally, the ability to have the typed items added to the dropdown list (as an option).

For example, in my use, I would like to use this plugin to control the input of Contact/Email Address entry. That is, the user can select a Contact from the list (as this control can do now) but also include a verbatim email address typed in as well.

so, given a list like this:
  Contact 1
  Contact 2
  Contact 3

one could end with a selected result of
  Contact 1
  Contact 3
  joe@email.com

I will be modifying this control to fit my desired needs as described above, and if successful I will attempt to contribute my solution back to this project. Or, perhaps someone else will beat me to it :-) ...

**Comment by stof** [comment]
This is out of the scope of Chosen, as Chosen is just about enhancing the UI of a ``<select>`` tag

**Comment by koenpunt** [comment]
See #166 for a possible solution (not merged).
