### ISSUE TITLE
Tab Not Working in All Tested Browsers

### ISSUE THREAD

**Issue by LiamElliott** [harvesthq/chosen#2769]
Tabbing to single-select control is not functioning properly. Setting tabindex on elements has no effect. I have tried the the trick of setting the tabindex on the chosen-select ul classes to -1. Initially, the suggestion was to set this inside of the `Chosen.prototype.set_tab_index` function using the `div.chzn-container` selector, but it seems that neither `.chzn-container` nor `.chz-select` exist any longer. 

I see that the tab functionality works correctly on the demo page now, so I must be missing something. Where is the first place that I should look? I am using jquery-chosen with ASP.Net Web Forms and Bootstrap if that matters.

Thanks for helping out, I am really lost in this issue.

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there, particularly if you can provide a link to public page that shows the issue or a [Fiddle](http://jsfiddle.net).
