### ISSUE TITLE
Breaks scrolling in firefox with jQuery malihu-custom-scrollbar-plugin

### ISSUE THREAD

**Issue by Sergeniy** [harvesthq/chosen#2770]
https://github.com/malihu/malihu-custom-scrollbar-plugin

Breaks scrolling(up/down) in firefox

**Comment by stof** [comment]
Well, there is clearly not enough info to do anything with this issue ("breaks scrolling" does not describe what is broken for instance).

And btw, as this plugin is the one replacing native scrolling, it should probably be reported as an issue to the plugin instead. What chosen does works fine with native scrolling.

**Comment by Sergeniy** [comment]
> What chosen does works fine with native scrolling.

I understand, there is no bug in Chosen. But malihu-plugin conflicts with your Chosen, maybe add this information to FAQ - https://harvesthq.github.io/chosen/#faqs

**Comment by koenpunt** [comment]
Closed as this isn't an issue with Chosen itself
