### ISSUE TITLE
Option to not consider accent and other special letters like ç

### ISSUE THREAD

**Issue by mariovalney** [harvesthq/chosen#2774]
It could be a desireable feature to add a option (not default) to allow search not consider accents and anothers special letters.

It could be done with a simple replace in compare search engine function.

## For exemple:
"Mario" in search will match "Mário" in select options

## Implementation:
That's sounds a nice implementation: http://stackoverflow.com/a/18391901

**Comment by koenpunt** [comment]
There are already quite some issues and pull requests concerning this functionality. E.g. https://github.com/harvesthq/chosen/issues/536
