### ISSUE TITLE
Ability to add the user-typed value as a new choice

### ISSUE THREAD

**Issue by philfreo** [harvesthq/chosen#2781]
Let's say the user is looking for an item from a list and it's not found. They see:

<img width="379" alt="screenshot 2017-02-27 17 26 12" src="https://cloud.githubusercontent.com/assets/97612/23382883/f511b3da-fd11-11e6-9a94-a869525b6dd6.png">

In some cases it's desirable for the user to be able to "add" that item to the list as a valid option for that dropdown. I'd imagine an "Add this option" link in the "no results" screen, or at least a way to customize the "no results" screen in a way that makes implementing this easy.

Question: Is this a feature we'd want to support in the core? Alternatively, since currently `no_results_text` looks like it only supports plaintext so you couldn't add a link, would you be open to a PR where this is more flexible? Or, are you happy with the current ability to override `get_no_results_html`?

**Comment by GPrimola** [comment]
I had to do that today.
I'm currently maintaining a system where the first developer used chosen.js.
As had never seen any other tool I continue with it in the project, however today I felt the need for that. And so I did.

`no_results_text` does accept html text. I manage to put a link auto-passing it to the onclick function and manage the DOM to send the typed text for storage on the server.
Not so beautiful but doable.
So I felt the need to extend this tool. That's how I got here.
I'm gonna do it. I will need that functionality over the system.
I will make the pull request and you can decide if it's in or out.
By the way, thank you for the tool! It's really nice! :)

**Comment by koenpunt** [comment]
This has been discussed many times, and there's #166 that does this.

But don't expect it in master soon.
