### ISSUE TITLE
how to pass the values to javascript function when i select the values every time

### ISSUE THREAD

**Issue by vijaydvk** [harvesthq/chosen#2784]
Hi guys..
I use chosen for page filter option from MySQL

I want to know how to pass the values to javascript whenever I select the values from choosen

Thanx.

**Comment by koenpunt** [comment]
As you would do with a normal select; with a change handler:

```js
$('select').on('change', function() {
  alert($(this).val());
});

**Comment by vijaydvk** [comment]
thnx mate. It works Fine..
