### ISSUE TITLE
The problem of chinese option search

### ISSUE THREAD

**Issue by battlesteed** [harvesthq/chosen#2791]
just like the picture,the chinese option can only be searched by the first word ,  can you please fix it or tell me how to fix it ?

[the picture uploaded fail click here to see picture](http://pan.baidu.com/s/1minwHFq)

**Comment by moliao5d** [comment]
just set the search_contains option to true, like  $(".chosen-select").chosen({search_contains:true})

**Comment by battlesteed** [comment]
thank you
