### ISSUE TITLE
TypeError: this.selected_item.bind is not a function

### ISSUE THREAD

**Issue by nekromoff** [harvesthq/chosen#2797]
```
 <label for="organization_id" class="control-label">Organization id</label>
        <select class="form-control" id="organization_id" name="organization_id"><option value="1">ratione</option><option value="2">ut</option><option value="3">iste</option><option value="4">nihil</option><option value="5">nulla</option><option value="6">maiores</option><option value="7">unde</option><option value="8">impedit</option><option value="9">et</option><option value="10">sed</option><option value="11">minus</option><option value="12">vitae</option><option value="13">quia</option><option value="14">aut</option><option value="15">aut</option><option value="16">itaque</option><option value="17">pariatur</option><option value="18">debitis</option><option value="19">quo</option><option value="20">cupiditate</option></select>    
```

`  $('#organization_id').chosen();`

**Comment by Isg90** [comment]
you use jquery older 3.0 version.
As of jQuery 3.0, .bind() has been deprecated. It was superseded by the .on() method.
http://api.jquery.com/bind/
Just replace all bind (to on) and unbind (to off) methods from chosen.jquery.js

**Comment by nekromoff** [comment]
Actually, I am using the JQuery version 3.1.1 and Chosen 1.6.2 that was
latest at the time of downloading.
I'll replace the methods though, but you should mention this on GitHub if
the version does not support the newest JQuery.

**Comment by nekromoff** [comment]
Also, I check your latest 1.7.0. release, but it does not a contain a any actual JS file to use.

**Comment by stof** [comment]
chosen is currently not compatible with jQuery 3 without using the jQuery Migrate plugin. See #2729.

I'm closing this issue as duplicate
