### ISSUE TITLE
New version (1.7.0) - Where is the actual js file?

### ISSUE THREAD

**Issue by flattt** [harvesthq/chosen#2800]
Hi,
I can't find the js file in the new release under /public/
(index.html is referring to an unexisting chosen.jquery.js)
Is it possible that you missed it?
Thanks.

**Comment by kixes** [comment]
from what I can tell it is located here --> https://github.com/harvesthq/chosen-package

**Comment by flattt** [comment]
@kixes It says "lastest commit 2 months ago"
1.7.0 was released 7 days ago

**Comment by tjschuck** [comment]
Whoops!

@koenpunt It looks like you forgot to include the built version on https://github.com/harvesthq/chosen/releases — there are only the source code downloads there.

**Comment by flattt** [comment]
Also, the new feature that everyone has been waiting for (hide_results_on_select = false) does not seem to work :/
I can give more details but frankly you can simply implement the latest version and see that it is not working. 

	INPUTSELECTOR.chosen({
	  hide_results_on_select: false, //Will keep the dropdown open when selecting an option 
	  hide_results_on_deselect: false, //Will keep the dropdown open when deselecting an option 
	});

**Comment by tjschuck** [comment]
@flattt Yeah, I'd say something's up with the release.  Based on the fact that https://github.com/harvesthq/chosen-package _was_ updated 7 days ago, but [only for the version string in the package.json and in a CSS comment](https://github.com/harvesthq/chosen-package/commit/20457c69249226af89fda0b357591622b922b36a), it seems like the final version didn't get rolled into 1.7.0 properly.  Stay tuned for an update from @koenpunt. 

In the meantime, you can always build Chosen yourself from source.  Instructions [here](https://github.com/harvesthq/chosen/blob/master/contributing.md#grunt-tasks-running-tests-and-building-chosen).

**Comment by koenpunt** [comment]
Hm, I'll have a look this weekend

**Comment by tjschuck** [comment]
@koenpunt Gotcha, that makes sense for the dates then.

**Comment by koenpunt** [comment]
Zip has been added: https://github.com/harvesthq/chosen/releases/tag/v1.7.0

**Comment by koenpunt** [comment]
But still worth investigating why the version/license comment isn't baked into the JS file of the package repo.
