### ISSUE TITLE
Add chosen to packagist.org

### ISSUE THREAD

**Issue by fabiomontefuscolo** [harvesthq/chosen#2802]
It would be very useful having chosen.js on packagist.org. Packagist is the preferred dependency manager for PHP projects. Developers can reference javascript, css and php from a single file. Several javascripts are there, but we are missing chosen!

I will submit "pull request" for composer.json, but I think composer.json should live in chosen-package repository. If you agree, there are more 3 steps to follow ( < 10 minutes ).

1. Create an account on packagist.org.
2. Submit https://github.com/harvesthq/chosen-package.
3. Connect github webhooks to packagist.

Your library is a "must have" for any cms project or sites with forms. Please, let us keep track of your efforts from packagist.org.

Thank you!

**Comment by landsman** [comment]
We will very grateful for it in Drupal community!

**Comment by stof** [comment]
Closing this, as this is now done: https://packagist.org/packages/harvesthq/chosen
