### ISSUE TITLE
Version 1.7.0 - search bug with cyrillic

### ISSUE THREAD

**Issue by Jeckerson** [harvesthq/chosen#2805]
By typing any cyrillic characters in search input - the output is the **last character of option value**.

This affects only cyrillic characters.

**Comment by koenpunt** [comment]
I don't think this is an issue with 1.7.0 alone, but also applies to previous versions?

**Comment by fuzegit** [comment]
This bug has appeared since 1.7.0 version. In 1.6.2 version everything works perfectly.

**Comment by eesau** [comment]
This bug is not limited to cyrillic characters, any non-ascii character in the option text sees to trigger it.
1.6.2 and before work fine.
See https://jsfiddle.net/bpnpzgh8/14/

**Comment by geminorum** [comment]
I too have this problem with Persian.

**Comment by Sogl** [comment]
Same here.

List:
![image](https://cloud.githubusercontent.com/assets/7556290/26380022/d38c5c26-4067-11e7-879d-d2506c09ae83.png)

With search:
![image](https://cloud.githubusercontent.com/assets/7556290/26379907/4bf23b0a-4067-11e7-8be6-51892e8aac46.png)

When will be fixed?

**Comment by msom** [comment]
https://github.com/harvesthq/chosen/pull/2811 seems to work:
![screen shot 2017-09-20 at 09 05 57](https://user-images.githubusercontent.com/5045627/30630966-f3f5e472-9de2-11e7-8490-c66e2357b63e.png)

**Comment by adunkman** [comment]
This has been fixed in versions 1.8.1 and above.
