### ISSUE TITLE
Compatibility with jQuery >= 1.9

### ISSUE THREAD

**Issue by nlips** [harvesthq/chosen#2806]
Chosen doens't work with jQuery 1.11.0.
Error about $.browser.msie
The jQuery object "$.browser" is [deprecated from version 1.9](https://api.jquery.com/jquery.browser/)

**Comment by stof** [comment]
I don't find any place in our codebase using `$.browser.msie`. Are you sure it comes from Chosen ?

And which version of Chosen are you using ?

**Comment by nlips** [comment]
Oups... sorry. Indeed, this piece of code does not come from chosen.
