### ISSUE TITLE
Unexpected Duplicate Selection with 'display_selected_options' and 'hide_results_on_select' Options

### ISSUE THREAD

**Issue by jasonjyu** [harvesthq/chosen#2808]
Chosen allows unexpected duplicate selection when the `display_selected_options` and `hide_results_on_select` are both set to `false`.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Set `display_selected_options: false` and `hide_results_on_select: false` in the example docsupport/init.js file for `'.chosen-select'` of the demo page.

  2. In the "Into This" selection under **Multiple Select**, type "United States", hit enter and then repeat.

### Expected behavior

"United States" is only allowed to be selected once.

### Actual behavior

"United States" is allowed to be selected twice.

### Environment

  - **Chosen Version**: 1.7.0

  - **jQuery or Prototype Version**: jQuery

  - **Browser and Version**: Chrome 57.0

  - **OS and Version**: Mac OS X 10.11.2 and Windows 7

**Comment by koenpunt** [comment]
Thanks for reporting this @jasonjyu. But this is not a bug, since "United States" is represented in the list twice :)

**Comment by jasonjyu** [comment]
Okay, I see the duplicates in the original selection list now.  I guess having duplicate values of "United States" and "United Kingdom" made things confusing for me.  Thanks for clarifying.
