### ISSUE TITLE
Any way to support the html "size=N" attribute?

### ISSUE THREAD

**Issue by ppeccin** [harvesthq/chosen#2815]
Thus making the list vertically showing N entries, with scroll when necessary?

**Comment by koenpunt** [comment]
You can do this using css by overriding the `max-height` property of `.chosen-container .chosen-results`:

```css
.chosen-container .chosen-results {
  max-height: 240px; /* the default */
}

**Comment by ppeccin** [comment]
No, that is not the behavior you get when using the size attribute on html select tags.
The size=N makes the list to be always open, and showing N lines, like a ListBox, NOT a Dropdown, understand?

I do not want to specify the height of the dropdown when open. I need the list to be always open, with no dropdown, like the correct behavior on normal select tags.
Is it possible to achieve this?

**Comment by koenpunt** [comment]
This might also be possible using CSS, but it's not supported by the library.
