### ISSUE TITLE
Remove CSS clip property

### ISSUE THREAD

**Issue by mateuspv** [harvesthq/chosen#2816]
I noticed that chosen is using `clip` property, with is deprecated...I would like to know if is possible to remove it.

> This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

Font: https://developer.mozilla.org/en-US/docs/Web/CSS/clip

Any hint's about how to do this?

**Comment by koenpunt** [comment]
There's already a PR pending for this; https://github.com/harvesthq/chosen/pull/2780

**Comment by H3xx3n** [comment]
On chrome 64 (dev) does no longer works. The clip property is making the dropdown invsibile

**Comment by adunkman** [comment]
Thanks for the heads-up, @H3xx3n! According to [their release schedule](https://www.chromium.org/developers/calendar), looks like Chrome 64 is scheduled to hit stable on  Jan 23rd, 2018, at which point we’ll be broken.
