### ISSUE TITLE
How to import this in a project

### ISSUE THREAD

**Issue by jonjie0317** [harvesthq/chosen#2817]
I have read the documentation, but there's no guides there where you can follow a steps on how to work with this package. Like:<br>

1. add `<link rel="stylesheet" href="...">`
2. add `<script src="chosenjs/path..."></script>`

hmm I tried to use the class `chosen-select` but its not working. Need help. Thanks

**Comment by tjschuck** [comment]
@jonjie0317 First, download the ZIP of the latest release from [the releases page](https://github.com/harvesthq/chosen/releases).

In the release, you'll find Chosen's built CSS and JS files.  First, decide if you're using the jQuery version or the Prototype version.  If you're unsure what this means, go with the jQuery version.

Next, decide if you want to use the minified versions or the full versions.  If you have a build pipeline that already concatenates and/or minifies your assets, you probably want the full versions.  If you're unsure, pick the minified versions.

Then, in your page, you include those files however you'd normally include CSS and JS files.  If you don't already have a system, the recommendation would be to put `<link rel="stylesheet" href="chosen.min.css">` somewhere in the `<head>` of your document.  Note that the `href` needs to point to the correct location relative to your HTML document.  If you have it inside a `css/` directory or something, you'll need to source it appropriately.

You'll next need to include the JS file.  If you don't have a system here, put `<script src="chosen.jquery.min.js" type="text/javascript"></script>` before your closing `</body>` tag in your document.  Again, the sourcing will have to be correct based on where you put the file.

You also need to include jQuery if you're not already.  If you need to include it, put this line above the Chosen one above to grab it from Google's CDN: `<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>`.

**Comment by jonjie0317** [comment]
@tjschuck I already have this set up sir. Also, I used `chosen-select` class in `<select>` tags but it doesn't work.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

**Comment by jonjie0317** [comment]
@tjschuck its ok now sir. Just need to add `$('selector').chosen();` in my js. Thank you so much :)

**Comment by tjschuck** [comment]
Glad you figured it out!
