### ISSUE TITLE
中文的筛选问题

### ISSUE THREAD

**Issue by C-GM** [harvesthq/chosen#2819]
我用1.6.2的版本可以筛选中文，1.7.0的中文筛选有问题，希望有时间更新一下呗。

**Comment by tjschuck** [comment]
Unfortunately, no one on the maintainer team speaks Chinese, so the best support I can offer here is via Google Translate, which says:

> I can use the 1.6.2 version of the Chinese filter, 1.7.0 Chinese screening problems, I hope to have time to update the chant.

Based on it sounding like a regression from 1.6 to 1.7, it might be related to https://github.com/harvesthq/chosen/issues/2821.  That's about RTL languages specifically (which I don't think typically applies to Chinese in modernity/on the internet), but perhaps it's more generally a bug with non-ASCII languages.  I'll leave a comment there about this, but I'm closing this issue in favor of that one.

**Comment by C-GM** [comment]
Received, I have not asked before, so I do not know only in English
