### ISSUE TITLE
Bug when searching non-ASCII languages

### ISSUE THREAD

**Issue by ali1360** [harvesthq/chosen#2821]
hi
I am using chosen 1.7.0 JQuery  in my asp.net MVC project. It works perfect in English, but in my case when I use chosen in multi-select mode for Persian language the search text shows just last charterer instead of whole word. i have work around it and found the problem happens in line 394 , 395 of "chosen.jquery.js" when creating <em> tag.
no difference whether using rtl option or not the result is the same.
![1](https://cloud.githubusercontent.com/assets/1688001/26556393/7c381a40-44af-11e7-9b65-e9a941bb7589.PNG)
![2](https://cloud.githubusercontent.com/assets/1688001/26556398/811bf766-44af-11e7-8f83-3ebe50bdb71b.PNG)

thanks in advance.

**Comment by aaltheiab2012** [comment]
Thank you, this helped me a lot
I had to remove ( .substr(startpos); ) from line 395 to fix the issue. i'm using Arabic.

**Comment by tjschuck** [comment]
Based on #2819, it sounds like there might be a similar issue with Chinese (a regression in search between 1.6.2 and 1.7), so this might not be limited to RTL languages.

Based on the `.substr(startpos)` highlighted above, it might be a multi-byte char issue?  That would affect a number of non-ASCII languages, not just RTL ones.

**Comment by evanre** [comment]
Hi, I've got the same problem with cyrilic languages. Signed up on the topic and waiting for solution)

As temp solution, commented this string:
`option.search_text = text.substr(0, startpos) + '<em>' + text.substr(startpos);`

**Comment by adunkman** [comment]
Today I learned that `\w` and `\b` are ASCII-specific in JavaScript — they do not work for characters outside the ASCII character range. 

I’m working on an alternative solution, but just wanted to post here because it was surprising news to me and thought you might be interested in learning, too!

**Comment by tjschuck** [comment]
This was fixed in #2877 and has been released as part of [version 1.8.1](https://github.com/harvesthq/chosen/releases/tag/v1.8.1).
