### ISSUE TITLE
chosen:update not working in $.ajax success call

### ISSUE THREAD

**Issue by khnumtemu** [harvesthq/chosen#2825]
I am going to try to be as clear as possible. My issue is that Chosen isn’t updating my dropdown at all. I am not having an issue with it working correctly. The issue is within my $.ajax success call I am pulling data from the database to on an update to repopulate the Chosen dropdown with the previously selected items. My first screen shot shows that the data does come back and populates the dropdown but at the first and second images shows it doesn’t do it correctly because of the chosen:update not working correctly, based on what I understand at this point.

I am including the code and the rendered HTML for your review. Any insight and/or assistance that you can provide would be most appreciated.

--HTML--

```
<div class="row top-buffer">
	<div class="col-xs-6">
		<div class="input-group">
		<span class="input-group-addon">Current States Distribution</span>
		 <select name="DistributionStates" id="ddlDistributionStates" multiple="multiple" class="form-control chosen-select" data-placeholder="Select State(s)">
			<option>Alabama </option>
			<option>Alaska </option>
			<option>Arizona </option>
			<option>Arkansas </option>
			<option>California </option>
			<option>Colorado </option>
			<option>Connecticut </option>
			<option>Delaware </option>
		</select>
		</div>
	</div>
</div>
```

--Rendered HTML--

```
<div class="col-xs-6">
	<div class="input-group">
		<span class="input-group-addon">Current States Distribution</span>
		 <select name="DistributionStates" id="ddlDistributionStates" multiple="multiple" class="form-control chosen-select" data-placeholder="Select State(s)" style="display: none;">
			<option>Alabama </option>
			<option>Alaska </option>
			<option>Arizona </option>
			<option>Arkansas </option>
			<option>California </option>
			<option>Colorado </option>
			<option>Connecticut </option>
			<option>Delaware </option>
		</select>
		<div class="chosen-container chosen-container-multi chosen-with-drop chosen-container-active" style="width: 364px;" title="" id="ddlDistributionStates_chosen">
			<ul class="chosen-choices">
				<li class="search-choice"><span>Arkansas</span><a class="search-choice-close" data-option-array-index="1"></a></li>
				<li class="search-choice"><span>Alaska</span><a class="search-choice-close" data-option-array-index="0"></a></li>
				<li class="search-field"><input type="text" value="Select State(s)" class="default valid" autocomplete="off" style="width: 118px;" aria-invalid="false"></li>
			</ul>
			<div class="chosen-drop">
					<ul class="chosen-results"><li class="active-result" data-option-array-index="0">Alabama </li>
					<li class="active-result" data-option-array-index="1">Alaska </li>
					<li class="active-result" data-option-array-index="2">Arizona </li>
					<li class="active-result" data-option-array-index="3">Arkansas </li>
					<li class="active-result" data-option-array-index="4">California </li>
					<li class="active-result" data-option-array-index="5">Colorado </li>
					<li class="active-result" data-option-array-index="6">Connecticut </li>
					<li class="active-result" data-option-array-index="7">Delaware </li>
				</ul>
			</div>
		</div>
	</div>
</div>
```

--js--

```
$('#ddlDistributionStates').chosen();

$.ajax...
success: function (data) {

            $(data).each(function (index, item) {
var ds = item.DistributionStates.split(",");
$.each(ds, function (i, p) {
	$("#ddlDistributionStates_chosen ul").prepend('<li class="search-choice"><span>' + p + '</span><a class="search-choice-close" data-option-array-index="' + i + '"></a></li>');
});

$("#ddlDistributionStates").trigger("chosen:updated");

	}
}
```

### Environment

  - **Chosen Version**: Version 1.6.2

  - **jQuery or Prototype Version**: jQuery

  - **Browser and Version**: Chrome

![chosendropdownissue_01](https://cloud.githubusercontent.com/assets/29149559/26737415/0652ef1c-4798-11e7-8925-7536bde97be0.PNG)
![chosendropdownissue_02](https://cloud.githubusercontent.com/assets/29149559/26737414/0651e810-4798-11e7-8f9a-3cef3222ae76.PNG)

**Comment by cbetancourt** [comment]
Not sure if you've found a workaround for this, but have you tried firing the event twice? I know it sounds silly, but my tests also show `chosen:updated` does not work until I fired the event a second time.

**Comment by cbetancourt** [comment]
This might be related to your DOM not being ready when the `chosen:updated` event is fired.

I encountered a similar issue when firing this event as a form is reset. Apparently `chosen:updated` was firing at the same time as the form is changing, which did not reset Chosen form fields. So I ended up delaying the action by 200ms achieving the desired effect.

**Comment by koenpunt** [comment]
You should update the select where Chosen is attached to and the trigger `chosen:updated` to let Chosen update the HTML for you
