### ISSUE TITLE
Unable to populate select with options using jsrender

### ISSUE THREAD

**Issue by yedduprasasd** [harvesthq/chosen#2835]
Dear Experts, I need help with this issue. I really like chosen look and feel as well as ease of use. Great job on this.

I use jsrender to get the data into a template and then use this data to populate the select options. When I use the class "chosen-select" on the select tag, the list is bank. If I remove the class, my data is displayed but the select loses the functionality that is so valuable to me. In order to render the template I use the delimiters [% %]. I suspect chosen-select is looking for certain characters and my delimiters are being treated as unclean characters.

Please can you help me with a work around. I cannot use {{ }} as my server side is django and django uses {{ }} for templating.

### Steps to reproduce

  1. If I remove the class chosen-select from the select item, the data is displayed

  2. instead of templating, if I hardcode the values it works

  3. when I check for the data after templating the tags and data, it gives me the right option tags and values.

### Environment

  - **1.7.0**:

  - **jQuery**:

  - **Chrome ver. 58.0.3029.110 (64-bit)**:

  - **Windows 10**:

### Additional information

I am a novice to web development and I am still learning but I feel the below code might be an issue but I may be wrong.

    SelectParser.prototype.escapeExpression = function(text) {
      var map, unsafe_chars;
      return text;
      if ((text == null) || text === false) {
        return "";
      }
      if (!/[\&\<\>\"\'\`]/.test(text)) {
        return text;
      }
      map = {
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#x27;",
        "`": "&#x60;"
      };
      unsafe_chars = /&(?!\w+;)|[\<\>\"\'\`]/g;
      return text.replace(unsafe_chars, function(chr) {
        return map[chr] || "&amp;";
      });
    };

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there. Additionally, if you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue, you'll be much more likely to get an even better answer faster.
