### ISSUE TITLE
Chosen Demo Page not using latest Chosen Version

### ISSUE THREAD

**Issue by tjschuck** [harvesthq/chosen#2842]
@koenpunt It seems like you're working on some packaging stuff, so this is probably a good time to point this out!

[The Chosen demo page](https://harvesthq.github.io/chosen/) is still running 1.6.2 ([current version is 1.7.0](https://github.com/harvesthq/chosen/releases)).

I thought the demo page was supposed to be built and pushed automatically with a release, so maybe something's broken there.

**Comment by koenpunt** [comment]
Nope, that's done manually. But really easy, just run `grunt publish-release` (I just did)

**Comment by tjschuck** [comment]
@koenpunt :heart: :heart: :heart_eyes_cat: :heart:
