### ISSUE TITLE
Chosen and Muti Select

### ISSUE THREAD

**Issue by skouf** [harvesthq/chosen#2843]
Hello

When using multiple select with a mobile, the rendering of the field is not the same as computers.

It shows a classic select form. The problem is that the placeholder of the multiple select is "No items". And it can't be change to a custom text.

How is it possible to have the same display as computers ?

Thanks !

**Comment by tjschuck** [comment]
Chosen is explicitly disabled on mobile (see the [third answer here](https://harvesthq.github.io/chosen/#faqs)).  There's more information about that decision on https://github.com/harvesthq/chosen/pull/1388.  It's not likely to be reversed any time soon — sorry.
