### ISSUE TITLE
data-placeholder length should be taken into account for width calculation

### ISSUE THREAD

**Issue by greg0ire** [harvesthq/chosen#285]
If all options in a list are shorter than the length of the data-placeholder string, then this string is cut and followed by "..."
test markup:

    <select data-placeholder="looooooooooooong">
      <option>short</option>
      <option>small</option>
      <option>tiny</option>
    </select>

The length of the data-placeholder should be taken into account for the select width calculation.

**Comment by pfiller** [comment]
Chosen does it's best to guess the width that makes sense, but it's not perfect. We added the option to provide a `width` on instantiation for just these occasions. Calculating the width of a placeholder is a lot of complexity for something with a very simple workaround.
