### ISSUE TITLE
Not working properly with hebrew charachters

### ISSUE THREAD

**Issue by querysol** [harvesthq/chosen#2851]
Version 1.7 

If the select field holds Hebrew characters the autocomplete feature will only show 1 letter or gibberish on the autocomplete results...

https://www.screencast.com/t/RbnElqhnz7NH

This works properly in previous versions

**Comment by tjschuck** [comment]
I'm pretty sure this is the same as https://github.com/harvesthq/chosen/issues/2821, and that it's a bug with all RTL languages.  Closing this one in favor of that, but feel free to leave any additional information you have over on that issue!

Thanks for reporting.
