### ISSUE TITLE
Deceptive site ahead

### ISSUE THREAD

**Issue by doricsoft** [harvesthq/chosen#2853]
Hi, when I am trying to download your library I get  a "Deceptive site ahead".

Is there a problem with your hosting site?

Thank you

**Comment by tjschuck** [comment]
@doricsoft What URL are you accessing?  And from where?  Browser and browser version?

Our downloads are hosted [on Github](https://github.com/harvesthq/chosen/releases), so there shouldn't be any issue, but perhaps you were trying to download it from an untrusted third party.

(Closing pending more info, but will reopen once it's given.)
