### ISSUE TITLE
$(selector).chosen(),.val()  gives wrong value. It only gives the immediate value in the dropdown, not the value in box

### ISSUE THREAD

**Issue by madhur77** [harvesthq/chosen#2858]
$(selector).chosen(),.val() gives wrong value. It only gives the immediate value in the dropdown, not the value in box

**Comment by adunkman** [comment]
This is expected behavior — the text input is merely searching/filtering the available options, and doesn’t represent a selected item. Does that make sense? 

![image](https://user-images.githubusercontent.com/14930/29832538-90f0c79e-8cb6-11e7-9127-dac1d1bd38cb.png)

**Comment by madhur77** [comment]
So what is the way to get value of the selected item?

**Comment by adunkman** [comment]
To get the selected items, call `.val()` as you did above — for instance, `$(".chosen-select").val()` would return `["Albania"]` in the screenshot I posted.

**Comment by madhur77** [comment]
Alright.That makes absolute sense. 
Great
