### ISSUE TITLE
Too much files, which should I import into my jsp?

### ISSUE THREAD

**Issue by GYiyouth** [harvesthq/chosen#2861]
Sorry, I download amazing chosen, but I got a lot of files(about 20 files! ), which file should I use?

**Comment by tjschuck** [comment]
You'll need some selection of the following files to use Chosen:

```
# Images
chosen-sprite.png
chosen-sprite@2x.png

# jQuery
chosen.jquery.js
chosen.jquery.min.js

# Prototype
chosen.proto.js
chosen.proto.min.js

# CSS
chosen.css
chosen.min.css
```

You'll need both image files.  Next, you need to determine if you want the jQuery version of Chosen or the Prototype version.  (If you don't know, you almost certainly want the jQuery version.)  Lastly, you need to decide if you want to use the minified versions, or if you want to use the non-minified versions (and use your own build pipeline to minify for production).

In general, you'll probably want to pick 4 files — both images, one CSS file, and one JS file.  Which of the CSS and JS files is up to your environment.

In the simplest case (just dropping these files into a static site that you serve up as-is with no build pipeline), you probably just want the following four files:

```
chosen-sprite.png
chosen-sprite@2x.png
chosen.jquery.min.js
chosen.min.css
```
