### ISSUE TITLE
jQuery Chosen Version 1.7.0 is running very slow in IE edge with long list of options in Multiselect dropdown

### ISSUE THREAD

**Issue by nitin-agarwal** [harvesthq/chosen#2863]
Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. Run application with jQuery Chosen in IE Edge

  2. have Multiselect dropdown with 5k items.

### Expected behavior

It should work fast as it is working in Chrome and Firefox browser

### Actual behavior

It is loading very slow Multiselect dropdown and after searching of item is very slow.

### Environment

  - v1.7.0:

  - IE Edge:

  - Windows 10:

### Additional information

jQuery Chosen plugin for Multiselect is working fine in Chrome and firefox but not in IE Edge. Kindly try to solve this issue soon.

**Comment by tjschuck** [comment]
It seems like you're saying that it's sufficiently performant in Chrome and Firefox, but _not_ in Edge?  If so, that sounds more like an Edge issue than a Chosen issue...

I'm going to go ahead and close this unless you (or anyone) knows of something we can actually do in Chosen to specifically improve performance in Edge contrary to what we're already doing for general performance improvements.

**Comment by koenpunt** [comment]
@tjschuck labeling this as "IE" is actually incorrect, since IE and Edge have their own lifecycle. But apart from that I agree on not knowing how to actually act on this.

**Comment by stof** [comment]
@koenpunt actually, IE does not really have a lifecycle anymore. IE 11 still receive security patches, and that's all.

**Comment by koenpunt** [comment]
end-of-lifecycle 😅

**Comment by tjschuck** [comment]
@koenpunt @stof Yeah, I knew that, but that "IE" label was there already, and as a spoiled backend developer, I just lump them 😅  But I'll relabel because I love you.

Anyway, everything else stands ¯\\\_(ツ)_/¯

**Comment by nitin-agarwal** [comment]
I have found one article which has one suggestion, 

" the underlying issue is the rnoInnerhtml RegEx used to look for Script tags in the jQuery.html() functionality. The RegEx used there is very slow in IE when rolling over large data sets."

Refer https://stackoverflow.com/questions/21322894/jquery-plugin-chosen-enhances-mutliselects-works-great-in-chrome-but-slow-in
