### ISSUE TITLE
search in not working when cloudflare is enabled on website

### ISSUE THREAD

**Issue by monovm** [harvesthq/chosen#2865]
when we enable cloudflare performance setting on website chosen search is not working.

**Comment by tjschuck** [comment]
Please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen (although I really can't imagine this is a Chosen issue; this sounds like some kind of infrastructure configuration issue).
