### ISSUE TITLE
Broken in Chrome Mobile View.

### ISSUE THREAD

**Issue by Nadareh** [harvesthq/chosen#2866]
Hi there, I don't know if I'm using it correctly but it seems broken in Chrome when using mobile view. Here's the screenshot:  http://prntscr.com/gbnqto

But it seems fine in Firefox:  http://prntscr.com/gbnr13
I'm using Genesis Theme.

Thanks in advance!

**Comment by tjschuck** [comment]
Neither of those appears to be Chosen, so it seems like you're just having regular style issues.

Regardless, Chosen should be disabled on mobile across the board.  See [the third answer here](https://harvesthq.github.io/chosen/#faqs).
