### ISSUE TITLE
Filtering by ':' character does not seem to work properly

### ISSUE THREAD

**Issue by classicalConditioning** [harvesthq/chosen#2872]
### Steps to reproduce

Make sure that you have a collection of items that include ':' in two different types of situations:
1) with a space before ':', such as "score 1 : 2",
2) with no space before ':', such as "example: foo"

### Expected behavior

When filtering by only ':' character all items with ':' character should show up.

### Actual behavior

When filtering by only ':' character only items that have a preceding space before ':' character show up. 

### Environment

  - **Chosen Version**: 1.6.2

  - **jQuery or Prototype Version**: 2.2.0

  - **Browser and Version**: Chrome 60.0.3112.101

  - **OS and Version**: Windows 10 64 bit

**Comment by tjschuck** [comment]
Do you have the [`search_contains` option](https://harvesthq.github.io/chosen/options.html#options) enabled?

**Comment by classicalConditioning** [comment]
I did not. And once I set it to true, the problem was solved. Thanks

**Comment by stof** [comment]
without the option, it search matches at the beginning of words only

**Comment by classicalConditioning** [comment]
I am not sure if this is useful for special characters. I get it why you would want to keep `search_contains` set to default `false` for cases when searching for an actual word, but if you have it set to `false` you won't find anything by punctuation marks (or other special characters that are within the word, but not at the beginning of it). If you set it to `true`, because it makes sense for users in a given case to search by punctuation marks (or other special characters)- you are now enabling search by anything within any word, which could be annoying.

**Comment by tjschuck** [comment]
@classicalConditioning The way searching and filtering works has been changed pretty significantly in the versions since 1.6.2 — grab the [latest release](https://github.com/harvesthq/chosen/releases) and see if that aligns more to your expectations.
