### ISSUE TITLE
Select is not enhanced on Mobile Edge

### ISSUE THREAD

**Issue by davestevens** [harvesthq/chosen#2876]
Select is not enhanced on Mobile Edge, the browsers select are still seen when loaded the page. I can't see any errors being thrown.

### Steps to reproduce

1. View https://harvesthq.github.io/chosen/ in Edge in Windows mobile

### Expected behavior

Examples should show chosen UI

### Actual behavior

Default browser UI is shown

**Comment by davestevens** [comment]
I've just seen in the code that it is disabled for windows phones (along iPhone and blackberry).

**Comment by tjschuck** [comment]
Just to clarify, Chosen is disabled on all mobile platforms — see [the third FAQ here](https://harvesthq.github.io/chosen/#faqs), and https://github.com/harvesthq/chosen/pull/1388 for more information and rationale.

**Comment by davestevens** [comment]
Thanks, I didn't see Windows Mobile defined so wasn't sure why.
It makes sense to have it disables on Android and iPhone as they have decent alternative UI, Edge however is the default desktop multi select.

**Comment by tjschuck** [comment]
Sheesh, Mobile Edge's user-agent string [is almost comically overloaded](https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx#edge).  Quickly scanning, it looks like it's probably actually getting blocked by [the Android mobile rule](https://github.com/harvesthq/chosen/blob/736b4299d1204702ce4412448a563cf7a011f06a/coffee/lib/abstract-chosen.coffee#L373), not something specifically intended for Edge.  (Although IEMobile and Windows Phone _are_ [explicitly blocked](https://github.com/harvesthq/chosen/blob/736b4299d1204702ce4412448a563cf7a011f06a/coffee/lib/abstract-chosen.coffee#L369-L370).)
