### ISSUE TITLE
1.8.0 does not draw multiselect.

### ISSUE THREAD

**Issue by badfiles** [harvesthq/chosen#2878]
```
<select data-placeholder="(выберите значение)" multiple="multiple" class="chosen-multiselect" tabindex="5" id="id" name="id[]">
....
</select>
<script type="text/javascript">$(".chosen-multiselect").chosen({width: "100%", max_selected_options: 6});</script>
```

results in

```
<div class="chosen-container chosen-container-multi" title="" id="id_chosen" style="width: 100%;"><ul class="chosen-choices">
  <li class="search-field">
    <input class="chosen-search-input default" type="text" autocomplete="off" value="(выберите значение)" tabindex="5" style="width: 152.438px;">
  </li>
</ul>
<div class="chosen-drop">
  <ul class="chosen-results"></ul>
</div></div>
```
chosen-drop and chosen-results are empty.

Tried in latest chrome and firefox.

Falling back to 1.7.0 helps.

**Comment by tjschuck** [comment]
1.8.0 _does_ work for multiselects — you can see it working [on the demo page](https://harvesthq.github.io/chosen/).  There must be something amiss with your specific setup.

Here's your exact sample code working in a Fiddle: https://jsfiddle.net/75204mbs/1/

Please link to a publicly accessible page or a Fiddle so we can attempt to debug.  Closing in the meantime.

**Comment by badfiles** [comment]
if options go like this:
```
<option value="a">a</option>
<option value="b">b</option>
<option value="c">c</option>
```
1.7.0 works, 1.8.0 -- empty dropdown box.

**Comment by tjschuck** [comment]
Here's a Fiddle showing that exact code working with 1.8.0: https://jsfiddle.net/75204mbs/8/

**Comment by tjschuck** [comment]
Check your JS console.  Make sure no errors are being thrown there.

**Comment by badfiles** [comment]
No errors, I am sorry, but it looks like it does not work only with Russian words.
Try this set.

```
<option value="v">я</option>
<option value="z">м</option>
<option value="x">и</option>
```

**Comment by tjschuck** [comment]
Now we're getting somewhere!  That sounds like it's related to https://github.com/harvesthq/chosen/issues/2821, which should be fixed by https://github.com/harvesthq/chosen/pull/2877.  You can continue using 1.7.0 in the meantime, or you can pull down that branch and build Chosen yourself from source to see if that fixes your issue.  We're hoping to get https://github.com/harvesthq/chosen/pull/2877 merged and released very soon.

/cc @adunkman

**Comment by badfiles** [comment]
thanks

**Comment by tjschuck** [comment]
Here's a JSBin with Chosen from that branch and your code that you shared — it seems to be working with that fix: https://jsbin.com/diwaxomuju/edit?html,output
