### ISSUE TITLE
Chosen Issue with ajax codeigniter

### ISSUE THREAD

**Issue by abdulahadbsit** [harvesthq/chosen#2882]
Summarize your issue here.

### Steps to reproduce

Tell us how to reproduce this issue.

  1. I have two input fields(Company name, employee name) those are dependent. when i select company name then an ajax request send and get employees name from DB. The issue data is not display in employee input field. 

### Expected behavior

employees name have to show and i select multiple employees in 

### Actual behavior

your script set an css property Display none to the input field that why data is not showing.

### Environment

  - **Chosen Version**: Version 1.8.0

  - **jQuery or Prototype Version**: Version 1.8.0

  - **Browser and Version**: chrome latest

  - **OS and Version**: Windows 8.1

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by tjschuck** [comment]
@abdulahadbsit The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

That said, only part of this is Chosen related — the majority of what you want to do is straight Javascript (or jQuery, if that's your lib of choice).

It sounds like you're already successfully executing the AJAX request.  Once you have your new data, you'll need to populate the underlying `select` for your employees field with all of the new `option`s that you received from the AJAX request.

Once you've updated the underlying select to have the options you want, _then_ you can rebuild Chosen with the new options.  You just need to call `$("#your-select-id").trigger("chosen:updated");` ([documented here](https://harvesthq.github.io/chosen/#change-update-events)).

**Comment by abdulahadbsit** [comment]
Thank you sir its working now :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by abdulahadbsit** [comment]
Hi respected sir,
Sir i am working with your multiple select (chosen-select) . Actually i
need the same thing like this but it show all emails to users. i need it
just select email on user input and just show that email not all emails.
please Help me as soon as it possible for you. I attache a file for batter
understanding
Don't Show all emails in drop down
Thank you

**Comment by tjschuck** [comment]
Once again, the issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions like this one that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.
