### ISSUE TITLE
placeholder span width does not properly change when using chosen-single-with-deselect

### ISSUE THREAD

**Issue by cgatesman** [harvesthq/chosen#2885]
chosen v1.7.0

If you have a chosen-single-with-deselect and nothing initially selected, the span for the placeholder is larger than when an item is selected.  This is ok, but when you deselect the selection, the span for the placeholder is then shorter potentially cutting off the placeholder text.

### Initial state when page is loaded:
<img width="227" alt="screen shot 2017-09-13 at 10 09 37 am" src="https://user-images.githubusercontent.com/6276072/30381897-b12b92d0-986b-11e7-8e81-e5e993337373.png">

### After selecting option:
<img width="227" alt="screen shot 2017-09-13 at 10 08 00 am" src="https://user-images.githubusercontent.com/6276072/30381823-850e9c38-986b-11e7-91fe-d689abae1244.png">

### After deselecting option:
<img width="228" alt="screen shot 2017-09-13 at 10 08 17 am" src="https://user-images.githubusercontent.com/6276072/30381828-88653f04-986b-11e7-81ee-14ff4180d9b7.png">

**Comment by tjschuck** [comment]
1.7.0 is a few versions behind — can you try on the [latest release](https://github.com/harvesthq/chosen/releases) (or the [Chosen demo page](https://harvesthq.github.io/chosen/)) and confirm that you're still seeing an issue?

Closing pending your response, but we'll reopen if you can confirm this is still happening on the latest version.  Thanks @cgatesman !
