### ISSUE TITLE
Chinese typing filter fail

### ISSUE THREAD

**Issue by y7t2ffff** [harvesthq/chosen#2908]
Hi
I have a problem with single select. In Chinese, after we type a character, we must press "Enter" to make sure the character. In this case, when I pressed "Enter", the filter failed. But when I copied and pasted the Chinese character, it worked.

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

Closing until more info is provided, then we'll reopen.

**Comment by y7t2ffff** [comment]
OS:Win 10
Browser: Firefox 56.0.1(But Chrome  62.0.3202.62 It Worked)
Chosen Version: 1.8.2

Site:http://104.199.206.54/Chosen/
This Vedio is how i get this bug: https://www.youtube.com/watch?v=s14u81CaSv8&feature=youtu.be
