### ISSUE TITLE
Seems chosen doesn't work on mobile devices How to correct this? 

### ISSUE THREAD

**Issue by kselax** [harvesthq/chosen#2909]
Hi guys, I've made script using chosen recent and noticed in mobile 
A search field is disappeared. 
Can I somehow correct this? 

In nowadays users are using mobile much, I hope this is supporting?

**Comment by tjschuck** [comment]
That's intentional.  See the [third FAQ here](https://harvesthq.github.io/chosen/#faqs) — more information on https://github.com/harvesthq/chosen/pull/1388.
