### ISSUE TITLE
How to get multiselect selected values after postback programaticaly?

### ISSUE THREAD

**Issue by mohamednasr2028** [harvesthq/chosen#2911]
how to get multiselect selected values in code behind after postback ?

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

Ultimately, you probably just want to do some standard Javascripting/jQuerying on the underlying `select`.  The data of Chosen is just the normal data of your regular HTML `select` — Chosen is just visual skin on top of it.

**Comment by mohamednasr2028** [comment]
ok .. thanks
But i post it here to make contributors try to fix this issue in the next releases.

Thanks,
