### ISSUE TITLE
How to do ontextchanged event using Chosen ddl search ?

### ISSUE THREAD

**Issue by mohamednasr2028** [harvesthq/chosen#2918]
How to do ontextchanged event using Chosen ddl search ?

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

**Comment by mohamednasr2028** [comment]
thanks
