### ISSUE TITLE
How to use 2 dropdowns?

### ISSUE THREAD

**Issue by Xelmep** [harvesthq/chosen#2926]
I have 2 dropdowns, included chosen plugin.
First dropdown is Barcode of Article, Second is Name of Article. 
I need When i choice Barcode of article to update second Dropdown, and show name of article, or backward, when i choice Article name in second Dropdown to update first Dropdown and show barcode of article.

  I have the srcipt to update, and before installing chosen plugin stopped update.

   How to solve this problem?
  Thank you

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.

You'll also be more likely to get help faster over there if you include a link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so people can directly reference the code you're discussing.

That said, you should be able to do pretty much everything you're after with a combination of vanilla JavaScript (or pretty straightforward jQuery, if that's your preference) and [one Chosen-specific trigger](https://harvesthq.github.io/chosen/#change-update-events), `.trigger("chosen:updated");`.  Pretty much: do whatever you want to do on whatever events you so choose to the underlying `select`s, and whenever you'd like their data to be updated in Chosen, just call `.trigger("chosen:updated");` on the appropriate `select` elements and Chosen will be rebuilt for them.
