### ISSUE TITLE
Reference Id being dropped?

### ISSUE THREAD

**Issue by Nicholas-Hoff** [harvesthq/chosen#2936]
Summarize your issue here. 

Once my select statement goes to the chosen select, it seems to lose the reference id.  

### Steps to reproduce

To reproduce the issue change the select to facility, division, market, or group. 

  1. This is the first step

Once you change the select option and the chosen select pops up change it again and you'll see the show/hide no longer functions properly.

Here is my fiddle
https://jsfiddle.net/dzyggftn/104/

### Expected behavior

The chosen select option should be hiding when the select option changes.

### Actual behavior

The chosen select option shows after the select option changes.

### Environment

  - **using the latest Chosen Version**:

  - **https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js**:

  - **Chrome Version 63.0.3239.132 (Official Build) (64-bit)**:

  - **Windows 10 Enterpise**:

**Comment by stof** [comment]
The Chosen UI is inserted in the DOM as a sibling of the `<select>` element (and the `<select>` element gets moved into invisible land). So if you hide only the `<select>` element, it is totally expected that its sibling is not impacted.
what you should do is adding a `<div>` around your select, and hiding that `<div>` instead (which will then work fine as both the `<select>` and the Chosen UI will be inside that `<div>` and so get hidden).

**Comment by tjschuck** [comment]
Closing this per @stof's answer — the `select` itself and the Chosen representation are separate entities.  His solution should solve your problem.
