### ISSUE TITLE
Follow-up: Remove `clip` CSS property

### ISSUE THREAD

**Issue by tjschuck** [harvesthq/chosen#2942]
@harvesthq/chosen-developers, particularly @adunkman: this is a follow up to PR #2939, which was to fix issue #2816.

Per [this comment on #2939](https://github.com/harvesthq/chosen/pull/2939#issuecomment-360336277), there's one `clip` remaining [here](https://github.com/harvesthq/chosen/blob/f86fa9b7f70f71a84971e6e4c2b48972d3db9aee/sass/chosen.scss#L146).

**Comment by adunkman** [comment]
Thanks for the heads up @taichunmin, and thanks for the issue wrangling @tjschuck! I think I can just substitute a `display: none` here — taking a look now!
