### ISSUE TITLE
License text missing from chosen-package

### ISSUE THREAD

**Issue by kreynen** [harvesthq/chosen#2945]
While you include https://github.com/harvesthq/chosen/blob/master/LICENSE.md, it is missing from https://github.com/harvesthq/chosen-package

In the MIT license itself, it states...

> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

You are making it MUCH harder for downstream users of this code to meet the licensing requirements when you don't include the LICENSE.md for Bower and NPM builds.

**Comment by stof** [comment]
hmm, we should indeed copy the LICENSE file in the packaged archive.

**Comment by kreynen** [comment]
This is coming up again https://www.drupal.org/project/drupalorg_whitelist/issues/2954806

While I know everyone just wants to focus on writing and sharing code, the role the Licensing Working Group in the Drupal project is vet the code being distributed from Drupal.org for licensing issues. We're similar to Drupal's security team, but much less glamorous :)

Because the MIT license allows the copyright holder to also distribute code under other licenses, we can't really just assume that because the original source was licensed as MIT all derivatives are MIT like we can with GPL licensed code.  

To properly distribute this under the license, the Drupal project that wants to include it would have to patch the copyright notice back in.

**Comment by tjschuck** [comment]
As of [version 1.8.5](https://github.com/harvesthq/chosen/releases/tag/v1.8.5), https://github.com/harvesthq/chosen-package contains the LICENSE.md file.

Thanks for reporting, @kreynen!
