### ISSUE TITLE
Search input box shows as normal text input

### ISSUE THREAD

**Issue by Dylan-Buth** [harvesthq/chosen#2952]
I tried posting on SO and got downvoted like crazy. I updated chosen from 1.7.0 to 1.8.3 and now my select boxes that were working properly look like this. 

Any ideas what could be causing this? Didn't see anything looking through commits or other issues.

![screen shot 2018-02-13 at 10 56 33 am](https://user-images.githubusercontent.com/2185074/36162407-636f803a-10b4-11e8-9c10-c60265ad716b.png)

**Comment by Dylan-Buth** [comment]
The difference is the presence of this input element that wasn't there in 1.7.0. 
![screen shot 2018-02-13 at 11 53 34 am](https://user-images.githubusercontent.com/2185074/36162484-99a435b0-10b4-11e8-8ee8-2aaacca21775.png)

**Comment by tjschuck** [comment]
@Dylan-Buth Did you also update the CSS files from 1.7.0 to 1.8.3?

Can you please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce?

**Comment by Dylan-Buth** [comment]
👍 Duh! That was it! I was using a separately generated css file. Removed that and imported the one from the package. Thanks!

**Comment by tjschuck** [comment]
Glad that fixed it!

**Comment by yeungDev** [comment]
I'm still seeing this problem. I have the CSS files updated. On version 1.7.0.
