### ISSUE TITLE
IE 11 not working correctly with Chosen 1.8.3

### ISSUE THREAD

**Issue by wittdavid** [harvesthq/chosen#2953]
IE11 does not work correctly with keyboard actvitity with Chosen 1.8.3.  Prior versions seem to work okay.   

### Steps to reproduce

Tell us how to reproduce this issue.

  1. https://harvesthq.github.io/chosen/  Click in standard HTML dropdown in Standard Select.  TAB to chosen version of dropdown.

  2.  Note that browser shows the flashing input caret within the text of the placeholder.

  3. Press space bar, or down arrow, or press letter U.  All of these should cause the dropdown to appear.  Instead the dropdown flashes and disappears.

### Expected behavior

At step 2, browser should not show input caret.

At step 3, Dropdown should appear so that user can select, or input box in focus, as appropriate.

### Actual behavior

dropdown flashes and disappears.

### Environment

  - **Chosen Version**: 1.8.3

  - **jQuery or Prototype Version**:  n/a

  - **Browser and Version**:  IE 11

  - **OS and Version**:  Windows 7

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by bennybee** [comment]
Tested the above in Edge 14, 15 and 16 - they all show caret but step 3 works.
