### ISSUE TITLE
I have a small problem with using 'chosen'

### ISSUE THREAD

**Issue by Kierian** [harvesthq/chosen#2954]
hi. i'm korean.
I do not speak English very well. Please understand.
I am not a professional web programmer.

![1](https://user-images.githubusercontent.com/6712562/36469858-0edd66d0-172c-11e8-8e3e-64b85f3eadb7.png)

this picture f12 
![2](https://user-images.githubusercontent.com/6712562/36470026-bb202e28-172c-11e8-82de-a49dc8dfd482.png)

'span' is located below

How do I resolve this issue?

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`jquery-chosen` tag](http://stackoverflow.com/questions/tagged/jquery-chosen).  You'll be more likely to get a quick answer there.  Providing a link to a publicly accessible page that shows the issue will also increase your odds.
