### ISSUE TITLE
Search_group doesn't work :(

### ISSUE THREAD

**Issue by Eloytxo** [harvesthq/chosen#2960]
Hi, I using chosen 1.8.3. I have set search_group to true in options, because by default it didn´t work for me, but still not working.

`		$("#mySelect").chosen({
			group_search:true
		});`

I made a gif to see it in action.
[https://giphy.com/gifs/Y4tXqeTAe2BN5WkLNz](https://giphy.com/gifs/Y4tXqeTAe2BN5WkLNz)
Any help?

P.D. Using : 
```
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
```

**Comment by tjschuck** [comment]
Right off the bat, something's up with your particular Chosen — the searching should underline the matches.  See this example recorded off of [the Chosen demo page](https://harvesthq.github.io/chosen/) (currently also v1.8.3):

![2018-03-14 11_26_14](https://user-images.githubusercontent.com/308724/37412027-8d85438c-277a-11e8-9215-be5d5a102ac3.gif)

What browser, browser version, OS, and OS version are you using?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
