### ISSUE TITLE
chosen works only for a starts with character search rather than a contains search for dynamically populated select options 

### ISSUE THREAD

**Issue by AnirbanIndecomm** [harvesthq/chosen#2965]
When i call chosen on a particular select tag and trigger the chosen updated manually the 'search textbox doesn't do a contains with search and rather does a startWith Search

$('select').chosen();
$('select').trigger("chosen:updated");

Now my select options on the html contains something like this 

				<option value="3">170002</option>
		
				<option value="4">170002</option>
		
				<option value="10">17000</option>
		
				<option value="13">170009</option>
		
				<option value="14">170010</option>

After which when i try to search say for example 02 it doesnt give results , it only gives results which starts with say for example "17"

**Comment by tjschuck** [comment]
You need to set the `search_contains` option to true (it's false by default).  [Documentation here](https://harvesthq.github.io/chosen/options.html).

**Comment by AnirbanIndecomm** [comment]
Thanks to you ... Sadly i missed
