### ISSUE TITLE
Search supposed to support numeric input?

### ISSUE THREAD

**Issue by bitwombat** [harvesthq/chosen#2968]
Hi,

Using v1.8.2, I have options that have numbers in them (eg. WHS301) and I find I can search for 'W' (or 'WH' or 'WHS'), but not '301'.

Is this meant to be?  I had a thumb through the source but couldn't find what I was looking for.

I will create a testcase if this is not the intended behavior.

**Comment by bitwombat** [comment]
Thanks, that works, sorry it was a RTFM.

But wait... without that option, my searches *do* start from the middle of the word.  It's specifically the numbers that are different:

![image](https://user-images.githubusercontent.com/3937658/38641673-110f854e-3e1b-11e8-9d95-e08d96ae1f1f.png)

Now I type a 3:

![image](https://user-images.githubusercontent.com/3937658/38641702-27252604-3e1b-11e8-9ef0-a43f8475e6f3.png)

Something undocumented?

**Comment by tjschuck** [comment]
@bitwombat No worries — glad to help!

As for the behavior you're seeing, that is strange!  What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Can you link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue?

**Comment by bitwombat** [comment]
Will put together a testcase and fill out the questions on your contributing guidelines...

**Comment by tjschuck** [comment]
@bitwombat Thanks, that would be great!

**Comment by bitwombat** [comment]
Good  news - jsFiddle knows about v1.8.5.  Bad news, the link they use to cloudflare is 404.

This is 404
https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.5/chosen.jquery.min.js

and this
https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.4/chosen.jquery.min.js

but not this
https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.3/chosen.jquery.min.js

Want me to make a new issue for that?

**Comment by tjschuck** [comment]
@adunkman ^ Know anything about how those files end up there?  Both of the versions you pushed today seem to not be currently working.

**Comment by bitwombat** [comment]
Alright, here we go:

### Steps to reproduce
Go to 
[current v1.8.5](http://bitwombat.com.au/chosen/chosen_bug.html)

Type "WHS" then "3" (no quotes)

Compare with:

[v 1.6.1](http://bitwombat.com.au/chosen/chosen_bug_older.html)

I include both because they act differently.  v1.6.1 highlights the *first* occurrence of "WHS", which makes the lack of matching of "WHS3" odd.  

However 1.8.5 highlights the occurrence of WHS in the description part of the option, which if that means it's not seeing the first part, would make sense that "WHS3" doesn't match anything.

### Expected behavior

Chosen should not be matching the middle of the string without the search_contains option.

With the current behavior which seems to be matching within the string anyway, Chosen should match BSBWHS302

### Actual behavior

No results are found.

### Environment

  - **Chosen Version**:
Shown in links above.

  - **jQuery or Prototype Version**:
See source.

  - **Browser and Version**:
Firefox 59.0.2 (linux)
Chrome 65.0.3325.181 (linux)

  - **OS and Version**:
Linux

**Comment by tjschuck** [comment]
@bitwombat It looks like you're still missing the `search_contains` option. You need to set the `search_contains` option to true (it's false by default).

If you add `search_contains: true` in your example JS here http://bitwombat.com.au/chosen/js/init.js everything works as you'd expect:

![screenshot showing correct functionality](https://user-images.githubusercontent.com/308724/38820053-fb5c24c0-416a-11e8-832c-131e37300b02.png)

[Options documentation](https://harvesthq.github.io/chosen/options.html).

Please let me know if I'm misunderstanding your issue, though!

**Comment by bitwombat** [comment]
Correct.  The issue is really that when the option is false, Chosen sort of, sometimes, matches things in the middle.

**Comment by tjschuck** [comment]
@bitwombat That's actually the correct, _fixed_ behavior.  When you have the option set to `false`, it's matching on the middle one because that's the first instance that actually matches with that rule — it doesn't match the first WHS because it's inside of a word, and it does match the second WHS (correctly) because that's the occurrence that starts on a word boundary.

PR https://github.com/harvesthq/chosen/pull/2692 is what fixed this behavior, and that fix was included in version 1.7.0.

**Comment by MB-VictoryRider** [comment]
What if you must enter numbers only?

I am using a list of **_ALL_** numeric characters such as:

0400000010469004
0400000010468342
0400000010468949
0400000010469059
0400000010469106
0400000010468214
0400000010468932
0400000010469058
0400000010468438
0400000010467091
0400000010468973
0400000010469063
0400000010468341
0400000010468672
0400000010469081
0400000010468723
0400000010468081
...

Which gives:

![list](https://user-images.githubusercontent.com/45498358/49313390-b69b8d80-f4ac-11e8-9468-70e9772e81d0.PNG)

I would like the users to only have to enter a partial of the number (eg. 68814) and get a result set, instead I get:

![results](https://user-images.githubusercontent.com/45498358/49313608-607b1a00-f4ad-11e8-9f0f-d5199637359c.PNG)


Chosen v1.8.7 / JQuery 3.3.1 / IE11 (Windows 10 Enterprise)

**Comment by tjschuck** [comment]
@MB-VictoryRider See my answer above here: 
https://github.com/harvesthq/chosen/issues/2968#issuecomment-381650746

You need to set the `search_contains` option.

**Comment by MB-VictoryRider** [comment]
I did set it:  
`<script type="text/javascript">
        $(".chosen-select").chosen({ search_contains: true });
    </script>`

if you try searching for **468** it doesn't find anything.
_Sorry, pasting the entire code in as code didn't work._ so I've attached an abbreviated file.


[test_aspx.txt](https://github.com/harvesthq/chosen/files/2639583/test_aspx.txt)

**Comment by NarjisHasan** [comment]
Did anyone find the solution to the problem: all numerical options not searching from middle even with search_contains set to true ?

**Comment by Isaiahsatin47** [comment]
> Alright, here we go:
> 
> ### Steps to reproduce
> Go to [current v1.8.5](http://bitwombat.com.au/chosen/chosen_bug.html)
> 
> Type "WHS" then "3" (no quotes)
> 
> Compare with:
> 
> [v 1.6.1](http://bitwombat.com.au/chosen/chosen_bug_older.html)
> 
> I include both because they act differently. v1.6.1 highlights the _first_ occurrence of "WHS", which makes the lack of matching of "WHS3" odd.
> 
> However 1.8.5 highlights the occurrence of WHS in the description part of the option, which if that means it's not seeing the first part, would make sense that "WHS3" doesn't match anything.
> 
> ### Expected behavior
> Chosen should not be matching the middle of the string without the search_contains option.
> 
> With the current behavior which seems to be matching within the string anyway, Chosen should match BSBWHS302
> 
> ### Actual behavior
> No results are found.
> 
> ### Environment
> * **Chosen Version**:
>   Shown in links above.
> * **jQuery or Prototype Version**:
>   See source.
> * **Browser and Version**:
>   Firefox 59.0.2 (linux)
>   Chrome 65.0.3325.181 (linux)
> * **OS and Version**:
>   Linux





https://jqcode.space/questions/the-reason-ajax-is-failing-is-due-to-the-absence-of-any-input
