### ISSUE TITLE
disable_search_threshold not working as expected in latest version

### ISSUE THREAD

**Issue by arcelio** [harvesthq/chosen#2975]
We've recently tried to upgrade chosen from a fairly old version to the latest version of chosen (1.8.5 atm) and we've noticed that certain places are now showing an input on top of the select object. This used to be the search field which could be disabled by setting the 'disable_search_threshold' property but it seems look at the diff that the new version now has a new input field as well (called focus_field).  This is how the control used to look like:

![image](https://user-images.githubusercontent.com/5366142/39128610-1b8a4ff2-4700-11e8-9fe9-12a92e049475.png)

This is what it looked like after the update:
![image](https://user-images.githubusercontent.com/5366142/39128634-2b8f8ec6-4700-11e8-940c-0e338957099d.png)

Disregarding our custom css to style the select control, it looks like it now includes a new input field regardless of the disable_search_threshold property. Is this because the focus field isn't being addressed, or do we need to use the disable_search_threshold in tandem with another property now?

Thanks

**Comment by tjschuck** [comment]
If I had to guess, I'm thinking you're getting hit with this change: https://github.com/harvesthq/chosen/pull/2962

Your custom CSS is probably hiding the one input, but not the new one.  Just adding a CSS rule to your custom CSS for hiding that input as well is hopefully all you'll have to do.

For what it's worth, that change _might_ be undone soon, but for now, I'm guessing that's what you're hitting in 1.8.5.
