### ISSUE TITLE
In some cases not a all selected values returned

### ISSUE THREAD

**Issue by zopyx** [harvesthq/chosen#2978]
We are using Chosen since version 1.4.X usually for multi-select field with the jquery-sortable plugin.

In some cases we notice exactly one particular value of a selected item is not returned. Let's say you chose A, B, C and you save the form then the backend will see only A and B but not C. ALso you can choose C alone...it won't be saved..

Chosen is integrated into the Plone CMS and I really can't see the value of C in the browser dev tools....that's driving me crazy...any idea how to hunt this down?

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

Closing until more info is provided, then we'll reopen.
