### ISSUE TITLE
Not able to fire on-change event

### ISSUE THREAD

**Issue by mtkfork** [harvesthq/chosen#2982]
`<select class="sel" on-change='myevent'>
        <option value="hello">hello</option>
        <option value="world">world</option>
 </select>`

$('.sel').chosen()

// myevent definition //

**Comment by muralisugu** [comment]
click event only it is working fine. but when remove the tags it is not working.
please give suggestion for this error

$('.sel').chosen()

**Comment by muralisugu** [comment]
These it is working fine.

pls read documentation 

https://harvesthq.github.io/chosen/

$("#form_field").chosen().change( … );
