### ISSUE TITLE
jQuery 3+ support

### ISSUE THREAD

**Issue by jkneepkens** [harvesthq/chosen#3000]
I'm trying to get this chosen-js plugin (1.8.5) to work in combination with jQuery version 3.3.1. But when i have the jquery-migrate script running, i get the following warning:`JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated`
This warning is being set because of this line in chosen: `return this.search_field.blur();` and also for this one: `this.search_field.focus();`
For the latest jQuery this need to be changed to `return this.search_field.trigger("blur");` and `this.search_field.trigger("focus");`
Is it possible to change this plugin to get it to work with the latest jQuery version?

**Comment by stof** [comment]
This plugin is working. The `.blur()` shorthand is not removed in jQuery 3 (and I don't even think they plan to remove it in 4.0. They only removed it from the slim build).

**Comment by jkneepkens** [comment]
Oh then it's strange that the jQuery migrate plugin marks this as an warning... Is it the same for the .focus shorthand function?

**Comment by stof** [comment]
yes. Shorthands are not yet planned for removal from the full build.

**Comment by jkneepkens** [comment]
Thanks for your reply! I will ignore those warnings for now :-)
