### ISSUE TITLE
Octal literal in strict mode

### ISSUE THREAD

**Issue by ps1x** [harvesthq/chosen#3001]
Latest version of chosen from npm.
When using chosen with webpack build process the "Octal literal in strict mode" error appear when trying to build application in production mode.

`import "chosen";`
This already makes an error.

If i replace line 62 in main.js from:
`        var exit = ["\003", "\x1b"];`
to
`        var exit = ["\x003", "\x1b"];`
then it works without a problem, but i'm not sure if it's correct way to solve it.

**Comment by stof** [comment]
This repo is for the `chosen-js` npm package, not for the `chosen` one. They are totally different packages.
