### ISSUE TITLE
Inputs are showing autofills/autocompletes

### ISSUE THREAD

**Issue by drdrak3** [harvesthq/chosen#3002]
### Recommended action

Change all inputs inside the component to type="search" and all css references to type="text" will need to be changed as well.

**Comment by tjschuck** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#Differences_between_search_and_text_types, this seems like a no-go both stylistically (Chrome will add a cancel ⓧ that we don't want) and behaviorally (Firefox will autocomplete it like this suggestion is trying to avoid).

If you can figure out a way to avoid the behavior your seeing using `type="text"` or to mitigate the two issues above using `type="search"`, a PR would be welcome!

**Comment by drdrak3** [comment]
I just tested the above points and both are not an issue in fiddle I have set up.
https://jsfiddle.net/Lv2gzjqe/4/

- Chrome's ⓧ is simply removed via css
- Firefox autocomplete is removed with autocomplete="off", which is obeyed on type="search" fields

I would post a PR, except not sure where to make the Javascript updates, not really across Coffee script
