### ISSUE TITLE
Feature Request: GetChosenOrder() and SetChosenOrder() to get and set in the order chosen (with working code)

### ISSUE THREAD

**Issue by garyhoff1** [harvesthq/chosen#3007]
New feature request: two new methods, GetChosenOrder() to get items order the user selected them, and GetChosenOrder() the order provided in the values array.

I have a working version of this functionality and would like to see it incorporated into the latest official release.   I made some changes to the code in version 1.2.0, as well as GetChosenOrder and GetChosenOrder defined outside of Chosen code which should be incorporated into the chosen code.

If I knew more about chosen internals there might be a better way.  Feel free to modify as you see fit.

I have attached chosen.jquery.js. Search for GH to see the modifications
[chosen.jquery.zip](https://github.com/harvesthq/chosen/files/2173965/chosen.jquery.zip)

Code for the two functions:

```
function  GetChosenOrder($e) {
    var values = [];
    var options = $e[0].options;
    var $a = $('#' + $e[0].id + "_chosen").find('.chosen-choices .search-choice').find('a');
    for (var x = 0; x < $a.length; x++) {
        var idx = parseInt($($a[x]).attr('data-option-array-index'));
        values.push(options[idx].value);
    }
    return (values.length == 0) ? null : values;
}
```

```
function SetChosenOrder($e, values) {
	if (values == null || values.length == 0) {
		$e.val(values);
	} else {
		for (var i = 0; i < values.length; i++) {
			var $o = $e.find("[value='" + values[i] + "']");
			if ($o.length == 1) { // if still in the list
				$o.attr('chosen-seq', i);
				$o[0].selected = true;
			}
		}
	}
	$e.trigger("chosen:updated");
}
```

**Comment by tjschuck** [comment]
This is something we're definitely _not_ adding to Chosen.  It has come up a few times — see https://github.com/harvesthq/chosen/issues/1847, https://github.com/harvesthq/chosen/issues/2022, https://github.com/harvesthq/chosen/issues/2291, etc.

In short, Chosen aims to be a progressive replacement for HTML select elements. Native multi-selects don't support a notion of order — they're submitted in the order that the selected elements appear in the DOM — therefore neither does Chosen.

Thanks for providing your patch, though!  Others might find that helpful to patch in to their own apps.

**Comment by garyhoff1** [comment]
This enhancement doesn't alter existing functionality. $(e).val() works the same as before.  You have to use GetChosenOrder() and SetChosenOrder() to see a difference., and even then  $(e).val() still works the same. I don't see the down side.  Probably seems like a inconsequential feature, but when you need items in the order chosen (and not a large list) this is by far the best way I have found.

**Comment by stof** [comment]
it is not inconsequential, as it means we have to maintain it, and it changes the scope of the library (which is not just an enhancement of the native component anymore as it would store some extra state)

**Comment by garyhoff1** [comment]
I'm using chosen with my changes.  If you are interested, I'll provide a like to the code.

**Comment by abuzer-firdousi-confiz** [comment]
@tjschuck, if you are referring to the native select field. The selection of the ordering in chosen must remain same then. Like if there is a list of multi option [A, B, C, D] and user selects/clicks in order [C, D, A] the selection shows as C,D,A which is contrary to your statement that we are following native component. 

The current behavior gives the impression to user that the selection is done in order C,D,A but the options sent to server are A,C,D and get save in this order. 

On rendering again the order appears A, C, D.

Either there should 
* be order remain same 
* sorting is added
* or the selection to be shown in the same order those are being sent to server of form submit

**Comment by tjschuck** [comment]
Chosen is a visual skin.  If it had absolutely no differences from a native select, it wouldn't exist.  Displaying multi-select options out of selected order would be worse UX, so Chosen has decided to display selected options in the order selected.

However, Chosen is _just_ a visual skin.  The underlying data and what is posted to the server is the underlying native select.  That has no notion of order in a multiselect.  There's nothing Chosen can do about that without completely changing the data model of the form.

If you want ranked options, you can't use a multi-select, either native or Chosen.  (You could do ranked options with multiple _single_ selects, both native and Chosen.)

Sorry if this doesn't work for you, but this isn't going to change in Chosen.

**Comment by garyhoff1** [comment]
T.J,
When you multi select options, the browser marks them as selected by adding "selected='selected'" to the option html.Once that is done, the browser looses track of the order they were selected for a normal select statement.
However Chosen does know the order, and I was able to easily modify the Chosen code to preserve the order when I need to.I don't understand their resistance to adding this as an optional feature, but they sure don't want to.
I would like to make it a plug in, or some other method to alter the code, so I don't modify the Chosen code, but I haven't done that yet.
If you are interested, I can send you the code that I have.
Gary.

    On Tuesday, January 29, 2019, 10:48:46 AM CST, T.J. Schuck <notifications@github.com> wrote:  
 
 
Chosen is a visual skin. If it had absolutely no differences from a native select, it wouldn't exist. Displaying multi-select options out of selected order would be worse UX, so Chosen has decided to display selected options in the order selected.

However, Chosen is just a visual skin. The underlying data and what is posted to the server is the underlying native select. That has no notion of order in a multiselect. There's nothing Chosen can do about that without completely changing the data model of the form.

If you want ranked options, you can't use a multi-select, either native or Chosen. (You could do ranked options with multiple single selects, both native and Chosen.)

Sorry if this doesn't work for you, but this isn't going to change in Chosen.
