### ISSUE TITLE
Unable to compile sass using non-compass based compiler.

### ISSUE THREAD

**Issue by jakguru** [harvesthq/chosen#3011]
When using a non-compass based scss processor (in this case, webpack), the system is failing to include / require `compass` libraries. In my case it returned an error: `Module build failed: 
@import "compass/css3/box-sizing";`

### Steps to reproduce

I'm using Laravel 5.5 with webpack on Ubuntu 18.04.
Node version 8.11.3
NPM version 6.2.0
Yarn version 1.7.0
`webpack.mix.js` [removed comments]:
```
let mix = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .copy('node_modules/@fortawesome/fontawesome-free-webfonts/webfonts/', 'public/webfonts')
   .options({ processCssUrls: false })
   .version();
```

  1. Add chosen using the command `yarn add chosen-npm`

  2. Add `@import '~chosen-npm/sass/chosen';` to `/resources/assets/sass/app.scss`

  3. Run `yarn run dev`

### Expected behavior

Compilation is successful

### Actual behavior

Multiple Error message related to required files which aren't present

### Environment

Laravel 5.5 with webpack on Ubuntu 18.04.
Node version 8.11.3
NPM version 6.2.0
Yarn version 1.7.0
`webpack.mix.js` [removed comments]:
```
let mix = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .copy('node_modules/@fortawesome/fontawesome-free-webfonts/webfonts/', 'public/webfonts')
   .options({ processCssUrls: false })
   .version();
```
### Additional information

I suggest either requiring a package like `compass-sass-mixins` as a dependancy, or including the relevant files in the project.

**Comment by tjschuck** [comment]
`chosen-npm` isn't us!  You want the package [`chosen-js` on NPM](https://www.npmjs.com/package/chosen-js).

Regardless of that, the SASS in Chosen is just for development — you shouldn't be including that in your app.  `chosen-js` on NPM is the pre-built version that includes the actual compiled CSS that you can just include like you normally would.
