### ISSUE TITLE
placeholder_text for Standard Select search field

### ISSUE THREAD

**Issue by SailorMax** [harvesthq/chosen#3012]
Can you add support of `placeholder_text` setting as placeholder for Standard Select (https://harvesthq.github.io/chosen/) search field?

Possible this change:
after string https://github.com/harvesthq/chosen/blob/master/coffee/chosen.proto.coffee#L279
add `@search_field.placeholder = @default_text`

### Environment

  - **Chosen Version**: 1.8.5
  - **jQuery or Prototype Version**: 3.2.1
  - **Browser and Version**: Chrome 67
  - **OS and Version**: Windows 10

**Comment by tjschuck** [comment]
Chosen already supports placeholder/default text: https://harvesthq.github.io/chosen/#default-text-support

**Comment by SailorMax** [comment]
@tjschuck Currently it supports placeholder only for selects with multiple choice! Standard Select allow only single choice.

**Comment by tjschuck** [comment]
@SailorMax Nope — check out the very first example for a single select with default text: https://harvesthq.github.io/chosen/#standard-select

Please see the note on the default text docs:

> Note: on single selects, the first element is assumed to be selected by the browser. To take advantage of the default text support, you will need to include a blank option as the first element of your select list.

You probably just need a blank first option.

**Comment by SailorMax** [comment]
@tjschuck  You tell me about wrong place for placeholder.
Steps:

1. open https://harvesthq.github.io/chosen/#standard-select
2. click on "Into This" select to open it

= in opened "frame" you can see "search" field and list of items. I tell to use placeholder for **this "search" field**. Not for select itself.

**Comment by tjschuck** [comment]
Hm, okay.  Why would you want that?

**Comment by SailorMax** [comment]
When using Chosen with https://github.com/michaelperrin/ajax-chosen/ opened list is empty and I need write somewhere that user have to write something to find something.
I understand that it is not your problem, but maybe some time you will add support ajax-lists also and this issue will be already fixed ;)
