### ISSUE TITLE
.val() gives the wrong value

### ISSUE THREAD

**Issue by McFcologne** [harvesthq/chosen#3015]
I have a pretty huge option list used with chosen:

```
<select id="sourceSelection" class="chosen">
<option value="011111:DEV:tXXXestMcF with ';1127">011111:DEV:tXXXestMcF with '</option>
<option value="011111:All-Smartphones;235">011111:All-Smartphones</option>
<option value="All-Smartphones;-1">All-Smartphones</option>
...
<option value="user-katharina;87">user-katharina</option>
<option value="web@work;10">web@work</option>
</select>
```

Here is, how i activate chosen:
`$("#sourceSelection").chosen({search_contains: true}).trigger("chosen:updated");`

When i type: "All-Sm" and select "All-Smartphones", the command: $('#sourceSelection').val() returns '011111:All-Smartphones;235' which is wrong.

I found no documented way to ensure to update the selection to the select.

As a work around i wrote a small function which fixes this issue forall .chosen components on my page:

```
function updateChosen() {
    $("select.chosen").each(function () {
        console.log('check: ' + $(this).attr('id'));
        if ($('#' + $(this).attr('id')).length === 1 && $('#' + $(this).attr('id') + '_chosen span').length === 1) {
            console.log('found: ' + $(this).attr('id'))
            if ($('#sourceSelection option:selected').text() !== $('#' + $(this).attr('id') + '_chosen span').text()) {
                console.log('fix: ' + $('#sourceSelection option:selected').text());
                $('#' + $(this).attr('id') + ' option').each(function () {
                    if ($(this).text() === $('#' + $(this).parent().attr('id') + '_chosen span').text()) {
                        $(this).attr("selected", true);
                        console.log('fixed: ' + $('#sourceSelection option:selected').val());
                        return false;
                    }
                });
            }
        }
    });
}
``` 

Is this a known issue and will this be fixed?

**Comment by tjschuck** [comment]
This would be pretty surprising — that's pretty much saying "Chosen doesn't work at all", which would be shocking!

What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Can you link to a [Fiddle](http://jsfiddle.net) or publicly accessible page that shows the issue?
