### ISSUE TITLE
How get the selected values on multiple selection

### ISSUE THREAD

**Issue by SebastianCBA** [harvesthq/chosen#3027]
I get this code

```
<select chosen multiple options="categories" ng-model="related_categories" name="related_categories[]" id="related_categories[]"
                  ng-options="category.value as category.text for category in categories" 
                  placeholder-text-multiple="Categories">
          </select>

<button class="btn bt-default btn-lg connectsocial-bt-continue" href="javascript:;" step-next ng-click="saveartist()">Finish & publish</button>
```

how I can get the selected values on an angularjs function like:
```
$scope.saveartist = function()
{
console.log($scope.related_categories);
}

```

**Comment by tjschuck** [comment]
The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions (like this one) that are not bugs in Chosen itself, please post somewhere like [StackOverflow](http://stackoverflow.com/).  You'll be more likely to get a quick answer there.

For what it's worth, this doesn't have anything to do with Chosen per se — Chosen is just visually decorating a standard `select` element.  Ultimately, you probably just want to do some standard Javascripting on the underlying `select`. The data of Chosen is just the normal data of your regular HTML `select`.

You can also check out something like https://github.com/leocaseiro/angular-chosen — I don't use Angular, so I can't say if this will help or not, but maybe it will!
