### ISSUE TITLE
2 dropdowns showing instead of one

### ISSUE THREAD

**Issue by SalmanJavaid05** [harvesthq/chosen#3049]
I am getting this issue with chosen select, it shows 2 dropdowns, one with simple dropdown list  option and the other with chosen select dropdown list option.

  - **Chosen Version**: 1.1.0

Image is attached to show how it renders on browser.

![image](https://user-images.githubusercontent.com/22293369/56216844-9a734400-607b-11e9-8350-32f4eb952d65.png)

**Comment by tjschuck** [comment]
Chosen 1.1.0 is [over 5 years old](https://github.com/harvesthq/chosen/releases/tag/v1.1.0).  Please update to the latest version and see if you're still having your issue.

Aside from that, what browser, browser version, OS, and OS version are you using?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
