### ISSUE TITLE
jQuery loaded separately and Chosen Plugin not working

### ISSUE THREAD

**Issue by muhamed87** [harvesthq/chosen#3060]
Dears,

I already loaded **jQuery** separately and then loaded the **chosen.proto.min.js** when I open the browser to check I don't get the plugin work, and I check the console and I see the following error:

**Uncaught TypeError: $(...).chosen is not a function**

I loaded **chosen.jQuery.min.js** instead and I get it works perfectly, but I don't know if it is ok to load 2 jQuery plugins? Will that make conflict in other functions or in other pages?

**Comment by koenpunt** [comment]
`chosen.jquery.min.js` doesn't include jquery, it's just just the version that's built for usage with jquery.

Same for the proto version, that's for usage with prototypejs
