### ISSUE TITLE
Chosen not working on IE 11 

### ISSUE THREAD

**Issue by 2ndSamurai** [harvesthq/chosen#3072]
Summarize your issue here.
Chosen does not work with 10000+ items. Works fine on Chrome and Opera
### Steps to reproduce

Tell us how to reproduce this issue.

  1. Try loading 10000+ items on MVC 4 page

  2. Run application 

  

### Expected behavior

The Items should be loaded and selectable on DropdownListFor

### Actual behavior

Page Freezes

### Environment

  - **Chosen Version**: 1.4.2

  - **jQuery or Prototype Version**: 3.4.1

  - **Browser and Version**:IE 11

  - **OS and Version**: Windows 7 Pro Service Pack 2

### Additional information

Any other information you want to share that is relevant to the issue being reported. This might include the lines of code that you have identified as causing the bug, or potential solutions and workarounds.

**Comment by tjschuck** [comment]
Version 1.4.2 of Chosen is four and a half years old.  Please try upgrading to [the latest version of Chosen](https://github.com/harvesthq/chosen/releases) and let us know if you're still having issues.
