### ISSUE TITLE
How to use chosen with Blazor?

### ISSUE THREAD

**Issue by abdulqayyum** [harvesthq/chosen#3078]
I have following html in razor component that works but when I render drop down with Chosen it stops working. because chosen do not update actual drop down value it creates its own element that holds selected value. but i can not access that so how to trigger the onchange event then?

```
<select id="search" single class="chosen-select" @onchange="UpdateValue" bind="@searchValue">
        ...
</select>
...In @Code
void UpdateValue(ChangeEventArgs e)
{
    searchValue = e.Value.ToString();
    ... 
}
```

Now if I initialize drop down with chosen then I can not detect on change but can other wise. I am using Blazor GL - Server Side with .net core 3.0.1

**Comment by tjschuck** [comment]
Check out this section of the docs: https://harvesthq.github.io/chosen/#change-update-events

Primarily, what you're probably after is `$(".chosen-select").trigger("chosen:updated");` — if you've changed the underlying select in any way, you can call that and it will rebuild Chosen to reflect the updated state.
