### ISSUE TITLE
Is it possible to modify Chosen so that "chosen-search" div won't take up vertical space when select box isn't expanded?

### ISSUE THREAD

**Issue by vkelman** [harvesthq/chosen#3079]
It's not a bug, just a question.

Activating Chosen on a select box drastically modifies vertical alignment of a form.
F12 screen seems to show that additional vertical space it taken up by "chosen-search" div - even when select is not expanded.
It would be very nice if a closed "chosen" box didn't require [much] additional vertical space, comparing to a regular select box.   Do you think this would be a feasible change?

**Comment by vkelman** [comment]
My mistake. Our code developed before I was placed there had explicit 
```
.chosen-container {
  margin-bottom: 3.5rem; }
```
Removing that style fixed everything.

**Comment by tjschuck** [comment]
Thanks for following up, @vkelman! Glad you got it sorted.

**Comment by vkelman** [comment]
@tjschuck - I must admit, Chosen is the best jQuery select plugin I ever encountered. Really good looking, convenient, flexible, easy to use in a code.  Thank you.

**Comment by tjschuck** [comment]
@vkelman Thanks for the kind words!  That was a real nice end-of-year treat.
