### ISSUE TITLE
chosen hides selected option

### ISSUE THREAD

**Issue by ishan-shah** [harvesthq/chosen#3089]
Hello,
My issue is regarding selected options in chosen multiple select. When I select the first option, it sometimes hides in the body OR sometimes visible only half value.I am attaching an image for the said issue. Kindly, guide me regarding this.

![image](https://user-images.githubusercontent.com/51081190/84344163-a8f9b480-abc7-11ea-9cc7-cc4b3c823a59.png)

**Comment by tjschuck** [comment]
What browser, browser version, OS, and OS version are you using?  And what version of Chosen?  If not the latest version, does it still happen on the [latest version](https://github.com/harvesthq/chosen/releases)?

Additionally, please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.  Alternatively, confirm that the [Chosen demo page](http://harvesthq.github.io/chosen/) shows the issue.

Closing until more info is provided, then we'll reopen.
