### ISSUE TITLE
Modal validation in mvc

### ISSUE THREAD

**Issue by MahammadMoine** [harvesthq/chosen#3094]
I am using chosen for Country field as $("#Country").chosen() in MVC.net but for this field modal validation not firing,
because library adding css display none for this element.

When I am using $("#Country").css("display", "").addClass("sr-only"); after calling $("#Country").chosen() then working fine so,
I want to suggest to use "sr-only" class of bootstrap in place of display none.

Thanks.

**Comment by pjfsilva** [comment]
This is not a problem with chosen but with MVC.net , actually jquery.validate, https://jqueryvalidation.org/validate/#ignore, that by default doesn't validate :hidden fields.

What I do is just add a special class to that Country field like `js-validate` and then run this code on that page:

`
$.validator.setDefaults({
        ignore: ":hidden:not(.js-validate)",
        onfocusout: function (element) {
            $(element).valid();
        }
    });
`

Please close as this is not chosen related.
