### ISSUE TITLE
Differences of chosen single behavior compared to native selects when clicking outside/pressing ESC

### ISSUE THREAD

**Issue by k-risc** [harvesthq/chosen#3098]
I was wondering to which extend the differences in the behaviors are on purpose.

Given the fact we compare a native select with a chosen single select. We open both selects and then navigate using the cursor keys to highlight another option. We then either click outside of the select, or hit the ESC key, so that the selects' dropdowns are closed.

Chosen: The previously selected option is displayed again, no change event is triggered

Native: The option which was highlighted in the dropdown is selected, a change event is triggered

Would it not make more sense to rebuild the behavior of native selects?

**Comment by JJJ** [comment]
> The option which was highlighted in the dropdown is selected, a change event is triggered

This must be browser dependent. In Safari on macOS, hitting ESC does not trigger a change event, and the previously selected option is displayed again.
