### ISSUE TITLE
Set selected value with javascript

### ISSUE THREAD

**Issue by mrpohoda** [harvesthq/chosen#31]
Setting selected value with javascript doesn't work. I know that chosen() adds class single_examplechzn_o_0 to `<li>` which has nothing in common with option value and that #single_example no more exists after chosen(). Is there a way this can work?

This works:
```<select style="width:200px" id="single_example">
     <option value="1">1</option> 
     <option value="2">2</option> 
</select>

```

```

$("#single_example").val(2);

``````

This doesn't work:
```<select style="width:200px" id="single_example" class="chzn-select">
     <option value="1">1</option> 
     <option value="2">2</option> 
</select>
``````

```
$("#single_example").val(2);
```

**Comment by comtronix** [comment]
gpdhillion:
use this
$('.album-select').val([1,2,3]).trigger('chosen:updated');

**Comment by binamaniar** [comment]
$ ("#id").val(id_value);
$("#id").chosen('destroy');
$("#id").chosen({});

**Comment by hemanthkumarg70** [comment]
Use below code for multiple selection it works for me.

Javascript:- 

function btnupdate() { 
      $("#single_example").chosen().val(['2', '1']).trigger("chosen:updated");     
    }

HTML:- 
 <select style="width:200px" class="chosen multiple" multiple="multiple"  id="single_example">
 <option value="1">1</option> 
 <option value="2">2</option> 
</select>
 <button id="ins"  onclick="btnupdate();return false;">Insert</button>
