### ISSUE TITLE
Selected options overwrite other options in multi-select dropdown

### ISSUE THREAD

**Issue by MichaelEC** [harvesthq/chosen#3113]
Hi,

Chosen has been working fine, although there's one small issue which I can't seem to figure out why is happening.

I have a multi-select dropdown and if you select 2 options, close the modal and then re-open it. The dropdown then has both those selected options at the top of the dropdown, replacing the two that was there previously.

It may be easier to explain with images, I'll show below:

![image](https://user-images.githubusercontent.com/39829763/105897844-9cb84f80-6010-11eb-9ad1-4088108bba02.png)

As you can see, Users 2 & 3 have been selected and now they're greyed out below which is correct, although I can select User 3 again and User 1 has been essentially over-written by User 2, meaning I can't select User 1 anymore.

Any ideas?

**Comment by pjfsilva** [comment]
Can you provide a code example (codepen, jsfiddle) where this is happening? As you can clearly see on chosen demo site, this works properly so it must be related to something special on your code. Remove all extraneous code and try to provide us a code example for this. 

Make sure the HTML for your select is properly formed (closed tags in the right place and all) and that you don't have repeated values for different options.

**Comment by tjschuck** [comment]
Closing pending Fiddle/more info; will reopen when it's provided.

**Comment by MichaelEC** [comment]
Hi, this can be kept closed - nothing wrong with Chosen! realised it was my own mistake after re-writing it from top down!

**Comment by tjschuck** [comment]
Great, thanks for following up, @MichaelEC!
