### ISSUE TITLE
How to deactive plugin

### ISSUE THREAD

**Issue by new-furry** [harvesthq/chosen#3114]
I wanna deactive plugin when some conditions change.
plugin should support that function. I am not sure if I didn't find that function.
could you pls help me this? It's pretty urgent.
thx

**Comment by tjschuck** [comment]
Mark the underlying `select` as `disabled`, and then trigger `chosen:updated`: https://harvesthq.github.io/chosen/options.html#triggerable-events

**Comment by new-furry** [comment]
Hi @tjschuck . thanks for your quick response.
But I still need to use select tag.
I need to deactive plugin just.

**Comment by new-furry** [comment]
also, your solution is not working...

**Comment by tjschuck** [comment]
https://harvesthq.github.io/chosen/#change-update-events

`chosen("destroy")` to destroy Chosen and revert back to the native select.

**Comment by new-furry** [comment]
great!. it works. thank you @tjschuck
