### ISSUE TITLE
Fails to load when Chrome is set to touch mode

### ISSUE THREAD

**Issue by qianshancun** [harvesthq/chosen#3125]
Fails to load when Chrome is set to touch mode:

This issue happens on the official page:
https://harvesthq.github.io/chosen/

Screenshot:

![image](https://user-images.githubusercontent.com/85496448/140494431-d2603813-69c3-4b8a-a15a-82d9144c51eb.png)

**Comment by tjschuck** [comment]
@qianshancun Are you talking about `#top-chrome-touch-ui` in chrome://flags/ ?  If so, I cannot reproduce.

If you're talking about changing the "Device" in the web inspector, this behavior is expected if you're changing to a device with a mobile `Android` user-agent.  See [the third question in the FAQ](https://harvesthq.github.io/chosen/#faqs).  Chosen is disabled for any user-agent that includes both `Android` and `Mobile`.

**Comment by qianshancun** [comment]
> @qianshancun Are you talking about `#top-chrome-touch-ui` in chrome://flags/ ? If so, I cannot reproduce.
> 
> If you're talking about changing the "Device" in the web inspector, this behavior is expected if you're changing to a device with a mobile `Android` user-agent. See [the third question in the FAQ](https://harvesthq.github.io/chosen/#faqs). Chosen is disabled for any user-agent that includes both `Android` and `Mobile`.

You can do this to reproduce it:

![image](https://user-images.githubusercontent.com/85496448/140598430-3540d4e6-8091-4554-b23c-466f2b1fdc36.png)

**Comment by tjschuck** [comment]
@qianshancun Okay, that's the second thing I mentioned.  I can reproduce when I do what's shown in your screenshot, but using those settings, my request has the User Agent `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Mobile Safari/537.36` — that User Agent matches on the `Android` + `Mobile` check, so Chosen is intentionally disabled.

See https://github.com/harvesthq/chosen/pull/1388 for more info about why Chosen is disabled in touch environments.

**Comment by qianshancun** [comment]
Hi, thanks very much for the information. Is there any way I could keep it enabled? Like passing in an option like this:

    $el.chosen({bypass_mobile_disable:true});

**Comment by tjschuck** [comment]
There's no existing option like that, no.  Your best bed would just be to locally modify the `browser_is_supported` check to do what you'd like.
