### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by andrewmoise** [harvesthq/chosen#3141]
Hello, are you open to help with maintaining this project? I actively use it and it's great for me; since it's not hosted anymore I'm probably planning to build it locally + make some updates + start hosting it just so I can use it, and I'd be happy to take on a more official maintainer role if that's something useful / something you're open to.

**Comment by tjschuck** [comment]
Chosen is not currently under active development, and we're not currently looking for "official" maintainers.

However, it is released under the MIT License and you are free to fork it and modify it to your heart's content, [in accordance with the license](https://github.com/harvesthq/chosen/blob/master/LICENSE.md).

A popular Chosen alternative, [Select2](https://select2.org), began its life as a Chosen fork, so the sky's the limit!

**Comment by andrewmoise** [comment]
Ah, got it -- if there's a successor I'm happy to just use Select2; I just thought it was a good thing and didn't want it to die. Thanks for all your work on it + I'll check out Select2 instead 👍
