### ISSUE TITLE
Please set this project as Archived if it is not maintained

### ISSUE THREAD

**Issue by 7h3Rabbit** [harvesthq/chosen#3147]

**Comment by tjschuck** [comment]
There is a deprecation notice in the repo description, and [a large deprecation notice at the top of the README](https://github.com/harvesthq/chosen?tab=readme-ov-file#deprecated).

The reason we haven't archived the repo is that Chosen is still perfectly functional.  It works as-is, and we haven't had a credible show-stopping bug report in ages.  It's not actively being _developed_, but it's still arguably being "maintained" (hi!), so no need to archive it.

**Comment by makarovpro** [comment]
Everything works and I use this product, nothing needs to be closed!
