### ISSUE TITLE
jQuery Type error 

### ISSUE THREAD

**Issue by anish-kumarbasti** [harvesthq/chosen#3153]
$(document).ready(function() {
            $('#service').chosen();
            $('#userid').chosen();
            $('#service').on('change', function() {
code note run
 alert('Ok');

**Comment by tjschuck** [comment]
Not really enough information here to help you.

Please link to a publicly accessible page (or a [Fiddle](http://jsfiddle.net)) that shows the issue so we can attempt to reproduce.

Closing until more info is provided, then we'll reopen.
