### ISSUE TITLE
allow_single_deselect

### ISSUE THREAD

**Issue by nyfer** [harvesthq/chosen#339]
i want to add allow_single_deselect: true , where in the code should i add it?

**Comment by webislife** [comment]
does not work

**Comment by isochronous** [comment]
This still does not work. We're passing in `true` for the option value and have an empty option as the first in the list.

**Comment by webislife** [comment]
It's work! Just need add empty option before domcontentload!

**Comment by isochronous** [comment]
The way we load the data for the controls means that chosen is initialized
with no options in the DOM. The options are loaded via ajax, inserted into
the DOM, and then we trigger the 'chosen:updated' event.  The "deselect" X
is NOT added to the selected option dom, and there is no way to deselect
the selected option.

**Comment by donpedro** [comment]
I had the same problem; it seems to need the empty option upon init.  So, if your tag looks like 
```html
<select class="chosen-select">
  <option></option>
</select>
```
when you initialize chosen, you can then update options with via dom, trigger 'chosen:updated' and you get the "deselect" X.  You don't even seem to need a blank option at that point.
