### ISSUE TITLE
Chosen Inside iFrame Not Overlapping

### ISSUE THREAD

**Issue by ghost** [harvesthq/chosen#355]
Chosen inside iframe not overlapping container like normal select box.

jQuery 1.6.4 / Firefox 8.0 / Mac OS X 10.6.8 

![Chosen Inside iFrame Not Overlapping](http://dl.dropbox.com/u/627571/chosen-iframe.png)

**Comment by Delgaranor** [comment]
Hi Janne,

It was some time ago that I was experimenting with this, and it still didn't work.
At that time I had little experience with HTML and Javascript, but now I see I made a stupid mistake.
I'm not using iFrames, but a page build up from normal frames.

Do you know something to make it work for normal frames?

Thanks!

**Comment by Rastik80** [comment]
You have errors in your fixing code. On the line 1 and line 4 there should be "= function" instead of ": function". After correction it works perfectly.

**Comment by WhitecastlePT** [comment]
Hello everyone. I tried to use this solution and in fact, the dropdown overlaps the iframe has promised. But the CSS is not applied to it plus if you have an onclick event attached to every option doesn´t get executed. Any ideas? 

Here are some images for what I'm talking about:
[https://ibb.co/c8ofTo](url)
