### ISSUE TITLE
allow_single_deselect does not work if first option has text

### ISSUE THREAD

**Issue by mikejolley** [harvesthq/chosen#362]
In the code you have:

``` this.allow_single_deselect = (this.options.allow_single_deselect != null) && (this.form_field.options[0] != null) && this.form_field.options[0].text === "" ? this.options.allow_single_deselect : false;```

This means it only works when 'text' is empty - well if you have a first option like this:

```<option value="">N/A</option>```

For example, it won't work. Changing it from 'text' to 'value' solves the issues:

``` this.allow_single_deselect = (this.options.allow_single_deselect != null) && (this.form_field.options[0] != null) && this.form_field.options[0].value === "" ? this.options.allow_single_deselect : false;```

**Comment by pfiller** [comment]
> Can this problem not be solved by setting `data-placeholder` on the `select` element?

It can be!
