### ISSUE TITLE
Binding to a dynamically created drop down list?

### ISSUE THREAD

**Issue by KevinUK** [harvesthq/chosen#363]
Hi,

Is there a function I can call to bind a drop down list created after the page has loaded?

I have a copy of an existing chunk of HTML and so have a duplicate of another chosen drop down and have changed the new one so that it has a different random id but when I click on the drop down nothing happens, the one that was bound on page load continues to work properly.

Thanks,
Kevin

**Comment by tibinvpaul** [comment]
@jaminto Your solution helped me! Thanks a lot :)
