### ISSUE TITLE
Update Panel

### ISSUE THREAD

**Issue by pahamad** [harvesthq/chosen#369]
I am using inside the update panel (Asp.net), when page first time loading its looks good and working fine but when page is posting back in update panel then look & Feel get break and stop working search functionality.

Please do the needful.

Thanks,
Parwej

**Comment by nilesh9724** [comment]
If any example?
please give an example for re-apply the jquery selector after each time the update panel updates

**Comment by stof** [comment]
I just edited the message posted by @joejwright above to fix the markup, so that the code snippet is visible

**Comment by nilesh9724** [comment]
You have some example for update panel?
