### ISSUE TITLE
.chosen().change() not working

### ISSUE THREAD

**Issue by gav-fyi** [harvesthq/chosen#383]
Hi, I am wanting to update the the options in one chosen based on the value selected in another, using AJAX.

I have the underlying AJAX code working great on standard selects, but when I try either of the following two code snippets to trigger a change, it does not work.

I get the alert() on page load, but not when I change the value of the select with id "categories"

[code]

$("#categories").chosen().select(alert());
$("#categories").chosen().change(alert());

[/code]

**Comment by phqvince** [comment]
var choice, close_link,
                _this = this;
            choice = $('<li />', {
                "class": "search-choice"
            }).html("<span>" + item.html + "</span>");
            if (item.disabled) {
                choice.addClass('search-choice-disabled');
            } else {
                close_link = $('<a />', {
                    "class": 'search-choice-close',
                    'data-option-array-index': item.array_index
                });
                close_link.bind('click.chosen', function(evt) {
                    return _this.choice_destroy_link_click(evt);
                });
                choice.append(close_link);
want to ask,how to addClass to <span>?

**Comment by diparthshah** [comment]
This works for me Perfectly. If someone was looking for CoffeeScript implementation, its here: 
`$('.myselect').chosen().change(`
	`(event) ->`
		`console.log "data changed"`
`) `

**Comment by amiranbari** [comment]
i have same thing here. no solution worked for me!
