### ISSUE TITLE
chosen.css: z-index issue

### ISSUE THREAD

**Issue by axwax** [harvesthq/chosen#39]
Hi,
first of all great piece of code!
There's a small issue with z-index in the default stylesheet:
a.chzn-single gets assigned a z-index of 19 (in line 75 of chosen.css at the time of writing).
This can lead to clashes with other jquery widgets, such as the ui datepicker, which get displayed behind the (closed) dropdown field.
Removing that line and adding <pre>div.chzn-container a.chzn-single-with-drop{
    z-index:19;
}</pre> instead seems to fix the issue for me.

There is probably a similar issue with the multiple select box (I think it may be ul.chzn-choices which gets assigned a z-index of 21), but I haven't had a proper look at that yet.

Cheers,
Axel

**Comment by Rajats786** [comment]
> 
> 
> To be frank, this last post helped, but it wasn't entirely the fix for me.
> My chosen css file is custom made so I couldn't be 100% sure if I triggered the issue or not.
> I tried it with the original one and the problem was the same.
> 
> My solution:
> If you have a holder (p,div etc) for your input as in the example below, set relative you have t o remove it's position. That will do the trick. It worked for me!
> 
> p, {position:relative; // REMOVE THIS}

thank you it's working
