### ISSUE TITLE
Items not displaying when dropdown is opened

### ISSUE THREAD

**Issue by ryexley** [harvesthq/chosen#437]
I've created a _very_ simple select list and applied the chosen plugin to it, and I've attempted to follow the provided examples as closely as possible (though I wish there was more/better documentation for the available plugin options...am I missing something?), and yet for some reason, when I open the list (click the dropdown) on the resulting list, Firefox (9.0.1) is the only browser that displays the available options.

I'm using plugin version 0.9.5, and this is my code:

```
<!-- markup -->
<select id="sort-order" name="sort-order" data-placeholder="Sort order">
    <option value=""></option>
    <option>Most recent first</option>
    <option>Oldest first</option>
</select>

// JS
$(function () {
    $('#sort-order').chosen({ allow_single_deselect: true });
});
```

The control seems to render itself just fine, the search box is there, and it's even sized appropriately for the number of items/options in the list, but the items/options themselves aren't displayed in any modern browser other than Firefox. Inspecting the element in both Firebug and Chrome dev tools appear to indicate that the problem is with the CSS for `ul.chzn-results` and its contained `li`s, though I'm not completely certain of that. More details and version information is below. If anyone has any ideas what the problem might be and/or how to get around it, that would be much appreciated.

OS: Windows 7 (64 bit)
jQuery: 1.7.1
Chosen: 0.9.5
Google Chrome: 16.0.912.75 (doesn't work in this browser)
Safari: 5.1.2 (7534.52.7) (doesn't work in this browser)
Internet Explorer: 9.0.8112.16421 (doesn't work in this browser)
Firefox: 9.0.1 (works in this browser)

**Comment by itsryandrake** [comment]
Still an issue for me with the latest version of Chosen in our staging environment.

 Funnily enough, working fine in development.

Tried 
.chosen-container .chosen-results { 
   margin-left: -5px; 
   clear: both; 
}

but no luck as you can see from the screenshot.
![screen shot 2015-05-06 at 9 45 39 am](https://cloud.githubusercontent.com/assets/3394807/7485129/b6d590ac-f3d4-11e4-87b1-ed48fe55def9.png)

**Comment by moyarich** [comment]
tried this, and it worked
<code> .chosen-results {
  min-width: 1px;
}</code>

**Comment by JoshiAsha** [comment]
Just comment the following line in chosen.css
`.chosen-container .chosen-drop {
  /*position: absolute;*/`

**Comment by bharti8800** [comment]
Works for me too, thanks everyone:

.chosen-container .chosen-results {
margin-left: -5px;
clear: both;
}

**Comment by timisi** [comment]
Please guys help. 1.	I have 2 HTML select option, in which the SELECTION of the first determines what is populated in the second SELECTION and display to the user. I have the code working with JAVASCRIPT, but my problem how is how to add search option using (JS CHOSEN SELECT plug-in) to the second populated SELECT OPTION because of the numbers of the options. But the CHOSEN SELECT plugin is not working in the second select option . The search is there though; on the second SELECTION Option after it must have been populated by the first SELECTION, but its empty (not displaying NOTHING!!!).
