### ISSUE TITLE
Right-to-Left monster scroll bug

### ISSUE THREAD

**Issue by jonagoldman** [harvesthq/chosen#447]
A very common bug in Firefox and Chrome is that when the page direction is set to 'rtl' and 'position' is used to place an element, the 'left:-9000px' or similar negative value creates a monster horizontal scroll instead of 'hiding' the element.

In Chosen, the 'chzn-drop' div is positioned using a negative 'left' so in LTR direction it works well but in RTL it need to be changed to a positive value.

So,
for LTR position left:-9000px is OK
for RTL it needs to be position left:9000px

Its useless to post a 9000px print-screen, so in order to reproduce the error just use Chosen with the rtl tag inside a page with rtl direction, you will notice the horizontal scroll in FF and Chrome.

I see that the position is 'hard-coded' into the plugin, so it is possible to fix this in a feature version?

**Comment by salmanshariati** [comment]
The easiest solution: 
Replace {top:e+"px",right:0"} with {top:e+"px",right:0,display:"block"}
and replace {right:"-9000px"} with {right:"-9000px",display:"none"}

**Comment by rfnbnkr** [comment]
In chosen.css change
.chosen-container .chosen-drop {
  position: absolute;
  top: 100%;
  left: -9999px;
  z-index: 1010;
  width: 100%;
  border: 1px solid #aaa;
  border-top: 0;
  background: #fff;
  box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
}`
to
.chosen-container .chosen-drop {
  position: absolute;
  top: 100%;
  left: 9999px;
  z-index: 1010;
  width: 100%;
  border: 1px solid #aaa;
  border-top: 0;
  background: #fff;
  box-shadow: 0 4px 5px rgba(0, 0, 0, 0.15);
}`
and fixed my problem
