### ISSUE TITLE
Fix for zero-width problem

### ISSUE THREAD

**Issue by gullbyrd** [harvesthq/chosen#472]
I like Chosen, but because I use a lot of ajax and hidden panels, I've been having hellish problems with Chosen rendering the selects with zero width, apparently because the width is being calculated before the select is visible.

I added a line that seems to fix this problem (or provide a workaround), at least in my case.

In the Chosen.prototype.set_up_html function, after "this.f_width = this.form_field_jq.outerWidth();", add:

```
  if (this.f_width==0) this.f_width = this.form_field_jq.css("width");
```

Obviously, this only works if the width is explicitly set in css. But in my case, it solves the problem. A better fix would be welcome.

**Comment by cortopy** [comment]
Thanks @fabioduque It also worked for me!

**Comment by wilsonsmith** [comment]
pfiller, thank you! that solved my problem.

**Comment by verybigelephants** [comment]
why does this happen sometimes? :(

**Comment by AlissonRS** [comment]
I used the css approach, because I didn't want to look all the places I used chosen (and other developers might have the same problem when building new views). So the css fixes the problem globally. Thanks @fabioduque

**Comment by tripflex** [comment]
I was running into this issue with conditional logic in one of my WordPress plugins ... specifically with the width being set to 0px ... even after init (which I queue chosen fields with `chosen:ready` so if it's already init and I hide the parent div) ... but anyways, this is what I used to fix this when my jQuery code runs to show the parent DIV element before executing `chosen:updated`

```js
// This is the original select field
$field = $( '#' + field );

// This is the select field wrapper that I hide (just shown for reference)
$( '.fieldset-' + field ).show();

// Chosen container ID will be original select element ID + _chosen
var $chosen_container = $( '#' + field + '_chosen' );
if( $chosen_container && $chosen_container.width() === 0 ){
    $chosen_container.css( 'width', '100%' );
}

$field.trigger( 'chosen:updated' );
```

**Comment by jjStanley** [comment]
If anyone else is still having this issue, check when you are calling $(".chosen-select").chosen(). I had a list of javascript function calls on page load, when I moved the .chosen() call to the top of the list it applied the width properly, no more zero width. The functions that I moved it above were retrieving some data and doing a lot of dom operations.

**Comment by GhAc-2017** [comment]
why am i having 2 search icon ,I tried both of the above solutions-
![Screenshot from 2019-08-23 00-34-17](https://user-images.githubusercontent.com/24763998/63542376-dc3a5c80-c53d-11e9-881f-432213c8090c.png)
