### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by korki696** [harvesthq/chosen#473]
I am using the following validation engine but am having issues making it work with Chosen.
http://www.position-absolute.com/articles/jquery-form-validator-because-form-validation-is-a-mess/

When I do the following:
$('.chzn-select').bind("change", function(){
$myForm.validate().element($(this));
});
It works and validates the field. Just hitting submit will validate every other field type other than chosen drop-downs. It will validate regular drop-downs.

Any ideas?
Thanks

**Comment by pfiller** [comment]
Looks like this issue had some solutions 3 1/2 years ago! I think we can safely close it.
