### ISSUE TITLE
Making a chosen input a required field

### ISSUE THREAD

**Issue by jbrooksuk** [harvesthq/chosen#496]
My original markup sets the select to be a `required` field, however Chosen doesn't seem to comply to that?

**Comment by tripflex** [comment]
If you're using Chosen for all `select` elements, you can use this CSS to change make it visible (to DOM), but no opacity, no height, absolute position.

These CSS selectors target invalid select elements, with one of them targeting `multiple` adding a `15px` `margin-top` to center it on the multiselect elements.

    select:invalid {
    	height: 0px !important;
    	opacity: 0 !important;
    	position: absolute !important;
    	display: flex !important;
    }
    
    select:invalid[multiple] {
      	margin-top: 15px !important;
    }

Demo: http://jsfiddle.net/tripflex/2zdeu9oc/
