### ISSUE TITLE
cake build fails with CakePHP 1.3.7

### ISSUE THREAD

**Issue by tych0** [harvesthq/chosen#508]
cake build fails with:

$ cake build
PHP Warning:  /usr/share/php/cake/console/templates/skel/tmp/cache/ is not writable in /usr/share/php/cake/libs/cache/file.php on line 267

Warning: /usr/share/php/cake/console/templates/skel/tmp/cache/ is not writable in /usr/share/php/cake/libs/cache/file.php on line 267
Error: Class BuildShell could not be loaded.

I'm using the cake package from Ubuntu 11.10, do I need a newer version? (If so, could the version needed be noted somewhere in the docs? :-)

**Comment by TheNotary** [comment]
Confirmed, `apt-get remove phpcake` `apt-get install coffeescript` and finally `cake.coffeescript build` worked for me, thanks Melgar.

**Comment by 275761919** [comment]
@melgar thank you very much!
