### ISSUE TITLE
How to programmatically set the value?

### ISSUE THREAD

**Issue by elneilios** [harvesthq/chosen#605]
I don't seem to be able to find much documentation for usage so I'm not sure how to set a chosen dropdown's value? 

I tried using jQuery .val() which retrieves the value but doesn't seem to be able set it. If I don't use chosen then this method works fine on an ordinary select dropdown.

E.g.
var value = $("#chzn-select").val(); // Gets the value ok

var value = 1;
$("#chzn-select").val(value); // Doesn't set the value

**Comment by michel1991** [comment]
thanks you about multiselect chosen with array.

**Comment by shaggygolvelkar** [comment]
Please can anyone help me on postback issues in asp.net. when I am going to select multiple options and click on button, everything is getting deselect and only one option is by default selected after postback.

**Comment by tjschuck** [comment]
@shaggygolvelkar The GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests.

For support issues or usage questions like yours, please post somewhere like [StackOverflow](http://stackoverflow.com/), using the [`chosen.js` tag](http://stackoverflow.com/questions/tagged/chosen.js).  You'll be more likely to get a quick answer there.

**Comment by manish07** [comment]
How do I populate the chosen value from controller. I am using multiple chosen select and from the controller when I try to open my form in the edit I am not getting value populated in the drop-down field.
So if I have selected 3 drop down item then whenever I will open my form that 3 items must be present in the drop down field with ability to add or remove items from the drop down list. How I will do that. Any suggestion.

**Comment by NirbanRouth** [comment]
Please help me... i have chosen drop down list in my page.there is input filed to search.but i have another input filed outside.I want to search in chosen drop down list from the outside input filed like chosen inner input field...please..

**Comment by NirbanRouth** [comment]
![image](https://user-images.githubusercontent.com/35569567/35104107-df216648-fc8d-11e7-9503-5072a24b9b3d.png)

**Comment by Cartonmarc** [comment]
@tjschuck https://daragh-dissonance.github.io/clayton/
