### ISSUE TITLE
Some way of setting value of the selection through JS

### ISSUE THREAD

**Issue by septerr** [harvesthq/chosen#608]
Say the select box has an id of "foo". Incorporating chose.jquery.js in our existing code base breaks any Javascript that does things like -

${'foo'}.val('1')

or 

$('foo').style.display = 'none;' //this we can resolve by enclosing all our select boxes in a span which we can hide instead of the select box itself.

Is there any way you can catch JS calls that modify the select boxes value and accordingly update the awesome drop down that chosen displays?

**Comment by Hoax87** [comment]
I was able to solve the problem by removing some (for me) unwanted code.

chosen.jquery.min.js ->

e.prototype.show_search_field_default=function(){return this.is_multiple&&this.choices<1&&!this.active_field?(this.search_field.val(this.default_text),this.search_field.addClass("default")):(this.search_field.val(""),this.search_field.removeClass("default"))}

remove this line: `this.search_field.val(""),` which will not update the input-field with the (possibly empty default value).
