### ISSUE TITLE
Selecting Options using jQuery with Multi-Select Causing Errors

### ISSUE THREAD

**Issue by Albert-IV** [harvesthq/chosen#609]
When I attempt to set a option(s) as selected in a select that accepts multiple inputs and trigger the liszt:updated event Javascript throws an error saying an element is undefined (Uncaught TypeError: Cannot call method 'find' of undefined).  

Using the example.jquery.html, I add id's to the Multiple Select field and a few of the options, and then run the liszt:updated event.

``` javascript
<script type="text/javascript">
  jQuery( function ($) {
     $(".chzn-select").chosen();
     $(".chzn-select-deselect").chosen({allow_single_deselect:true});

     $('#firstVal').attr('selected', true);
     $('#secondVal').attr('selected', true);
     $('#thirdVal').attr('selected', true);
     $('#fourthVal').attr('selected', true);
     $('#thisOne').trigger("liszt:updated");
  })
</script>
```

``` html
<select data-placeholder="Choose a Country..." id='thisOne' class="chzn-select" id="2873829*&@#$*&![]" multiple style="width:350px;" tabindex="4">
   <option value=""></option> 
   <option id='firstVal' value="United States">United States</option> 
   <option id='secondVal' value="United Kingdom">United Kingdom</option> 
   <option id='thirdVal' value="Afghanistan">Afghanistan</option> 
   <option id='fourthVal' value="Albania">Albania</option> 
   <option value="Algeria">Algeria</option> 
   <option value="American Samoa">American Samoa</option> 
   <option value="Andorra">Andorra</option> 
   ...
</select>
```

Suddenly, error.  Changing the tags to a Select with only one option seems to work fine.  Maybe I'm missing something?

**Comment by michailanatger** [comment]
@pfiller , your method, don't work.

**Comment by stof** [comment]
in chosen 1.0+, the event is `chosen:updated` rather than `liszt:updated`

**Comment by michailanatger** [comment]
@stof, not work, I am using select box object from asp.net. When I added from client-side data to select box, he not updating. I don't know how I can update this object.
