### ISSUE TITLE
"liszt:updated" resets selected option [tested for jquery version]

### ISSUE THREAD

**Issue by XiaNi** [harvesthq/chosen#610]
for example:
$("#foo").val("1").trigger("liszt:updated").val() 
returns empty string

without trigger works as expected
$("#foo").val("1").val() returns "1"

**Comment by sampathcse5816** [comment]
I have also faced same problem. The below syntax helped me to solve the issue.

 Jquery:
 $('.chosen-control').val('').trigger('liszt:updated');

Reference:
https://wikigurus.com/Article/Show/32498/How-do-I-reset-a-jquery-chosen-select-option-with-jQuery

**Comment by stof** [comment]
@sampathcse5816  ``liszt:updated`` is the event used in the old 0.x versions of Chosen. These version are totally outdated (1.0 was released in July 2013). you should really upgrade your version

**Comment by tjschuck** [comment]
@sampathcse5816 You can find the latest version [here](https://github.com/harvesthq/chosen/releases).

**Comment by Hoax87** [comment]
I was able to solve the problem by removing some (for me) unwanted code.

chosen.jquery.min.js ->

`e.prototype.show_search_field_default=function(){return this.is_multiple&&this.choices<1&&!this.active_field?(this.search_field.val(this.default_text),this.search_field.addClass("default")):(this.search_field.val(""),this.search_field.removeClass("default"))}`

remove this line: `this.search_field.val(""),` which causes the input-field to update the value with the (possibly empty) default value.
