### ISSUE TITLE
Keywords support

### ISSUE THREAD

**Issue by jeffg2k** [harvesthq/chosen#640]
Would be really nice if there was something for keywords, so when the user searched it not only hit on the Option Value, but the key terms as well.

For example, I have a list of business types.  My category is Optometrist.  The user searches "Eye care".  I would like to assign key terms to the Optometrist option, so when the user types "Eye", Optometrist is listed a selection.

**Comment by pfiller** [comment]
Closing this request. Discussion can continue in #628 if needed!
