### ISSUE TITLE
Chosen doesn't play nicely with jquery UI modal dialog

### ISSUE THREAD

**Issue by bradrobertson** [harvesthq/chosen#646]
Check out [this fiddle](http://jsfiddle.net/rz2es/)

When you expand the select, the search input doesn't allow keypresses.  I'm not sure who's issue this is, but I figured I'd start with chosen.  Can't really figure out what's going on, and it doesn't appear to be a z-index problem.

**Comment by pfiller** [comment]
Reading this thread and looking at #1390 makes me think this was actually a disguised duplicate of #86. Alright!
