### ISSUE TITLE
Custom delimiter option

### ISSUE THREAD

**Issue by jbrooksuk** [harvesthq/chosen#685]
I've not been able to find anything, but it'd be handy for an option to add custom delimiters.

I'm using Chosen to take in a list of ages, rather than pressing return each time, it feels more natural to press the comma key. If this is already possible, please ignore my ignorance (but please tell me how ;))

**Comment by ComeBurguburu** [comment]
The keycode of enter is 13 , the keycode of comma is 88
add "case 88:" before each lign like "case 13:" and add e.preventDefault
