### ISSUE TITLE
Selection text gets cut off because the select is too narrow

### ISSUE THREAD

**Issue by mejibyte** [harvesthq/chosen#713]
I have this on my HTML:

```
<select class="chzn-select">
  <option value="A">A</option> 
  <option value="B">B</option> 
  <option value="C">C</option> 
  <option value="D">D</option> 
</select>
```

I'm using this JavaScript to bind the library to the select:

```
$(".chzn-select").chosen();
```

And here's the final result:
- Closed: ![Screenshot 1](https://img.skitch.com/20120702-f94nqimfig46c7cc555cn3pt6s.png)
- Open: ![Screenshot 2](https://img.skitch.com/20120702-m9qnxu6pgaan1wp847ixfqir61.png)

It looks fine though if I use:

```
<select class="chzn-select" style="width: 45px;">
  <option value="A">A</option> 
  <option value="B">B</option> 
  <option value="C">C</option> 
  <option value="D">D</option> 
</select>
```

I think you shouldn't need to set an explicit width. It would be nice if it worked out of the box.

**Comment by vm-jade** [comment]
@pfiller - If chosen matches the width of the select element, shouldn't it account for the additional margins/padding that chosen uses? I would think that having the longest option fully visible would be preferable to exactly matching the original width (which hasn't been explicitly set in the first place).

E.g., http://jsfiddle.net/ng7yx2a0/ 
The longest option "Plane" is cut down to "P...".

It seems that adding a fixed number of pixels as others have suggested should solve the issue, but I guess its more complex than that if it hasn't been fixed already?

**Comment by yasnaderi** [comment]
> This would be a nice option to have within the plugin.
> 
> Barring that though, here's a work-around to set the width of the element automatically based on the width of the placeholder text.
> 
> ```
> $('select').chosen().each(function() {
>     var $elem = $(this).parent('.chosen-select');
>     $elem.find('.chosen-container')
>         .css({ 'width' : 'auto' });
>         .css({ 'width' : $('.chosen-default').outerWidth() + 25});
> });
> ```
> 
> The drop-down will be the same size as the select element and will wrap if text is longer.
> 
> If you wanted to set a specific width, you could do something like the following inside the each.
> ` $elem.find('.chosen-drop').css({ 'width' : 250}); `
> 
> If you wanted the drop-down to always expand to the full length of its options' text, you could use something like the following. Though use that with caution, because if you have lengthy options, you could end up with drop-downs that run out of your layout.
> ` $elem.find('.chosen-drop').css({ 'white-space' : 'nowrap', 'width' : 'auto'}); `

I use your code with a small modification:

```
$('.chosen-container').each(function() {
    var $elem = $(this);
    $elem.css({ 'width' : $elem.outerWidth() + 15});
});

```
