### ISSUE TITLE
chosen trigger error, if select is empty

### ISSUE THREAD

**Issue by rvinokurov** [harvesthq/chosen#738]
I have dynamic select, and some times this select has no option. Error triggered on:

<pre>
  Chosen.prototype.results_reset = function() {
            this.form_field.options[0].selected = true;
....
</pre>

<pre>
TypeError: this.form_field.options[0] is undefined
http://localhost/current/js/vendors/jquery/plugins/chosen.js
Line 697
</pre>

Can you add a check on the length of an array of options?

**Comment by lakshmandev** [comment]
Prepending an empty `<option value="1"></option>` tag in your select HTML, should work fine.
