### ISSUE TITLE
Multibyte characters - autocomplete does not work

### ISSUE THREAD

**Issue by tomiford** [harvesthq/chosen#739]
Chosen select's autocomplete does not work for multibyte characters such as Japanese. 

When you type in Japanese into a select box chosen does not search for options containing the Japanese characters entered.

**Comment by pfiller** [comment]
I'm going to #wontfix this issue. It seems like there may be some potential progress [coming from Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=354358#c43):

> We'll dispatch "keydown" and "keyup" events in the future for compatibility with other browsers

In the meantime, you can look to #2017 if you need to patch Chosen.
