### ISSUE TITLE
Mulitple Select: Place selected items on top/outside of input

### ISSUE THREAD

**Issue by Cyclodex** [harvesthq/chosen#743]
Wouldn't it be nice if we can select if the selected items are shown outside of the input field?
I mean the selected Items are now just added before the actual ```<li>``` element, selecting a lot of items makes the field a bit confusing to click after the last item.

I would like to have an option where we can set the target of the added Items, this would allow to attach the Items where people want to. A simple solution would be to just add them before the shown input field (before the whole ```<ul>```).

If I have some time, I could try to investigate code to see what is needed for that.
I am a new Drupal Chosen-Modul Maintainer and wanted to discuss this feature here with you.

[Beep] Cyclodex

**Comment by pfiller** [comment]
I'm not sure a feature like this is something I would want to see added to Chosen. Chosen is meant to be a simple drop-in replacement for select boxes and things like this add complication that push it outside of its intended purpose. Seems like a good thing to keep in a fork.
