### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by steine-locus** [harvesthq/chosen#766]
I'm using a super-simple test page and the height of the text inside the widget is compressed - there isn't enough room in the widget for the vertical height of the text, so it gets cut off on the top and bottom. Once an item is selected, it renders properly, but new items being typed out are still cut off.

I haven't made any changes to chosen.jquery.min.js or chosen.css, and I'm using version 0.9.8 with Firefox 14.0.1.

With everything else the same and using IE 9.0.8112.16421, the text is pushed down so only the top half is visible. Once any change is made to the select (typing, clicking in, the text centers itself properly.

Any thoughts?

```
<html>
    <head>
        <link rel="stylesheet" href="./css/chosen.css" type="text/css"/>

        <script type="text/javascript" src="./javascript/jquery.min.js"></script>
        <script type="text/javascript" src="./javascript/chosen.jquery.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function() {
                $(".chzn-select").chosen();
            });
        </script>
    </head>

    <body>
            <select class="chzn-select" name="test" multiple data-placeholder="Select at least one (1)" style="width:350px;">
                    <option value="Test1">Test1</option>
                    <option value="Test2">Test2</option>
                    <option value="Test3">Test3</option>
                    <option value="Test4">Test4</option>
                    <option value="Test5">Test5</option>
            </select>
    </body>
</html>
```

**Comment by mpGitHub** [comment]
Is there a workaround if I am forced to use this plugin where quirks mode is used?

**Comment by mpGitHub** [comment]
This is an ugly hack, but seems to do the trick.  I set top/bottom margin for it to display properly centered onload and then when focus occurs re-balance the top/bottom margin.

NOTE:  Code needs to be added to only do this for IE when in quirks mode.

   // First Create Chosen input.  Not shown here...

   // Then manually modify the input position
   var searchInputs = $(".search-field").find("input:first") ;
   searchInputs.css("margin-top","6px");
   searchInputs.css("margin-bottom","0px");
   searchInputs.css("margin-left","5px");
   searchInputs.css("height","20px");
   searchInputs.css("line-height","20px");

   // On focus of the input box balance out the top/bottom margins.
   searchInputs.on("focus",function(event){
      $(this).css("margin-top","2px");
      $(this).css("margin-bottom","4px");
   });
