### ISSUE TITLE
If "display:none" is active when chosen first loads, the auto-width is not working correctly

### ISSUE THREAD

**Issue by shackrock** [harvesthq/chosen#795]
I've noticed that my "select" menus appear at the minimum size if they are not displayed when chosen is called (on document load).  Is there a fix for this?

To be clear: the page loads and nothing is displayed (CSS is set to display:none).  Once a user clicks a certain checkbox, the dropdowns are displayed, but sized incorrectly by Chosen (although all of the other styles seem to have been applied, all widths are wrong).

Thanks.

**Comment by magedmakled** [comment]
:+1:  @raphapassini Thanks

**Comment by rico** [comment]
@raphapassini - thanks!

**Comment by jungledre** [comment]
@raphapassini Thank you!! Nice easy fix.

**Comment by niknokseyer** [comment]
Thanks @raphapassini.

**Comment by philipstratford** [comment]
Thanks @raphapassini, feel silly for not thinking of that myself!

**Comment by uhrohraggy** [comment]
For those who may not like chosen setting the width, you can easily instead of specifying a direct width specify .chosen({width: 'auto'}) as a string. works like a charm for me and automatically adjusts for multiple chosen dropdowns on the same page. Any hardcoded width or min-width I specify using CSS and override with !important; I realize this isn't the best for CSS purists but solves 99% of my issues.

**Comment by alvarotrigo** [comment]
+1

**Comment by philtyphils** [comment]
@raphapassini THanks you so much

**Comment by milkovsky** [comment]
Here is my workaround for it:
```   
      /**
       * Re-draws selects to fix width of 'chosen' wrapper.
       */
      refreshSelects = function() {
        $('select').each(function(){
          // Re-calculate width of every select wrapper. Hidden selects width is
          // calculated as 0 by 'chosen' plugin.
          $(this).siblings('.chosen-container').css('width', realWidth($(this)));
        });
    
        /**
         * Calculates real width of an element.
         *
         * @param {object} $element
         *   jQuery object.
         *
         * @returns {string}
         *   Element width string.
         */
        function realWidth($element){
          var $clone = $element.clone();
          $clone.css("visibility","hidden");
          $('body').append($clone);
          var width = $clone.outerWidth();
          $clone.remove();
          return width;
        }
      }
```
I execute refreshSelects() right after $('select').chosen();

**Comment by stof** [comment]
@milkovsky your ``realWidth`` does not work well if the size of the select depends on some CSS rules including the parent node, or from the size of the parent (often in response design)

**Comment by milkovsky** [comment]
Agree. But width: '100%' is also not an option.

**Comment by clasence** [comment]
@raphapassini
you just relieved me from an hour of work

**Comment by wb400** [comment]
My solution without cloning...
Usage example to assign to all selects with class overview 
>> Elements.formatDropDown ('class', 'overview');

    Elements.attachChosen = function (element) {
        var $this;
        element.each(function () {
            $this = $(this);
            $this.chosen({
                disable_search_threshold : 10,
                search_contains          : true,
                inherit_select_classes   : true,
                width                    : $this.css('width')
            });
        });
    };

    Elements.formatDropDown = function (selectorType, element) {
        var selector;
        switch (selectorType) {
            case 'id':
                Elements.attachChosen(element);
                break;
            case 'name':
                selector = $("select[name=" + element + "]");
                Elements.attachChosen(selector);
                break;
            case 'class':
                selector = $("select." + element);
                Elements.attachChosen(selector);
                break;
        }
    };

**Comment by jonathanbl** [comment]
+1 for @raphapassini solution

**Comment by rolturn** [comment]
+1 for @raphapassini solution
If width: '100%' is not a option for you try width: 'inherit' that solved it for me and it keeps the integrity of the expected width

**Comment by KZeni** [comment]
I just leave the default chosen width (auto) and add `.chosen-container { min-width:4em; }` to my site's CSS (adjusting the mix-width as needed). This makes it never become 0px (or just too small to use) while still fitting the select's ideal width when possible.

**Comment by tripflex** [comment]
I was running into this issue with conditional logic in one of my WordPress plugins ... specifically with the width being set to 0px ... even after init (which I queue chosen fields with `chosen:ready` so if it's already init and I hide the parent div) ... but anyways, this is what I used to fix this when my jQuery code runs to show the parent DIV element before executing `chosen:updated`

```js
// This is the original select field
$field = $( '#' + field );

// This is the select field wrapper that I hide (just shown for reference)
$( '.fieldset-' + field ).show();

// Chosen container ID will be original select element ID + _chosen
var $chosen_container = $( '#' + field + '_chosen' );
if( $chosen_container && chosen_container.width() === 0 ){
    chosen_container.css( 'width', '100%' );
}

$field.trigger( 'chosen:updated' );
```

**Comment by naffi192123** [comment]
> Hi guys, i'm having the same problem.
> 
> If the parent element is hide (i'm using a select inside bootstrap panel element) the chosen width is set to zero or it's not calculated.
> 
> Chosen works very well if i specify the width in `options` param.
> 
> ```
> $("#my_select_inside_hidden_parent").chosen({width: '100%'})
> ```

thanks this solution really works

**Comment by Maitry-IITB** [comment]
> Oh I was showing my markup BEFORE calling chozen. I'm doing Display-none on the element myself on the page BEFORE I call the chozen with jQuery.

Thanks for sharing this. Same thing happened with me. I was hiding the element before calling chosen. I changed it to hide the element after chosen is being called and it solved my issue.
