### ISSUE TITLE
Open Chosen dropdown on hover?

### ISSUE THREAD

**Issue by daGUY** [harvesthq/chosen#837]
Apologies if this isn't the right place to ask this, but I couldn't find an answer anywhere.

Is it possible to have a Chosen dropdown open automatically when the select is hovered on? Or, put another way, can I trigger whatever event it is that shows the dropdown menu on hover as opposed to on click?

**Comment by pfiller** [comment]
This is over 3 1/2 years old now, so I'm guessing you don't need help any longer.

If you do, you should know that our GitHub issue tracker is intended for bug reports, specific feature requests, and submitting pull requests. For support issues or usage questions (like this one) that are not bugs in Chosen itself, you should post somewhere like StackOverflow, using the jquery-chosen tag. You'll be more likely to get a quick answer there.
