### ISSUE TITLE
Allow Chosen to be initialized with a specific version of jQuery

### ISSUE THREAD

**Issue by jaypeeZero** [harvesthq/chosen#893]
I'm working on a website that has legacy versions of jQuery sitting around.  Because of old code $ is some ancient version of jQuery but I have access to variables like $jq18 for jQuery 1.8.2.

You should allow Chosen to be initialized with a specific version of jQuery to account for situations where $ is not the desired version.

**Comment by beneficiarybudding** [comment]
I think this could really help you out



https://jquerys.space/questions/can-you-explain-the-purpose-of-the-unique-function-in-the-jquery-142-version
