### ISSUE TITLE
Browser autocomplete fails with chosen select

### ISSUE THREAD

**Issue by skwp** [harvesthq/chosen#896]
I have a select field with a value of autocomplete="state" following the   standards of autocomplete http://wiki.whatwg.org/wiki/Autocompletetype. When it's a regular select field, it correctly autofills from the browser cache (Chrome) of user info. When it's a chosen select, all fields around it autocomplete correctly but it does not. 

Has anyone experienced this?

**Comment by pfiller** [comment]
This issue has existed for 3 1/2 years with minimal activity. I know that some rules around autocomplete have changed in that time (especially in Chrome). I think it's probably safe to close this, but if it still appears to be an issue feel free to re-open.

**Comment by jagfiend** [comment]
Have experienced this in the last few weeks, any chance of re-opening?
