### ISSUE TITLE
Blank options do not show up as selectable options

### ISSUE THREAD

**Issue by tlconnor** [harvesthq/chosen#93]
In the select box below there are three options to choose from, but in the Chosen version the blank option is ignored.  This means that once an option is selected the user is not able to deselect it.  An example of this is where a select box is used to filter a list of items.  The user cannot select the blank option so cannot undo any filtering selected.

<select>
  <option></option>
  <option selected>Something</option>
  <option>Something Else</option>
</select>

**Comment by asadnauman** [comment]
&nbsp;  worked for me +1
