### ISSUE TITLE
Use HTML inside results cells

### ISSUE THREAD

**Issue by gottfrois** [harvesthq/chosen#94]
Hi !

This plugin is great but do you think it would be possible to add a new feature to it ? Like it could be great to pass in some kind of way (through JSON autocomplete data maybe ?) an HTML that could be inserted inside results cells.

An exemple for that feature could be a User list where you may want to add user profile's avatar to your auto completed results.

However this plugin is awesome thanks for spending hard time on it :)

**Comment by pfiller** [comment]
Something like #692 would probably solve this issue. Closing in favor of that thread.
