### ISSUE TITLE
Hide list unless user type some text in search box

### ISSUE THREAD

**Issue by Bongs** [harvesthq/chosen#946]
Hi,

Is it possible to hide the list unless user start typing anything in search box? So when user clicks on chosen dropdown, only search box will be shown and as user starts typing it will display matching results/no results text.

Please consider this as a feature request. Thanks. :)

**Comment by pfiller** [comment]
I'm not sure what advantage there would be to hiding the results from the end user. Can someone explain it to me? I don't think this is an option we'll be likely to add without a pretty compelling reason.
