### ISSUE TITLE
Allow the abilty to specify search options (e.g. startsWith or contains)

### ISSUE THREAD

**Issue by ryanhaugh** [harvesthq/chosen#97]
Right now the search feature only uses 'contains' logic, meaning the results will include all items that have the specified text anywhere in the text.  It would be nice if we could change the functionality to only include items that start with the specified text.

For example,  if I type in 'es' I would see 'United States' among the results.  It would be nice if I could changed it so I would only see 'Estonia'

**Comment by karthikeyar9** [comment]
I am unable to search with starting words in a sentence

**Comment by karthikeyar9** [comment]
I am unable to search with starting letters of a word. Please help
