### ISSUE TITLE
Set focus on option in chosen.

### ISSUE THREAD

**Issue by VasilisPrimudriy** [harvesthq/chosen#991]
Hi guys,
Not sure if it's the right place to post this but I'll try my luck anyways. 
I'm using chosen plugin and trying to set a focus on a default option when the drop-down is shown. 
So I have something like this:

$("#chosen_element_id").bind('liszt:showing_dropdown', function() {
     // set focus on some option in the list
}

Can someone help and tell me how to do that (set focus on some option in chosen)?
Please note that I don't want to select an option (by changing the value), just focus on it.

Thank you.

Awesome plugin by the way!

**Comment by MsDacia** [comment]
I believe I have a solution to this. I had to implement all of the aria requirements for selects, and having the option be read out as the user arrows through them was a big one that is missing in this plugin. How should I share my solution?

**Comment by yahyaerturan** [comment]
You may share your forked version or may ask the pull request with your
commit.

*Yahya A. ERTURAN, **Senior IT Consultant*
M: (544) 658-3787        E: yahya@vayes.net

*Vayes Web Tasarım & Yazılım ve Reklam Hizmetleri*
MidPoint Residence D.27 Beylikdüzü, İstanbul
Tel: (212) 855-9404    Faks: (212) 855-9404

**Comment by MsDacia** [comment]
Perfect. I apologize for the delayed response, just trying to perfect it. One question, we only implemented this fix for single selects, are we required to also update the multiple selects as well?
